### ISSUE TITLE
Offering 2 cams for remote testing

### ISSUE THREAD

**Issue by pep4n** [roleoroleo/yi-hack-Allwinner-v2#1]
Hey @roleoroleo _or anybody else who has the knowledge but no cams ,)_ 

I have 2 of these cams here which I could offer for testing. 
Also would love to support. Only my dev skills are near zero. 
Id also be available for a screen sharing call if that could be of help.
Let me know, 
p

**Comment by roleoroleo** [comment]
I could sure use.

**Comment by pep4n** [comment]
Ah sry I rather meant remotely. 
I guess sending these across Europe is more expensive then what I paid on amazon ,)

**Comment by roleoroleo** [comment]
Remotely it's ok.

**Comment by luisglezi** [comment]
I have also 2 brand new cameras that can be used for testing

**Comment by pep4n** [comment]
> 
> 
> Remotely it's ok.

ok cool. let me know how we should do this!

**Comment by pep4n** [comment]
I'd be available tonight for some remote testing. 
Cheers,
P

**Comment by roleoroleo** [comment]
What UTC offset?
:)

**Comment by luisglezi** [comment]
I will not be available until Thu next week. I am GMT+2 (Spain)

**Comment by pep4n** [comment]
> 
> 
> What UTC offset?
> :)

I'm in CEST. 
So atm GMT + 2. 

Would be available from around 8pm. 
What App would you like to use?

**Comment by roleoroleo** [comment]
I'm gmt+2 too.
But tonight I'm not at home.
Sorry.

**Comment by roleoroleo** [comment]
About the application...
Are you able to publish ssh with a temporary port forwarding?
Maybe on a non-standard port?

**Comment by pep4n** [comment]
> 
> 
> I'm gmt+2 too.
> But tonight I'm not at home.
> Sorry.

no worries & happy Friday! 
Only we need to fix something so I can block it. 
I have a wife and two kids who book slots very fast ,)  

for SSH ports I need to check. 
I am in a double NAT network and only have direct access to one of the routers. 
Would teamviewer or similar also be an option?

**Comment by roleoroleo** [comment]
I can understand.
:)
I have two wifes and three kids!

Teamviewer is ok for me.

**Comment by pep4n** [comment]
ahaha that would sure be too much for me ,) 

Lets see if we find a time.

**Comment by pep4n** [comment]
I have some time today...

PS: What applications would you need? 
To not steal more of your time I would already install them before we teamview...

**Comment by roleoroleo** [comment]
Sorry, I read the message too late.
Are you online?

**Comment by pep4n** [comment]
No worries, need to cook dinner now. 
Would be available from 8 on...

**Comment by roleoroleo** [comment]
We will never make it... :)

**Comment by HuangRicky** [comment]
Hi @roleoroleo  I have a [Yi Outdoor 1080p](https://www.amazon.com/YI-Waterproof-Surveillance-Detection-Deterrent/dp/B01CW49AGG/ref=sr_1_3?dchild=1&keywords=yi+outdoor+camera&qid=1603244323&sr=8-3)  

Does this fw work on this cam? I can also provide it for testing if you tell me what I need to do: I assume I shall flash it and then expose the ssh thru port-forwarding? Thanks!

**Comment by HuangRicky** [comment]
the serial number starts with 9CUS
