### ISSUE TITLE
High res with r30gb

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-Allwinner-v2#10]
@artemy 
I understand why high resolution doesn't work: the high res stream is h265 coded.
The old models (y21ga too) use h264 for both, high res and low res streams.
r30gb uses h264 for low res stream and h265 for high res stream.
I will try to solve the problem, but is not simple.

**Comment by roleoroleo** [comment]
Try this binary:
[rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5446733/rRTSPServer.gz)

channel0 is an h265 stream.
At the moment the address is rtsp://IP-CAM/ch0_0.h264

**Comment by artemy** [comment]
VLC can't open the high-res stream. Low-res works fine still.

**Comment by roleoroleo** [comment]
Please, another try:
[rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5447664/rRTSPServer.gz)

**Comment by artemy** [comment]
Both streams do seem to work alright now.

**Comment by wimpie007** [comment]
@artemy highres confirmed??

**Comment by roleoroleo** [comment]
Please try snapshot too:
[snapshot.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5447784/snapshot.tar.gz)

**Comment by artemy** [comment]
> Please try snapshot too:
> [snapshot.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5447784/snapshot.tar.gz)

Both are broken. Low-res just shows green screen, high-res doesn't give any output at all

**Comment by roleoroleo** [comment]
Another try?
:)
[snapshot.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5447903/snapshot.tar.gz)

**Comment by artemy** [comment]
So both are good now, although I think there is another issue now. 
I can get a high-res snapshot once after camera boots, but then it randomly causes camera reboot after one of the next requests

**Comment by roleoroleo** [comment]
The problem here is the memory.
The cam runs with very little ram available and ffmpeg library is very "big".
Try to enable swap space.
