### ISSUE TITLE
Webserver not responding

### ISSUE THREAD

**Issue by nonexus** [roleoroleo/yi-hack-Allwinner-v2#102]
Hi all,

i just recently noticed that after applying the hack (y21ga, hack version 0.1.4) I cannot access the http server anymore.
SSH is still functional but I cannot find any httpd running (at least from the output of "top").

Reboot, power reset etc. does not help unforunately.

Let me know if you need any log files etc :)

**Comment by roleoroleo** [comment]
Try to remove the hack and apply it again.

**Comment by roleoroleo** [comment]
Yes, the command is:
`
/tmp/sd/yi-hack/usr/sbin/httpd -p 80 -h /tmp/sd/yi-hack/www/ -c /tmp/httpd.conf
`
