### ISSUE TITLE
Will the yi home 1080p 9FUSY25RO8 compatible?

### ISSUE THREAD

**Issue by eyswear** [roleoroleo/yi-hack-Allwinner-v2#104]
I have Yi Home Camera 3 yys2518 and when I put hack on sd card I can't login to camera and camera can't connect also to Yi Home Software.

**Comment by eyswear** [comment]
I tried to back up with instructions from wiki, but It's not working :(

**Comment by roleoroleo** [comment]
What sw version do you have?

**Comment by eyswear** [comment]
My cam software is: 4.5.0.0C_201910080934

**Comment by roleoroleo** [comment]
Your cam is not supported by this hack.
https://github.com/roleoroleo/yi-hack-MStar
