### ISSUE TITLE
Issues flashing camera

### ISSUE THREAD

**Issue by pomtom44** [roleoroleo/yi-hack-Allwinner-v2#107]
Hi Team
I have some of the older 720P cams which I have with a older hacked firmware
I figured i might get some 1080P ones and upgrade, so did a bit of research and found 2 online for a good price
9FUS model which supposedly is supported on both this and V1 of the hack
I downloaded the image and put onto a SD card and left for a good 2 hours, but the orange light just kept flashing with no indication of it doing anything or if I needed to do anything
SO i left that and tried setting up the other one via the official app first, then to flash it
I got it showing in the app ok, and connected to my wifi, then put the image on the sd card and rebooted it,
the app shows it as disconnected, but I cant seem to access any web services on the camera, and the app no longer connects

I have tried to reset the camera but now its just stuck on a solid orange light with no progress visible, 

How am I supposed to flash the firmware on these cameras?
Im sure im doing something wrong but i dont know what

that for the help

**Comment by roleoroleo** [comment]
If the camera doesn't connect to yi app, probably the hack is running.
Check again the web site on port 8080.
