### ISSUE TITLE
Real time live stream in Home Assistant

### ISSUE THREAD

**Issue by Simone1922** [roleoroleo/yi-hack-Allwinner-v2#110]
Hi guys,

I'm using a YI 1080p IFUS and everything is working. The rtsp stream I get with VLC is just one second delayed while in Home Assistant I get longer delays (5 seconds or much more). I was wondering if there is a way to avoid this delay and see the "live" stream from the camera with a shorter delay? I used a smartphone with "IP webcam app" and the stream with "http" was almost in real time so I'd like to have the same with the Yi camera (if possibile).

Thanks in advance for any suggestion.

**Comment by wild-run** [comment]
same problem here

**Comment by roleoroleo** [comment]
Please try webrtc plugin.
https://github.com/AlexxIT/WebRTC/

**Comment by wild-run** [comment]
First congratulate you for your great work, this addon that you comment works well to see the video, but now the problem is when I create an entity to detect movement and others, I have used this addon https://github.com/roleoroleo/yi-hack_ha_integration and I have also tried to add it manually but it does not work at all well

**Comment by roleoroleo** [comment]
Did you enable mqtt in ha?
It's required.

**Comment by Gifford47** [comment]
> Hi guys,
> 
> I'm using a YI 1080p IFUS and everything is working. The rtsp stream I get with VLC is just one second delayed while in Home Assistant I get longer delays (5 seconds or much more). I was wondering if there is a way to avoid this delay and see the "live" stream from the camera with a shorter delay? I used a smartphone with "IP webcam app" and the stream with "http" was almost in real time so I'd like to have the same with the Yi camera (if possibile).
> 
> Thanks in advance for any suggestion.

Does anybody have an ideo how to stream realtime? I use shinobi and the stream lag is about 7 seconds ...
