### ISSUE TITLE
Night vision/ir light does not turn off

### ISSUE THREAD

**Issue by phoenix1887** [roleoroleo/yi-hack-Allwinner-v2#120]
This seems to be a bigger problem with all the yi cameras as it doesn't work for any of the 12 cameras I have (different models). But I have several bfus and ifus cams (hacked). You can turn the IR light off for any of them in the yi hack settings but it doesn't disable night vision it continues using it. The strange thing is even if I turn it off in the yi home camera app settings it still stays on. So there seems to be no way to disable night vision on any of the cameras despite the setting. Unless the hacks I installed on the cameras disabled the ability to turn off the night vision?

Can anyone else confirm this isn't working either for their cams? By the way cycling the lights on and off and rebooting the camera doesn't help...

To test it out disable the IR light on the camera then dim the lights in the room until you see the camera switch to night vision... Even though it shouldn't...

Anyone have any ideas how to fix this? I emailed yi.

**Comment by ghanashyaml** [comment]
Not sure if any of your later installs are affecting this. I have about 8 BFUS based Yi 1080p home cameras and the IR led setting is working as expected. I only have the basic Yi hack installed, yi29xxxx. Have 2 looking inside and 3 looking outside from behind glasses. If I turn on the ones for behind the glasses I see reflections, so I just turn them off. No more night vision for them but the feature works.
