### ISSUE TITLE
ONVIF pairing error on Windows 10

### ISSUE THREAD

**Issue by rubenlesmes** [roleoroleo/yi-hack-Allwinner-v2#132]
Hi @roleoroleo

I've tried to pair my **y21ga** with firmware _0.1.5_ and _0.1.6_ with Windows 10 device pairing (Device enumeration and pairing Windows store app) to connect to the ONVIF service, but I can't manage to.

The **NotPaired** error pop-ups altho I can see the device on the ONVIF Device Manager.

![pairing](https://user-images.githubusercontent.com/55602139/114619327-b6317500-9caa-11eb-885e-c4a8d847dbd0.jpg)

**CONFIG:**
![config](https://user-images.githubusercontent.com/55602139/114619999-68693c80-9cab-11eb-81b0-a130f64b0c31.jpg)

**WINDOWS VERSION:**
VERSION 21H1 (OS COMP: 19043.906)

**Comment by mik999** [comment]
Same here

**Comment by roleoroleo** [comment]
I don't know how to fix the problem.
The cam replies to the discovery request but Windows doesn't understand the response.
I have to investigate.

**Comment by liunett** [comment]
> I don't know how to fix the problem.
> The cam replies to the discovery request but Windows doesn't understand the response.
> I have to investigate.

Is there any update with the issue?

**Comment by roleoroleo** [comment]
I tried to change the response from the cam but no luck.
I don't know how to fix it.
