### ISSUE TITLE
RSTP High stream no video Yi Cam y21ga v0.1.6 hack

### ISSUE THREAD

**Issue by itsbasix** [roleoroleo/yi-hack-Allwinner-v2#136]
I am experiencing a very similar issue with this one I found on Allwinner repo 
https://github.com/roleoroleo/yi-hack-Allwinner/issues/81

Using 2 cameras, same wifi network, same AP. One camera indoor on the upper floor, works fine no problem at all.
Second camera, added recently behaves weirdly.
When this camera is put close to my window frame (still indoor) in order to point the garden outside, RSTP high stream stops working. VLC says it's receiving video H264 but no video is shown (as in the other issue I linked). Audio stream is disabled (by settings, as I don't need it).

Slightly moving one cm behind or above or holding the camera with hands mid-air restores the RSTP stream.
Another thing I noticed is that if you start the RSTP high stream and then move the camera to the "problematic" position the stream still works. while if you try to start the stream with the camera already in the problematic position, no video.
RSTP Low stream works anytime regardless of positioning, same goes for snapshots.

"Faulty" camera web server page states that WiFi quality is always around 74-75%.
Cameras are both y21ga model. Using latest version of the hack 0.1.6.

Thanks for the amazing work anyway!

**Comment by manuelv04** [comment]
Have you found a solution? I have a Y211ga with no RSTP
