### ISSUE TITLE
BFUSY44GPV firm 9.0.19.02_202007141512

### ISSUE THREAD

**Issue by Sildenafil99** [roleoroleo/yi-hack-Allwinner-v2#14]
Hi,
today I got these cameras but the hack don't work.
Any help?

**Comment by Sildenafil99** [comment]
I have no yellow led flashing but fixed...

**Comment by mcanteri** [comment]
Are you using the original cable and wall adaptor ?

**Comment by Sildenafil99** [comment]
With the original cable and wall adaptor, i have first yellow led fix, after two seconds blue led flashing and then the camera is ready but with the original firmware.
I have extract the y21ga_0.1.2 into the root of the sd card ( it contain 3 folder Factory, newbackup, yi-hack and 1 file lower_half_init.sh) is it correct?
Thx

**Comment by pep4n** [comment]
> I have extract the y21ga_0.1.2 into the root of the sd card ( it contain 3 folder Factory, newbackup, yi-hack and 1 file lower_half_init.sh) is it correct?

that's correct.

**Comment by Sildenafil99** [comment]
> > I have extract the y21ga_0.1.2 into the root of the sd card ( it contain 3 folder Factory, newbackup, yi-hack and 1 file lower_half_init.sh) is it correct?
> 
> that's correct.

Why the hack don't work?

**Comment by damanti-me** [comment]
Is your SD in FAT32 format?

**Comment by Sildenafil99** [comment]
> Is your SD in FAT32 format?

Yes, I tried with two different sd card, I tried to format via windows FAT32/4096 and via Yi camera and i have the same result...

**Comment by Sildenafil99** [comment]
Help?

**Comment by pep4n** [comment]
It seems your cam is not supported. 

You gave the DID BFUSY44GPV
But what is the SN? It should start similar to this: by21ga ...

**Comment by Sildenafil99** [comment]
Yes the sn Is by21gaeuw.....

**Comment by roleoroleo** [comment]
Try the backup procedure in the wiki.
Check if it works.

**Comment by Sildenafil99** [comment]
This is the backup
[backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5458351/backup.zip)

**Comment by mcanteri** [comment]
> > Is your SD in FAT32 format?
> 
> Yes, I tried with two different sd card, I tried to format via windows FAT32/4096 and via Yi camera and i have the same result...

What is the size of the SD cards you are trying ? Do you have a small one, like 4GB or 8GB to try ?

**Comment by mcanteri** [comment]
> This is the backup
> [backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5458351/backup.zip)

It is exactly as ours, so it must be something else.

**Comment by Sildenafil99** [comment]
> > > Is your SD in FAT32 format?
> > 
> > 
> > Yes, I tried with two different sd card, I tried to format via windows FAT32/4096 and via Yi camera and i have the same result...
> 
> What is the size of the SD cards you are trying ? Do you have a small one, like 4GB or 8GB to try ?

16gb... i don't have 8 or 4 sd card, i can try to create a 4gb partition...

**Comment by pep4n** [comment]
fyi I'm using 16gb sandisk as well.

**Comment by Sildenafil99** [comment]
I can try to reset cam and choise a different server?

**Comment by Sildenafil99** [comment]
I have reset the camera and chose a different localization on tha app, set the camera and the power off and insert the sd but nothing change,  yellow led fix, after two seconds blue led flashing and then the camera is ready but with the original firmware.

**Comment by roleoroleo** [comment]
The backup procedure uses the same hack.
And I can confirm that your cam is a y21ga.
It must work.

**Comment by mcanteri** [comment]
> I have reset the camera and chose a different localization on tha app, set the camera and the power off and insert the sd but nothing change, yellow led fix, after two seconds blue led flashing and then the camera is ready but with the original firmware.

Sorry, but when the cam is online have you tried to connect using ssh ? (ssh root@YOUR_LAN-IP)

**Comment by Sildenafil99** [comment]
> > I have reset the camera and chose a different localization on tha app, set the camera and the power off and insert the sd but nothing change, yellow led fix, after two seconds blue led flashing and then the camera is ready but with the original firmware.
> 
> Sorry, but when the cam is online have you tried to connect using telnet ?

No i have tried this with chrome:
Access the web interface by entering the following in your web browser: http://yi-hack-v4

Depending upon your network setup, accessing the web interface with the hostname may not work. In this case, the IP address of the camera has to be found.

This can be done from the App. Open it and go to the Camera Settings --> Network Info --> IP Address.

Access the web interface by entering the IP address of the came in a web browser. e.g. http://192.168.1.5

**Comment by mcanteri** [comment]
> Sorry, but when the cam is online have you tried to connect using telnet ?

Try open http://yourLanIp:8080  with Chrome

**Comment by mcanteri** [comment]
> > Sorry, but when the cam is online have you tried to connect using telnet ?
> 
> Try open http://yourLanIp:8080 with Chrome

Ok, accordingly to what you wrote, try to open in Chrome http://192.168.1.5:8080

**Comment by Sildenafil99** [comment]
Ok, i'm feel so stupid now... I forgot to writer the port...
