### ISSUE TITLE
Questions about upgrade procedure

### ISSUE THREAD

**Issue by ivanfor** [roleoroleo/yi-hack-Allwinner-v2#145]
As I can see, this hack lives on sdcard as /home is RO.
The upgrade procedure says that an empty sdcard is needed. 
Isn't it possible to extract the tar.gz over the currently used sdcard and overwrite the needed files?
I know config can be easily saved and restored, but what about recordings, custom scripts, etc, can they be kept?

**Comment by roleoroleo** [comment]
I changed the readme file.
Upgrade procedure ---> Install procedure
When you update the firmware you can use the same sd card without problems.
