### ISSUE TITLE
mqtt_adv settings are not saved

### ISSUE THREAD

**Issue by dcbo** [roleoroleo/yi-hack-Allwinner-v2#146]
### Reproduce:
- Go to "page=mqtt_adv"
- change one Setting
- Click on "Save"

### Observation
- When I click on `Save` in any other dialog the Word `saving` directly appears near to the Button and 
- changes to `saved` after some seconds. 
- In the Advanced MQTT Configuration this is not happening.

### My System
- Firmware Version | 0.1.6
- Base Version | 9.0.19.02_202007141512
- Model Suffix | y21ga
- Serial Number | IFUSY445LTJ74R######
- Load Average | 1.29 1.16 1.21
- Free/Total Memory | 35560/60912 KB
- Free SD Space | 100%
- I just upgraded from 0.1.4 to 0.1.6 OTA
- Upgrade from 0.1.3 to 0.1.4 with SD card a while ago.

**Comment by roleoroleo** [comment]
I retested it now and it works with my y21ga.
The procedure is slow because there are a lot of parameters.
Are you sure you have waited long enough?
