### ISSUE TITLE
RTSP audio not working on y21ga

### ISSUE THREAD

**Issue by ivanfor** [roleoroleo/yi-hack-Allwinner-v2#147]
Hi.
RTSP audio is not working on y21ga. However, recordings do have audio. I can reproduce it in 4 identical cams, so it doesn't seem hw related.
```
ivan@sinchan:~$ ffmpeg -hide_banner -i  rtsp://ctest/ch0_0.h264
Input #0, rtsp, from 'rtsp://ctest/ch0_0.h264':
  Metadata:
    title           : Session streamed by "rRTSPServer"
    comment         : ch0_0.h264
  Duration: N/A, start: -0.046489, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 20 fps, 39 tbr, 90k tbn, 40 tbc
At least one output file must be specified
```
```
ivan@sinchan:~$ ffmpeg -hide_banner -i  rtsp://ctest/ch0_2.h264
[rtsp @ 0x5633d605a600] method DESCRIBE failed: 404 File Not Found, Or In Incorrect Format
rtsp://ctest/ch0_2.h264: Server returned 404 Not Found
```

Thinking it could be [this](https://github.com/roleoroleo/yi-hack-Allwinner/issues/237), I removed user and password but nothing changed.
Interestingly, AAC codec does work:
```
ivan@sinchan:~$ ffmpeg -hide_banner -i  rtsp://ctest/ch0_0.h264
Input #0, rtsp, from 'rtsp://ctest/ch0_0.h264':
  Metadata:
    title           : Session streamed by "rRTSPServer"
    comment         : ch0_0.h264
  Duration: N/A, start: 0.000250, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn, 40 tbc
    Stream #0:1: Audio: aac (LC), 8000 Hz, mono, fltp
At least one output file must be specified
ivan@sinchan:~$ ffmpeg -hide_banner -i  rtsp://ctest/ch0_2.h264
Input #0, rtsp, from 'rtsp://ctest/ch0_2.h264':
  Metadata:
    title           : Session streamed by "rRTSPServer"
    comment         : ch0_2.h264
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 8000 Hz, mono, fltp
At least one output file must be specified
```

Is this a known bug?
Is there anything I can do to debug?
Thanks

**Comment by roleoroleo** [comment]
There is a know bug, probably it depende on the old g++ used.
Sometimes when I build the solution, audio doesn't work.
Changing  optiomization options it comes back.
Please check if it works using aac codec.

**Comment by ivanfor** [comment]
Yep. Aac works.
Should I recompile?

**Comment by roleoroleo** [comment]
I will recompile and test it asap.
Are you using authentication with rtsp?

**Comment by ivanfor** [comment]
I've tried both with and without auth. Same result.

**Comment by roleoroleo** [comment]
Please overwrite this binary and let me know if it works:
[rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/6386560/rRTSPServer.gz)

**Comment by ivanfor** [comment]
It's working perfectly, with and without authentication.
Thanks for this!

**Comment by 4ndinger** [comment]
Hi,
on my CAM IFUS with y21ga I have the same issue. Currently I'm not able to compile it for myself.
When I change to aac the audio is working but the video stream is very slow (I think aac is to cpu itense)
Will there come an update to have audio (not aac) available?

Best regards!
Andi

**Comment by roleoroleo** [comment]
Use the binary above.

**Comment by roleoroleo** [comment]
Please check if this fw works.
If it's ok, I will create a new release.

[y21ga_0.1.6.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/6409361/y21ga_0.1.6.tar.gz)

**Comment by ivanfor** [comment]
> Please check if this fw works.
> If it's ok, I will create a new release.
> 
> [y21ga_0.1.6.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/6409361/y21ga_0.1.6.tar.gz)

I've extracted and overwritten /tmp/sd contents in my test cam, and everything seems to be working well.

**Comment by roleoroleo** [comment]
> I've extracted and overwritten /tmp/sd contents in my test cam, and everything seems to be working well.

rtsp too?

**Comment by ivanfor** [comment]
Yes. Rtsp and audio (only tested ulaw, though)

**Comment by RedKage** [comment]
Works on my end as well, sound is back!
