### ISSUE TITLE
Which version to use for "Yi 1080p Dome", h20m, Hardware ID 45US

### ISSUE THREAD

**Issue by PatrickR68** [roleoroleo/yi-hack-Allwinner-v2#149]
Hello, 

many thanks for your time. 

I'm not sure which version is compatible for my camera
"Yi 1080p Dome", h20m, Hardware ID 45US

Is it compatible? 

Many thanks,
Patrick

**Comment by roleoroleo** [comment]
Check this:
https://github.com/TheCrypt0/yi-hack-v4
or this:
https://github.com/alienatedsec/yi-hack-v5

**Comment by PatrickR68** [comment]
@roleoroleo Thanks for your answer. 
I will check. 
Does the backup and unbrick procedure will also work for this versions?
Best wishes, 
Patrick

**Comment by roleoroleo** [comment]
I don't know.
