### ISSUE TITLE
Where i can find the FW File ? 

### ISSUE THREAD

**Issue by afrojaner** [roleoroleo/yi-hack-Allwinner-v2#15]
bfus    9.0.19

**Comment by afrojaner** [comment]
?

**Comment by Sildenafil99** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/tag/0.1.2

**Comment by pep4n** [comment]
as this has been resolved, could you please close this issue? 
thanks,
p

**Comment by afrojaner** [comment]
Thank you
