### ISSUE TITLE
kami mini model YYS.2919

### ISSUE THREAD

**Issue by marcjohnen** [roleoroleo/yi-hack-Allwinner-v2#155]
Hi @roleoroleo ,
as suggested on https://github.com/roleoroleo/yi-hack-MStar/issues/362, I made a backup of the flash.
It would be highly appreciated if you could try to add support for this model.
Here is the backup : https://drive.google.com/file/d/14Qg3XMuKQZVV4w1PUXG0vyIFZ2baOm3W/view?usp=sharing
Many greetings
Marc

**Comment by roleoroleo** [comment]
Please, send me 2 copies of the video buffer (/dev/shm/fshare_frame_buf).
Make a copy, wait 5 seconds and make another copy.

**Comment by marcjohnen** [comment]
Sorry for my late reply. I'm not sure how to do that. I need to connect via ssh? Does this work without custom firmware?

**Comment by roleoroleo** [comment]
I will send a beta hack and you will be able to access with ssh.

**Comment by roleoroleo** [comment]
Here it is:
[y28ga_0.1.7.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/6478309/y28ga_0.1.7.tar.gz)

**Comment by esix4rmyy** [comment]
What a great news! I was just wondering buying this cam (if it is this https://www.amazon.it/Telecamera-Rilevamento-Sorveglianza-Intelligenza-Artificiale/dp/B08DCRMYV9?ref_=Oct_DLandingS_D_3aba57eb_65&smid=A3LDXR48R7LTSM) Can you please keep us updated about your work? Is it worth to buy it now for then flashing the hack?

**Comment by roleoroleo** [comment]
I don't know, we have to check how this alpha works.

**Comment by marcjohnen** [comment]
I'm quite busy, sorry if my responses will be a bit slow. When I use the beta, the camera keeps rebooting endlessly. I'll give it another try as soon as I can.

**Comment by rpkilgore** [comment]
This is a continuation of [this ](https://github.com/roleoroleo/yi-hack-Allwinner-v2/discussions/237)discussion, Moving to this thread for tracking.
Attached is an every 5 second capture of the fshare_frame_buf file.  It didn't look like it changed any while i was getting this.  I tried to hit the rtsp url to see if it would make it change but didn't appear to.  Also streamed from the Kami app and that didn't make the file change either, but here is the file captures for you to review.
[fshare_frame_buf.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7034128/fshare_frame_buf.zip)
Just to be sure you had enough data I rebooted and grabbed 3 more :) maybe overkill but wanted to make sure you had the data you need.
[fshare_frame_buf_2.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7034167/fshare_frame_buf_2.zip)

**Comment by roleoroleo** [comment]
Please try this:
[h264grabber.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7034467/h264grabber.gz)
Overwrite the original h264grabber.

**Comment by roleoroleo** [comment]
And this archive for the snapshot:
[snapshot.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7034500/snapshot.tar.gz)

**Comment by rpkilgore** [comment]
Where should i extract the h264grabber.gz?  it appears to only contain hidden files?

The snapshot one looks like it should go in the /tmp/sd/yi-hack/bin folder correct?

**Comment by roleoroleo** [comment]
All files in /tmp/sd/yi-hack/bin
What the model stored in /tmp/sd/yi-hack/model_suffix?

**Comment by rpkilgore** [comment]
I placed the new files from the snapshot archive here:
![image](https://user-images.githubusercontent.com/19828182/130684827-ce4a8ec8-89d2-4759-85a6-049e4dc3a35d.png)

I didn't know where you wanted these files:
![image](https://user-images.githubusercontent.com/19828182/130684958-a0353d0c-0990-478a-a8e1-f98559c61f06.png)

**Comment by roleoroleo** [comment]
h264grabber is not a .tar.gz but only a .gz, simply gunzip to the bin directory.
The hidden files are the content of the binary.

You need to fix the model_suffix. You used the hack for the y21ga model and now the software doesn't recognize the cam.
Edit the file model_suffix and change y21ga with y28ga.

**Comment by rpkilgore** [comment]
Ok, well we are 1 step closer.  The snapshots work now :)

However, the rtsp stream still not working.

**Comment by roleoroleo** [comment]
The algorithm to extract the frames  is the same.
If the snapshot work, the grabber should work.
Check if h264grabber and rRTSPServer are running.

**Comment by roleoroleo** [comment]
>  I'm going to try and run the uninstallers for the y21 hacks then re-apply to see if maybe it's because we have done so much testing on this one.

Wait a fer hours, I will create an unhack procedure for y28ga.

> I do have another question.. Since I have a backup, how can i restore the camera using the backup I made? Do i just copy the rootfs and home to the sd card and reboot? Or do something through ssh to restore the images?

Check the wiki for the restore, but you need a serial connection.

**Comment by roleoroleo** [comment]
> You are absolutely right! I tried indeed to hack with y211ga. And unfortunately, the original app tells me that I'm in the last version, so I cannot update.

This is strange.

> However, I've just opened a brand new camera (I bought 2, one still on the package); I put the y28ga_0.1.8 and the result is the same: It boots, looks like it's working well, and in 10 seconds it starts rebooting, continuously.

Maybe a snoapshot causes a reboot.
Did you enable swap space?

**Comment by rpkilgore** [comment]
Well time to get my hands dirty... Ran the uninstall, then cleaned up the sd card and ran the yt28ga_0.1.8 hack... seems my camera is now locked at the yellow light screen.  I pulled out the sd card and checked.  It does look like it applied the hack because I have the Factory_Done folder.  Just won't boot now.  Just ordered me a serial to usb connector that should be in tomorrow so i can attempt to solder and do a restore.  Will update this post once I'm back in to the camera.

**Comment by roleoroleo** [comment]
Try to apply y28ga_unhack.

**Comment by rpkilgore** [comment]
Tried running the y28ga_unhack.. Cam is just sitting there with the yellow light on.  :(

**Comment by noman1228** [comment]
I know I must have tried the y21 and y211 hacks just for giggles (232ttl in hand) this sounds crazy but in complete frustration, I just left the cam unplugged and on my desk (after throwing it across the room, which I don't recommend however it is what I did to get back on track) came back to it in the morning and it booted stock immediately. I also tried a few of the Allwinner v1 hack/unhack and yi-Hack V4, V5, mStar was in the mix. I tried them all and never needed to "hardware flash" my cam. These things take a beating. Only way I killed one was a 3AM solder job on those tiny ass fly-leads for Serial. Smoke was in fact released.

**Comment by roleoroleo** [comment]
> Tried running the y28ga_unhack.. Cam is just sitting there with the yellow light on. :(

Try to remove "record" folder from your sd card (if it exists) and try again.
If this doesn't work, a serial connection is needed.

**Comment by rpkilgore** [comment]
Sorry for going silent there for a few days.  Was having some health issues that kept me in bed.  I'm back now for the time being.. lol going to try to get this cam working again

> this sounds crazy but in complete frustration, I just left the cam unplugged and on my desk (after throwing it across the room, which I don't recommend however it is what I did to get back on track) came back to it in the morning and it booted stock immediately. 
HAHA when you take it out of the case there, it does seem to fit nicely in your hand for throwing,  Bet  you could get several skips off the water.  Plus it does resemble a hockey puck.. lol

> Try to remove "record" folder from your sd card (if it exists) and try again.
If this doesn't work, a serial connection is needed.

Yeah, tried that too.  Time to break out the soldering iron and see if I can dust off my old skills to make a serial connection work.  Will keep ya'll posted.

**Comment by rpkilgore** [comment]
Sooo.. just an update... My soldering skills leave much to be desired.  Spectacular failure in my attempt to connect to the cam via serial.  Now it really is only useful for skipping across the water. lol  I'll be ordering a new cam.  Once it gets in I can continue testing.

**Comment by rpkilgore** [comment]
Ok, my replacement camera has arrived.  For those curious the exact camera I bought is [here](https://www.amazon.com/gp/product/B08DCX834V/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1).
Known here as the y28ga model.  I powered it up, used the Kami app to connect to wifi.  Once connected I used the backup script to grab a dump on the camera before apply the hack.  Then simply ran the hack.

I am happy to report that everything works perfectly, and I'd like to say a HUGE thank you to rolo for helping me get this camera added and working.

Thank you sir!  Hope you have a wonderful day, and I'll probably be back soon to see if my other camera's are supported by this hack :)

**Comment by roleoroleo** [comment]
I'm glad to know it worked although I'm sorry the debrick didn't work.

And thank you for your huge donation.

**Comment by rpkilgore** [comment]
Its been awhile, but I had a chance to get back to looking at this, and I tried your new unhack process and it seems to have worked! At least there is no more solid orange light..  Right now it's blinking blue.  When will I know it's done? or is that the indication?

**Comment by roleoroleo** [comment]
If the light is blue, the procedure completed.
Try to reset with the button and pair the cam again.

**Comment by rpkilgore** [comment]
Yup that worked.  Thank Goodness.. Won't lie I was skeptical that it would work but it did.  Whahoo! no soldering and brought it back to life.. Great Job and Thanks for providing that unbrick!

**Comment by marcjohnen** [comment]
Sorry that I was gone for so long. I successfully tried this as well. Thanks a lot!
