### ISSUE TITLE
audio and video live home assitant?

### ISSUE THREAD

**Issue by wild-run** [roleoroleo/yi-hack-Allwinner-v2#164]
Some way to have audio and video at the same time live in home assistant, in vlc it works well for me but in home assistant I can't get it out

**Comment by roleoroleo** [comment]
Use this component:
https://github.com/AlexxIT/WebRTC/

**Comment by wild-run** [comment]
yes, i use this, and I have activated in the configuration as pcm output, i use this link rtsp://192.168.1.133/ch0_0.h264, the video works perfectly but I can't get audio

**Comment by roleoroleo** [comment]
Did you enable rtsp audio?
Which codec?

**Comment by wild-run** [comment]
yes , i active rtsp audio: pcm

**Comment by roleoroleo** [comment]
Try alaw or ulaw.

**Comment by wild-run** [comment]
perfect, now work :)
