### ISSUE TITLE
R30 keeps rebooting

### ISSUE THREAD

**Issue by casperaudenaert** [roleoroleo/yi-hack-Allwinner-v2#175]
my R30 keeps rebooting without doing anything
But it works the time between reboots

**Comment by WalkingDot** [comment]
What did you do before that?
More details would help.

**Comment by seuffert** [comment]
i am having the same issue. Just installed this firmware on my brand new dome guard. 
sadly it keeps rebooting e.g. if i take a snapshot  

i was able to reduce reboots by enabling SWAP, but not completely

**Comment by WalkingDot** [comment]
I have the same cam and had no problems with reboots yet.
I disabled some services after the first start... maybe it helps?

**Configurations:**
_Enabled:_
Disable Cloud
RTSP Stream (low)
NTPD
HTTPD
Swap File

_Disabled:_
RTSP Audio
ONVIF
SSH (only activated if I need it)
FTP (only activated if I need it)
Telnet
Proxychains-ng

**Camera Settings:**
_Enabled:_
Save video when a motion is detected
Sound Detection (not sure if it's running)

_Disabled:_
AI Human Detection

**Comment by roleoroleo** [comment]
Reboot happens when the cam has no more memory.
Normally. enabling swap fix the problem.
Check if the swap file is ok by running:
`cat /proc/meminfo | grep Swap`

**Comment by Mi-Sanchez** [comment]
I bought on the last yi sale a r30gb. I don't need a swap file. Most of the time the memory is about  30408 of 60908 KB. A new revision?

**Comment by roleoroleo** [comment]
Probably yes.
If I remember correctly r30gb has only 32 MB.

**Comment by roleoroleo** [comment]
Could you please make a backup copy of the flash?

**Comment by WalkingDot** [comment]
I have uploaded a backup that I created before the hack:
r30gb_backup.zip (I sent you an invite)

**Comment by roleoroleo** [comment]
There are no difference between old r30gb and your r30gb.
I don't understand why it reboots.
