### ISSUE TITLE
Unbrick the cam, confused characters

### ISSUE THREAD

**Issue by romakrau** [roleoroleo/yi-hack-Allwinner-v2#176]
Hi, I try to unbrick my cam via rs232. I got a lot of mircale characters. Which parameters I should set to get to boot message. i'm using MobaXterm with utf-8 character-set. Greetings Roman

**Comment by roleoroleo** [comment]
If I'm not wrong 115200N81.
Try to check:
- cables (primarily GND)
- rx/tx reversed
- power supply

**Comment by romakrau** [comment]
Thanks, it was the speed I changed it 115000 .
