### ISSUE TITLE
no S/N and forgotten wifi after unplug power

### ISSUE THREAD

**Issue by MATN92** [roleoroleo/yi-hack-Allwinner-v2#180]
i've got problem with my camera. I bought it from a seller who said that after updating a  firmware camera 'bricked' [according him - only speaks Chinesse and cant add in Yi Home app or Chinesse version]. after install hack it works again, but it cant be visible S/N and also I noticed that after disconnection with power forgets wifi ssid and password [after power reset i need scan QR code from app]. Is there any possibility to add wpa_suplicant with this hack or update firmware for working YI cloud - i preferred wpa_suplicant :)

DID: BFUSY446G8QKMM200807
S/N: BY21GAEUW09027706
processor:QG2101A

![Screenshot 2021-06-02 09 44 09](https://user-images.githubusercontent.com/71932968/120521887-536c7800-c3d5-11eb-94f9-9824f23b879b.png)

**Comment by roleoroleo** [comment]
I will check it.

**Comment by roleoroleo** [comment]
Could you please make a copy of your /backup folder?

**Comment by MATN92** [comment]
here is backup before hack
[Archive.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/6587277/Archive.zip)

**Comment by roleoroleo** [comment]
I checked your files and all is ok.
Send me a copy of your /tmp/mmap.info
Pay attention to the content, hide your personal data but don't change the binary structure.

**Comment by MATN92** [comment]
where i can find nmap.info?

**Comment by roleoroleo** [comment]
In /tmp

**Comment by MATN92** [comment]
i cant find folder tmp or i havent got it... can i acess via ssh?
![Screenshot 2021-06-03 22 27 11](https://user-images.githubusercontent.com/71932968/120707702-f519c500-c4ba-11eb-82f4-29ba71db722a.png)

**Comment by roleoroleo** [comment]
Go up.
`cd /tmp`

**Comment by MATN92** [comment]
I might be doing something wrong, but here what i got:
^P^@^@^@^P^@^@^@^@^@^@^@https://api.eu.xiaoyi.com^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
^@^@^@^@^@^@^@.^G^@^@}^B^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^A^@^@^@^@^@^@^@.Q^A^@^@^@^@^@^@^@^@^@^@^@^@^BP^@^@^@^P'^@^@^@^@^@^@02544d53413136475548a9d3d80149b1
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^B^@^@^@^@^A^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
~
~
~
~
~
~

**Comment by MATN92** [comment]
i checked wpa_supplicant.conf and seems good, but why forgoted every time when power reset?
![wpa](https://user-images.githubusercontent.com/71932968/120923077-ddb22600-c6cc-11eb-96e6-615f5035699a.JPG)

**Comment by roleoroleo** [comment]
wpa_supplicant is a temporary file created when system boots up.
You can't edit it.
Please, send me mmap.info zipped as a binary file.

**Comment by MATN92** [comment]
[mmap.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/6604672/mmap.zip)
he it is...

**Comment by roleoroleo** [comment]
There is no serial number in your mmap.info
I don't know why...

**Comment by MATN92** [comment]
for now i use https://github.com/roleoroleo/yi-hack-Allwinner/issues/289 and its working, but i think is bricked sw - i cant find newer firmware from producent for y21ga [this model]

**Comment by roleoroleo** [comment]
rootfs, home and backup partitions are ok.
Did you try to reset the cam with the button?

**Comment by MATN92** [comment]
many time... every time after reset talked chinese and cant connected via Yi Home app Global or Chinesse [connected WiFi, but not YI cloud etc]... i think missing S/N is the first problem on this device...

**Comment by roleoroleo** [comment]
We could try to overwrite the partition where the cam stores sn.

**Comment by MATN92** [comment]
ok thanks

**Comment by roleoroleo** [comment]
You could try to overwrite mtd7 with this file:
[mtdblock7.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/6611767/mtdblock7.zip)

But only if you can unbrick the cam with a serial connection because it's a risky operation.

**Comment by uklatt** [comment]
I had the same problem.  Look here: https://github.com/roleoroleo/yi-hack-Allwinner-v2/discussions/383
I took mtdblock6 and mtdblock7 from an international camera and wrote it to the chinese camera.
Both models are y21ga!
Now the camera speaks english and works with yi-hack without problems ;-)

Uwe
