### ISSUE TITLE
Remove YI watermark from frames

### ISSUE THREAD

**Issue by c3kkos** [roleoroleo/yi-hack-Allwinner-v2#19]
As topic says, is it possible to remove the YI logo that appears in the lower left corner of every frames?

**Comment by roleoroleo** [comment]
I will check it but if it's like in the other cam there is nothing to do.
Read this issue: https://github.com/roleoroleo/yi-hack-Allwinner/issues/34

**Comment by c3kkos** [comment]
Ok i read.

Si even if it is not possible to disable the watermark maybe there's a trick to make it disappear.

I see from frames that the white color is somehow blended with the pic content. Like the blend mode we have in photoshop/gimp: if blend mode is "screen" or "add" maybe we can just fill the bmp full black.

Well this reminds me the UFO wall poster "i want to believe"

**Comment by c3kkos** [comment]
So here i attach the modified bmp, which is filled by the gray color of the original.

It should blend with frame content but.... i'm unable to test due to main.bmp is on a read only filesystem.

There's a trick to write onto it?

**Comment by roleoroleo** [comment]
> There's a trick to write onto it?

If you dont' want to overwrute the whole partition, the better solution is to use mount with bind option.
Check out this file: https://github.com/roleoroleo/sonoff-hack/blob/master/sdhack/boot.sh

**Comment by c3kkos** [comment]
Sorry to bother you Roleo, 

binding the file is ok.. even without upload the modified file, i ran (for test):

```
root@yicam1:/tmp# . /tmp/sd/yi-hack/script/env.sh
root@yicam1:/tmp# touch /tmp/main.bmp
root@yicam1:/tmp# mount --bind /tmp/main.bmp /home/app/main.bmp
```

and logically the logo is still there cuz it is loaded into ram. 

After binding the new main.bmp we need to restart the specific service.

**Comment by roleoroleo** [comment]
I think you can't restart processes, the system probably crashes.
You have to add the bind to the startup scripts before rmm starts.
For example in /tmp/sd/yi-hack/script/system.sh

**Comment by c3kkos** [comment]
ok i'll try asap

**Comment by roleoroleo** [comment]
Could you take a snapshot?

**Comment by c3kkos** [comment]
sure, here we have the grey watermark.

now i'll try if black is better.
![download](https://user-images.githubusercontent.com/30070329/98023009-a01fae80-1e06-11eb-87d1-3082fac232ce.jpg)

**Comment by c3kkos** [comment]
This is the results with pure black bmp.. not so different. 
![black_watermark](https://user-images.githubusercontent.com/30070329/98023824-bf6b0b80-1e07-11eb-9668-4c87b22d2561.jpg)


and this is the black bmp


[black_main.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5483155/black_main.zip)

**Comment by roleoroleo** [comment]
> And.. strange enough, the BMP after use by the cam, becomes unreadable..
> 
> if i try to force open and save it turns black. (irfanview and gimp)

Maybe it's busy.

**Comment by c3kkos** [comment]
> > And.. strange enough, the BMP after use by the cam, becomes unreadable..
> > if i try to force open and save it turns black. (irfanview and gimp)
> 
> Maybe it's busy.

But windows preview (thumbnail) works! Gimp reject it and ifranview opens it correctly! But when i overwrite the bmp within irfanview, the new picture is pure black!

I double checked this since its a weird behaviour.

**Comment by roleoroleo** [comment]
> Roleo thank you again. I'm using your stuff once again though, i remember you for your agpf firmware. What a good time!

It's been a long time...

**Comment by EsEnZeT** [comment]
@c3kkos @roleoroleo I've installed the hack FW on my camera but switching watermark ON/OFF doesn't change anything (rtsp / /cgi-bin/snapshot.sh). Do I understand correctly I can only replace (bind mount) some file in this case?

<img width="149" alt="image" src="https://user-images.githubusercontent.com/3882467/103026962-e9f65c80-454c-11eb-9263-7b4ba1d30987.png">

**Comment by roleoroleo** [comment]
Where do you switch on/off watermark?

**Comment by EsEnZeT** [comment]
Using WEB GUI:
- http://{CAM_IP}:8080/index.html?page=configurations (ONVIF watermark)

Also tried to force no watermark by visiting:
- http://192.168.1.8:8080/cgi-bin/snapshot.sh

**Comment by roleoroleo** [comment]
Yes, it's date and time in the snapshot.

**Comment by chross** [comment]
Just a little addition:
there is also a sub.bmp with 32x32 dimensions, that needs to be rebound using the same method.
