### ISSUE TITLE
Solder wires for uart bridge

### ISSUE THREAD

**Issue by lassieee** [roleoroleo/yi-hack-Allwinner-v2#2]
This is not so much an actual issue, but more to get confirmation about where to solder the wires to attach a uart bridge. 
Can you please tell if I'm correct in the location for the wires? 
![IMG_20201008_180846](https://user-images.githubusercontent.com/4531126/95485253-c3834500-0991-11eb-9c47-abcb7c3d14fa.jpg)

**Comment by danielk117** [comment]
Yes you are right. 
In theory, you don't even have to solder. You just need someone with a steady hand or some skill with tape. 😉

**Comment by lassieee** [comment]
attached is my uart logging (obtained with tremendous tape skills ;-)), perhaps it's useful.

[screen_output.txt](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5350886/screen_output.txt)

**Comment by roleoroleo** [comment]
Are you able to login with a root shell?

**Comment by lassieee** [comment]
I couldn't really test.. I had to keep my fingers on the tape lol. If I feel lucky tomorrow, I might give soldering a try and let you know :-)

**Comment by lassieee** [comment]
unfortunately no shell, or I might be doing something wrong. I tried with 'screen /dev/ttyUSB0 115200' and with putty.
I wasn't able to solder the wires. The little copper dots on the board are just too damn tiny! I lack proper tools and skills. The solder doesn't stick to the copper dots and I don't have any flux, nor have I ever used it.

**Comment by roleoroleo** [comment]
If you have no shell, we have to stop the boot process and work with u-boot.
Like the previous model.

**Comment by roleoroleo** [comment]
@lassieee 
Could you check it the wiki I wrote is ok?
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Unbrick-the-cam

Could I add your image posted above?

**Comment by lassieee** [comment]
Yes, sure you can use the picture. Happy to be of any help :-)

At step "2: List the content of the SD card:", perhaps you could change the output to include the files that are actually on the sd card for this version:
```
=> fatls mmc 0
            record/
     2502   lower_half_init.sh
            newbackup/
            yi-hack/
  1245184   mtdblock4.bin
            Factory.done/
            log/

2 file(s), 5 dir(s)
```

The flash commands are what I've used and work great. I see you already added the v2 partition table.

At step "8: Reset and cross your fingers." I would change it to:
8: Reset and cross your fingers:
`=> reset`



p.s. with the uart wires properly attached, I do have a root shell on the serial console after the cam boots.

**Comment by roleoroleo** [comment]
Ok, thanks.
