### ISSUE TITLE
Looking for y21ga

### ISSUE THREAD

**Issue by romakrau** [roleoroleo/yi-hack-Allwinner-v2#20]
Hi, I'm looking for the relaese y21ga for my YI-Home camera with the newest firmware 9.019.01_202007141512.
How can I do a backup first. I've got the backup.tar.gz and copy the backup.tar file into the root directory of a sd-card. I got a log and a record directory. No backup directory. Any help welcome. 
Greetings Roman

EDIT! Backup are completed. I'va done a mistake copy the files to SD-Card.

**Comment by c3kkos** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases

**Comment by romakrau** [comment]
Thank you for the link. I had to unbrick the cam first. After that the hack works fine. 
Thanks to roleo for this excellent peace of software. 
Greetings Roman
