### ISSUE TITLE
YI Outdoor Camera 1080p YHS.3020 - Update do not start!

### ISSUE THREAD

**Issue by Johanson2020** [roleoroleo/yi-hack-Allwinner-v2#200]
Hello,
I am in despair & need your help please.
I have the same problem, that the camera ignore the mod. firmware on the SD-Card
Firmware: 9.0.26.07_202104231123
FCC ID: 2AFIB-YHS3020
DID: IFUSY

what can I do to narrow down the problem?
Sorry but i have no idea...

Thanks a lot for your support!

![Unbenannt](https://user-images.githubusercontent.com/67189760/122773315-8dc88700-d2a8-11eb-98a3-c58b4478ceee.JPG)

![Unbenannt](https://user-images.githubusercontent.com/67189760/122773505-b3ee2700-d2a8-11eb-856b-61c2175a28a0.JPG)

**Comment by Johanson2020** [comment]
![Unbenannt](https://user-images.githubusercontent.com/67189760/122778096-f4e83a80-d2ac-11eb-872a-08e54316cce5.JPG)

my mistake...just decompress..

**Comment by roleoroleo** [comment]
Too many folders in your card.
Please remove all files and try again.
You should find in your card only these:
![immagine](https://user-images.githubusercontent.com/39277388/122929987-d5fcad80-d36b-11eb-87a4-f7a6cca1724c.png)
