### ISSUE TITLE
Dropbox CLI

### ISSUE THREAD

**Issue by davidedg** [roleoroleo/yi-hack-Allwinner-v2#204]
Hi. I managed to run [dbxcli](https://github.com/dropbox/dbxcli) on y211ga:

- [download](https://github.com/dropbox/dbxcli/releases/download/v3.0.0/dbxcli-linux-arm) arm pre-compiled binary
- put it under `/tmp/sd/yi-hack/dbxcli-linux-arm`
- make `/root` **writeable** to let it save its account data under `/root/.config/dbxcli/`:
> mkdir /tmp/root
> cp -R /root/* /tmp/root
> mount --bind /tmp/root /root
- make `/etc` **writeable** to install ssl certificate bundle where dbxcli expects it:
> mkdir /tmp/etc
> cp -R /root/* /tmp/etc
> mount --bind /tmp/etc /etc
- copy ssl certificates bundle from `/tmp/sd/yi-hack/ca-certificates.crt` (grab a copy from your favourite Linux distro):
> mkdir -p /etc/ssl/certs
> cp /tmp/sd/yi-hack/ca-certificates.crt /etc/ssl/certs/

Now you can use dbxcli (configure it once with `/tmp/sd/yi-hack/dbxcli-linux-arm account` )
(ofc the commands should be done on every boot)

@roleoroleo:
- are there any cons on the above steps ? (ie - making /root and /etc/ writeable with a bind mount) ?
- if not - do you think this could be included in a future fw version ?

Bye and Thx!
Davide.

**Comment by roleoroleo** [comment]
>     * are there any cons on the above steps ? (ie - making /root and /etc/ writeable with a bind mount) ?

This mount could be a problem.
There are many bind mounts in the file system.sh:
- mount --bind "/tmp/sd/yi-hack/etc/passwd" "/etc/passwd"
- mount --bind "/tmp/sd/yi-hack/etc/shadow" "/etc/shadow"
- mount --bind /tmp/etc /etc

We should merge them into one command.

>     * if not - do you think this could be included in a future fw version ?

The binary is very big. I prefer to keep it as an external package.
But we should prepare a repo or a package (like gdrive: https://github.com/roleoroleo/yi-hack-MStar.gdrive)
and link it to the readme or to a wiki.
