### ISSUE TITLE
KAMI WIRE-FREE OUTDOOR CAMERA - is this camera hackable?

### ISSUE THREAD

**Issue by gabaszo** [roleoroleo/yi-hack-Allwinner-v2#208]
Hello, 

I have bought this camera : https://kamihome.com/kami-wirefree
Is it possible to hack it and allow rtsp and other stuff?
cam Id is: BFUSY273TCE1MR200102
FW ver: 5.1.0.0A_202105261538

thx for any advice

**Comment by roleoroleo** [comment]
At the moment it's not supported.
Check if you are able to make a backup (see the wiki) and I will take a look.

**Comment by gabaszo** [comment]
roleo - which country are you in? 
Maybe I can send one of this cam to you?

**Comment by roleoroleo** [comment]
Italy.

**Comment by gabaszo** [comment]
unfortunately, this backup script is not working. nothing is created on SD
;(
any other idea?

**Comment by roleoroleo** [comment]
The last idea is to open the cam and take some pictures.

**Comment by RebeliusGaming** [comment]
Hi roleo. I own one of this cameras. Would you like for me to send you the information?
If so, what would you need?

**Comment by RebeliusGaming** [comment]
[wire free yi cam.zip](https://github.com/user-attachments/files/15936202/wire.free.yi.cam.zip)
This are some photos of me trying to unmount. Coulndt go further. I see no more screws, and nothing moves further. Any suggestions?

**Comment by RebeliusGaming** [comment]
![20240622_121852](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/94674848/32d0d34f-3c9a-4434-8183-7efa60528c3d)
![20240622_122530](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/94674848/50d6e579-4d3c-458d-b526-856a0aba6fad)
![20240622_122224](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/94674848/65508b7a-c98a-4670-a9fe-887f6468f591)
![20240622_122208](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/94674848/b1cb1862-2573-4118-9e7b-7d1c9d68b905)
![20240622_121928](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/94674848/b972fbad-19d7-4188-bd6b-7153518abe49)

**Comment by RebeliusGaming** [comment]
@roleoroleo just in case you have this turned off

**Comment by roleoroleo** [comment]
I have never seen a camera like this one.
But without a picture of the pcb I'm not able to understand if I can support it.

**Comment by RebeliusGaming** [comment]
Do you have any idea on how to open it without damaging?

**Comment by erela** [comment]
Hi guys,

I think the question about the platform is answered here: https://github.com/roleoroleo/yi-hack-MStar/issues/281
Seams it's not supported for a hack for now.

**Comment by RebeliusGaming** [comment]
Yes, It looks like it.
Sad news. Thank you for the heads up

**Comment by natgoodfellow** [comment]
I have a few of these cameras.  What would it take to get them supported?  I would love to be able to use them.  I'm happy to tear one apart to experiment with.

**Comment by roleoroleo** [comment]
Try to make a backup and I will check if they can be supported.

**Comment by akuznetsov-magaya** [comment]
The camera is based on Huawei LiteOS, when i put a bunch of .sh autorun files it actually runs telnet itself. There is no access to any important partitions and commands are very limited. Firmware is packed for HarmonyOS and It needs unpacker from camera to extract.
