### ISSUE TITLE
Dome U Pro - Sensor camera AI Human Detection

### ISSUE THREAD

**Issue by SmartM-ui** [roleoroleo/yi-hack-Allwinner-v2#209]
Hi,
would it be possible to display the photograph also for the AI Human Detection sensor when a human movement is detected as it already happens for the motion detection sensor (camera.yi_camera_motion_detection_image)?

Thank you

**Comment by roleoroleo** [comment]
At the moment it's not supported.
It requires a change in mqttv4 project.

**Comment by SmartM-ui** [comment]
> At the moment it's not supported.
> It requires a change in mqttv4 project.

Thanks anyway

**Comment by roleoroleo** [comment]
I will add it to my todo list.

**Comment by SmartM-ui** [comment]
Thanks!

**Comment by SmartM-ui** [comment]
Hi @roleoroleo 
in these days of vacation I was able to monitor well the motion detection sensor and the AI human detection sensor.

By leaving only motion detection active, I often had alerts (both from the official app and from the Home Assistant notification on the binary_sensor.yi_camera_movement sensor) about motion, for example when an insect passed the camera.

I activated the AI Human Detect sensor from your web page and I noticed that the official YIhome app no longer sent notifications relating to insect movements, while the binary_sensor.yi_camera_human_detection sensor was also activated by recording the video and sending me the notification that the sensor had passed to the ON state.

Would it be possible to match the binary_sensor.yi_camera_human_detection sensor to the real Human Detection sensor of the YIhome app so as to detect only human movement?

Another request, since the sensor is already present in YI-HACK, can you insert it as a switch in Home Assistant, perhaps using the same system provided for the other switches? 

<img width="792" alt="Schermata 2021-09-02 alle 15 47 10" src="https://user-images.githubusercontent.com/63554131/131861216-aebd9dd0-17a7-4dd6-aefa-3350b142903b.png">

THANKS

**Comment by roleoroleo** [comment]
> I activated the AI Human Detect sensor from your web page and I noticed that the official YIhome app no longer sent notifications relating to insect movements, while the binary_sensor.yi_camera_human_detection sensor was also activated by recording the video and sending me the notification that the sensor had passed to the ON state.
> 
> Would it be possible to match the binary_sensor.yi_camera_human_detection sensor to the real Human Detection sensor of the YIhome app so as to detect only human movement?

I need to analyze this behavior.

**Comment by SmartM-ui** [comment]
> > I activated the AI Human Detect sensor from your web page and I noticed that the official YIhome app no longer sent notifications relating to insect movements, while the binary_sensor.yi_camera_human_detection sensor was also activated by recording the video and sending me the notification that the sensor had passed to the ON state.
> > Would it be possible to match the binary_sensor.yi_camera_human_detection sensor to the real Human Detection sensor of the YIhome app so as to detect only human movement?
> 
> I need to analyze this behavior.

Hi @roleoroleo 

I did some tests both last night and now and this is the result with AI_HUMAN_DETECT ON:

When I pass in front of the camera (therefore human detection)
MQTT explorer: I can see that the human_start command is sent and immediately afterwards a series of human_stops are sent:
<img width="366" alt="Schermata 2021-09-03 alle 11 29 26" src="https://user-images.githubusercontent.com/63554131/131986840-81d7fdd0-92f2-4c80-8327-e6de47a75cf6.png">
<img width="373" alt="Schermata 2021-09-03 alle 11 29 16" src="https://user-images.githubusercontent.com/63554131/131986832-9aeb7ef8-bf41-42ce-b933-95caf86aff1b.png">
<img width="370" alt="Schermata 2021-09-03 alle 11 29 08" src="https://user-images.githubusercontent.com/63554131/131986781-07dfcfb7-3466-4932-b998-b3730ab8b942.png">
<img width="344" alt="Schermata 2021-09-03 alle 11 28 58" src="https://user-images.githubusercontent.com/63554131/131986761-a1786375-f20e-4168-8fff-125757e7f5f9.png">

Home Assistant: I can see that the binarysensor activates for a second and then automatically turns off again.

<img width="311" alt="Schermata 2021-09-03 alle 11 29 57" src="https://user-images.githubusercontent.com/63554131/131987087-36ea19a6-73e8-4a4e-9ab8-50c510155fa1.png">

On the official YIhome app I receive the notification with video of the detection (OK)
On Home Assistant I get the Human Detect notification (OK)

When I turn on a light or an insect passes in front of the camera (so it shouldn't detect human movement):
MQTT explorer: I can see that the human_start command is sent and the human_stop command is NEVER sent.
In this case the human_start command should not be sent, so it is right that the human_stop command is not sent:

<img width="364" alt="Schermata 2021-09-03 alle 11 34 50" src="https://user-images.githubusercontent.com/63554131/131987146-c0e4c5ba-0604-4c89-8686-ee12a6cb7e47.png">

Home Assistant: I can see that the binarysensor activates and is never turned off:

<img width="310" alt="Schermata 2021-09-03 alle 11 35 12" src="https://user-images.githubusercontent.com/63554131/131987193-c7860a29-ed4b-46a7-b944-6d853fb471b3.png">

On the official YIhome app I do not receive the notification with video of the detection (OK)
On Home Assistant I receive the Human Detect notification (NO)

If I can debug the check on AI_HUMAN_DETECTION or if I can help you in any way, please ask 

Thanks

**Comment by roleoroleo** [comment]
Today I tried for 2 hours but I couldn't get your behavior. When I activate human detection, my cam no longer sends me human_start.
Could you send me a screenshot of the app's detection settings?

**Comment by roleoroleo** [comment]
Please, could you test again human detection with retain=0?

**Comment by roleoroleo** [comment]
I completely rewritten the human detection.
I think there was an error in the reverse of the cam behavior.
I removed start and stop message, now there is only a detection message (like sound).

@SmartM-ui 
Do you want to try a beta? h60ga?

**Comment by SmartM-ui** [comment]
> I completely rewritten the human detection.
> I think there was an error in the reverse of the cam behavior.
> I removed start and stop messages, now there is only a detection message (like sound).
> 
> @SmartM-ui
> Do you want to try a beta? h60ga?

Hi @roleoroleo 
I would love to try and wait for this update, but as I told you I brick the Dome U Pro trying to remove your YI-HACK to update the IPcam firmware. For the moment I don't think about shooting another YI.

Thanks again for all your work and for putting my requests in your firmware. 
I enjoyed "playing" with you :-)

**Comment by roleoroleo** [comment]
Do you want to try to unbrick it?
You need only an usb-serial adapter.

**Comment by SmartM-ui** [comment]
> Do you want to try to unbrick it?
> You need only an usb-serial adapter.

Unfortunately I don't have a serial adapter.
I preferred to return the cam.
Thanks again for everything!

**Comment by cookienet** [comment]
> I completely rewritten the human detection.
> I think there was an error in the reverse of the cam behavior.
> I removed start and stop messages, now there is only a detection message (like sound).
> 
> @SmartM-ui
> Do you want to try a beta? h60ga?

I would. What do I have to do?

**Comment by roleoroleo** [comment]
I'm working on it.
I will share with you a beta asap.
Which model?

**Comment by roleoroleo** [comment]
After so many attempts I think I understand why I can't get human detection to work.
I believe the algorithm is run server side by Yi's servers. 
Because if I remove the network connection between the cam and the cloud, the detection doesn't work.
So I can't get it to work.

**Comment by roleoroleo** [comment]
Yes.
If the cam is able to connet to the server, I can see ipc messages between processes when a human is detected.
If I ban connections to api.eu.xiaoyi.com, I can't see them anymore.
Reading the ipc messages it seems that:

- The cam detects a motion
- The cam captures a snapshot and sends to the cloud
- The cloud reads the image
- The cloud sends the human detection event (if true)
