### ISSUE TITLE
Dome U Pro - Switch / Sensor for Face Detection

### ISSUE THREAD

**Issue by SmartM-ui** [roleoroleo/yi-hack-Allwinner-v2#210]
Hello,
would it be possible to provide a switch and sensor for face detection supported by the Dome U Pro? (also via MQTT)

Thank you

**Comment by roleoroleo** [comment]
My cam doesn't support face detection and I can't develop it at the moment.

**Comment by SmartM-ui** [comment]
> My cam doesn't support face detection and I can't develop it at the moment.

If you want I can volunteer for tests :-)

I'm at your service!
Thanks anyway

**Comment by roleoroleo** [comment]
I need to know if the app sends a message to the cam when you toggle the switches on/off.
Use ipc_sniff
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/168#issuecomment-862667876
Run it manually and check if you can see a numeric code when you toggle the switch.

**Comment by SmartM-ui** [comment]
> I need to know if the app sends a message to the cam when you toggle the switches on/off.
> Use ipc_sniff
> [#168 (comment)](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/168#issuecomment-862667876)
> Run it manually and check if you can see a numeric code when you toggle the switch.

Sorry, how do you use ipc_sniff? Where should I run it from?

**Comment by roleoroleo** [comment]
You can copy it to your sd card /tmp/sd using ftp after decompressing it.
Then login with ssh and run it manually /tmp/sd/ipc_sniff

**Comment by SmartM-ui** [comment]
Hi @roleoroleo 
I copied the ipc_sniff file to the microSD (via USB), creating the tmp / sd folder, but when I try to start ipc_sniff via the mac terminal, it can't find the file.
Where am I wrong?

<img width="607" alt="Schermata 2021-07-07 alle 00 30 49" src="https://user-images.githubusercontent.com/63554131/124675497-12c4ba80-debd-11eb-801f-c4b117893c22.png">

<img width="302" alt="Schermata 2021-07-07 alle 00 33 40" src="https://user-images.githubusercontent.com/63554131/124675509-18220500-debd-11eb-9e99-eb4e4c878488.png">

**Comment by WalkingDot** [comment]
@SmartM-ui

**Comment by WalkingDot** [comment]
@SmartM-ui

**Comment by SmartM-ui** [comment]
> @SmartM-ui
> The "tmp" folder is only available if the cam is running.
> If you copy it via usb, you can place ipc_sniff into the root of your sd-card.
> Than with ssh you can find the file here: /tmp/sd/ipc_sniff

Hi,
I put the file directly into the microSD root, but when I launch it with / tmp / sd / ipc_sniff, it reports "Segmentation fault".

For info, I have formatted the microSD directly from the cam, the macbook does not read it and the partition with Windows detects that there is an error in the microSD, but I can still use it and write. I have tried several microSDs and they all have the same behavior.

PS can you recommend a free FTP software for MacOS?

<img width="464" alt="Schermata 2021-07-07 alle 09 48 32" src="https://user-images.githubusercontent.com/63554131/124721330-4fb69e80-df09-11eb-9ef6-3b05108435d1.png">

**Comment by WalkingDot** [comment]
> it reports "Segmentation fault".

Then try the following:
1. `killall ipc_multiplexer`
2. `/tmp/sd/yi-hack/bin/ipc_multiplexer &`

Than toggle the app settings how roleoroleo has described.
**When you are done you should restart the camera.**


> formatted the microSD directly from the cam

Maybe because the cam is formating at sector 2. My linux machine has no problems with it.


> FTP software for MacOS?

I don't have a mac but I like filezilla and it is also available for mac. (filezilla-project.org)

**Comment by SmartM-ui** [comment]
> > it reports "Segmentation fault".
> 
> Then try the following:
> 
>     1. `killall ipc_multiplexer`
> 
>     2. `/tmp/sd/yi-hack/bin/ipc_multiplexer &`
> 
> 
> Than toggle the app settings how roleoroleo has described.
> **When you are done you should restart the camera.**
> 
> > formatted the microSD directly from the cam
> 
> Maybe because the cam is formating at sector 2. My linux machine has no problems with it.
> 
> > FTP software for MacOS?
> 
> I don't have a mac but I like filezilla and it is also available for mac. (filezilla-project.org)

Perfect,
it worked! After I try to check the settings and bring them back to Roleoroleo

<img width="474" alt="Schermata 2021-07-07 alle 12 55 27" src="https://user-images.githubusercontent.com/63554131/124747908-c1e7ad00-df22-11eb-95ae-b86995f2387b.png">

**Comment by SmartM-ui** [comment]
Hi @roleoroleo 
this is the data that is detected when I press the Home and Not_Home button from the YIhome app 

![Screenshot_20210707-152636_YI Home](https://user-images.githubusercontent.com/63554131/124767693-54df1200-df38-11eb-9237-35e52e43dcd1.jpg)


Not_Home:
IPC message. Len: 20. Status: No error information!
Parsing message.
01 00 00 00 04 00 00 00 8e 00 01 00 04 00 00 00 00 dd 6d 00 

Home:
IPC message. Len: 20. Status: No error information!
Parsing message.
01 00 00 00 04 00 00 00 8e 00 01 00 04 00 00 00 00 dd 6d 00 

I hope it can be used for the switch and synchronization with Home Assistant

**Comment by SmartM-ui** [comment]
Hi @roleoroleo 
this is the data that is detected when I press the face detection from the YIhome app:

Face detect ON
IPC message. Len: 20. Status: No error information!
Parsing message.
01 00 00 00 08 00 00 00 3d 10 01 00 04 00 00 00 01 00 00 00 

Face detect OFF
IPC message. Len: 20. Status: No error information!
Parsing message.
01 00 00 00 08 00 00 00 3d 10 01 00 04 00 00 00 00 00 00 00

**Comment by roleoroleo** [comment]
Ok, now try to send these messages.
1 - Save the binary code (20 bytes) into a file (use hxd if you are a windows user).
2 - Use the command `ipc_cmd -x file.bin`
3 - Refresh the app and check if the switch is changed.

**Comment by SmartM-ui** [comment]
Hi,
this code turns face detection on and off from the YIhome app 

Face detect ON
01 00 00 00 08 00 00 00 3d 10 01 00 04 00 00 00 01 00 00 00

Face detect OFF
01 00 00 00 08 00 00 00 3d 10 01 00 04 00 00 00 00 00 00 00

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/ccea78899b1e781771222a0975f9cf3fcfcb6593

**Comment by SmartM-ui** [comment]
Hi @roleoroleo 
the Face Detection sensor, after the firmware update to version 0.1.9, manages to perfectly enable the sensor on the official YIHome app.

You are GREAT!

Would it be possible to implement the motion tracking switch as you did for the other sensors via MQTT?

<img width="792" alt="Schermata 2021-09-02 alle 15 47 10" src="https://user-images.githubusercontent.com/63554131/131858996-f36b621c-2259-4c28-a3eb-bfd24241dd99.png">

**Comment by roleoroleo** [comment]
> Would it be possible to implement the motion tracking switch as you did for the other sensors via MQTT?

I didn't implement the advertise part. It was a contribution from EnricoFerro.
Do you want to try to make a pr?

**Comment by SmartM-ui** [comment]
> > Would it be possible to implement the motion tracking switch as you did for the other sensors via MQTT?
> 
> I didn't implement the advertise part. It was a contribution from EnricoFerro.
> Do you want to try to make a pr?

If you show me how to do it, gladly!
We can also ask @EnricoFerro for support?
