### ISSUE TITLE
Completely turn off night mode.

### ISSUE THREAD

**Issue by tonkado** [roleoroleo/yi-hack-Allwinner-v2#214]
Is it possible somehow disable detecting of the low light conditions and/or switching to night mode?

I want to use cam (IFUS) to monitor door eye hole and it's working fine 2 secs... until it switches to the night mode.
Maybe somewhere in the firmware we can set something like:

```
if (light_conditions_low):
  # nightmode_on()
  # --do nothing--
```
@roleoroleo

Any ideas? )

**Comment by roleoroleo** [comment]
This behavior is handled entirely by yi's software and I can't change it.
Sorry.

You could try with a hardware hack.

**Comment by tonkado** [comment]
@roleoroleo, appreciate your quick response.
>>You could try with a hardware hack.
I will try. But it sounds easier than it look inside after disassembling )

Thanks anyway!
