### ISSUE TITLE
Select hidden ESSIDs

### ISSUE THREAD

**Issue by johannes-mueller** [roleoroleo/yi-hack-Allwinner-v2#217]
The wifi configuration page has a dropdown menu to select among the available ESSIDs the one to connect to. However, it does not seem to be possible to manually type an ESSID in order to to a hidden network.

Could this feature be added?

Thanks

**Comment by roleoroleo** [comment]
I'm working on this feature.

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/bef4dbaef965926b4c29ccf2e87d3d52efdbeaa6

**Comment by johannes-mueller** [comment]
Works in 0.1.9. Thanks a lot.
