### ISSUE TITLE
Mibao D700

### ISSUE THREAD

**Issue by ezruneko** [roleoroleo/yi-hack-Allwinner-v2#222]
Hi,

I have a Mibao D700 and i have the dump file using the backup.tar.gz.

Is it possible to add compatibility with this amazing firmware?

Thank you

**Comment by roleoroleo** [comment]
It depends on the platform.
Share your backup with me and I will take a look.

**Comment by pcaro90** [comment]
I also have a Mibao D700 (which seems to be the same found in the issue #124, model q321br). Is there anything I could do to help adding support to this camera? Do you already have a backup? If not, I could send you mine.

**Comment by pcaro90** [comment]
I forked the project and added preliminary support for this model. It seems to be working nicely, I just tried PTZ controls, RTSP and snapshots, and they all seem to be working. I'll test it more thoroughly over the following days.

**Comment by roleoroleo** [comment]
> I also have a Mibao D700 (which seems to be the same found in the issue #124, suffix q321br). Is there anything I could do to help adding support to this camera? Do you already have a backup? If not, I could send you mine.

I already have the backup file if the model is q321br_lsx
If your model is q321br without _lsx then is different.
In this case, please share your backup with me.

**Comment by pcaro90** [comment]
Sure thing, there you go: https://we.tl/t-bpyL3BW3id

**Comment by roleoroleo** [comment]
Thank you.
File downloaded.

**Comment by roleoroleo** [comment]
The exact model is q321br_lsx
Check backup/init.sh

**Comment by pcaro90** [comment]
You're right, my bad; I saw the "q321br" string (without "_lsx") somewhere inside the backup files and assumed that was it.

**Comment by ezruneko** [comment]
i've try to dismount my camera to check the chip but not luck and i've tried to install qg311r hack but any port was opened and the cam was soft-bricked, i've extract the sd and after 2 restart i've recovered it.

Did you need my backup? i've shared with you and screenshot of my research.

![photo1637307910](https://user-images.githubusercontent.com/1853429/142584887-386bd176-79eb-4924-ad5b-e00dfca6a302.jpeg)
![backup](https://user-images.githubusercontent.com/1853429/142584890-b3ceb008-4615-40ee-aaa0-7303239721c2.png)

**Comment by roleoroleo** [comment]
If you share with me your backup, I can try to add the support for this cam.
But I need a backup before you apply the hack.

**Comment by ezruneko** [comment]
could you send me an email (my email in my profile) to send you the link to download the firmware please?
Thank you

**Comment by roleoroleo** [comment]
Check the email address in the paypal link.

**Comment by ezruneko** [comment]
i can't find it. i've uploaded to mega. https://mega.nz/file/75tlwAiR#h3tJuPyeliHh1SThgGX7KpmmkoRYz6IAA7ODwcSFjig

**Comment by roleoroleo** [comment]
Please, try this beta:
[q321br_lsx_0.1.9.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7574244/q321br_lsx_0.1.9.tar.gz)

Could you please confirm that it's a ptz cam and the resolution is 3k?

**Comment by ezruneko** [comment]
The cam is this https://www.amazon.es/gp/product/B08FCDJDZ9/ref=ppx_yo_dt_b_asin_image_o00_s00?ie=UTF8&psc=1

And yes it's a ptz cam and the resolution in the specs is 1296x 2304 (1296P).

Today asap i will test the beta and i will write my feedback. thank you!

**Comment by ezruneko** [comment]
bricked, i've extracted the sd and the cam doesn't started to the default firmware.

**Comment by roleoroleo** [comment]
Are you able to get a log with a serial connection?

**Comment by ezruneko** [comment]
no, it's complicated to dismount the case to me and i haven't got a serial cable to do it.

**Comment by roleoroleo** [comment]
Please try this binary.
Clear your SD and unzip the archive.
[backup_q321br_lsx.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7582853/backup_q321br_lsx.gz)

**Comment by ezruneko** [comment]
i've tried it but it's bricked :( no motion or sound when i've started. thank you to try it with me

**Comment by roleoroleo** [comment]
Weird. This solution should work.
Is the led on?
Is the power adapter/cable ok?

**Comment by roleoroleo** [comment]
If led and power are ok, please another try:
[backup_q321br_lsx.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7583377/backup_q321br_lsx.gz)

**Comment by ezruneko** [comment]
Yes, it's connected and the cable and charger is OK. I've supposed that not run because after the brick i've extracted the micro sd and format in the pc in fat32 to install in a rpi. last time when i've installed the firmware, i've needed to format the microsd in the cam with the yi iot app.

**Comment by mimogh** [comment]
Hi 👋 i need firmware caméra mibao d600 please 🥺

**Comment by mimogh** [comment]
Hi 👋 i need firmware caméra mibao d600 please
