### ISSUE TITLE
RTSP only when wifi is enabled. No RTSP by ethernet.

### ISSUE THREAD

**Issue by Camaca71** [roleoroleo/yi-hack-Allwinner-v2#224]
Hi, I am experiencing with a very odd behaviour.
RTSP works fine only when I connect the camera to wifi (by using the "Network" section of index.html page of webserver.
If I disable wifi the RTSP does not work. 
Thank you for you help

**Comment by roleoroleo** [comment]
What's your model?

**Comment by Camaca71** [comment]
Yi Dome Guard. 
Hack version r30gb.

**Comment by roleoroleo** [comment]
What client are you using?

**Comment by Camaca71** [comment]
VLC Media Player
Moreover the video is not visible on webserver too (localhost:8080/ptz)

**Comment by Camaca71** [comment]
Note: after a few checks, I notice that the audio stream is available and running on VLC.

**Comment by Camaca71** [comment]
Does anyone have any suggestion?

**Comment by roleoroleo** [comment]
> VLC Media Player
> Moreover the video is not visible on webserver too (localhost:8080/ptz)

PTZ page doesn't show a stream, but a low rate sequence of snapshot.

> Does anyone have any suggestion?

No, sorry.
