### ISSUE TITLE
Disable snapshots

### ISSUE THREAD

**Issue by SmartM-ui** [roleoroleo/yi-hack-Allwinner-v2#226]
Hi,
unfortunately with the Dome U Pro, even by enabling the swap file on the SD, when a movement is detected and the photograph is then taken, the camera freezes for a few seconds and then restarts, but I noticed that it remains "slow" anyway.

Is it possible to avoid taking the photograph upon detection or to have it saved only in low resolution? 

Thank you

**Comment by roleoroleo** [comment]
Remove the topic motion_detection_image and the cam will not take a snapshot.

**Comment by SmartM-ui** [comment]
> Remove the topic motion_detection_image and the cam will not take a snapshot.

Hi,
I try to remove it from the MQTT section of your YIHACK webpage.

<img width="766" alt="Schermata 2021-07-09 alle 11 40 54" src="https://user-images.githubusercontent.com/63554131/125058912-0605b980-e0ab-11eb-8c92-24d0be8a319a.png">


However, for information, when only detection is active (disabling human detection), the live view, when it does not freeze to take the image, is slowed down and often goes forward two seconds at a time.

It is not possible to shoot it in low resolution, just to try if the problem is less obvious.
Now, perhaps, it should take 2 images at a time, one in high resolution and one in low resolution:

High res snapshot | http://IP:8080/cgi-bin/snapshot.sh?res=high&watermark=yes
-- | --
Low res snapshot | http://IP:8080/cgi-bin/snapshot.sh?res=low&watermark=yes

**Comment by roleoroleo** [comment]
If you disable the snapshot, the cam should works better.
It's not possible to change the resolution in the motion snapshot, it's hardcoded:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/master/src/mqtt/dir.patch

**Comment by SmartM-ui** [comment]
> If you disable the snapshot, the cam should works better.
> It's not possible to change the resolution in the motion snapshot, it's hardcoded:
> https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/master/src/mqtt/dir.patch

I haven't tried to disable the option yet, but I have seen that it works much better, and without any freeze, by also activating the AI Human Detect from your WebPage. Obviously in this way, the snapshot is not taken.

I have to try to check if it is possible to take an image directly from Home Assistant when the detection sensor is activated.
