### ISSUE TITLE
Yi outdoor 1080 not hack

### ISSUE THREAD

**Issue by yaronagar** [roleoroleo/yi-hack-Allwinner-v2#228]
I need help, Where am I wrong?, I download the latest version, everything I do fails, yi cam outdoor 1080
I try with 4 different sd card
IFUSY59UGGUV0A201222
Version: 9.0.26.07_202104231123

**Comment by roleoroleo** [comment]
Which archive are you trying? h30ga?
Is the folder "Factory" renamed to "Factory.done"?
