### ISSUE TITLE
Which file for my camera?

### ISSUE THREAD

**Issue by soundylinz** [roleoroleo/yi-hack-Allwinner-v2#229]
I'm not sure which file to flash for my camera?

I currently selected https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/download/0.1.8/h30ga_0.1.8.tgz, but not sure if that was correct? 

Here is the packaging for my camera:

![20210722_165914](https://user-images.githubusercontent.com/70177555/126661713-220eb2d1-514a-4a7e-a603-b7885d645a12.jpg)

**Comment by roleoroleo** [comment]
What is your firmware revision?

**Comment by soundylinz** [comment]
I've tried "y211ga", it works - with a few problems (example: ftp upload)

Base Version | 9.0.36.02_202105081647

**Comment by roleoroleo** [comment]
Yes, your file is y211ga.
