### ISSUE TITLE
Turn Microphone off and on

### ISSUE THREAD

**Issue by tunerooster** [roleoroleo/yi-hack-Allwinner-v2#234]
When playing audio through the camera speaker, I am getting feedback because the microphone is on and is picking up the audio from the speaker.  I noticed there is a feature in the `YI app` to turn the `microphone off/on`.  Can a feature be added to `ipc_cmd` to turn the mic off and on?  E.g.,
```
ipc_cmd -c on                  # -c MIC switch on or off the mic
```
Another idea, in addition to the above feature...  Would it be a good idea to _always_ turn off the mic when playing through the camera speaker?

This is regarding: **YI Outdoor 1080p IFUSY59UOS Model: YHS.3020**
```
name":"yi-hack-allwinner-v2",
"hostname":"backdoor",
"fw_version":"0.1.8",
"home_version":"9.0.26.07_202104231123",
"model_suffix":"h30ga",
"ptz":"no",
"serial_number":"",
"local_time":"Thu Jul 29 08:51:10 GMT 2021",
"uptime":"1575.18",
"load_avg":"2.31 2.52 1.98",
"total_memory":"60912",
"free_memory":"30492",
"free_sd":"97%",
"local_ip":"192.168.1.75",
"netmask":"255.255.255.0",
"gateway":"192.168.1.111",
"mac_addr":"64:E0:03:3A:ED:03",
"wlan_essid":"tunerooster",
"wlan_strength":"51" 
```
As always. thanks for a very well done hack!

**Comment by roleoroleo** [comment]
So, you would like to switch off the mic when the speaker is playing.
And switch on again when the audio is finished.
Right?

**Comment by tunerooster** [comment]
Yes, that would be fine (at least I can't think of a downside to that
strategy for my purposes), but I also think adding an option to ipc_cmd
would be useful.

Thanks so much for your great hack.  It has *totally* enhanced and extended
my camera automation capabilities!

**Comment by roleoroleo** [comment]
I tried to sniff the system when I swith on the mic from the app but I didn't find a suitable message linked to this action.
I also tried to find a gpio but nothing.
I will study it again the next week.

**Comment by tunerooster** [comment]
On my YI App, for this camera, there is a switch to turn off the mic, so
apparently it is possible.  I don't see the option on my other camera
models.

Outdoor 1080p IFUSY59UOS Model: YHS.3020

 Thanks for your efforts!

**Comment by roleoroleo** [comment]
Could you take a snapshot of this switch?

**Comment by tunerooster** [comment]
Did you ever get the snapshot of the MIC switch?  I sent it weeks ago to you by email.  I.e., I "shared" it and so it wasn't clear to me how to post it here.

I am attaching it again here...
![Screenshot_20210913-200750](https://user-images.githubusercontent.com/13290146/133183046-0a4cc0f1-ddaf-4a33-ad77-28bfe033ba00.png)

Does this feature request look doable?

**Comment by roleoroleo** [comment]
Sorry, I didn't receive your previous message.
This is the code when the mic is switching off:
02 00 00 00 08 00 00 00 2a 10 01 00 04 00 00 00 65 00 00 00
and on:
02 00 00 00 08 00 00 00 2a 10 01 00 04 00 00 00 64 00 00 00

I think it's possible to add a command to ipc_cmd

**Comment by tunerooster** [comment]
Outstanding!  Thanks!

Do you have any preference for the option letter to use for MIC on/off.  I see you used "-c" for face detection.

**Comment by tunerooster** [comment]
I just realized, I don't have the tools to build the ipc_cmd binary.  I will gladly add the code to ipc_cmd.h and ipc_cmd.c and send you a patch if you will build it?

**Comment by roleoroleo** [comment]
No problem, I will edit the files myself.

**Comment by roleoroleo** [comment]
Here it is:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/fe5a18b91744ce4d8914e87c5c3a155d97b275f5

**Comment by tunerooster** [comment]
You're the **best**!   Looking forward to a new ipc_cmd, speak.sh and speaker.sh

**Comment by tunerooster** [comment]
Were you going to post the updated ipc_cmd and speak scripts?  Or did I miss something?

Sorry for the confusion on my part...

**Comment by roleoroleo** [comment]
I'm testing them but something is wrong.

**Comment by tunerooster** [comment]
No problem.  I just wanted to make sure I didn't miss something.

Thanks as always...

**Comment by tunerooster** [comment]
Don't mean to push, but have you had any luck with this yet?

**Comment by roleoroleo** [comment]
No.
I believe there is a conflict between the yi firmware and my command.
Probably yi switch on and off the microphone when I play a sound.
I'm trying to understand.

**Comment by tunerooster** [comment]
I much appreciate your effort and thanks for the update!

**Comment by roleoroleo** [comment]
I tested the command but it works only with the app.
If I disable the mic, rtsp stream contains audio.
I don't know how to disable it in a different manner.

**Comment by tunerooster** [comment]
I understand.  It sounds like that's all the option does.  Too bad...  Do
you also hear feedback from the mic when the camera speaker plays?
