### ISSUE TITLE
Only a grey screen via IP

### ISSUE THREAD

**Issue by Noel1337** [roleoroleo/yi-hack-Allwinner-v2#24]
I flashed my yi cam with the BFUSY tag and the FW 9.0.19.02_202007141512 Flashing process seemed to run great but after the light turned blue i tried to conect via the IP and something seems to be there since i dont get the "unavailable" site but sadly i only get a grey screen... I could realy need some help

**Comment by roleoroleo** [comment]
How are you trying to connect?
ssh, http?
