### ISSUE TITLE
Mibao 1296p G1

### ISSUE THREAD

**Issue by colab999** [roleoroleo/yi-hack-Allwinner-v2#240]
Hi, I've got a MIBAO G1 1296p dome camera (similar to this one [https://www.amazon.it/B098X5KY23/](https://www.amazon.it/B098X5KY23/)). I opened it up and the chip on it is marked as QG2101B, which lead me here. 
I tried (at my own risk) all the firmware that supports ptz.  Ptz works fine, ssh, telnet and httpd are working, but rtsp and onvif do not work. Only with r30gb firmware, I sometimes manage to get a solid green low res snapshot, with the timestamp impressed.
I've managed to dump the backup from the webcam LINK REMOVED.
If you have any suggestion or need any other files or information, please let me know. 
Thank you for your work.

edit: forgot to mention that the version reported by the YI IoT app is 9.0.04.99

**Comment by roleoroleo** [comment]
@colab999 
Hi colab 999, could you share a copy of your /dev/shm/fshare_frame_buf?
I need it to fix a bug in the RTSP server.

**Comment by colab999** [comment]
@roleoroleo sorry for the delay.

[https://bashupload.com/i4hvs/Qowhe.](https://bashupload.com/i4hvs/Qowhe.)

note the final dot . in the link. 
Downloaded it using ssh browser tab from mobaxterm

**Comment by roleoroleo** [comment]
I think the link is expired.
Could you post it again?

**Comment by colab999** [comment]
[https://bashupload.com/rveoR/g2iwp.](https://bashupload.com/rveoR/g2iwp.)

here it is. dot at the end.

**Comment by roleoroleo** [comment]
Thank you.

**Comment by colab999** [comment]
Hi @roleoroleo,
I've updated to v3.0.0, but i noticed that during the daylight hours, the high stream is very glitchy. Is this issue related to the bug you mentioned? I also tried the alternative rtsp server, but it didn't improved. Tried with swap on and off, and nothing changed.

Thank you.
Buon Natale

**Comment by roleoroleo** [comment]
Maybe.
Please try this beta version:
[qg311r_0.3.0.tgz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13762357/qg311r_0.3.0.tgz)

**Comment by colab999** [comment]
Hi! The video now seems to be working much better! Both streams enabled and streaming at the same time with audio. Some compression artifacts, but related to the low spec of the camera.

However, it seems that the stream stops for one minute every 10-15 minutes (i use frigate for recording), but i'm not sure if it is related to a wifi problem or something is crashing. Do you have any suggestion on how to debug the issue?

Anyway, thank you again!

**Comment by roleoroleo** [comment]
It could be:
- Crash and reboot of the cam: check if the cam is alive when the stream stops.
- Crash and reboot of the rtsp daemon: list the processes and check if rRTSPServer is running when the stream stops.

Are you using snapshots?
Did you enable swap file?

**Comment by colab999** [comment]
No, i'm not using snapshots (disabled them from settings) and swap file was not enabled. 

I disable some other services (onvif and no audio on stream) and now it seems more stable. However, when the camera went down, the http page was reacheable the whole time and in addition the rtsp server seemed to be running at the time, so i cannot exclude a problem on my side (low wifi).

But now i've noticed that the ptz left and right are not working. Before the update, they worked inverted (left was right and viceversa), but now it does not move. At boot, however, it fully rotates and if i enable cruise mode with the ipc_cmd command, it moves. I quickly checked the commits on the ipc_cmd module, but i do not see any difference in the ptz command.
