### ISSUE TITLE
Motion detection doesn't work in general -- y21ga -- allwinnerV2 0.1.8

### ISSUE THREAD

**Issue by Pulsar981** [roleoroleo/yi-hack-Allwinner-v2#242]
y21ga -- allwinnerV2 0.1.8
offline use no internet but wifi, no Yi app, no other app, just with web interface

Hi,
unfortunately I can't get my motion detection running, no matter which combination of settings I try (I've tried a lot). When I set the option "save video when a motion is detected" to off, the cam records constantly 1min-videos - this is correct behaviour as described there. I see the videos in the web interface in the Events section. When I activate this option, it should only record when a motion is detected, but no videos are recorded. Directing the cam on a near TV to ensure constant motion. I don't see new records in the Events section, nor on the SD card.
I thought maybe it's because date+time are not correct causing the system not to work correctly, so I set up a time server app (since I'm using the cam offline) and have correct date+time now - this did not solve the problem. 
I also added a line in the eventsfile.sh like described in a similar issue by roleoroleo (https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/218). I kept the entry "y211ga", even that my model is y21ga - did not help. Then I renamed it to my model name - did not help.
I tried around with cloud dis-/enabled, recording with cloud dis-/enabled, with MQTT dis-/enabled and other settings. Reset the cam and hacked again. Would appreciate help.

Here are my current settings:
#camera.conf
SWITCH_ON=yes
SAVE_VIDEO_ON_MOTION=yes
SENSITIVITY=high
AI_HUMAN_DETECTION=no
SOUND_DETECTION=no
SOUND_SENSITIVITY=80
LED=no
ROTATE=no
IR=no

#system.conf
HTTPD=yes
TELNETD=no
SSHD=no
FTPD=no
BUSYBOX_FTPD=no
DISABLE_CLOUD=yes
REC_WITHOUT_CLOUD=yes
MQTT=no
RTSP=no
RTSP_STREAM=high
RTSP_AUDIO=no
SPEAKER_AUDIO=yes
ONVIF=no
ONVIF_WSDD=no
ONVIF_PROFILE=high
ONVIF_NETIF=wlan0
ONVIF_WM_SNAPSHOT=yes
NTPD=yes
NTP_SERVER=1.1.1.1:1
PROXYCHAINSNG=no
SWAP_FILE=no
RTSP_PORT=554
ONVIF_PORT=80
HTTPD_PORT=8080
USERNAME=
PASSWORD=
TIMEZONE=CET-1CEST,M3.5.0,M10.5.0/3
FREE_SPACE=0
FTP_UPLOAD=no
FTP_HOST=
FTP_DIR=
FTP_DIR_TREE=no
FTP_USERNAME=
FTP_PASSWORD=
FTP_FILE_DELETE_AFTER_UPLOAD=no
SSH_PASSWORD=
CRONTAB=

**Comment by roleoroleo** [comment]
Try to enable motion detection from the app.
I know that you don't use the app but try to activate it  only for the startup configuration.

- Enable cloud
- Configure yuour settings from the app
- Disable cloud

**Comment by mcsshs** [comment]
> Try to enable motion detection from the app.
> I know that you don't use the app but try to activate it only for the startup configuration.
> 
> * Enable cloud
> * Configure yuour settings from the app
> * Disable cloud

I have the same problem. I did your suggestions, but the problem remained. :(
Model Suffix: y21ga
Firmware Version: 0.1.9

**Comment by roleoroleo** [comment]
Let's start from scratch. We need to check if the problem is mqtt or the detection of the event.
If you use the app, does motion detection works?
Do you receive notification messages when a motion is detected?

> Directing the cam on a near TV to ensure constant motion.

This is not a good idea because this is a single event, until the motion stops.
You have to alternate a still image with a movement.

**Comment by Maxym77** [comment]
my y21ga send a lot of MQTT motion message every 1/2/3 minutes... is bugged

**Comment by roleoroleo** [comment]
Are you sure that the image doesn't change?
My cam sends a motion message when I leave the phone in the kitchen and the led blinks.
