### ISSUE TITLE
r30gb stucks after connecting to wifi, even without hack

### ISSUE THREAD

**Issue by areyoufserious** [roleoroleo/yi-hack-Allwinner-v2#243]
i applied hack, everything worked for 30 mins, then stucked
i reset the camera and even can't finish the default setup, camera tells that connected to wifi, then stuck and restart

can you please help me?

**Comment by areyoufserious** [comment]
also after tries i see file in logs folder log_no_wifi_dev.tar.gz
[log_no_wifi_dev.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7073712/log_no_wifi_dev.tar.gz)

**Comment by roleoroleo** [comment]
Maybe the hack is not completed successfully.
Try to unhack the cam and reset with the back button.

**Comment by areyoufserious** [comment]
if you mean unbricking section, unfortunately, i don't have USB flashed to do that
is there any way?

**Comment by roleoroleo** [comment]
I mean "Remove the hack".
Unbrick is the last try.

**Comment by areyoufserious** [comment]
sure, remove sd card was my first idea

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Remove-the-hack
