### ISSUE TITLE
Yi app cannot play back saved video

### ISSUE THREAD

**Issue by gunthre** [roleoroleo/yi-hack-Allwinner-v2#245]
Forgive me if this has already been made obvious (I searched through the issues and didn't find anything relevant), but once the hack has been applied, I cannot get the Yi app (Android) to play back saved video.  It will show live video just fine, and on the time scale bar it can see where video has been saved, but when I try to scroll back to watch video it just jumps right back to live video.

I have all the main video features disabled (RTSP, ONVIF, MQTT).  I just like the hack because of the web-based configuration, and the SSH/FTP access.  I use the app for everything else.  Is my use case unsupported?

I have an older Yi Home indoor camera with the yi-hack applied (I think it's hi-hack-v2) and the app works without issue.

Thanks very much!

My setup: Yi Outdoor 1080p IFUS, firmware 9.0.26*, using file h30ga.

**Comment by gunthre** [comment]
That did it! Thanks so much!!

Coupla beers headed your way!

**Comment by roleoroleo** [comment]
Thank you.
