### ISSUE TITLE
Should it work with camera IY21GA...

### ISSUE THREAD

**Issue by enboig** [roleoroleo/yi-hack-Allwinner-v2#250]
I have a camera with a serial number starting with IY21GA... (date: 2020.11). I don't know the firmware version because I tried to flash it before pairing (to avoid firmware upgrade). I tried the y21ga_0.1.9 firmware but it didn't work. Should it work? (and the problem is the sdcard) Or it is another model?

Thanks

**Comment by roleoroleo** [comment]
Without firmware version is not possible to know the model.
Try to create a backup following the wiki and share it with me. I will check the model inside the file system.
