### ISSUE TITLE
Gdrive loader. Is this possible?

### ISSUE THREAD

**Issue by losika12** [roleoroleo/yi-hack-Allwinner-v2#27]
From this:
https://github.com/roleoroleo/yi-hack-MStar.gdrive

I have followed the steps but I get the error "/ tmp / sd / yi-hack / gdrive / GDriveConf: line 218: curl: not found" However, curl is in this path

**Comment by roleoroleo** [comment]
Which curl did you use?

Try using this guide:
https://github.com/roleoroleo/yi-hack-Allwinner.gdrive
I don't know it it works but is the same platform and you have binary compatibility.

**Comment by losika12** [comment]
Oh excuse me.
I tried this and had the same error. I have done the process from scratch with another SD card and the problem has been fixed. Thank you!
