### ISSUE TITLE
Ai Human Detection non funziona

### ISSUE THREAD

**Issue by piesinopoli** [roleoroleo/yi-hack-Allwinner-v2#271]
Sul firmware y21ga installato sulla mia Yi Home Camera 1080p, non funziona Ai Human Detection.

Uso il tuo firmware con la tua integrazione su Home Assistant e credo che il problema sia qui nel firmware e non nell'integrazione. Leggevo in qualche altra issue che hai riscritto quella parte, ho capito bene?

Funzionano tutte le altre entità tranne sound detection e ai human detection.
Per un progetto che sto facendo vorrei riuscire a fare funzionare la seconda, grazie.

**Comment by ErliPan** [comment]
> [#209 (comment)](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/209#issuecomment-928009979)
> 
> I will remove it in the next commit.

A me Ai Human Detection funziona perfettamente con firmware v0.1.8 e camera y211ga. Le telecamere sono in una VLAN isolata dietro OPNsense quindi non hanno accesso a internet

**Comment by ErliPan** [comment]
Disable cloud True
Recording Without Cloud True
RSTP True

Switch on/off the camera True
Save video when motion is detected True
Detection sensitivity True
AI Human Detection True
Sound Detection False


This is the url I call when setting up a camera

`f"http://{self.ip}:8080/cgi-bin/camera_settings.sh?save_video_on_motion=yes&sensitivity={self.sensitivity}&ai_human_detection=yes&sound_detection=no&sound_sensitivity=80&led={status}&ir=yes&rotate=no&switch_on={status}"`

**Comment by piesinopoli** [comment]
Ma a te funziona su Home Assistant?

**Comment by ErliPan** [comment]
> Ma a te funziona su Home Assistant?

Non lo uso con HA

**Comment by roleoroleo** [comment]
Quindi non usi mqtt giusto?
Credo che @piesinopoli nel primo post volesse dire che non va la notifica mqtt su human detection.

**Comment by piesinopoli** [comment]
Si esatto, ma se a lui funziona potrebbe essere un problema sull'integrazione o no? Rimuoverai la funziona lo stesso?

**Comment by ErliPan** [comment]
Allora ho capito male perché avendo letto https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/209#issuecomment-928009979 e https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/271#issuecomment-937630438 ho pensato che la funzione verrà rimossa.

**Comment by roleoroleo** [comment]
Verrà rimossa solo la funzionalità del messaggio mqtt su human detection.

**Comment by fabiosoft** [comment]
la mia yi dome ogni volta che manda un messaggio di movent su mqtt crasha e si riavvia...

**Comment by roleoroleo** [comment]
Did you enable swap space?
