### ISSUE TITLE
DOME U PRO - Remove original timestamp

### ISSUE THREAD

**Issue by zimgui** [roleoroleo/yi-hack-Allwinner-v2#275]
Hello, I have an YI DOME U PRO with base version 9.0.27.20_202108161046 and firmware 0.1.9 (h60ga) that works great but in snapshot and rtsp stream appear 2 timestamps, one from YI and another one from hack, is it possible to remove the original one?

Pd: I have two YI Dome U (h51ga) where the original timestamp is always removed without any additional configuration.

Thanks in advance.

**Comment by helmbrandt** [comment]
h60ga

same problem here, I thought it might be the wrong timezone or something, but setting it right doesnt change the original timestamp, like it shouldnt.

**Comment by 0-Al** [comment]
If I understand correctly disabling watermark leaves just the original Yi date and time overlay. Also Yi time zone should be set to zero and real time zone should be set in Yi-Hack for correct local time providing you have a time reference such as NPT.

**Comment by zimgui** [comment]
And here and example from another camera (h51ga) working fine

![image](https://user-images.githubusercontent.com/33359092/137969179-681599aa-c80c-463b-925e-1d325e8857ff.png)

**Comment by zimgui** [comment]
Sure this upper-left timestamp is added in new h60ga PRO cameras, thanks again Roleo.

**Comment by roleoroleo** [comment]
I found a new experimental method to add/remove the upper-left timestamp.
If you want to try.
Dump current status:
`# hexdump -C -n 16 /tmp/mmap.info`
Enable:
`# printf "\01\00\00\00\x10\00\00\00\00\00\00\00" | dd of=/tmp/mmap.info bs=1 count=12 conv=notrunc`
Disable:
`# printf "\x10\00\00\00\x10\00\00\00\03\00\00\00" | dd of=/tmp/mmap.info bs=1 count=12 conv=notrunc`

**Comment by ErliPan** [comment]
@roleoroleo I tried the command on the Yi Dome Guard and it didn't work. Anything else I could try?

Also here's what the first command returns
`root@yi-827e:~# hexdump -C -n 16 /tmp/mmap.info`
`00000000  10 00 00 00 10 00 00 00  03 00 00 00 68 74 74 70  |............http|`
`00000010`
