### ISSUE TITLE
Can we check the firmware version without using the Yi app?

### ISSUE THREAD

**Issue by justynspooner** [roleoroleo/yi-hack-Allwinner-v2#279]
I'd like to avoid signing up for a Yi account if at all possible. Is there another way to check the firmware version of a brand new Yi 1080p Home Camera?

**Edit**
Am I right in saying that the Yi app is required in order to set the camera up and there is no other way around this? If so, then I may have to create a Yi account.

**Comment by 0-Al** [comment]
A few ways, easiest might be to make a backup and read version from /home partition (block3?). Unsquash / 7zip block and read homever file. I don't have that camera so haven't tried it.

**Comment by justynspooner** [comment]
Thank you, that worked a treat.

It's a Yi 1080p Home Camera IFUS
The firmware version is: `9.0.19.09_202010291747`

For my future self or anyone else that finds this and wondering how to unsquash the backup bin files on OSX to find the version number, you can use the following:

Do a backup of your Yi firmware using the instructions here:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)

Download and install [Homebrew](https://brew.sh) or just run
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
Then install `squashfs`
```
brew install squashfs
```
Restart terminal and now you can extract the binaries using
```
unsquashfs ../path/to/your/mtdblock3.bin
```
Now read the contents of the file at `squashfs-root/homever`
```
cat squashfs-root/homever 
```
and you'll get your firmware version, something like: `9.0.19.09_202010291747`

**Comment by justynspooner** [comment]
Ah… so I believe I've now installed the firmware. How can I connect it to my network and use it without using the Yi app?

**Comment by roleoroleo** [comment]
@justynspooner 
I have a question about the solution you used (https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Change-WiFi-credentials)
This procedure was created to change wifi credentials when the hack didn't allow this.
This is why I moved to "deprecated".

I need to know the correct sequence: did you apply this method after the hack? Or before?

**Comment by kikecalpe** [comment]
I suggest to add something to the backup script that copies the firmware version, so we can know what firm the backup belongs to, and we can also check it to avoid signing up for a Yi account.
Something like:
`cp /home/homever /tmp/sd/backup/`

**Comment by roleoroleo** [comment]
Yes, I will add it to the backup procedure.
