### ISSUE TITLE
not installing on two BFUS

### ISSUE THREAD

**Issue by loginsistemas** [roleoroleo/yi-hack-Allwinner-v2#28]
Hi.

I just received two Yi home 1080. Both are "BFUS..." and came with factory firmware 9.0.19.02_202007141512

I formatted a 16GB SD inside the camera. Copied files from yi-hack-Allwinner-v2 0.1.2 "y21ga_0.1.2.tgz".

But unfortunately firmware isn't installed. The first time that camera boots from microsd, the orange led blinks once (and only once). Then it become fixed again and quickly turns blinking blue and then fixed blue. The firm is not altered at all and the boot process doesn't take much more time than original.

Tested in both cameras with same results. It's not my first "hacked" yi, so i think i'm doing it in the right way. 

Any clue about what's my mistake?

P.D. Not having success with v2, I tried v1. I know, BFUS is for firm 18..., but i had to try. Off course, it didn't work neither.

**Comment by roleoroleo** [comment]
> I formatted a 16GB SD inside the camera. Copied files from yi-hack-Allwinner-v2 0.1.2 "y21ga_0.1.2.tgz".

Did you decompress the archive?

**Comment by loginsistemas** [comment]
> > I formatted a 16GB SD inside the camera. Copied files from yi-hack-Allwinner-v2 0.1.2 "y21ga_0.1.2.tgz".
> 
> Did you decompress the archive?

Oh, sure! I forgot to talk about this step.

**Comment by d-paw** [comment]
So there are two of us, @loginsistemas 
I've got exactly the same problem as you do.
The orange led blinks once. Then it become fixed again and quickly turns blinking blue and actually connects to wifi. There's no "flashing" going on.

**Comment by mcanteri** [comment]
Guys, did you try to connect to the camera http://192.168.X:X:8080/ ?  Put your address there

**Comment by chechilll** [comment]
Cant flash my yi 1080p home camera BFUS.
I open the camera and got Y29GA_MB_V2.1 2020/04/07 with firmare 9.0.19.02_202007141512
Chipset QG2101A L1026AA
I tryed with diferents SD's, all in fat32 format.
Put the files downloaded from --> https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases --> file y21ga_0.1.2
I decompress the folder and put in the SD. Put the SD and power on the camera.
I've tried several times. Never work, always boot normal. Got ERR_CONNECTION_REFUSED if i put the http://IP_CAM:8080
SSh conection refused also

Please help, i'm desperated


![image](https://user-images.githubusercontent.com/57603613/99558616-3554a280-29c4-11eb-8a97-af1f3f5f1a65.png)

**Comment by d-paw** [comment]
> Guys, did you try to connect to the camera http://192.168.X:X:8080/ ? Put your address there

You are a legend, works like a charm!

**Comment by roleoroleo** [comment]
@chechilll 
Factory.done means that the hack worked.
Check again your connection.

**Comment by loginsistemas** [comment]
> Guys, did you try to connect to the camera http://192.168.X:X:8080/ ? Put your address there

OMG. Stupid mistake, I was triying port 80, like in other hacks. It's working fine. Maybe the confussion came from how easy is to apply the patch (just one blink doesn't looked to me like a firm update), and chinesse cloud continued to work as usual.
Now i have a CAM that doesn't connect to China or any other place.

Thank you and sorry for the waste of time. Thread can be closed.

**Comment by chechilll** [comment]
Hello roleoroleo ,
It's not a connection problem. If the hack works, i've the followinf problems.
I'm reaching the IP address with ping.

![image](https://user-images.githubusercontent.com/57603613/99664968-46a3ba80-2a69-11eb-9eda-533991b243de.png)

I'm not able to connect with no one browser, as you can see it says connection refused as i said.

![image](https://user-images.githubusercontent.com/57603613/99665095-72bf3b80-2a69-11eb-9dc0-a4bb32b1ef2d.png)

Also cant connect with SSH to port 22, connection refused

![image](https://user-images.githubusercontent.com/57603613/99665158-8a96bf80-2a69-11eb-91a6-c0812a569372.png)

**Comment by roleoroleo** [comment]
The correct address is http://192.168.1.244:8080

**Comment by chechilll** [comment]
Thanks but i know. I read the posts :) I'm not newby
I tryed exactrly http://192.168.1.244:8080

![image](https://user-images.githubusercontent.com/57603613/99687594-1ff37d00-2a85-11eb-839c-fd9ca2f7aaf3.png)

**Comment by roleoroleo** [comment]
Try to remove the hack and to apply it again.

**Comment by chechilll** [comment]
Same result.
Can see the image via yi home app but with explorer connection refused, SSH connection refused
