### ISSUE TITLE
MQTT Camera Settings Advertise on r30gb

### ISSUE THREAD

**Issue by snico2** [roleoroleo/yi-hack-Allwinner-v2#280]
Hi roleo, I have a issue with "MQTT Advertise".

Issue io only on r30gb model & 0.1.9 Version
The h201c model work well (but it has yi-mstar hack)

When I enable "Camera Settings" (it doesn't matter what values Onboot and Periodic have)
the firmware send mqtt publish Birth messages in loop (every 1 seconds)

The others flag (Global Information & Telemetry )work well

The script mqtt_set_config.sh is active as well as the mosquitto_sub process 

  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 1777     1 root     S      988  1.6   0  0.0 {mqtt_set_config} /bin/sh /tmp/sd/yi-hack/script/mqtt_advertise/mqtt_set_config.sh
    1     0 root     S      980  1.6   0  0.0 /sbin/init
 2337  2267 root     S      980  1.6   0  0.0 -ash
 3028  1366 root     S      980  1.6   0  0.0 sleep 10
 1318     1 root     S      980  1.6   0  0.0 udhcpc -i wlan0 -b -s /backup/tools/default.script -x hostname:yitest
  544     1 root     S      980  1.6   0  0.0 -/bin/sh
 1272     1 root     S      876  1.4   0  0.0 dropbear -R -B -p 0.0.0.0:22
 1244     1 root     S      860  1.4   0  0.0 httpd -p 8080 -h /tmp/sd/yi-hack/www/ -c /tmp/httpd.conf
 1303     1 root     S      860  1.4   0  0.0 ntpd -p pool.ntp.org
 1405     1 root     S      860  1.4   0  0.0 /tmp/sd/yi-hack/usr/sbin/crond -c /var/spool/cron/crontabs/
 1258     1 root     S      844  1.3   0  0.0 pure-ftpd (SERVER)
 1811  1777 root     S      820  1.3   0  0.0 /tmp/sd/yi-hack/bin/mosquitto_sub -i yitest -v -C 1 -h 192.168.1.41 -p 1883 -u yahas -P yahas -t yahas/camera_setting/+/set
 

From mosquittio server log is seems that mosquitto_sub 
continuously creates new connections to the server

I don't know what process name done the PUBLISH  

D:\mosquitto>mosquitto -v -c mosquitto.conf
1634723034: mosquitto version 1.6.9 starting
1634723034: Config loaded from mosquitto.conf.
1634723034: Opening ipv6 listen socket on port 1883.
1634723034: Opening ipv4 listen socket on port 1883.
1634723034: Opening ipv6 listen socket on port 8883.
1634723034: Opening ipv4 listen socket on port 8883.
1634723034: Opening websockets listen socket on port 18083.
1634723055: New connection from 192.168.1.201 on port 1883.
1634723055: New client connected from 192.168.1.201 as yitest (p2, c1, k120, u'yahas').
1634723055: Will message specified (24 bytes) (r1, q1).
1634723055:     yahas/virtual/reply/camtest/camtest/status
1634723055: Sending CONNACK to yitest (0, 0)
1634723056: New connection from 192.168.1.201 on port 1883.
1634723056: Received PUBLISH from yitest (d0, q1, r1, m1, 'yahas/virtual/reply/camtest/camtest/status', ... (23 bytes))
1634723056: Sending PUBACK to yitest (m1, rc0)
1634723056: New client connected from 192.168.1.201 as yitest_c (p2, c1, k15, u'yahas').
1634723056: No will message specified.
1634723056: Sending CONNACK to yitest_c (0, 0)
1634723056: Socket error on client yitest_c, disconnecting.
1634723063: New connection from 192.168.1.201 on port 1883.
1634723063: Client yitest already connected, closing old connection.
1634723063: New client connected from 192.168.1.201 as yitest (p2, c1, k60, u'yahas').
1634723063: No will message specified.
1634723063: Sending CONNACK to yitest (0, 0)
1634723063: Received SUBSCRIBE from yitest
1634723063:     yahas/camera_setting/+/set (QoS 0)
1634723063: yitest 0 yahas/camera_setting/+/set
1634723063: Sending SUBACK to yitest
1634723064: New connection from 192.168.1.201 on port 1883.
1634723064: Client yitest already connected, closing old connection.
1634723064: New client connected from 192.168.1.201 as yitest (p2, c1, k120, u'yahas').
1634723064: Will message specified (24 bytes) (r1, q1).
1634723064:     yahas/virtual/reply/camtest/camtest/status
1634723064: Sending CONNACK to yitest (0, 0)
1634723064: Received PUBLISH from yitest (d0, q1, r1, m2, 'yahas/virtual/reply/camtest/camtest/status', ... (23 bytes))
1634723064: Sending PUBACK to yitest (m2, rc0)
1634723065: New connection from 192.168.1.201 on port 1883.
1634723065: Client yitest already connected, closing old connection.
1634723065: New client connected from 192.168.1.201 as yitest (p2, c1, k60, u'yahas').
1634723065: No will message specified.
1634723065: Sending CONNACK to yitest (0, 0)
1634723065: Received SUBSCRIBE from yitest
1634723065:     yahas/camera_setting/+/set (QoS 0)
1634723065: yitest 0 yahas/camera_setting/+/set
1634723065: Sending SUBACK to yitest
1634723066: New connection from 192.168.1.201 on port 1883.
1634723066: Client yitest already connected, closing old connection.
1634723066: New client connected from 192.168.1.201 as yitest (p2, c1, k120, u'yahas').
1634723066: Will message specified (24 bytes) (r1, q1).
1634723066:     yahas/virtual/reply/camtest/camtest/status
1634723066: Sending CONNACK to yitest (0, 0)
1634723066: Received PUBLISH from yitest (d0, q1, r1, m3, 'yahas/virtual/reply/camtest/camtest/status', ... (23 bytes))
1634723066: Sending PUBACK to yitest (m3, rc0)
1634723067: New connection from 192.168.1.201 on port 1883.
1634723067: Client yitest already connected, closing old connection.

The 2 PID (1777 & 1811) don't crash, but the connetion with mqtt crash 

Other strange thing is the "client name" yitest_c, who it is ?

1634723056: New client connected from 192.168.1.201 as yitest_c (p2, c1, k15, u'yahas').

My ipcam hostname is yitest

1634723055: New client connected from 192.168.1.201 as yitest (p2, c1, k120, u'yahas').

**Comment by roleoroleo** [comment]
Check il the client ids are unique.
mosquitto_sub uses the hostname as a client id: "-i yitest"
mqttv4 uses the parameter configured in the MQTT web page: "Client ID" field.
mqtt-config uses the same field with "_c" appended at the end.

You can't connect 2 different clients with the same client id.
