### ISSUE TITLE
 Speak through camera (TTS / audio upload PPT)

### ISSUE THREAD

**Issue by fabiosoft** [roleoroleo/yi-hack-Allwinner-v2#286]
I repost here... avoid writing in other repo.

I updated to 0.1.9 and browsing to speak.html page... the UI is really nice.
But i click on TTS or upload a wav file nothing happens, and the camera is quite. 

I installed the engine for tts and nothing changes...
Wav file format seems correct... i converted the file using the specs you provided. (S16LE / 8 KHz, 16 bit, mono)

Here is a VLC file information:
<img width="552" alt="137207957-5251c11e-1b89-4010-b60b-2c13cdd20f91" src="https://user-images.githubusercontent.com/812037/138360825-bed93e76-55ea-41f0-be69-8ec903ad5770.png">

How can i use this feature?
I tried on a y21ga and r30gb models

**Comment by Giulianini** [comment]
@roleoroleo news for speak through camera?

**Comment by Giulianini** [comment]
I'm using y20ga and all winner V1. The speaker.sh file of allwinner V1 is different from V2. They don't have to be the same?

**Comment by roleoroleo** [comment]
They are different, yes.

**Comment by d0m1n1qu3** [comment]
i have also the problem to hear something and found aout that in v 0.19 th cgi-bin/speaker.sh use the command "speaker on" but this it not in path .. if i do it over ssh with 
`root@yi-cam-1:~# /tmp/sd/yi-hack/bin/speaker on
Running ioctl: num 16
root@yi-cam-1:~# cat /tmp/sd/yi-hack/samples/Front_Center.wav > /tmp/audio_in_fifo
root@yi-cam-1:~# /tmp/sd/yi-hack/bin/speaker off
Running ioctl: num 17
root@yi-cam-1:~# 
`
it works fine
so i think i could be also you problem?
can we fix it in 0.20?

**Comment by roleoroleo** [comment]
speak.cgi should inherit PATH variable from httpd daemon, but I can add it to the next release to avoid any problem.
But @Giulianini is running on a different cam, where speaker command doesn't exist (no need to move the gpio to activate the speaker).

**Comment by Giulianini** [comment]
Ok thanks @roleoroleo

**Comment by Staini** [comment]
If I'm use the speak html page, the sound output is working.

But if I'm use the terminal, there is no sound output:
`cat /tmp/sd/speak.pcm > /tmp/audio_in_fifo`

The **speak.pcm** is created by commenting out the rm line 77:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/32d33cafdbd752e7c15b02cb11e4565826de3e84/src/www/httpd/cgi-bin/speak.sh#L77
The file should 100% working.

Am I doing something wrong?
