### ISSUE TITLE
1080p AI+ (BFUS) bricked with no backup

### ISSUE THREAD

**Issue by tomascrespo** [roleoroleo/yi-hack-Allwinner-v2#292]
Hi! Someway I have bricked my 1080p AI+ (BFUSY4), only orange steady light.
 
I have no backup to follow the unbrick procedure, so  could I do it some other way?

Lots of thanks

**Comment by roleoroleo** [comment]
What's the prefix of your cam?

**Comment by DerpyDoom** [comment]
I'm currently facing the same Problem. I wanted to use my Cam after I stored it for quite some time. I had no sdcard in it. Tried to get the latest Firmware on the card but no luck.

My cam used the Y21GA Firmware. No Backup available.

**Comment by roleoroleo** [comment]
Try this:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/305#issuecomment-980365447
