### ISSUE TITLE
Camera still phones home

### ISSUE THREAD

**Issue by xzaz** [roleoroleo/yi-hack-Allwinner-v2#293]
Can you disable the connection ping to 

`api.eu.xiaoyi.com` my PiHole still notice this phone home every 3 seconds? I disabled the cloud option.

**Comment by roleoroleo** [comment]
It should already be disabled:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/d44a3fe29c17aa51e37614e3161b146907c18101/src/static/static/yi-hack/script/system.sh#L165

**Comment by xzaz** [comment]
Yhe. It's a RTFM for me, had to reboot.

**Comment by 1-Al** [comment]
What about the others?
```
        mount --bind /tmp/etc /etc
        echo "127.0.0.1    api.eu.xiaoyi.com" >> /etc/hosts
        echo "127.0.0.1    api.us.xiaoyi.com" >> /etc/hosts
        echo "127.0.0.1    api.xiaoyi.com.tw" >> /etc/hosts
        echo "127.0.0.1    log.eu.xiaoyi.com" >> /etc/hosts
        echo "127.0.0.1    log.us.xiaoyi.com" >> /etc/hosts
        echo "127.0.0.1    log.xiaoyi.com.tw" >> /etc/hosts
```

**Comment by roleoroleo** [comment]
I will add them.
