### ISSUE TITLE
Fuckup during flashing

### ISSUE THREAD

**Issue by marithpl** [roleoroleo/yi-hack-Allwinner-v2#294]
I bought new Yi 1080p

First thing I did is download a y21ga_0.1.9 file and copy to SD Card.
Device was welcome me by sound and now I have a "Waiting for connection" sound.

How Should I connect to the device? There is no SSID in my WiFi networks.

**Comment by marithpl** [comment]
Ok, I downloaded Yi Home app.

It should be in manual, I think :)

**Comment by roleoroleo** [comment]
I will add it to the readme.
