### ISSUE TITLE
CAUTION - Using unhack in h60ga bricks my cam

### ISSUE THREAD

**Issue by zimgui** [roleoroleo/yi-hack-Allwinner-v2#295]
I used the unhack tool h60ga in a YI Dome U PRO with hack installed, it seems to work fine (the sd rename factory dir to factory.done) but my cam remains with yellow light every time I reboot it, no way to connect or make it boot.

**Comment by 1-Al** [comment]
Unfortunately the manufacturer left very little free space on that model's backup partition (mtdblock4.bin) which can cause problems when writing or replacing files there. 

Have you recovered this yet?
