### ISSUE TITLE
Stuck out of the control panel

### ISSUE THREAD

**Issue by omerbitas** [roleoroleo/yi-hack-Allwinner-v2#297]
Hi,
I have a model Yi 1080p Home, hardware IFUS, with firmware 9.0.36 and y211ga installed.
Everything worked fine, i've followed the instruction on the Home Assistant integration page and set an FTP password and username [as requested](https://www.home-assistant.io/integrations/yi/). 
once i've reset the camera, I cannot access the managing system, even with the credentials Ive just set.
can these be reset somehow?
this is the login request im getting:
![image](https://user-images.githubusercontent.com/49685964/141172101-0ac06999-c74e-4a47-94ac-3c463707391c.png)
Thanks,

**Comment by omerbitas** [comment]
Nevermind,
I just needed to login with no password...

**Comment by omerbitas** [comment]
Thought it got solved but im still stuck.

**Comment by roleoroleo** [comment]
This integrations isn't compatible with new yi models.
Please try this:
https://github.com/roleoroleo/yi-hack_ha_integration

**Comment by omerbitas** [comment]
I ended up using the ONVIF integration.
works fine. still cant set a password as it locks me out.
