### ISSUE TITLE
Not able to update firmware

### ISSUE THREAD

**Issue by aalllop** [roleoroleo/yi-hack-Allwinner-v2#30]
I have downloaded the files of the project but i'm not able to flash firmware. Are files correct? My cam is BFUS serial with firmware 9.0.19

**Comment by roleoroleo** [comment]
Did you follow the update procedure described?

**Comment by Murada99** [comment]
Exactly same serial BFUS and firmware 9.0.19 and same problem. The camera does not boot from the SD (formatted with the camera) but starts the YI solution.

**Comment by aalllop** [comment]
The tgz files not contain a firmware like in the other projects. Maybe are they incorrect?

**Comment by roleoroleo** [comment]
Yes, it's correct.

**Comment by aalllop** [comment]
But have i got to compile the firmware and then flash it?

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2#update-procedure

**Comment by aalllop** [comment]
I have extracted y21ga_0.1.2.tgz on my sd card, pluged into the cam and powered on and nothings happended. The tar.gz file is full of folders and files, not 2 files with de firmware as the other git projects

**Comment by roleoroleo** [comment]
This fw is different. It works using sd as a file system.
Because the home partition is read only.
A lot of files in the sd is normal and you can't remove the card.

**Comment by Murada99** [comment]
@aalllop : same problem, I have extracted the same file to my SD Card (formatted with the camera) and nothing happens when I restart the camera.

**Comment by jmtemmos** [comment]
same here. nothing happens. No update

**Comment by aalllop** [comment]
I have tried again and the firmware was uploaded. The cam doesn't seem to upgrade but it did. To test it you can go to http://IP-CAM:8080/cgi-bin/snapshot.sh and you will se a snapshot

**Comment by Murada99** [comment]
OK, it seems to work and I get access with http://ipcam:8080. 
Great !

**Comment by gabaszo** [comment]
same here. nothing happens. No update  for Dome Guard model (Production model: YRS.3019)

**Comment by Tomasinjo** [comment]
Can't get it to boot from the SD.
Model YRS.3019
R30GB_IN_V1_O 2019/11/04

Can someone check we have identical versions?

**Comment by Murada99** [comment]
@Tomasinjo: When it says waiting to connect, follow the setup of the camera with the YI application. When it's done, insert the SD card and restart the camera. When restarted, check the the following address http://ip_of_camera:8080.

**Comment by Tomasinjo** [comment]
Thanks, it works now. I just bought it and didn't even bother with their cloud service :)
