### ISSUE TITLE
Support for "Xiaomi Mi 360° Home Security Camera 2K Pro" (MJSXJ06CM)?

### ISSUE THREAD

**Issue by odya** [roleoroleo/yi-hack-Allwinner-v2#301]
Do you have plans to support new 2K xiaomi cameras? 
There is a GitHub project for cheaper version (MJSXJ05CM) but it seems to be dead https://github.com/cmiguelcabral/mjsxj05cm-hacks

**Comment by roleoroleo** [comment]
I think this cam is based on mstar platform.
But the file system is very different.
It requires a completely new hack.
