### ISSUE TITLE
Firmware IFUSY32O4H

### ISSUE THREAD

**Issue by IvanDeMarco** [roleoroleo/yi-hack-Allwinner-v2#307]
Hi,
I have an YI Home Camera 3 (IFUSY32O4H), which firmware should I use?

Thanks!

**Comment by roleoroleo** [comment]
You need the Yi firmware version to know which hack to use.
Check the Yi app.
In the meantime, make a backup (see the wiki).

**Comment by IvanDeMarco** [comment]
Yi firmware is 8.3.0.0A_201912271707 (the last version).
Please help me.
Thanks!

**Comment by roleoroleo** [comment]
I think it's a y25ga: https://github.com/roleoroleo/yi-hack-Allwinner

**Comment by IvanDeMarco** [comment]
It works!
