### ISSUE TITLE
What difference do these settings make?

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#309]
![image](https://user-images.githubusercontent.com/12989749/143662355-a5064d38-b180-4558-9441-a43eba991834.png)
More video? different file names? I don't know

**Comment by roleoroleo** [comment]
They are a replica of the settings you find in the app.
You can enable/disable various detections, if your cam supports them.
For example, if you enable "Sound detection" the cam will send you a notification when it detects a sound.

**Comment by PilaScat** [comment]
But if they aren't synchronized with the app what they do?
I don't understand what use they have
