### ISSUE TITLE
Yi Dome Guard compatability?

### ISSUE THREAD

**Issue by gabaszo** [roleoroleo/yi-hack-Allwinner-v2#31]
Can I use this custom FW for Dome Guard model (Production model: YRS.3019)?

**Comment by HoussamOtarid** [comment]
I would say yes, as I am doing that myself. The firmware is in beta version for the Dome Guard though.

Something additional you could check is that your product number (somewhere on the package label) should start with "*FUS" (mine starts with "KFUS"), and somewhere else on the package you should have the text "r30gb".

**Comment by gabaszo** [comment]
I can find model: YRS.3019 and in SN r30gb
But when I copy all files from repot to root SD, and rebooting it-- nothing gonna happens.
SD is accessible for recording, and stock firmware is still used.

**Comment by Murada99** [comment]
Didi you try to login with a browser at the following address http://cameraIP:8080 ?

**Comment by gabaszo** [comment]
yes-- is not possible to open, means is not working

**Comment by roleoroleo** [comment]
Try to chane the sd card.
r30gb hack should work.

**Comment by gabaszo** [comment]
yep-- is working with a different SD. Thank you

**Comment by tobal93** [comment]
> sí, está trabajando con una SD diferente. Gracias

What file should I download for dome guard?

**Comment by roleoroleo** [comment]
If it's r30gb version, r30gb_0.1.2.tgz is your file.

**Comment by tobal93** [comment]
> Si es la versión r30gb, r30gb_0.1.2.tgz es su archivo.

 it is a dome guard but it is KR30GB and when putting the file into it it does not start

**Comment by roleoroleo** [comment]
Try the backup procedure and check if it works.

**Comment by tobal93** [comment]
> Pruebe el procedimiento de copia de seguridad y compruebe si funciona.

I remove the card and if the camera works but with stock firmware, and when putting sd with hack it does not start

**Comment by Technikhouse** [comment]
Hello,

I have buy (https://kamihome.com/dome-R30/)

can me someone explane to Hack this cam.

I Have checked with r30gb_0.15 but not working, the cam restart but the webserver is not working.

This files on the SD

![file](https://user-images.githubusercontent.com/80832787/112205027-a88d5000-8c14-11eb-8da9-6c30f64d75b5.png)

**Comment by Technikhouse** [comment]
![cam ](https://user-images.githubusercontent.com/80832787/112205700-56006380-8c15-11eb-9561-507b370c81c4.jpg)

**Comment by roleoroleo** [comment]
If the folder Factory is not renamed to Factory,done the hack didn't work.
Probably it isn't an r30gb.
