### ISSUE TITLE
Timezones not working correctly

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#310]
For italy I need GMT0BST,M3.5.0/1,M10.5.0, but I have to set london time to be right

**Comment by roleoroleo** [comment]
Check this https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/246
and this https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/203#issuecomment-918762012

**Comment by PilaScat** [comment]
Thanks, now works perfectly
