### ISSUE TITLE
y28 bootloop

### ISSUE THREAD

**Issue by beamwerks** [roleoroleo/yi-hack-Allwinner-v2#315]
hooray for this project.  just tried on my kami home (fw 9.0.20) with y28ga_0.1.9 and having the same boot loop as described in this issue

https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/5

**Comment by roleoroleo** [comment]
Please try the unbrick procedure described here:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/tree/master/unbrick
or here:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Unbrick-the-cam

**Comment by beamwerks** [comment]
should have been clearer.  camera boots fine when i remove the sd card and works as normal pre hack.

it's just when i try the y28 software, it goes into the yellow light / short blue light and briefly working / then yellow light loop

**Comment by roleoroleo** [comment]
Try to enable swap space.

**Comment by beamwerks** [comment]
boom.  just had to catch it that setting in while the url was briefly working.    works great now.  donation sent.  cheers!

**Comment by 1-Al** [comment]
If the camera is too unstable for applying settings AFAIK you could manually change it by editing the setting in the 'yi-hack/etc/system.conf' SDCard file on a different device. Not much help to you now but might help someone else later.

**Comment by roleoroleo** [comment]
@beamwerks 
Thank you for your donation!
