### ISSUE TITLE
[FEATURE REQUEST] Add custom delay for motion detection snapshot via mqtt

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#318]
Come abbiamo detto su yi-hack-ha-integration, servirebbe un delay per la snapshot cam, così almeno cattura qualcosa

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/85af33eb1b1cc4cf2844965d252413dc5c2b17ae

**Comment by PilaScat** [comment]
Okay mi avevi detto di scriverlo qua ma sono un po' in ritardo ahah
