### ISSUE TITLE
[FEATURE REQUEST/FIX] Increase TTS volume or add custom volume

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#319]
Sempre come abbiamo detto sull'integrazione per ha, servirebbe più volume su yi-speak, che è bassissimo

**Comment by roleoroleo** [comment]
This should be possible changing pcm data on the fly when I send them to the alsa lib.
I need to study it.

**Comment by PilaScat** [comment]
Okay, take your time (btw preferisci l'italiano e l'inglese qua su github?)

**Comment by roleoroleo** [comment]
English is better, thx.
