### ISSUE TITLE
Yi Outdoor 1080p IFUS

### ISSUE THREAD

**Issue by emadwealthsimple** [roleoroleo/yi-hack-Allwinner-v2#321]
Hey, there I have been trying to install the hack on the camera for the past 2 days with no luck.

I have tried different sd cards and files and versions. 

I installed it from https://github.com/TheCrypt0/yi-hack-v4/releases 
- yi hack outdoor zip 

But it only has two files the home_h30 file and roots_h30 file, I was looking at other issues and other people were uploading four files two of them being folders.

Can someone please help me out this is my first time trying something like this?

**Comment by roleoroleo** [comment]
It depends on the model of your cam.
Check your fw version in the mobile app.

**Comment by emadwealthsimple** [comment]
Model is YHS.3020
Version Number is 9.0.26

**Comment by roleoroleo** [comment]
See here:
https://github.com/roleoroleo/yi-hack-Allwinner-v2
h30ga

**Comment by emadwealthsimple** [comment]
Is it just these two files?

<img width="1274" alt="Screen Shot 2021-12-17 at 10 47 13 PM" src="https://user-images.githubusercontent.com/82470881/146627913-07072659-d799-4d76-b344-8eb1ee90d0a3.png">

**Comment by roleoroleo** [comment]
No, download the archive from the release page.

**Comment by emadwealthsimple** [comment]
Just did that now. Camera had yellow light for around 30 seconds and then blue light flashed then blue light on.

Getting an error when I try to access from IP address and from http://IP-CAM:8080

**Comment by roleoroleo** [comment]
Check the content of the sd card.
Is the Factory folder renamed to Factory.done?
