### ISSUE TITLE
YI Dome Guard QFUS r35gb

### ISSUE THREAD

**Issue by Rushmed** [roleoroleo/yi-hack-Allwinner-v2#323]
Hi,

my new cam YI Dome Guard QFUS r35gb FW: 9.0.46 arrived today.
Tried flashing r30gb and r40ga without success.
Is there any chance to get the cam hacked?

**Comment by roleoroleo** [comment]
I need a backup of the flash to check if I can support it.

**Comment by Rushmed** [comment]
[backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7740610/backup.zip)

Prego!

**Comment by roleoroleo** [comment]
This file should grant telnet/ssh access.
[r35gb_0.1.9.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7741219/r35gb_0.1.9.tar.gz)

Now I need a copy of the framebuffer file /dev/shm/fshare_frame_buf

**Comment by Rushmed** [comment]
[fshare_frame_buf.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7741301/fshare_frame_buf.zip)

Here it is!

**Comment by roleoroleo** [comment]
Please, test this archive.
[r35gb_0.1.9.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7741518/r35gb_0.1.9.tar.gz)
It should work.
You could find problem with rtsp, snapshot and/or ptz.

**Comment by Rushmed** [comment]
Thanks soo much!

Shoud I give feedback here or should I open issues if I find some?

**Comment by roleoroleo** [comment]
Here.
Probably we will need to change a few more bits.

**Comment by Rushmed** [comment]
- Serial number is not shown:
![image](https://user-images.githubusercontent.com/59259796/146796639-9a66204f-42dd-4ff2-a080-37c2550b3433.png)

- RTSP is working fine. Tested both streams wit VLC and tinyCam.

- ONVIF PTZ is working for pan and tilt. The zoom is not working. Tested with tinyCam Pro

- Snapshot is working but there is an additional timestamp at the top left corner which does not show the correct time. The cam is not a european model so I needed to choose American server at YiHomeApp to get the cam logged in. Its possibly a DST issue. Timezones are set up correct in the app and in the cams web UI. 
![image](https://user-images.githubusercontent.com/59259796/146813200-29972d7b-41ca-40d5-b39f-c3cd7ce9f23c.png)

Thats what I figured out so far. I tested the points you mentioned and set up the cam the way I did with my other hacked Yi cams. Every thing else seem to be fine. Of course this was not an in depth test.

**Comment by roleoroleo** [comment]
Zoom? Does the camera have a zoom?

You should set GMT in the app and set the correct time in the configuration web page.

The serial number is not ok. Please read the file /tmp/mmap.info with hexdump and tell me the offset of the serial number "QFUS..."

**Comment by Rushmed** [comment]
Zoom is menitoned on the package and [here](https://www.yitechnology.com.sg/products/yi-dome-guard/).
![image](https://user-images.githubusercontent.com/59259796/146817878-65e149be-efb5-4ca8-a2d0-6970466a3fff.png)

How to set GMT? This is the App setting:
![tempFileForShare_20211220-195246](https://user-images.githubusercontent.com/59259796/146818115-c70af622-4cda-4746-8c55-b30bb5e4e388.jpg)
and this is the web UI setting:
`CET-1CEST,M3.5.0,M10.5.0/3`
Should be correct for Germany.

I do not know/own hexdump. Tried wit NPP:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/59259796/146819498-064b28cd-d071-4b89-b777-4b20dcc9c6d5.png">
Cursor is after QFUS at position 789.

**Comment by roleoroleo** [comment]
> Zoom is menitoned on the package and [here](https://www.yitechnology.com.sg/products/yi-dome-guard/). ![image](https://user-images.githubusercontent.com/59259796/146817878-65e149be-efb5-4ca8-a2d0-6970466a3fff.png)
>

I think that this is a feature of the app. Not available on the cam.
But I could investigate.

> How to set GMT? This is the App setting: ![tempFileForShare_20211220-195246](https://user-images.githubusercontent.com/59259796/146818115-c70af622-4cda-4746-8c55-b30bb5e4e388.jpg) and this is the web UI setting: `CET-1CEST,M3.5.0,M10.5.0/3` Should be correct for Germany.

In the app, set GMT0 universal... (I don't remember exactly the name).
The web ui is correct.

> I do not know/own hexdump. Tried wit NPP: <img alt="image" width="650" src="https://user-images.githubusercontent.com/59259796/146819498-064b28cd-d071-4b89-b777-4b20dcc9c6d5.png"> Cursor is after QFUS at position 789.

hexdump is embedded in the hack, you can run it using ssh.

**Comment by Rushmed** [comment]
Ok, I dont need the zoom feature. Save your time.

With:
`hexdump -C /tmp/mmap.info`
I found QFUS @ `00000310` so 784

**Comment by roleoroleo** [comment]
Ok.
I will publish an official release asap.

**Comment by Rushmed** [comment]
Thanks a lot Sir, I am looking forward to test it!

**Comment by croessi** [comment]
The r35gb Beta works like a charm on Yi Dome Guard YRS. Super Thanks @roleoroleo! Only the Serial Number is not displayed correctly, as mentioned. 

Unfortunaltely Presets in PTZ are not working - seems like an issue of the camera itself: https://forum.yitechnology.com/t/yi-dome-guard-preset-bookmarks-unavailable/6523/20 Any suggestions?

**Comment by Rushmed** [comment]
I can confrirm the presets point too.

**Comment by rt400** [comment]
i have the same camera, after hack using r35gb the camera works fine until that i start to config the camera then i got stuck and the move up and stay there.

**Comment by croessi** [comment]
@rt400 maybe you have to enable swap, ths helped with stability issues on my side.

**Comment by roleoroleo** [comment]
@croessi 
@Rushmed 
Is the PTZ working with the original app?

**Comment by croessi** [comment]
@roleoroleo The PTZ is working fine in the App and in the Hack. But Presets/Bookmarks are missing in the App (as described here: https://forum.yitechnology.com/t/yi-dome-guard-preset-bookmarks-unavailable/6523/20). I tried other ONVIF Apps with the same result. I have a Dome U as well, where Presets are working fine. Strangely I do not understand why it is disabled in the Guard, since it is abel to move back in the exact same position after reboot.

**Comment by roleoroleo** [comment]
Probably it's a bug.
But I'm not able to enable presets if they don't work in the app.

**Comment by Rushmed** [comment]
> Is the PTZ working with the original app?

Nope

**Comment by rt400** [comment]
does r35gb still in beta ?

**Comment by roleoroleo** [comment]
> does r35gb still in beta ?

Yes.

@Rushmed 
I need more details about the differences between two mmap.info
Could you please send me a copy of both versions?
If you don't want to publish them here please send me a mail to the address of my paypal.

**Comment by Rushmed** [comment]
@roleoroleo Where to get these files?

**Comment by rt400** [comment]
i want to help to... what do you need ?

**Comment by roleoroleo** [comment]
> 
> @Rushmed I need more details about the differences between two mmap.info Could you please send me a copy of both versions? If you don't want to publish them here please send me a mail to the address of my paypal.

Sorry, forget this post.

**Comment by roleoroleo** [comment]
Serial is already fixed, for ptz I think we need to wait for an upgrade from yi.

**Comment by rt400** [comment]
i still get "000000" on serial

**Comment by roleoroleo** [comment]
Yes, fixed but not pushed.

**Comment by rt400** [comment]
@rt400 rtsp low quality is missing...

**Comment by roleoroleo** [comment]
Does low res stream work?
If I remember correctly @Rushmed tested both streams.

**Comment by roleoroleo** [comment]
Is it enabled in your config?

**Comment by rt400** [comment]
> Is it enabled in your config?

Sorry i see it now that is only on high, change it to both and now i have low also .

**Comment by rt400** [comment]
@roleoroleo How can I get package with the your fixes ?

**Comment by roleoroleo** [comment]
At the moment I didn't build a package.
If you want, I could send you a beta.

Try this rtsp server, audio should work, but no auth is supported:
[rtsp_server.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/7846459/rtsp_server.gz)
Remember to kill wd_rtsp.sh and rRTSPServer before to start it.

**Comment by rt400** [comment]
thanks, i make a bulid witk your wiki. there is a way to upload it to the camera? or i have to put it on SDCARD ?

**Comment by roleoroleo** [comment]
You have to update the sd card.

**Comment by pannal** [comment]
> Hi, bought it on [Ali](https://de.aliexpress.com/item/1005001320188881.html?gatewayAdapt=glo2deu&spm=a2g0s.12269583.0.0.7ab524f8O8IZxi) but the PTZ profiles are also not working. Must be a bug on YIs side cause even with unhacked cam they arent working.

Thank you! Do you have an r30gb to compare against? As far as I understand, the r35gb is nearly two years newer - does that show?

**Comment by Rushmed** [comment]
No I dont have a r30gb. I have a h201c which has working PTZ profiles with another @roleoroleo  mod.
