### ISSUE TITLE
[FEATURE REQUEST] Google Drive integration

### ISSUE THREAD

**Issue by wuith** [roleoroleo/yi-hack-Allwinner-v2#327]
First of all thank you for this hack!

I would like to kindly ask for a new feature: The possibility to upload the files to Google Drive.

In similar hack-projects there is this integration (the second one is from you) but I could not make it work.. My skills are not enough to make it run but maybe you could.

https://github.com/porunov/xiaomi_gdrive
https://github.com/roleoroleo/yi-hack-MStar.gdrive

Thank you very much in advance!

**Comment by nicmorais** [comment]
What about https://github.com/roleoroleo/yi-hack-Allwinner.gdrive?

**Comment by wuith** [comment]
> What about https://github.com/roleoroleo/yi-hack-Allwinner.gdrive?

Thank you very much. I did not find that before!
