### ISSUE TITLE
yi dome guard 

### ISSUE THREAD

**Issue by tecnologiaSsimple** [roleoroleo/yi-hack-Allwinner-v2#33]
all functions are supported by yi dome GUARD KFUS except high resolution image capture. good job

**Comment by roleoroleo** [comment]
Do you mean stream or snapshot?

**Comment by tecnologiaSsimple** [comment]
Snaphot

**Comment by tecnologiaSsimple** [comment]
Snaphot high resolution not working

**Comment by roleoroleo** [comment]
Please try to run it manually.

**Comment by ayasystems** [comment]
Same problem

High resolution is not working. I have done a backup prior to test the hack firmware i can send you if you want.

![IMG_20201126_154039](https://user-images.githubusercontent.com/7864168/100377222-1fbd2980-3011-11eb-8ed4-5df761c9e2a5.jpg)
![IMG_20201126_154029](https://user-images.githubusercontent.com/7864168/100377230-2481dd80-3011-11eb-87cb-cf481d63a577.jpg)
![IMG_20201126_154320](https://user-images.githubusercontent.com/7864168/100377235-29469180-3011-11eb-83f5-052d4018a415.jpg)


This is the ethernet chip of wired network
![IMG_20201126_171316](https://user-images.githubusercontent.com/7864168/100377325-572bd600-3011-11eb-9227-9d517b346211.jpg)

MDT File
[mtd.txt](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5604284/mtd.txt)

Main chip
![IMG_20201126_173116](https://user-images.githubusercontent.com/7864168/100377467-9c500800-3011-11eb-866e-29590b0f2be1.jpg)

**Comment by roleoroleo** [comment]
Try to run the command manually (with debug option) in ssh and post the output.

**Comment by ayasystems** [comment]
What command? I'm very dummy on this things :D

**Comment by roleoroleo** [comment]
imggrabber -r high -w > /tmp/test.jpg

**Comment by ayasystems** [comment]
Hi

Where is located imggrabber??

```
root@yi-5cb1:/# imggrabber -r high -w > /tmp/test.jpg
-ash: imggrabber: not found
root@yi-5cb1:/# /home/yi-hack/bin/imggrabber -r high -w > /tmp/test.jpg
-ash: /home/yi-hack/bin/imggrabber: not found
root@yi-5cb1:/# /sbin/imggrabber -r high -w > /tmp/test.jpg
-ash: /sbin/imggrabber: not found

```

**Comment by roleoroleo** [comment]
Source the env before sending the command:
```
. /tmp/sd/yi-hack/script/env.sh
```

**Comment by ayasystems** [comment]
Thanks @roleoroleo 

root@yi-5cb1:~# imggrabber -r high -w > /tmp/test.jpg
Starting program
Mapping file /dev/shm/fshare_frame_buf, size 1786156, to b6d1c000
Encoding h264 frame
Starting decode
Decode frame
Writing yuv buffer
Cleaning ffmpeg memory
Adding watermark
Encoding jpeg image
Unmapping file /dev/shm/fshare_frame_buf, size 1786156, from b6d1c000

![test](https://user-images.githubusercontent.com/7864168/100430758-7cfbbe00-3097-11eb-982e-6c26fc398378.jpg)

**Comment by roleoroleo** [comment]
@ayasystems 
Did you solve your problem?

**Comment by jjleto** [comment]
same problem with r30gb_0.1.2 (also tested r30gb_0.1.3 but with continuous reboot)

imggrabber -r high -w > /tmp/test.jpg
Starting program
Mapping file /dev/shm/fshare_frame_buf, size 1786156, to b6cd0000
Encoding h264 frame
Starting decode
Decode frame
Writing yuv buffer
Cleaning ffmpeg memory
Adding watermark
Encoding jpeg image
Unmapping file /dev/shm/fshare_frame_buf, size 1786156, from b6cd0000

![snapshot sh](https://user-images.githubusercontent.com/4290761/103230991-04f31300-4937-11eb-9278-0bef7d950be8.jpeg)

**Comment by roleoroleo** [comment]
Please, make a dump of the file /tmp/iframe.idx with hexdump.
The log shows that imggrabber tries to encode the frame using h264 and not h265.

**Comment by ayasystems** [comment]
Hi @roleoroleo 

Here the dump, let me know if need more info

```
root@(none):/tmp# hexdump iframe.idx > iframe.idx.dump
root@(none):/tmp# cat iframe.idx.dump
0000000 7c18 0002 0019 0000 7c41 0002 0008 0000
0000010 7c5f 0002 3c43 0000 a83b 0001 0019 0000
0000020 a864 0001 0008 0000 a882 0001 3c1a 0000
0000030
```

**Comment by roleoroleo** [comment]
Which versionvare you using?
iframe.idx should be 64 bytes long.

**Comment by jjleto** [comment]
root@dome:/tmp# cat iframe.idx.dump
0000000 2203 001b 0019 0000 222c 001b 0008 0000
0000010 224a 001b 332a 0000 da3a 0004 0019 0000
0000020 da63 0004 0008 0000 da81 0004 3348 0000
0000030
r30gb_0.1.2

**Comment by roleoroleo** [comment]
Maybe I found a bug in the OTA upgrade procedure.
Try to reinstall the last version from scratch.

**Comment by ayasystems** [comment]
Hi

High resoltion is working now with this firmware:

Firmware Version | 0.1.3
Base Version | 9.0.05.32_202004101552

But seems like this camera has not high resolution. 
[snapshots.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5757138/snapshots.zip)

**Comment by roleoroleo** [comment]
Why do you think this cam has not high res?
Probably the quality is not so good but is high res.

**Comment by ayasystems** [comment]
May be, the quality is not good..... A old foscam has better quality without hd

**Comment by jjleto** [comment]
Tested now with a fresh install of r30gb_0.1.3 on new sd card, hd snapshot when working it’s ok, but the cam have continuous reboot.

**Comment by roleoroleo** [comment]
This is a know issue.
It's a low memory condition.
Enable swap file.

**Comment by Zephael86** [comment]
I can confirm a successful fresh install using r30gb_0.1.3 to YI Dome Guard (SN: HR303G... DID: HFUSY....).
High resolution snapshot works.
Enables swap file.

**Comment by thehutgy** [comment]
> I can confirm a successful fresh install using r30gb_0.1.3 to YI Dome Guard (SN: HR303G... DID: HFUSY....).
> High resolution snapshot works.
> Enables swap file.

I can confirm this too, mine was crashing before, Enabling swap file should work perfectly.

Thanks for this amazing yi hack!
