### ISSUE TITLE
Black screen in stream both on mobile phone and home assistant (frigade) 

### ISSUE THREAD

**Issue by YoykoKoszko** [roleoroleo/yi-hack-Allwinner-v2#330]
Hi all

I have problem where my camera stream is black page when I try to use it on mobile phone (vlc android) and home assistant (frigade integration) it was OK on laptop. What do I have to do?

**Comment by roleoroleo** [comment]
> Hi all
> 
> I have problem where my camera stream is black page when I try to use it on mobile phone (vlc android) and home assistant (frigade integration) it was OK on laptop. What do I have to do?

Which app are you using on your laptop?

**Comment by YoykoKoszko** [comment]
I am using same app on both pc and phone which is VLC player.

**Comment by roleoroleo** [comment]
I don't use frigade but I can confirm that this cam works with:
- ha + webrtc
- vlc on pc
- vlc on andrtoid

With vlc use the rtsp address rtsp://192.168.1.200/ch0_0.h264
With your IP.
