### ISSUE TITLE
Support for Kami Outdoor H31?

### ISSUE THREAD

**Issue by Sprocket02** [roleoroleo/yi-hack-Allwinner-v2#331]
I bought the Kami (Yi) camera outdoor H31 with battery. The camera starts with the serial number BFUSXXX.
The firmware is version 5.1.XXX. Is there the possibility to support this camera? Maybe I can support there?

![image](https://user-images.githubusercontent.com/37394766/148222938-8af0241a-4d9f-4e94-b794-25c79cf0b995.png)

**Comment by roleoroleo** [comment]
5.1 doesn't sound good.
Are you able to open it and take a picture of the board?
