### ISSUE TITLE
mjpg_streamer or other browser format as output stream

### ISSUE THREAD

**Issue by bowski1** [roleoroleo/yi-hack-Allwinner-v2#332]
is it possible to get a output stream as mjpg_streamer or any other browser format to see the stream on a webbrowser?

**Comment by roleoroleo** [comment]
No, I can't access to the encoding features of the cpu.
It's configured to use only h264/h265.
And a software codec is too expensive in terms of cpu/memory.
You need to use an external converter/plugin.
