### ISSUE TITLE
human_start and human_stop WORK !!!

### ISSUE THREAD

**Issue by Maxym77** [roleoroleo/yi-hack-Allwinner-v2#333]
mmm i  have simply  inverted human_stop with human_start
here:
http://xxxxx:8080/index.html?page=mqtt

works perfetct!!!!  :D

the cam send mqtt human_start on detection and after 40 seconds send human_stop

i'm genius ?

the problem is the topic name:
camCucina/ai_human_detection human_start
camCucina/motion_detection human_stop

i think there is confusion with the topics name.....

why in homeassistant integration i don't see human detection integration ? is removed for this stupid bug of inverted topic? 

*** UPDATE *** 
i have solved (homeassistant integration) with this settings, this for me is perfect becouse it send mqtt message only on (real) human detection.:

/tmp/sd/yi-hack/etc/mqttv4.conf:

TOPIC_AI_HUMAN_DETECTION=motion_detection
TOPIC_MOTION=motion_detection

AI_HUMAN_DETECTION_START_MSG=motion_stop
AI_HUMAN_DETECTION_STOP_MSG=motion_start
MOTION_START_MSG=motion_fakestart
MOTION_STOP_MSG=motion_stop

**Comment by roleoroleo** [comment]
Mmmmmh
This does not match what I have seen in the past. 
Are you sure the event arrives only when there is a human?

**Comment by roleoroleo** [comment]
Check this issue:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/209#issuecomment-928009979

**Comment by Maxym77** [comment]
I just did this test: I turned the camera towards the wall and waited for the motion_stop.
Then I moved my hand in front, without showing my body,
I took an object and moved it in front, and no motion_start event started.
After this I have turned the cam towards me in order to show my body, the motion start event immediately occurred.

**Comment by roleoroleo** [comment]
Did you check if it works when you disable cloud services?

**Comment by skarcha** [comment]
Hi! I've my camera on his own vlan, without internet access and human motion detection works perfect saving files on SD card. All mqtt topics and messages are default, but it don't send the start event, only stop event. This is a extract off mqtt messages:

```
lucena/camterraza/ai_human_detection human_stop
lucena/camterraza/motion_detection motion_stop
lucena/camterraza/ai_human_detection human_stop
lucena/camterraza/motion_files {
"start":"1970-01-01T01:00:00+0100",
"end":"2022-01-09T13:16:45+0100",
"files":[ ]
}
```

After invert start and stop messages as @Maxym77 said, I got this:

```
lucena/camterraza/status offline
lucena/camterraza/status online
lucena/camterraza/ai_human_detection human_start
lucena/camterraza/motion_detection motion_stop
lucena/camterraza/motion_files {
"start":"1970-01-01T01:00:00+0100",
"end":"2022-01-09T13:37:41+0100",
"files":[ ]
}
```
So, @roleoroleo , take a look and restore human detection, please. It doesn't need the cloud, the problem is other.

@Maxym77 I'll test your solution and come with results. Thanks!

**Comment by roleoroleo** [comment]
I will restore the code but I think it's not the correct behavior.

**Comment by skarcha** [comment]
Don't get me wrong. I agree there is a bug that needs to be fixed. We should not do this sort of tricks to solve the problem.

Can I help you testing something?

**Comment by roleoroleo** [comment]
I can't fix this, it depends on the yi firmware.
I have done a lot of tests but have not found a solution.
But I can leave this feature on the hack, it doesn't break other features.

**Comment by skarcha** [comment]
Sending of MQTT events is on yi firmware? Excuse me, I don't know nothing about this software. How are called the functions to send the appropiate message?

**Comment by roleoroleo** [comment]
The mqtt daemon contained in the hack, catches some ipc messages between yi processes.
When there is a motion detection, the sequence of the messages is not clear.

**Comment by skarcha** [comment]
Ok, I see. Thanks for your time and work! We'll deal with this for now... ;-)

**Comment by trombik** [comment]
my camera is Yi Dome Guard (r35gb).

when person detection is enabled, as the issue author stated, the yi only generates `motion_stop` IPC message.

```console
Parsing message.
01 00 00 00 02 00 00 00 7d 00 7d 00 00 00 00 00 
Sending MOTION_STOP to queue #1
Sending MOTION_STOP to queue #2
Sending MOTION_STOP to queue #3
Sending MOTION_STOP to queue #4
Sending MOTION_STOP to queue #5
Sending MOTION_STOP to queue #6
Sending MOTION_STOP to queue #7
Sending MOTION_STOP to queue #8
Sending MOTION_STOP to queue #9
IPC message. Len: 16. Status: Resource temporarily unavailable!
Parsing message.
01 00 00 00 04 00 00 00 22 40 01 00 00 00 00 00 
IPC message. Len: 16. Status: Resource temporarily unavailable!
Parsing message.
01 00 00 00 02 00 00 00 ed 00 ed 00 00 00 00 00 
Sending AI_HUMAN_DETECTION_START to queue #1
Sending AI_HUMAN_DETECTION_START to queue #2
Sending AI_HUMAN_DETECTION_START to queue #3
Sending AI_HUMAN_DETECTION_START to queue #4
Sending AI_HUMAN_DETECTION_START to queue #5
Sending AI_HUMAN_DETECTION_START to queue #6
Sending AI_HUMAN_DETECTION_START to queue #7
Sending AI_HUMAN_DETECTION_START to queue #8
Sending AI_HUMAN_DETECTION_START to queue #9
```

no `motion_start` at all. the author's solution is to swap "start" and "stop" MQTT messages, but it breaks HA integration. as such, only workaround is the following patch for mqttv4 (haven't tried yet).

```diff
diff --git a/include/ipc.h b/include/ipc.h
index d5a6a3c..b111d8c 100644
--- a/include/ipc.h
+++ b/include/ipc.h
@@ -35,8 +35,8 @@
 #define IPC_QUEUE_NAME          "/ipc_dispatch_1"
 #define IPC_MESSAGE_MAX_SIZE    512
 
-#define IPC_MOTION_START                "\x01\x00\x00\x00\x02\x00\x00\x00\x7c\x00\x7c\x00\x00\x00\x00\x00"
-#define IPC_MOTION_STOP                 "\x01\x00\x00\x00\x02\x00\x00\x00\x7d\x00\x7d\x00\x00\x00\x00\x00"
+#define IPC_MOTION_START                "\x01\x00\x00\x00\x02\x00\x00\x00\x7d\x00\x7d\x00\x00\x00\x00\x00"
+#define IPC_MOTION_STOP                 "\x01\x00\x00\x00\x02\x00\x00\x00\x7c\x00\x7c\x00\x00\x00\x00\x00"
 #define IPC_AI_HUMAN_DETECTION          "\x01\x00\x00\x00\x02\x00\x00\x00\xed\x00\xed\x00\x00\x00\x00\x00"
 #define IPC_BABY_CRYING                 "\x04\x00\x00\x00\x02\x00\x00\x00\x02\x60\x02\x60\x00\x00\x00\x00"
 #define IPC_SOUND_DETECTION             "\x04\x00\x00\x00\x02\x00\x00\x00\x04\x60\x04\x60\x00\x00\x00\x00"
```

however, this inverts the result when motion detection is enabled, but person detection is enabled. in that case, the status is reversed because yi generates `motion_start` and `motion_stop` correctly.

personally, i do not use motion detection (too many false positive).

**Comment by trombik** [comment]
as a side note; the HA integration is out of sync with the firmware, and is broken. it does not know `human` or `baby_crying` MQTT payload. however, the integration only logs that error at `INFO` level. that's why it silently fails.

**Comment by roleoroleo** [comment]
Which firmware version are you using?

**Comment by roleoroleo** [comment]
> as a side note; the HA integration is out of sync with the firmware, and is broken. it does not know `human` or `baby_crying` MQTT payload. however, the integration only logs that error at `INFO` level. that's why it silently fails.

The ha integration doesn't manage human detection.
But baby_crying should work.

I would like to try to clarify how message handling in yi cams works.
Motion detection, human detection and baby crying share the same motion stop message.
For example, when a motion is detected the sequence is:
- MOTION_START
- MOTION_STOP
When a baby crying is detected the sequence is:
- BABY_CRYING
- MOTION_STIOP

**Comment by trombik** [comment]
thanks for your comment.

I spent quite a bit of time to understand why something works and doesn't in the hack and HA integration. during the course, I found that the work involved includes many many different areas, in-kernel IPC, video formats, tons of shells, HA API, and its internal. to me, it was not clear why some features do not work, or why something was dropped altogether. the commit logs explain what you did, but few on why you did.

would you document a bit more about how the hack works, issues you are facing, how you are trying to solve issues?

I maintain documentations, and i know it is not easy. but if you do it, others can help your work. your are great but you will be burning out otherwise. that would be a huge loss.

**Comment by roleoroleo** [comment]
This part of the hack comes from yi-hack-v4 (and maybe even earlier).
Yi processes communicate with each other using a message queue (typical method widely used in linux).
Detection messages are not an exception. When a detection is fired, a message passes in the ipc_dispatch queue.
What does hack do?
It catches the messages in the queue and, if it reads a detectcion message, it sends a mqtt message to the broker.

ipc_multiplex is responsible for catching messages (https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/master/src/ipc_cmd/ipc_cmd).
mqttv4 is responsible for mqtt publishing (https://github.com/roleoroleo/mqttv4/tree/4ee59d6a19994213d32510b5dc8a01fbbd9b6681/src).

Here you can see the ipc messages managed by mqttv4:
https://github.com/roleoroleo/mqttv4/blob/4ee59d6a19994213d32510b5dc8a01fbbd9b6681/include/ipc.h#L38

It's not simple to reverse the logic used by yi.
For example: why motion detection has start and stop and sound detection only start?
Often the only way to understand how this works is to analyze the disassembled code. A lot of work...

> I maintain documentations, and i know it is not easy. but if you do it, others can help your work. your are great but you will be burning out otherwise. that would be a huge loss.

You are right but time is not my friend: a full-time job, a large family and many projects.
This is the best I can do.

**Comment by trombik** [comment]
> It's not simple to reverse the logic used by yi. For example: why motion detection has start and stop and sound detection only start? Often the only way to understand how this works is to analyze the disassembled code. A lot of work...

quite a lot of work indeed. do you think there are other IPC messages that are yet to be discovered? for instance, `baby_crying`, or sound detection, logic has actually `stop`, but not yet discovered? are you sure sound detection has only `start`?

> You are right but time is not my friend: a full-time job, a large family and many projects. This is the best I can do.

your achievements under these circumstances are quite impressive.

**Comment by roleoroleo** [comment]
> quite a lot of work indeed. do you think there are other IPC messages that are yet to be discovered?

Maybe, but the important messages have been identified.
For example, you can check here
https://github.com/frankzhangshcn/p2p_tnp/blob/aa7855c9c17c07903f6fde20a9931faf7aa592b0/p2p_tnp.c
a partial source of p2p_tnp where each line
`if(p2p_send_msg(g_p2ptnp_info.mqfd_dispatch ...`
is a different IPC message

> for instance, `baby_crying`, or sound detection, logic has actually `stop`, but not yet discovered? are you sure sound detection has only `start`?

About events (motion, sound, etc...) the logic is pretty clear, obtained by disassembling the binary code.
But I can't be completely sure...
