### ISSUE TITLE
QG2101B  firmware   9.0.41.99_202109231032 use b091qp cannot connect to wifi and rtsp

### ISSUE THREAD

**Issue by pengkaiwei** [roleoroleo/yi-hack-Allwinner-v2#335]
Hi, thank you very much for your contribution.
My cam chip is QG2101B and the firmware version is 9.0.41.99\_202109231032.
I tried [#249 (reply in thread)](https://github.com/roleoroleo/yi-hack-Allwinner-v2/discussions/249#discussioncomment-1378470),
But wifi can't find the device, plug in the network cable directly, you can see the device ip, but rtsp still has no image.

Below are some pictures of my device, I hope it can help you. This is my factory firmware backup.

[![image](https://user-images.githubusercontent.com/10482885/149543188-188840d5-2da9-4c4d-a9f7-b67fa90888fb.png)](https://user-images.githubusercontent.com/10482885/149543188-188840d5-2da9-4c4d-a9f7-b67fa90888fb.png)

[![微信图片_20220114234545 - 副本](https://user-images.githubusercontent.com/10482885/149544007-33502402-99a1-4591-b64d-2d3118e7da5d.jpg)](https://user-images.githubusercontent.com/10482885/149544007-33502402-99a1-4591-b64d-2d3118e7da5d.jpg)
[![微信图片_202201142345452 - 副本](https://user-images.githubusercontent.com/10482885/149544076-5e7a8d2b-2a3a-4091-8e78-e162ea3f9490.jpg)](https://user-images.githubusercontent.com/10482885/149544076-5e7a8d2b-2a3a-4091-8e78-e162ea3f9490.jpg)
[![微信图片_202201142345453 - 副本](https://user-images.githubusercontent.com/10482885/149544139-b403a7cb-dd52-4b55-bf9f-ff3e629f3ff6.jpg)](https://user-images.githubusercontent.com/10482885/149544139-b403a7cb-dd52-4b55-bf9f-ff3e629f3ff6.jpg)
[![微信图片_202201142345454 - 副本](https://user-images.githubusercontent.com/10482885/149544197-7fffd1ec-58de-446c-8b1b-efd7ce71c249.jpg)](https://user-images.githubusercontent.com/10482885/149544197-7fffd1ec-58de-446c-8b1b-efd7ce71c249.jpg)
[![微信图片_202201142345451 - 副本](https://user-images.githubusercontent.com/10482885/149544238-b3b77b17-5f29-4442-9b05-9d70adea357f.jpg)](https://user-images.githubusercontent.com/10482885/149544238-b3b77b17-5f29-4442-9b05-9d70adea357f.jpg)

This is my factory firmware backup.

LINK REMOVED

**Comment by roleoroleo** [comment]
The cam is bq091qp.
But there are different versions of b091qp.
I have to check.

**Comment by pengkaiwei** [comment]
thank you

> The cam is bq091qp. But there are different versions of b091qp. I have to check.


Thank you and I look forward to your good news.
If you need help with anything, just let me know.

**Comment by forgani** [comment]
Hi, I have the same camera. 
@pengkaiwei did you make it and whether the last release supports this version. Thanks

**Comment by forgani** [comment]
**awesome** . Good work I confirm that everything is fine. works perfect. many thanks
