### ISSUE TITLE
Private mode not working

### ISSUE THREAD

**Issue by norb-HB** [roleoroleo/yi-hack-Allwinner-v2#349]
My Setup
YI 1080p Home Camera
Firmware Version | 0.2.0
Base Version | 9.0.19.02_202007141512
Model Suffix | y21ga

'Disable cloud'/'Private mode' seems not to work. Tested several combinations of setting in the hack but still able to see live pictures in YI app with LAN and LTE connect.

**Comment by VincentBerree** [comment]
Have you reboot the cam after each change?
What is the content of /etc/hosts?
When 'Disable cloud'/'Private mode' option is enabled, the file should contain the following lines (after a reboot).
```
127.0.0.1    api.eu.xiaoyi.com
127.0.0.1    api.us.xiaoyi.com
127.0.0.1    api.xiaoyi.com.tw
127.0.0.1    log.eu.xiaoyi.com
127.0.0.1    log.us.xiaoyi.com
127.0.0.1    log.xiaoyi.com.tw
```

**Comment by roleoroleo** [comment]
Did you solve the problem?

**Comment by norb-HB** [comment]
Sorry for bothering you guys. It's working ok. The problem were sitting on fornt of the PC.

Thanks!

**Comment by norb-HB** [comment]
Thanks! Private mode is working ok.
