### ISSUE TITLE
RTSP Low Quality doesnt Work

### ISSUE THREAD

**Issue by SeriousPat** [roleoroleo/yi-hack-Allwinner-v2#352]
Hi,
on 2 of my three IFUS Outdoor 1080p the RTSP Low mode doesnt work.
My rtsp player (android) or VLC (Windows) connect, but doesnt show a picture. (black video)

**Comment by roleoroleo** [comment]
Same versione and same hack?

**Comment by SeriousPat** [comment]
Hi, yes, i use 3 cams, all the same version and this hack (allwinnerv2) 0.2.0

**Comment by roleoroleo** [comment]
Is high res video ok?
Is low res snapshot ok?
Please take a screenshot of the statistics:
![immagine](https://user-images.githubusercontent.com/39277388/153639047-ff86e4be-9ef3-41b3-af1b-0838e8486990.png)

**Comment by roleoroleo** [comment]
> upgraded all 3 cameras to 0.2.0.

Same model?

**Comment by mspinolo** [comment]
Yes same model, 1080P BFUS

**Comment by mspinolo** [comment]
Not easy unluckily: it is in a remote place

**Comment by mspinolo** [comment]
so this is what I get

**1st camera**
```
root@CameraRose:~# cat /dev/mtdblock0 | grep uboot_
uboot_pkg magic 0x%x
uboot_ver
/uboot_y21ga
 uboot_message=%s(%s-%s)
```

**2nd camera**
```
root@CameraBarba:~# cat /dev/mtdblock0 | grep uboot_
uboot_pkg magic 0x%x
uboot_ver
/uboot_y21ga
 uboot_message=%s(%s-%s)

```
**3rd camera - one with issues**
```
root@YiCameraCorte:~# cat /dev/mtdblock0 | grep uboot_
uboot_pkg magic 0x%x
uboot_ver
/uboot_y21ga
 uboot_message=%s(%s-%s)
```

**Comment by roleoroleo** [comment]
The cam are ok.
There is no reason why the cam is not working.
Try to change the sd card.
