### ISSUE TITLE
Tested working Yi home 1080p SN/IFUS

### ISSUE THREAD

**Issue by flexiones** [roleoroleo/yi-hack-Allwinner-v2#36]
Tested on 4 pack yi home 1080p with serial number starting on IFUSXXXXXX.
Working with Qnap QVRpro over RTSP protocol.
![Captura de pantalla 2020-11-27 a las 13 06 12](https://user-images.githubusercontent.com/11464783/100448044-f6a0a580-30b1-11eb-8630-57f5d12a0ba3.png)
![Captura de pantalla 2020-11-27 a las 13 06 30](https://user-images.githubusercontent.com/11464783/100448046-f86a6900-30b1-11eb-8c69-aa51f99e7a31.png)
![WhatsApp Image 2020-11-27 at 13 09 44](https://user-images.githubusercontent.com/11464783/100448049-f99b9600-30b1-11eb-9d37-ad4406801396.jpeg)

**Comment by roleoroleo** [comment]
Thank you for your feedback.
Did you try onvif also with qnap?

**Comment by flexiones** [comment]
Onvif works as alocating service, But need to re-set as generic camera and rtsp h264.
I Can't setup Onvif, but not spent much time setting up devices. Maybe could try next week, but it's new for me, not understand yet.
