### ISSUE TITLE
How to use speak volume and snapshot delay

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#366]
I saw that you updated and added the feature that I requested, thanks!
But how can I use them?

**Comment by roleoroleo** [comment]
You can set snapshot delay in the web gui, mqtt section.
About speak volume, it's a web service feature. So you can use it only when called from another service.
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description#audio
If you use my ha custom integration, you will find a special option in the wizard.

**Comment by PilaScat** [comment]
> You can set snapshot delay in the web gui, mqtt section. 
Thanks!
> About speak volume, it's a web service feature. So you can use it only when called from another service. https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description#audio If you use my ha custom integration, you will find a special option in the wizard.
Can I change it without re-adding the integration? I have already changed all icons and names

**Comment by roleoroleo** [comment]
I don't know.
