### ISSUE TITLE
Setting exposure

### ISSUE THREAD

**Issue by chitown60608** [roleoroleo/yi-hack-Allwinner-v2#37]
I'm wondering if there's an option that we can set somehwere that will set the exposure on the camera?  My camera is in a pipe for protection and the lighting will never change.  Because it's in a pipe, there is approximately 12" of darkness between the lens and the opening of the pipe.  This causes the image to be washed out with light.  Every once in a while, the camera flips from night vision to day time and then back to night vision and when it returns, the image is crisp, clear and perfect.  I would like to be able to tinker with the exposure setting until I find the exact one I want and keep it from moving off that setting.  I've included a pic of the 2 different exposures.  They're looking at the exact same spot.  One is from the normal, washed out with light image and the other is the one that I'm hoping to lock in somehow.  Any suggestions?

![ir difference](https://user-images.githubusercontent.com/42260758/100475220-418adf00-30eb-11eb-9527-75de05d509eb.png)

**Comment by roleoroleo** [comment]
Sorry but I don't know how to control these parameters.
