### ISSUE TITLE
YI 1080P home BFUS- not flashing

### ISSUE THREAD

**Issue by mrgoodcat** [roleoroleo/yi-hack-Allwinner-v2#372]
Hi
i have a YI 1080P home model BFUS fw 9.0.19 so it seems this is the right hack (i also previously try with other before discover my fw version).
Seems that mod isn't working, after the procedure nothing happen. 
Camera is already connected to wifi and working with the app mobile and desktop.
Can you please clarify:
1) extracting the release file (y21ga) into the SD there isn't the folder newbackup/ , you mean that we have to put in the SD the backup crated with the other tool and call the folder newbackup ? or ? I try with and without "newbackup" folder and same.
2) during flashing what's happ to the camera led ) Just to expect something, in my case nothing strange happen, just fix yellow and then fix blue.
Trying the link IP-CAM i get error (and the confirm that flash failed)
Thanks for your support,

**Comment by roleoroleo** [comment]
>     1. extracting the release file (y21ga) into the SD there isn't the folder newbackup/ , you mean that we have to put in the SD the backup crated with the other tool and call the folder newbackup ? or ? I try with and without "newbackup" folder and same.

I updated the readme... Simply extract the archive into the sd card.

>     2. during flashing what's happ to the camera led ) Just to expect something, in my case nothing strange happen, just fix yellow and then fix blue.

Yes.

Try again with another sd card, but if you have tried other hacks, it may not work.

**Comment by mrgoodcat** [comment]
ok, i wil try with different SD and because i have 4 of this cam (i get the family pack) and may be the ones i test with different hack coulde be "corrupted", can you please just confirm that the right tool is this one ? So i try with the "virgin" ones with the right one.
Thanks

**Comment by roleoroleo** [comment]
Your file is y21ga_0.2.0.tgz
Please, make a backup before applying the hack to the cam.

**Comment by mrgoodcat** [comment]
tried with new cam and new SD, format SD fat32 then extract hack then put in and switch on, nothing, just a normal boot on and connection to my network. 
So sad..

**Comment by mrgoodcat** [comment]
> Your file is y21ga_0.2.0.tgz Please, make a backup before applying the hack to the cam.

Man, it works! or at least seems it works. It was just difficult to check, because no light flickering or other signs, and the link http://ip-cam:8080/ don't work for me, but using IP:addr:8080 it works!
