### ISSUE TITLE
Beta release: 0.2.1_beta

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-Allwinner-v2#378]
Before to publish the new release, I would like to be sure that I didn't broke a couple of feature.
1- I completely changed the way how the grabber read the frames from the buffer. Both the grabber (h264grabber) and the rtsp server (rRTSPServer) are new.
2 - After several issues about the wrong watermark time, I moved the export of the TZ environment variable.

Anyone want to try the new version?
And check if:
1 - The rtsp stream is ok.
2 - The date/time is ok in the app, the date/time is ok in the web gui, the videos are playable in the app, the events page shows the proper date/times. Remember to set the timezone of your region both in the app and in the web gui.

https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/tag/0.2.1_beta

**Comment by rpkilgore** [comment]
I'm attempting to test this beta version on y28ga, but having issues with it rebooting contantly, and the normal fix to disable the audio didn't work, then I disabled everything else except ssh and web and it still continues to reboot.  I'm going to run the remove hack and then try to re-apply and see if that corrects it,
Will keep you updated.

**Comment by roleoroleo** [comment]
I tested it before tu publish and it seems working fine with my y21ga.
If the problem persists, try the new unbrick procedure:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/tree/master/unbrick

**Comment by rpkilgore** [comment]
well damn.. I just revived this camera from what i thought was bricked a few days ago using that unbrick process, and now I've managed to brick it again, but this time that unbrick process isn't working :(  Going to unplug it for a bit and try again after lunch.. lol maybe being powered off for a bit will change something lol **fingerscrossed**

**Comment by roleoroleo** [comment]
Which model suffix?

**Comment by rpkilgore** [comment]
y28ga  The unbrick worked the first time around, this time nothing happens.

**Comment by Rushmed** [comment]
Hi rolee.

Thanks for this release.
Just installed [r35gb_0.2.0.tgz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/download/0.2.1_beta/r35gb_0.2.0.tgz) on my Dome Guard.
So far:
- Cam timezone, video recording and video playback in the app are ok
- Snapshot in web UI is also fine but still two timecodes are shown
![image](https://user-images.githubusercontent.com/59259796/156840527-b50de213-4633-4759-9272-828448890bcf.png)
- Time and date at /index.html are ok
- Events page semms to be ok

The test ran about 30 minutes so far, I`ll leave the cam online and will have an eye on it.

**Comment by rpkilgore** [comment]
Ok, finally got a chance to test out the beta on my Dome Guard Cam r35gb.  Already had the hack applied so just updated by deleting everything off the sd card and extracting the new hack.  Made my custom changes to the conf files and booted up.  1 Reboot later and it was up and running smoothly.
Results:

- Snapshot has the correct time EST but there are 2 timestamps one on the bottom right and one on the top left
- if i change the url to say no to the watermark the timestamp in the top left remains
- RSTP stream works smoothly, proper time in the upper left hand corner
- date time stamps are correct everywhere EXCEPT for the folder structure name is incorrect
- I can however scroll through the timeline in the app and watch recorded events in the app!
![eventspage](https://user-images.githubusercontent.com/19828182/156934399-da4f18ef-060c-401f-b74f-75cbf40df909.png)

**Comment by roleoroleo** [comment]
Than you for yuor feedback.
A couple of notes:

> Snapshot in web UI is also fine but still two timecodes are shown

Yes, I can't remove the watermark added by yi (upper left).

> For me its confusing that v2.2.1_beta is named v2.2.0.

Yes, my mistake.

> date time stamps are correct everywhere EXCEPT for the folder structure name is incorrect

The directory structure created by the yi processes is UTC and if I try to change it, dates and times are not consistent.

**Comment by outofsight** [comment]
I'll join here because I'm experiencing the issue of playback from SD card of previous events recorded by my y21ga.
I made the following settings about timezone:
- in the camera: "CET-1CEST,M3.5.0,M10.5.0/3"
- in the app: "UTC" (as of page recommendation)
Is that wrong?

When I try to playback, I'll see often the Kami Cloud request. If/when I can start watch a video I can't seek back where I want: the app go to live preview or to a wrong time in the past.

**Comment by rpkilgore** [comment]
@outofsight  You want to set both the Camera and the Hack to your timezone.  UTC is what the application uses in the background.

**Comment by outofsight** [comment]
> @outofsight You want to set both the Camera and the Hack to your timezone. UTC is what the application uses in the background.

Thanks, I made UTC setting in the app because I read this on the Hack Settings page:

> Timezone | Timezone. Get your timezone string from this page and copy here. If you want to use this feature, please set time to "UTC +0 Coordinated universal time" in the app.

**Comment by roleoroleo** [comment]
I will fix this problem in the next release.

**Comment by rpkilgore** [comment]
> I will fix this problem in the next release.

What fix are you going to apply?  I thought this was working already?

**Comment by roleoroleo** [comment]
There are 2 changes related to the date/time available in the next release.
- I moved the TZ settings so only hack programs read it.
- I changed mqttv4 because motion_files messages was wrong.

The beta version tested in this thread contain only the 1st change.

**Comment by outofsight** [comment]
In the last release should I put the correct TZ both in Yi app and in Hack?

**Comment by roleoroleo** [comment]
Yes.
