### ISSUE TITLE
Access media files from home assistant 

### ISSUE THREAD

**Issue by oat1** [roleoroleo/yi-hack-Allwinner-v2#380]
Hi is there a way to access these media files from home assistant ?

It would be nice to add this folder to media section and watch them directly from this section.

![unnamed](https://user-images.githubusercontent.com/59432560/156368816-4629381b-c69b-4338-bb5d-d15a0f079efa.jpg)

**Comment by roleoroleo** [comment]
You can upload the file to an FTP server or access them with the web services.
Check the wiki:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description

**Comment by oat1** [comment]
Yes, but now finding a file is a pain in the ass.

I'm thinking about something more "user friendly"
Accessing camera sd card like a network drive, and put the video catalog to media section in HA
The whole main catalog of video files, let's say " Yihack", then subfolder with specific days, hours and inside a list of files to play. Just like frigate does ( screen below)
It would be much easier to watch and find a specific video from specific

I do not know whether it is possible or not, It is just a wish to consider :)
But I think it would be a great thing. 

![frigate](https://user-images.githubusercontent.com/59432560/156377831-6ed02851-cf74-45f5-bf30-69a7069bf3b4.jpg)

**Comment by roleoroleo** [comment]
Try the new release.

**Comment by oat1** [comment]
Wow Great 😊👍 thanks . 
There is now a new folder yihackin media section but when I go inside, error appears

![Screenshot_20220306-174520_Home Assistant](https://user-images.githubusercontent.com/59432560/156932978-150046ca-911b-4b5c-8fec-94cecb2b0ba8.jpg)
![Screenshot_20220306-174507_Home Assistant](https://user-images.githubusercontent.com/59432560/156932979-bb6f8328-27bc-419d-ac29-10139675ce09.jpg)

**Comment by roleoroleo** [comment]
Please, check the registry log and send me the error.

This is what it should appear:

![immagine](https://user-images.githubusercontent.com/39277388/157393991-336bbfe8-4305-48a4-b0f6-01e2256c6db3.png)

![immagine](https://user-images.githubusercontent.com/39277388/157394049-4351292e-8764-46ef-b845-771f4a8da7c3.png)

![immagine](https://user-images.githubusercontent.com/39277388/157394098-f4e735cb-9ae1-47d1-b83e-7a7b58094109.png)

![immagine](https://user-images.githubusercontent.com/39277388/157394135-9b6e5834-54ee-4544-b5fb-40191f41f450.png)

**Comment by oat1** [comment]
Log below

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/yi_hack/media_source.py:76
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 06:23:53 (3 occurrences)
Last logged: 08:39:47

[547642575360] Error handling message: Unknown error
[547642851184] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 152, in websocket_browse_media
    media = await async_browse_media(hass, msg.get("media_content_id", ""))
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 111, in async_browse_media
    item = await _get_media_item(hass, media_content_id).async_browse()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 85, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/config/custom_components/yi_hack/media_source.py", line 76, in async_browse_media
    domain = list(list(device.identifiers)[0])[0]
IndexError: list index out of range

**Comment by roleoroleo** [comment]
Try this file:
[media_source.py.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8213566/media_source.py.gz)

**Comment by oat1** [comment]
Now Works flawlessly,  Thanks! For the feature and for help.
You're the best !!!


![image](https://user-images.githubusercontent.com/59432560/157419397-4200f268-4b43-4add-a13a-15cf80031fbd.png)

**Comment by roleoroleo** [comment]
With the next release cam/integration the video will have a thumbnail that will display the first frame.

**Comment by oat1** [comment]
Great 👍😃 Couldn't ask for more. Appreciate the job

**Comment by oat1** [comment]
Hi, I updated camera to the latest 0.2.1 release, but there is no thumbnail, still just icons
yi-hack Home Assistant integration is also updated to 0.3.8

![image](https://user-images.githubusercontent.com/59432560/158994347-8a5474ae-a861-48ad-864d-7a43a4b985b8.png)

**Comment by roleoroleo** [comment]
Login with ssh and check if crontab file is ok:
```
root@yi-hack-allwinner:~# cat /var/spool/cron/crontabs/root
* * * * * /home/yi-hack/script/thumb.sh cron
0 * * * * sleep 20; /home/yi-hack/script/clean_records.sh 30
```

Try to run the process manually and check the output:
```
root@yi-hack-allwinner:~# . /home/yi-hack/script/env.sh
root@yi-hack-allwinner:~# /home/yi-hack/script/thumb.sh cron
```

**Comment by oat1** [comment]
I get this

![image](https://user-images.githubusercontent.com/59432560/159006951-4b8ca1f8-c435-4884-ac0c-bbe98882a76a.png)

**Comment by oat1** [comment]
I've edited it a little and process started 
![image](https://user-images.githubusercontent.com/59432560/159007773-a635864e-76c6-4f8e-968e-77252aea521f.png)

**Comment by roleoroleo** [comment]
Sorry, I got confused with Allwinner.
This is for Allwinner-v2

```
root@yi-hack-allwinner:~# cat /var/spool/cron/crontabs/root
* * * * * /tmp/sd/yi-hack/script/thumb.sh cron
0 * * * * sleep 20; /tmp/sd/yi-hack/script/clean_records.sh 30
```

Try to run the process manually and check the output:
```
root@yi-hack-allwinner:~# . /tmp/sd/yi-hack/script/env.sh
root@yi-hack-allwinner:~# /tmp/sd/yi-hack/script/thumb.sh cron
```

**Comment by oat1** [comment]
It is running now, starting thumb.sh cron helped. 
Thumbnails are being created and I can see them in the media section.

To be honest I have no idea why the script did not run automatically after the update and reboot

**Comment by oat1** [comment]
Proces makes thumbnails, but only once. New records do not have them and cron does not start automatically again. How do I change it ?

![image](https://user-images.githubusercontent.com/59432560/159016273-540b9e8e-c436-4b2d-984d-b7feff669501.png)

**Comment by roleoroleo** [comment]
Is crond running?

**Comment by oat1** [comment]
How do I check that?

**Comment by roleoroleo** [comment]
```
root@yi-hack-allwinner-v2:~# ps | grep crond
```

**Comment by oat1** [comment]
![image](https://user-images.githubusercontent.com/59432560/159042617-58f0d87f-e151-4bb3-b726-7876d83af0b9.png)

**Comment by roleoroleo** [comment]
The process is ok, I don't understand.

> and I have
> 0 * * * * sleep 20; /tmp/sd/yi-hack/script/clean_records.sh 5

This is another process, don't care.
Do you have another line with thumb.sh or just this line with clean_records.sh?

**Comment by oat1** [comment]
I have this lines

![image](https://user-images.githubusercontent.com/59432560/159052497-8779938a-b841-4a42-86e2-60fb94d4c516.png)

**Comment by roleoroleo** [comment]
It's ok.
env.sh command sets environment variable.

Check if there are empty jpg in the record folder.
If the process find a jpg file it doesn't try to create it again.
But if the file is zero lenght you can't see the image in the media source.

**Comment by oat1** [comment]
I did not find any empty jpg :(

If it is a cron then how often should the process start? Every 1 hr ?

**Comment by roleoroleo** [comment]
"* * * * *" means every 1 minute.

**Comment by roleoroleo** [comment]
Found the problem.
Check the last commit:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/968dd8580b1800c2b0ae0d035a171be490b21781

**Comment by oat1** [comment]
Great 😃👍 can I test it now, upadte via ssh ? How?
Or wait till next release?

**Comment by roleoroleo** [comment]
> upadte via ssh ?

Yes.

**Comment by oat1** [comment]
But how ?

**Comment by roleoroleo** [comment]
You can use vi to edit the file.
Or, download the file from github and copy it to the cam with ftp.

**Comment by oat1** [comment]
I've applied these changes in ftppush.sh and thumb.sh, reboot the camera and the problem still appears. No new thumbnails are being created

**Comment by oat1** [comment]
Sorry, after some time works just fine :) thanks for your patience :)  
My last question due to this topic, Can I somehow enable the thumbnail in [yi-hack-v5](https://github.com/alienatedsec/yi-hack-v5)?
I know that it is not your project, but you help the creator. Maybe I will copy some files and lines of code from this project to make it work?
