### ISSUE TITLE
4M request to my DNS server in the last 30 days

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#381]
What is appening?
![image](https://user-images.githubusercontent.com/12989749/156537072-edd95d2a-7cae-44da-bb95-55feefd31a5d.png)

**Comment by PilaScat** [comment]
But not twice per second ahahah
And it has been doing it since the last update

**Comment by roleoroleo** [comment]
> But not twice per second ahahah And it has been doing it since the last update

Only after the update to 0.2.0?

**Comment by PilaScat** [comment]
> > But not twice per second ahahah And it has been doing it since the last update
> 
> Only after the update to 0.2.0?

It seems
