### ISSUE TITLE
Unbrick r30gb 

### ISSUE THREAD

**Issue by ibanmda** [roleoroleo/yi-hack-Allwinner-v2#393]
Hi  @roleoroleo

I bricked my Yi Dome Guard Camera with my backup after i didn't soft reset succesfully. The cam has permanent red light.

I've readed your how to hard unbrick, but how you can see in the photo my board hasn't GND, RX & TX to solder with my USB-TTL.

I'll aprecciate any suggestion.

Thanks!

![brick_dome_guard](https://user-images.githubusercontent.com/37747906/158073756-965f4836-9f46-4915-a05f-0cfa2da6a3cc.png)

**Comment by ibanmda** [comment]
Maybe is this?

TP3 -> GND
TP2 -> TXD
TP1 -> RXD

**Comment by ibanmda** [comment]
Ok! I tried again with soft method with my old backup and i had configured the cam with the YI app succesfully.
But when I try to hack with yi-hack after the reboot the led still permanently blink green without connection.

Any idea?

**Comment by roleoroleo** [comment]
Try to restore again backup partition.
But load a backup file obtained with this procedure:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/tree/master/unbrick
using the "hacked" option
`./build.sh hacked`

When you restart the cam, it should be already preapred fot the hack.
And the hack procedure shouln't brick the cam.

**Comment by ibanmda** [comment]
I got install again the hack with 0.2.1 firm. I think that the mistake was in the wifi config. Once I copied the key and SSID the cam works perfect with the firmware. Therefore this post can be closed succesfully! :)

Thank you again @roleoroleo !!!
