### ISSUE TITLE
rtsp server down on h60ga

### ISSUE THREAD

**Issue by unintended-consequences** [roleoroleo/yi-hack-Allwinner-v2#394]
Camera: Yi Dome U Camera Pro (LFUS)
Base Firmware: 9.0.27.14 (note latest is 9.0.27.20)
Yi-Hack Allwinner-v2: 0.2.0 (also tried 0.2.1_beta which seems to be mislabelled as 0.2.0 as well)

Issue: Hack installed OK. Settings page access is fine. 
RTSP server inaccessible. 
Snapshot working OK.

Tried RTSP alternative server
Tried low stream

Camera reset via maintenance page after settings change each time. Any suggestions for how to troubleshoot the broken RTSP server please?

**Comment by Close04** [comment]
I probably have the same issue but it didn't look like the server (the process) was down. It was there just not streaming. I downgraded from 0.2.2 to 0.2.1 and 0.2.0 then back to 0.2.2 and got it to stream again properly (not just run, challenge for authentication but not actually stream).

Try and see if that makes a difference.
