### ISSUE TITLE
Sound? 

### ISSUE THREAD

**Issue by Reddyzinho** [roleoroleo/yi-hack-Allwinner-v2#395]
Hi there. Can I hear a sound using RSTP link? I can’t get it to work. Any idea?

**Comment by roleoroleo** [comment]
rtsp://IP/ch0_0.h264 for high res video and audio
rtsp://IP/ch0_1.h264 for low res video and audio
rtsp://IP/ch0_2.h264 for audio only

Did you enable it?

**Comment by Reddyzinho** [comment]
I think I have missed the enable ;))

Atentamente,

Tiago Cunha

No dia 15/03/2022, às 13:55, roleo ***@***.***> escreveu:

﻿
rtsp://IP/ch0_0.h264 for high res video and audio
rtsp://IP/ch0_1.h264 for low res video and audio
rtsp://IP/ch0_2.h264 for audio only

Did you enable it?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Reddyzinho** [comment]
Well, its done. I reboot the camera and all good now. Thanks :)
