### ISSUE TITLE
r30gb bootloop when enabling mqtt

### ISSUE THREAD

**Issue by lcorsini** [roleoroleo/yi-hack-Allwinner-v2#397]
I have a strange problem with an r30gb
it was hacked before, but microsd died
got a new one, downloaded vers 0.2.1, it works fine until I enable MQTT config
any ideas? the only thing left to try is to reinstall 0.1.9 or keep mqtt disabled

I have another r30gb that works fine with mqtt I also upgraded it to 0.21 without problems

EDIT 
I tried a new out of the box r30gb that I had in my closet and upon installation of 0.2.1 it presents the same behaviour when MQTT is enabled it does bootloop

This is the actual situation
one upgraded from 1.9 works fine
one which was previously hacked presents the boot loop, but happens to talk to mqtt no matter the option
one new out of the box hacked with 0.2.1 which presents the problem

EDIT2
The problem seems to be related to motion detection 
the only one that works writes the motion_files topic while the other just crash and bootloop when detect movement
even if movement detection is disabled by app

**Comment by roleoroleo** [comment]
Is swap file enabled?

**Comment by lcorsini** [comment]
no swap is enabled at the moment, no

**Comment by roleoroleo** [comment]
Try to enable it.
Probably the problem is the snapshot.
When a motion is detected, the cam take a snapshot.
Snapshot requires a lot of memory.

**Comment by lcorsini** [comment]
I'll try (also probably disabling cloud will help) there is a documented  procedure to enable swapfile? I've found this issue https://github.com/roleoroleo/yi-hack-Allwinner/issues/5

**Comment by roleoroleo** [comment]
If you are able to reach the web page switch on the flag.
Otherwise, edit the file yi-hack/etc/system.conf in the sd card.

**Comment by lcorsini** [comment]
it seems to work now, so swapfile seems needed on 0.2.1 it is still strange that the upgraded one (0.1.9->0.2.1) works without

**Comment by roleoroleo** [comment]
My camera never worked without swap files.
But it really depends on the configuration.
