### ISSUE TITLE
Updated h30ga and rRTSPServer not running

### ISSUE THREAD

**Issue by xorguy** [roleoroleo/yi-hack-Allwinner-v2#398]
Hi.
I've just updated 3 cameras via UI to 0.2.1 and one worked great, other had to free space at SD (even it had 30% free) and another even with free space it refuses to load rRTSPServer on boot, I had to manually launch but I know if it reboots video will be down.

Any way I can get logs so you can investigate?

**Comment by ArekInc** [comment]
Same on my cams after UI update and due to that can't get the preview on home assistant integration. Any clues what could go wrong? All the restarts and resets have been done to the HA.

**Comment by roleoroleo** [comment]
Maybe the ota upgrade encountered some problem.
Try to create the sd from scratch.

**Comment by playersct** [comment]
i have this same problem. After upgrade to 0.2.1 i can't get preview on HA

**Comment by ArekInc** [comment]
Worked for me as well. I have noticed that mqtt was disabled after the update so I have switched that on again as well as enabled the alternative RTSP and the HA integration is on again.

**Comment by xorguy** [comment]
After disabling mqtt, restarting, the rRTSPServer was working. Reenabled mqtt and after restarting again it continued to be working, but the online upgrade it was not smooth at all.

**Comment by xorguy** [comment]
After another reboot  rRTSPServer was not running, had to manually launch but it is very very unreliable if it may or may not be running after rebooting.
Is there any way to downgrade without having to remove the SD from the camera?

**Comment by ivanfor** [comment]
Same here. Fresh install. rRTSPServer dies.
Is there anything I can do to help debugging before I downgrade?

**Comment by roleoroleo** [comment]
> After another reboot rRTSPServer was not running, had to manually launch but it is very very unreliable if it may or may not be running after rebooting.

All cams are the same model?

> Is there any way to downgrade without having to remove the SD from the camera?

You can connect with 2 sessions: ftp and ssh.
With ssh you can kill the processes and with ftp you can overwrite the binary files.
For example:
```
killall wd_rtsp.sh
killall rRTSPServer
```
and transfer rRTSPServer via ftp.

> Same here. Fresh install. rRTSPServer dies. Is there anything I can do to help debugging before I downgrade?

Could you please manually run rRTSPServer via ssh?
```
. /tmp/sd/yi-hack/script/env.sh
killall wd_rtsp.sh
killall rRTSPServer
rRTSPServer -m YOUR_MODEL -r both -a YOUR_AUDIO_CONFIGURATION &
```

**Comment by xorguy** [comment]
In my case all the cameras are the same, h30ga. I have reverted to previous version of both wd_rtsp.sh and rRTPServer and  so far the cameras are working with no problem.

The output of the commands, I replaced the IP address with <ip>:
"ch0_0.h264" stream, from memory
Play this stream using the URL "rtsp://<ip>/ch0_0.h264"

"ch0_1.h264" stream, from memory
Play this stream using the URL "rtsp://<ip>/ch0_1.h264"
