### ISSUE TITLE
No mkpasswd - SSH password can't be set.

### ISSUE THREAD

**Issue by AndWalu** [roleoroleo/yi-hack-Allwinner-v2#40]
Version y21ga_0.1.2

mkpasswd  is not available so "system.sh" script can't create PASSWORD_MD5 and setting of password fails.

Workaround:
In a file "/tmp/sd/yi-hack/script/system.sh" change line:
  PASSWORD_MD5="$(echo "${SSH_PASSWORD}" | mkpasswd --method=MD5 --stdin)" 
to:
  PASSWORD_MD5=$SSH_PASSWORD

On any Linux system compute  MD5 hash for your password using "mkpasswd --method=MD5 --stdin"
In file "/tmp/sd/yi-hack/etc/system.conf" set "SSH_PASSWORD" variable to computed MD5 hash.

**Comment by AndWalu** [comment]
The busybox includes mkpasswd applet but mkpasswd link is not created, simply copy any busybox  binary to mkpasswd...
  cp  /tmp/sd/yi-hack/usr/bin/tail  /tmp/sd/yi-hack/usr/bin/mkpasswd

**Comment by roleoroleo** [comment]
I will update the busybox installer.
Thank you.
