### ISSUE TITLE
Connection refused from HA since last firmware update

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#401]
I'm facing this problem after the latest update, I don't know if it's the cam or the integration
![image](https://user-images.githubusercontent.com/12989749/161251211-988b6232-8df5-44cc-a828-2e5479709a99.png)

**Comment by Sarunas88** [comment]
same, one camera out of 4 does this. done resetting and integrating everything from scratch, nothing helps. connection refused and thats all.

**Comment by Sarunas88** [comment]
![Screenshot_20220405_210046](https://user-images.githubusercontent.com/77541449/161830049-aabaec47-1a2e-4b1e-a5fa-aed43850329f.jpg)

**Comment by Sarunas88** [comment]
![Screenshot_20220405_213731](https://user-images.githubusercontent.com/77541449/161835864-a86854d9-f3be-4d5a-9ceb-27200a14ca1c.jpg)

**Comment by roleoroleo** [comment]
I will release 0.2.2 asap.
Check if it works.

**Comment by PilaScat** [comment]
ok thanks

**Comment by Sarunas88** [comment]
Failed to get system configuration from device 192.168.0.68: error HTTPConnectionPool(host='192.168.0.68', port=8080): Max retries exceeded with url: /cgi-bin/get_configs.sh?conf=system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b0dadd8b0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

Unable to get configuration from the cam

Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) rtsp://****:****@192.168.0.105/ch0_0.h264

Error from stream worker: Stream ended; no additional packets
Error from stream worker: No dts in 7 consecutive packets

Error getting status of device 192.168.0.105: error HTTPConnectionPool(host='192.168.0.105', port=8080): Max retries exceeded with url: /cgi-bin/privacy.sh?value=status (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f8b0e683df0>, 'Connection to 192.168.0.105 timed out. (connect timeout=10)'))

Failed to get status on device 192.168.0.105: error unknown

Error from stream worker: Stream ended; no additional packets

**Comment by Sarunas88** [comment]
only 1 out of 3 Cameras are running. 3 failed with same results :(

**Comment by dreimer1986** [comment]
Since yesterday the cams stop working out of nowhere. 2 of 2. 
![Screenshot_20220416-233030](https://user-images.githubusercontent.com/29841368/163691908-b8cb357b-9435-4d1b-bf54-e54a43991934.jpg)
This is what I see when this happens.
Some reboots later they work for a while again

**Comment by dreimer1986** [comment]
Maybe it's due to me activating swap or the new version. But they are running for 9 hours now which is a record when you look at the last week.

**Comment by Sarunas88** [comment]
so i got everything up to date and tried lots things, and one helped me, the cameras are running again. so i think i had very difficult password set on my cameras !? i changed it to something more easily 4 digits 4 letters and the cams are running again :/ we'll see for how long.

**Comment by dreimer1986** [comment]
Mine broke down again. This time only one. On Saturday both were gone. After a forced reboot they come back though:

![image](https://user-images.githubusercontent.com/29841368/165058001-7804eb35-b3e9-45b1-b923-684859d8303b.png)

**Comment by roleoroleo** [comment]
I have a doubt.
Did you configure a reservation for your cam? It is necessary.
Maybe, the cam changes ip address and it becomes unreachable.

**Comment by Sarunas88** [comment]
they are always the same, it got better woth the shorter password but didn't really changed much. the streams are vwry lagging and brakeup often

**Comment by dreimer1986** [comment]
> I have a doubt. Did you configure a reservation for your cam? It is necessary. Maybe, the cam changes ip address and it becomes unreachable.

Yes I did. They completely vanish off the network. After a hard reset they are back on duty.

**Comment by edmundasa** [comment]
I have same issue with 0.2.2 software.
Live stream and snapshot doesn't even load.
top load shows 8-9 ranges constantly. RMM CPU usage increased around 10% from 0.2.1 version with default settings.
On 0.2.1 versions top shows load around 4

**Comment by roleoroleo** [comment]
I tried to investigate the problem but I did not find anything.
I need to know which elements of the integration are not available.

- rtsp stream?
- still images?
- sensors?

> After a hard reset they are back on duty.

Reset of the cam? Whit the back button?
Or reset to factory from the web page?

> top load shows 8-9 ranges constantly. RMM CPU usage increased around 10% from 0.2.1 version with default settings.

RMM is a yi process. It is very unlikely that I can do anything that changes the cpu load of this process.

**Comment by edmundasa** [comment]
Hi @roleoroleo to upgrade I used automatic update and after that RTSP snapshots weren't loading and web interface was very laggy.
After that I reset camera, re-formated sd card and manually installed 0.2.2 and all of issues are gone. So 0.2.2 in itself is working as it should. Thanks. 
Maybe upgrade from interface messed up something in my camera (r35gb).

**Comment by Sarunas88** [comment]
Me too, i have no problems anymore. It took some time after the HA Update and 0.2.2 but I have no problems anymore. do not know why that suddenly working again.

**Comment by roleoroleo** [comment]
The ota procedure is complicated and it can happen that something goes wrong.

**Comment by TheBisk** [comment]
same problem here, 2 of 4 cam not working:
Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) rtsp://****:****@192.168.xxx.xxx:554/primary
Error from stream worker: Stream ended; no additional packets

**Comment by RadaKk** [comment]
Same for me too, I updraded to 0.2.2 manually and I could not access any of the RTSP channels from my dome guard.
Try to revert to 0.2.0 but I face the same issue now...

**Comment by RadaKk** [comment]
Is there any update on this issue? I tried to switch back to each available version of the hack for my dome guard and none of them allow me to use RTSP, snapshot... But everything is working through the yi-home app.

**Comment by dreimer1986** [comment]
Well after I posted here my cams started to behave as I expect them to do. All working fine.

**Comment by fredmassa** [comment]
> 

do you used the "Reset to yi-hack default" button via webpage?

**Comment by fredmassa** [comment]
> 

Hi @edmundasa , do you used the "Reset to yi-hack default" button via webpage?

**Comment by edmundasa** [comment]
@fredmassa no, just formated sd card and put newest hack version files there.

**Comment by fredmassa** [comment]
> @fredmassa no, just formated sd card and put newest hack version files there.

Thanks @edmundasa but no good news... formatted but I've always the same error message:
_2022-08-07 11:05:47.714 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.cam3] Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) rtsp://xx.xx.xx.xx:554/ch0_0.h264_

any idea @roleoroleo

**Comment by fredmassa** [comment]
I tried also opening it form the internal page using vlc but nothing
![image](https://user-images.githubusercontent.com/52414620/183283935-5996d8a9-56b4-46d3-af86-0b43ac3ecb75.png)

**Comment by edmundasa** [comment]
could it be your network issue? some router blocking?

**Comment by fredmassa** [comment]
I don't think.. i have 3 cam, 1 with yi-hack-allwinner and 2 with yi-hack-Allwinner-v2. They were working since 2 months ago and now, same config, same settings, same network.., only the one with yi-hack-allwinner is working properly. The other 2 reply me with that error

**Comment by fredmassa** [comment]
I can turn on/off them but not stream

**Comment by roleoroleo** [comment]
Did you run some yi fw update?
What damon are you running? Standard or alternative?

To debug the problem, please remove ha from the chain: try to read the stream with vlc (try 3-4 times).
If it doesn't work open a ssh terminal and check if the process is running:
`ps | grep rRTSPServer`

**Comment by fredmassa** [comment]
If I try to use the default password, I mean leaving it empty, I cannot login via ssh

**Comment by roleoroleo** [comment]
Please post your config (hide personal data).
`cat /tmp/sd/yi-hack/etc/system.conf`

**Comment by fredmassa** [comment]
yes, here the configs:
**CAM2**
![image](https://user-images.githubusercontent.com/52414620/185453735-8ed73081-6251-412a-9be9-072278e46874.png)

**CAM3**
![image](https://user-images.githubusercontent.com/52414620/185453764-604fadae-35fe-4b8c-bac4-ac58aaa17982.png)

**Comment by roleoroleo** [comment]
RTSP_AUDIO field is empty, it's not normal.
Try to set a value.

**Comment by fredmassa** [comment]
I set the default (disabled) but nothing changed
![SmartSelect_20220818-202322_Chrome](https://user-images.githubusercontent.com/52414620/185467231-83407f6a-faba-4205-ae60-bee288a550f2.jpg)

**Comment by roleoroleo** [comment]
The file is ok, I don't understand.

**Comment by roleoroleo** [comment]
You should try to restart from scratch.
Reset to default the cam with the button.
Then format the sd card and apply again the hack.

**Comment by fredmassa** [comment]
Ok! Please give me 1 week and half and I'll update you

**Comment by fredmassa** [comment]
Ok.. I've done the sd format and the camera hard reset. Followed the hack instruction (pairing with yi app and hack) and the cam was sending the video properly to HA. After 10 minute I moved the cam to the right room and unfortunately I had again the error message. Moved again in the previous position (the one that worked) I have the same error message.

**Comment by ghanashyaml** [comment]
Maybe something to do with internet availability in that area and something
goes wrong after that?

**Comment by fredmassa** [comment]
I don't think so because using yi app it's all working properly

**Comment by fredmassa** [comment]
@roleoroleo 🥳🥳🥳
After last updates all the cams are working properly!!!!
