### ISSUE TITLE
Camera settings not applied after /cgi-bin/camera_settings.sh?conf=value

### ISSUE THREAD

**Issue by outofsight** [roleoroleo/yi-hack-Allwinner-v2#404]
After changing a camera setting with the api `/cgi-bin/camera_settings.sh?conf=value`, for example after a `GET` to turn off the led at the endpoint `http://{{address}}:8080/cgi-bin/camera_settings.sh?LED=no`, the setting is not immediately applied. 
 
I can see the changed setting in the web page, ma the led on the camera is still on.

How to apply che change?

**Comment by outofsight** [comment]
Found the issue. `LED` and other settings key should be lowercase. I was sending uppercase because from `http://ip:8080/cgi-bin/get_configs.sh?conf=camera` you get the settings uppercase, and I was confused because the page `http://ip:8080/index.html?page=camera_settings` was correctly updating the settings.

**Comment by roleoroleo** [comment]
Maybe I could ignore the case...
