### ISSUE TITLE
Yi Dome Guard - RFUS supported !?

### ISSUE THREAD

**Issue by do1osc** [roleoroleo/yi-hack-Allwinner-v2#405]
Hello,

I have got an Yi Dome Guard with prefix RFUS with Base Version  9.0.46.00_202110081405.

I use the r35gb-hack.
It is working, except the Cloud-Disable.
If i disable it, no rtsp, snapshots,.. are working.

Is there a solution ?

**Comment by auanasgheps** [comment]
Hello!
I just installed r35 on the very same cam - Yi Dome Guard RFUS.

I am experiencing a similar issue, where I can't get RTSP to work, regardless of cloud-disable option. 

It also crashes and reboots sometimes.

I think it's not officially supported but let's wait for the dev.

**Comment by roleoroleo** [comment]
I need a backup to check the file system.
Please, share it with me.

**Comment by auanasgheps** [comment]
Should I reset the camera and follow this procedure? 
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)

**Comment by fernandolcardoso** [comment]
I just received this particular model, I decided to test it and everything is normal for me

![image](https://user-images.githubusercontent.com/16019127/161973372-a7f5f3c7-c575-4995-a654-bac741a3edba.png)

**Comment by do1osc** [comment]
I tried to make a Backup, but it seems not to work.
But i got logfiles. Where can i upload them ?

**Comment by auanasgheps** [comment]
So I made further testing:

My camera is exactly the same as OP:

- Base 9.0.46.00_202110081405


- Serial RFUS

I tried to use [this script](https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)): the cam keeps saying "Waiting to connect" and does not reboot. However something got inside the SD card under the "backup" folder so I'll attach it
[backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8445810/backup.zip)

An interesting thing I noticed is BOTH cloud options must be disabled to let RTSP work:

- If Disable Cloud and Recording without Cloud are enabled, RTSP does not work
- If Disable Cloud is turned off but Recording without cloud is enabled, RTSP does not work
- If both are turned off, RTSP works

**Comment by fernandolcardoso** [comment]
> So I made further testing:
> 
> My camera is exactly the same as OP:
> 
> * Base 9.0.46.00_202110081405
> * Serial RFUS
> 
> I tried to use [this script](https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)): the cam keeps saying "Waiting to connect" and does not reboot. However something got inside the SD card under the "backup" folder so I'll attach it [backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8445810/backup.zip)
> 
> An interesting thing I noticed is BOTH cloud options must be disabled to let RTSP work:
> 
> * If Disable Cloud and Recording without Cloud are enabled, RTSP does not work
> * If Disable Cloud is turned off but Recording without cloud is enabled, RTSP does not work
> * If both are turned off, RTSP works

Try:
1. Reset to yi-hack default
2. Reboot
3. Connect again

**Comment by fernandolcardoso** [comment]
![image](https://user-images.githubusercontent.com/16019127/162290595-6f49d9b8-1e54-4783-99d8-708899f250cf.png)

Here I am connected for more than 7 hours in FullHD transmission

**Comment by auanasgheps** [comment]
> Try:
> 
>     1. Reset to yi-hack default
> 
>     2. Reboot
> 
>     3. Connect again

With defaults doesn't work. I also made an additional reboot, but no RTSP (which is enabled). Snapshots work.

I restored my working settings. RTSP doesn't work. Crap.

**Comment by fernandolcardoso** [comment]
@auanasgheps, out of curiosity, what app or what are you using to connect. Depending on your need, I can guide you better.

**Comment by auanasgheps** [comment]
> @auanasgheps, out of curiosity, what app or what are you using to connect. Depending on your need, I can guide you better.

To verify if it works, I use VLC on my PC.
After all the firmware does not look super stable/reliable, because I can eventually get to connect.

**Comment by fernandolcardoso** [comment]
![image](https://user-images.githubusercontent.com/16019127/162317452-449ec3d9-51af-4a44-bb85-eb9c1d1bfff2.png)

Working around here... wouldn't your router be congested? Try putting it on the network cable and accessing via the cable's IP.

**Comment by auanasgheps** [comment]
My router is fine. 
Maybe you're missing the point that I can connect to the RTSP feed, but only when both "cloud disable" options are not enabled, and not using default config, but might be unrelated.

**Comment by fernandolcardoso** [comment]
![image](https://user-images.githubusercontent.com/16019127/162330021-2471b0e9-5701-437d-badf-a12352c4c19a.png)

It's really strange, here it works with the Cloud on and off

**Comment by fernandolcardoso** [comment]
![image](https://user-images.githubusercontent.com/16019127/162330218-bb01353d-c29e-4900-bfba-6290ec090c26.png)

@auanasgheps It's really strange, here it works with the Cloud on and off

**Comment by fernandolcardoso** [comment]
@auanasgheps try this...

Reset, reboot and then follow this step:

- Go to settings, disable only Telnet, save and restart;

Test connects at this step, if it doesn't work:

- Reset, restart and connect again.

I just remember doing it on my camera.

**Comment by IDerr** [comment]
I have the same issue for my camera, don't really know if it's linked to a ressource issue
but after some rebooting it does work.

**Comment by auanasgheps** [comment]
@fernandolcardoso Right now I cannot reset/mess with the camera, I need it to work (and right now it's working).

@IDerr I am experiencing a similar behaviour. Let's wait for the dev to comment, I provided a backup in a comment above

**Comment by roleoroleo** [comment]
Sorry for the delay in replying.

> Should I reset the camera and follow this procedure? https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)

You can follow the procedure without reset the camera.

> Hello @roleoroleo, when you request the backup, what do you do to see if it works or not? Can you simulate the camera in some virtual environment? I would like to understand this part to see if I can contribute in some way to this project.

I extract the 3 filesystems and I compare them with other models.
If the difference is not big I try to adapt the code to the new model.
It's very difficult to simulate the camera with a virtual environment, the software is closely related to the hardware.

> An interesting thing I noticed is BOTH cloud options must be disabled to let RTSP work:
> 
>     * If Disable Cloud and Recording without Cloud are enabled, RTSP does not work
> 
>     * If Disable Cloud is turned off but Recording without cloud is enabled, RTSP does not work
> 
>     * If both are turned off, RTSP works

This behavior is not normal, I will check the backup file.

**Comment by roleoroleo** [comment]
> I tried to use [this script](https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)): the cam keeps saying "Waiting to connect" and does not reboot. However something got inside the SD card under the "backup" folder so I'll attach it [backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8445810/backup.zip)

You cam is a "standard" r35gb and it's supported.
I don't know why the rtsp stream doesn't work with cloud disabled.
Try the following:
- Enable swap file to extend memory.
- Login with a ssh session and check if the rtsp process is running: "ps | grep RTSP".

**Comment by do1osc** [comment]
@roleoroleo 
On my cam, RTSP is running as process, when cloud is disabled, but no rtsp-stream is available.
With and without, it is not working. only if cloud is enabled, it is working.

Can you give us some information, what will be done if cloud is disabled ? What will be stopped, oder will some network-trasfer blocked ?

**Comment by auanasgheps** [comment]
> > I tried to use [this script](https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)): the cam keeps saying "Waiting to connect" and does not reboot. However something got inside the SD card under the "backup" folder so I'll attach it [backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8445810/backup.zip)
> 
> You cam is a "standard" r35gb and it's supported. I don't know why the rtsp stream doesn't work with cloud disabled. Try the following:
> 
> * Enable swap file to extend memory.
> * Login with a ssh session and check if the rtsp process is running: "ps | grep RTSP".

Will enable swap and let you know.

Another thing to bear in mind is that sometimes by simply rebooting the camera a couple of times RTSP starts to work, like @IDerr reported.

The other day I had to reboot the camera, because was online but RTSP stopped working. I basically had no recognition feature and only RTSP was enabled.

**Comment by roleoroleo** [comment]
> Can you give us some information, what will be done if cloud is disabled ? What will be stopped, oder will some network-trasfer blocked ?

When cloud is disabled the following process don't start:
```
cloud
p2p_tnp
oss
rtmp
watch_process
```

I don't know what is the role of these processes.
The rtsp process reads the stream from the frame buffer. The frame buffer is filled by rmm process.
I think the problem is not relater to the cloud.

**Comment by do1osc** [comment]
@roleoroleo 
i figured out:
/dev/shm/fshare_frame_buf will be filled, but rRTSPServer do not deliver the data to the port

**Comment by do1osc** [comment]
@roleoroleo 
Strange behaviour: After disabling snapshot and executing:
killall rRTSPServer && /tmp/sd/yi-hack/bin/rRTSPServer -m r35gb -r both -a no -p 554 -u <user> -w <password>

it works. After resets it works too

**Comment by roleoroleo** [comment]
Mmmmmhhh...
How do you test the server?
I noticed a strange behavior when I start a client: sometimes it doesn't start immediately and I have to run the play command several times before seeing the stream.

**Comment by do1osc** [comment]
> Mmmmmhhh... How do you test the server? I noticed a strange behavior when I start a client: sometimes it doesn't start immediately and I have to run the play command several times before seeing the stream.

I use the link from Main-page:
rtsp://192.168.178.65/ch0_0.h264
This starts VLC.

**Comment by roleoroleo** [comment]
When vlc returns an error, try to press play button again and check if it starts.

**Comment by do1osc** [comment]
> 

Connection failed
VLC could not connect to "192.168.178.65:554".

i can press it every 3 seconds. not possible to connect.

**Comment by roleoroleo** [comment]
Are you able to capture the network traffic with wireshark (or tcpdump)?

**Comment by do1osc** [comment]
> Are you able to capture the network traffic with wireshark (or tcpdump)?
> 
> 

I will try it today or Tomorrow.

**Comment by do1osc** [comment]
Here the dumps:
1. with Snapshot off (working)
2. with Snapshot on (not working

[Traces.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8505209/Traces.zip)

**Comment by do1osc** [comment]
@roleoroleo 
I have found out, that it seems to be a timing- or data-problem at startup.
After switch snapshot on for the traces, i disabled it, but rtsp was not working.

I killed at started rrtspserver manually and it works.
After a new reset it works automatically.

**Comment by roleoroleo** [comment]
Reading the dump, it seems that the damon is not running.
It doesn't reply to the tcp syn packet.

> I killed at started rrtspserver manually and it works.
> After a new reset it works automatically.

With this sequence, does it work?
1- Configure snapshot on.
2- Reboot.
3- Kill rRTSPServer
4- Wait for watchdog to restart it.
5- Connect with vlc.

**Comment by do1osc** [comment]
Yes, this works.

**Comment by roleoroleo** [comment]
Another try please.
Does it work with alternative rtsp server?

**Comment by do1osc** [comment]
> Another try please. Does it work with alternative rtsp server?

Yes, this is working with snapshot enabled.

**Comment by roleoroleo** [comment]
Please try the new version I released yesterday.

**Comment by do1osc** [comment]
> Please try the new version I released yesterday.

Same problems:
Rtsp not working until killall rRTSPServer && /tmp/sd/yi-hack/bin/rRTSPServer -m r35gb -r both -a no -p 554 -u <user> -w <password>

snapshot enabled, rtsp also not working

**Comment by roleoroleo** [comment]
The mystery deepens...

**Comment by auanasgheps** [comment]
I upgraded to the latest version, and RTSP did not work.
SSH in, killed RTSP with  `killall rRTSPServer` and waited, but nothing.

Rebooted and... nothing.

Rebooted again and nothing.

I don't have time to do more tests today, tomorrow I'll come back.

**Comment by roleoroleo** [comment]
When you have time, try to run rRTSPServer with debug option: "-d 3".

**Comment by auanasgheps** [comment]
> When you have time, try to run rRTSPServer with debug option: "-d 3".

How can I do it?

**Comment by roleoroleo** [comment]
Simply add  "-d 3" to the cmd line.
`/tmp/sd/yi-hack/bin/rRTSPServer -d 3 -m r35gb -r both -a no -p 554 -u -w`

You can redirect the output to a file:
`/tmp/sd/yi-hack/bin/rRTSPServer -d 3 -m r35gb -r both -a no -p 554 -u -w 2>&1 >/tmp/sd/rtsp.log`

**Comment by auanasgheps** [comment]
Alright but I understood the daemon would restart the service automatically when killed. Am I missing something?

**Comment by roleoroleo** [comment]
You can kill the watchdog:
```killall wd_rtsp.sh
```

**Comment by auanasgheps** [comment]
Hi,
So I used the command above to kill the watchdog and start the server redirecting the output to a file. The file gets created but is empty so I guess the command is wrong

**Comment by roleoroleo** [comment]
If you want to try, you can edit system.sh and change the starting command of rRTSPServer.

**Comment by auanasgheps** [comment]
So I enabled _Disable Cloud_ and now RTSP doesn't work.
Killed and restarted RTSP with the log command.

Tried connecting a couple of times, no success. 

I have attached the log, but looks like there isn't much
[rtsp.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8640117/rtsp.zip)
.

**Comment by roleoroleo** [comment]
The frame sequence in the log is ok.
There are no lost frames.
But I can't see the log:
`Stream detected: high res is h264, low res is h264`
https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/bf96b2413a9512e969afd5a43cc3113c7ddc48e1/src/rRTSPServer/src/rRTSPServer.cpp#L1323

I need a copy of your /dev/shm/fshare_frame_buffer
Maybe there is a difference between your cam and the m35gb I previously analyzed.

**Comment by auanasgheps** [comment]
Hey, I extracted the file you requested, but it's called `fshare_frame_buf`

[fshare_frame_buf.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8660910/fshare_frame_buf.zip)

**Comment by roleoroleo** [comment]
The frame buffer is ok, is the same as what I had already analyzed.
And the code seems ok.
Try this binary, if you can.
Rename the old one and decompress the new one in the same path: /tmp/sd/yi-hack/bin
[rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8679042/rRTSPServer.gz)

**Comment by auanasgheps** [comment]
I replaced the file, rebooted and... **IT WORKS!!**
Thank you!
I'm also using "Disable Cloud" feature! It never worked when this feature was turned on!

I've done multiple reboots and toggled the Cloud option, and has been working reliably since the file replacement.

Have you found the root of the problem?

One side problem, the stream always shows a timestamp which does not respect the real one, is this expected?
![immagine](https://user-images.githubusercontent.com/20586878/168340429-90c8a975-6310-444e-906e-4d62b08bc4b9.png)

**Comment by roleoroleo** [comment]
> So, have you found the root of the problem?

I moved 2 sleep instructions.

> One side problem, the stream always shows a timestamp which does not respect the real one, is this expected?

Set the timezone both in the app and in the web page.

**Comment by auanasgheps** [comment]
> > So, have you found the root of the problem?
> 
> I moved 2 sleep instructions.
Thank you, well spotted!
> > One side problem, the stream always shows a timestamp which does not respect the real one, is this expected?
> 
> Set the timezone both in the app and in the web page.
Thanks, will do. I haven't used the app yet on these cameras!

**Comment by auanasgheps** [comment]
@roleoroleo are you planning to eventually release an update with the rtsp server fixed for this camera and add it to the readme? I can do the second

**Comment by roleoroleo** [comment]
I'm ready to publish a new release.

**Comment by auanasgheps** [comment]
@roleoroleo after few days running the new firmware, RTSP is broken again.

Stream was unavailable, so I logged in the WebGUI. Load average is pretty high
![immagine](https://user-images.githubusercontent.com/20586878/193336152-37e3a2df-2ad7-4c4e-b148-fd8fd0fb08a9.png)


And guess who is behaving bad?
![immagine](https://user-images.githubusercontent.com/20586878/193336287-bb101495-e70f-40aa-abc9-39f56f3f0b9b.png)

I have not changed a single setting from 0.2.2, but I was running the patched RTSP Server. Did you commit that change to 0.2.3?

**Comment by roleoroleo** [comment]
Yes
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/c37d06e5b3565d9ea198cfc7776054cda8851142

Do you want to try again the patched rRTSPServer attached above?

**Comment by auanasgheps** [comment]
Sure, but I'll wait for the next crash / high load.

In the meantime I see that ./rmm is loading up the camera. Is this normal? I don't know what it does.

![immagine](https://user-images.githubusercontent.com/20586878/193404193-cb079ab5-256b-41c3-8aeb-669766b1dc35.png)

**Comment by roleoroleo** [comment]
rmm is the main yi process.
Normally is about 40-50% of CPU.

**Comment by auanasgheps** [comment]
Okay, it's in the 60ies range.
So this load average is expected? 3.91 3.61 3.61

Looks a tad too high.

**Comment by roleoroleo** [comment]
This is my load when rmm is 40%
1.96 1.51 1.31
It depends on the features you are using: motion detection, human detection, etc...

**Comment by auanasgheps** [comment]
> It depends on the features you are using: motion detection, human detection, etc...
Disable Cloud
RTSP
Snapshot
SSH and FTP
NTPD
Only Motion Detection, no Human Detection.

I remember the load in the past was similar to yours.


RTSP Server has crashed again, it's a consistent issue. I have now installed the patched RTSP that worked on the last firmware, I'll keep you posted.

**Comment by auanasgheps** [comment]
Crashed again. 
Very high load average:  5.93 5.51 5.10.

What am I supposed to do? Grab logs like the last time?

**Comment by roleoroleo** [comment]
Yes, grab the log.
Or could be the kernel that kills the process due to a low memory condition.

**Comment by auanasgheps** [comment]
memory is fine, now is  `Free/Total Memory | 29600/60676 KB` and usually is around this value.

So no problem there.

It's funny because two days ago after the crash I disabled "Disable Cloud" and "Recording without Cloud", and hasn't crashed since then.

Do you think is related?

**Comment by roleoroleo** [comment]
I think it's not related.
Is there a firewall between the cam and internet? Are you blocking any service?

**Comment by auanasgheps** [comment]
> Is there a firewall between the cam and internet? Are you blocking any service?

Nope, I'm not doing any of these.

The RTSP stream froze again, so it's not related.

**Comment by auanasgheps** [comment]
Allright, so:

killed the watchdog `killall wd_rtsp.sh`
killed the service `killall rRTSPServer`

Restarted the service `/tmp/sd/yi-hack/bin/rRTSPServer -d 3 -m r35gb -r both -a no -p 55 4 -u -w &> /tmp/sd/rtsp.log`

The terminal looks like this
![image](https://user-images.githubusercontent.com/20586878/194824691-14fd8f56-476a-410a-a36f-21235bf4c0bf.png)

So i can't close it.
I kept it open for a while but it's not recording much:

```
1665390070816: the size of the buffer is 1786156
1665390070826: mapping file fshare_frame_buf, size 1786156, to b6c0d000
1665390070826: closing the file fshare_frame_buf
1665390070826: starting capture main loop
```

I will now reboot the camera and try again.

**Comment by auanasgheps** [comment]
After I restart the camera, if I run the same commands, logs do actually grab a lot of stuff.

How can I configure logging in the service by default, so I can properly grab the crash?

**Comment by roleoroleo** [comment]
Edit the file system.sh

**Comment by auanasgheps** [comment]
I have found the file but there are so many options. Can you please tell what exactly should I change? Thanks

**Comment by roleoroleo** [comment]
3 occorrences:

https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/eee53a333d16ff7e5d933220a7c62edbb5787b82/src/static/static/yi-hack/script/system.sh#L282

https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/eee53a333d16ff7e5d933220a7c62edbb5787b82/src/static/static/yi-hack/script/system.sh#L290

https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/eee53a333d16ff7e5d933220a7c62edbb5787b82/src/static/static/yi-hack/script/system.sh#L298

**Comment by auanasgheps** [comment]
Thank you! I've done the following to each line:
`$RTSP_DAEMON -m $MODEL_SUFFIX -r both $RTSP_AUDIO_COMPRESSION $RTSP_PORT $RTSP_USER $RTSP_PASSWORD &> /tmp/sd/rtsp_new.log`, so I just added `> /tmp/sd/rtsp_new.log`

Now the log populates automatically:

```
unable to find /tmp/audio_fifo, audio disabled
1665483243294: warning - 85 frame(s) lost

"ch0_0.h264" stream, from memory
Play this stream using the URL "rtsp://192.168.0.150/ch0_0.h264"
```

Will update you when it crashes.

**Comment by roleoroleo** [comment]
If you want the complete log you have to add "-d 3" option.

**Comment by auanasgheps** [comment]
@roleoroleo the camera hasn't crashed yet since i enabled logs. That's strange :)
I will do what you recommend.

I have to report another issue, though. All night vision videos are blocky/bugged and are unusable. Daylight videos are fine. Are you aware of this problem?

**Comment by roleoroleo** [comment]
> I have to report another issue, though. All night vision videos are blocky/bugged and are unusable. Daylight videos are fine. Are you aware of this problem?

Unfortunately I can't change this behavior.
h264 comression is made by yi processes and it's not configurable.

**Comment by auanasgheps** [comment]
> > I have to report another issue, though. All night vision videos are blocky/bugged and are unusable. Daylight videos are fine. Are you aware of this problem?
> 
> Unfortunately I can't change this behavior. h264 comression is made by yi processes and it's not configurable.

It's not really compression. It also freezes for many seconds! 
I can send a video to you if you want to check.

**Comment by roleoroleo** [comment]
Ok.

**Comment by auanasgheps** [comment]
Can you please provide an email address, I'll send it via wetransfer or similar. I don't want to upload it publicly.

**Comment by roleoroleo** [comment]
Let me know when you read this message, I will remove it.
roleo@iperbole.bologna.it

**Comment by auanasgheps** [comment]
Go ahead and remove it.

**Comment by auanasgheps** [comment]
In the meantime, I enabled full logging on RTSP server and here's a big log. It has crashed, but I don't know where.
Do you see anything relevant?
[rtsp_241022.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/9850891/rtsp_241022.zip)

**Comment by roleoroleo** [comment]
The log doesn't show serious problems.
At line 228419 the capture thread exits unexpectedly (or maybe is locked with a mutex) and stops filling the buffer.
But without error messages.
I don't understand.

**Comment by auanasgheps** [comment]
Ok if it is completed, but Yi Dome Guard RFUS is missing from the list of supported models

**Comment by roleoroleo** [comment]
Did the last release fix your issue?

**Comment by auanasgheps** [comment]
@roleoroleo with the firmware 0.2.6 it keeps rebooting.
It's fine with 0.2.4

**Comment by vgisbert** [comment]
What about "Yi Dome Guard RFUS" with the version 12.1.47.05_202411081421 ?
What version should I install?

**Comment by roleoroleo** [comment]
r35gb

**Comment by vgisbert** [comment]
> r35gb

@roleoroleo Sorry. No run properly.

![{C51D2609-1EF1-46CC-A696-817FA55B70CF}](https://github.com/user-attachments/assets/686f2e79-bfc9-4a4e-8a82-580f1152b8a0)

**Comment by vgisbert** [comment]
Yi Dome Guard YRS 12.1.47* yi-hack-Allwinner-v2 0.3.3 r35gb port 554 is closed

I have tried 6 versions, from 0.2.9 to 0.3.3 and none of them work. It seems that Yi has blocked port 554.

@roleoroleo Is it necessary to open an issue?

**Comment by roleoroleo** [comment]
Please, share your backup with me.

**Comment by vgisbert** [comment]
> Please, share your backup with me.

How do I share it? (forgive my ignorance)
