### ISSUE TITLE
It is possible to change camera settings via MQTT?

### ISSUE THREAD

**Issue by outofsight** [roleoroleo/yi-hack-Allwinner-v2#407]
It is possible to change camera settings via MQTT?

I enabled the MQTT config topic, say `yicamera/yi-cam-04/config`.
I publish (from MQTT Explorer) `yes` under the topic like `yicamera/yi-cam-04/config/camera/LED` but nothing changes.
I tried several combination of casing.

**Comment by roleoroleo** [comment]
It doesn't work.
You should try to use mqtt advertise:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/tree/master/src/static/static/yi-hack/script/mqtt_advertise

**Comment by itkfilelor** [comment]
How do we set this up?
Pardon my noobness =)

**Comment by roleoroleo** [comment]
You should enable the config section:
![immagine](https://user-images.githubusercontent.com/39277388/163791550-230f556b-fa0f-4382-a26d-f0a4c2c4fc75.png)

and send the following command:
Topic:
YOUR_MQTT_TOPIC_PREFIX/camera_setting/LED/set
Payload:
yes or no

**Comment by itkfilelor** [comment]
Oof, didn't see the link at the top of the MQTT page. :sweat_smile:
