### ISSUE TITLE
Web interface password

### ISSUE THREAD

**Issue by xzaz** [roleoroleo/yi-hack-Allwinner-v2#41]
First: THANKS for all the work!

I'v got a issue with the web interface. After i'v set the username and password an rebooted the device the username and password for the rtsp stream are set. But the interface on :8080 does not accept the username and password. The rtsp stream does. 

I'v checked `cat /tmp/httpd.conf` and the username and password are correct.

Any ideas?

**Comment by xzaz** [comment]
Yes `#`

**Comment by roleoroleo** [comment]
The parser is very ugly, the # char is not supported.

**Comment by xzaz** [comment]
Np. It was a rtfm since it was explained right under the input.
