### ISSUE TITLE
Swapfile not working

### ISSUE THREAD

**Issue by Netlims** [roleoroleo/yi-hack-Allwinner-v2#413]
Since version 0.20 the swapfile option seems to be ignored.
After I upgraded my camera keeps rebooting every few minutesand when I ssh into it and run 'top' I can see no difference whether I'm using swapfile or not.
I tried creating and using the swapfile myself but many commands are not known to busybox.
How can I do that?

My camera model is h60ga and I'm currently using version 0.21

Thanks a lot!

**Comment by roleoroleo** [comment]
To use all the command you have to sources the environment:
```
. /tmp/sd/yi-hack/script/env.sh
```

Run "free" command and post the output.

**Comment by Netlims** [comment]
![Screenshot_20220417-171822_Chrome](https://user-images.githubusercontent.com/52779912/163718744-ff77660d-82f9-406e-b14f-755d2ec77433.jpg)

I'm on vacation right now so I don't have access to the web interface, only ssh.
If there is anything else you need please let me know.
Do you recommend I will enable swap by myself or should we fix the internal function?

**Comment by roleoroleo** [comment]
Your swap file doesn't work.
You should check your sd card.
- Remove it from the cam (when you are at home).
- Insert it on a PC and run a file system check.
- Remove the file "swapfile" from the card.
- Check if you have enough space (64 MB).

If this doesn't work, probably there is a problem with your model.

**Comment by Netlims** [comment]
My PC indeed detected issues with the SD card, I fixed the issues and deleted the swapfile as suggested.
The camera recreated the swapfile and now everything work!
Thank you very much!
I really appreciate your work and your help
