### ISSUE TITLE
REST-API via Web-Server ?

### ISSUE THREAD

**Issue by do1osc** [roleoroleo/yi-hack-Allwinner-v2#416]
Is it possible to use an REST-API for control the camera ?
E.g: PTZ-Control ?

**Comment by roleoroleo** [comment]
It's not exactly REST but yes, it's possible:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description

**Comment by do1osc** [comment]
This cool and exact, what i am searching for.

Thanks
