### ISSUE TITLE
Yi home 1080 does not create/send alerts

### ISSUE THREAD

**Issue by caiocesar87** [roleoroleo/yi-hack-Allwinner-v2#420]
Hi guys, Congrats for the job!

I installed the hack to upload my images to an ftp server. But after installation, the camera stopped creating motion alerts and saving images in "record" folder. It only works when I enable the "Record continuous video" option. Does anyone know what can it be?

**Comment by roleoroleo** [comment]
Are you using human detection?
If yes, disable it.

**Comment by caiocesar87** [comment]
Hi! Thanks for answer me,

I'm not using the human detection.
