### ISSUE TITLE
Yi Outdoor IFUS - Firmware Version - 0.2.2

### ISSUE THREAD

**Issue by logzorz** [roleoroleo/yi-hack-Allwinner-v2#421]
Hi guys, I've recently flashed my outdoor camera with the latest firmware, I have an issue where I cannot access the status page and it appears to spike the ping to 1300ms, aswell as the image quality coming through with lines across the live image, the camera ran fine prior for about 6 hours. Im unsure on how to send you guys a log if you could please advise.

Thank you.
![Outdoor](https://user-images.githubusercontent.com/8142977/164707115-7a68b1fc-c24a-4a44-bfd0-b47091b25813.JPG)
![tempsnip](https://user-images.githubusercontent.com/8142977/164707718-866b2f5f-ff3e-47e5-adc8-43a8d2b5aa35.png)

**Comment by roleoroleo** [comment]
You should try to restore the original fw and check it the cam works.
I think it's a hardware problem.

**Comment by logzorz** [comment]
I think you may be right, I reflashed the Y21GA firmware as a test and its doing the same thing. Ill restore the original firmware and report back. Thank you for the reply Roleoroleo!

**Comment by logzorz** [comment]
Confirmed hardware problem! Apologies for the issue raise!
