### ISSUE TITLE
yi home 1080p no record on sd card

### ISSUE THREAD

**Issue by kidlerz** [roleoroleo/yi-hack-Allwinner-v2#422]
Hello,
Firmware Version | 0.2.2
Model Suffix | y21ga

Disable Cloud  - ON
Recording without Cloud - ON
Switch on/off the camera - ON
Save video when a motion is detected - OFF

and no files on sd card /tmp/sd/record/

why ?

**Comment by razem-io** [comment]
Same here. It only works for me if I am connected to Wi-Fi. Will try every option and report back if anything works.

**Comment by roleoroleo** [comment]
> Same here. It only works for me if I am connected to Wi-Fi. Will try every option and report back if anything works.

Is the cam connected to the network?

**Comment by razem-io** [comment]
Hey @roleoroleo, somehow missed the notification, sorry. 

Yes, the cam is connected to the network. Then the recording works without issues. If I take it somewhere else, where the wifi is not available, it won't record any videos.

Also my model is the QFUS, so I am using y211ga not y21ga.

**Comment by razem-io** [comment]
@roleoroleo if it is time issue I can try to fix it myself. I was browsing through the project to find where it could fail. So far I haven't found anything. Do you have a suggestion?

**Comment by roleoroleo** [comment]
Other people have reported this problem.
Unfortunately it depends on the yi processes and I have not found a solution.

**Comment by razem-io** [comment]
Not stale, just no solution yet.

**Comment by razem-io** [comment]
@kidlerz why did you close the issue? It still exists, right?
