### ISSUE TITLE
Privacy initialize as on

### ISSUE THREAD

**Issue by piesinopoli** [roleoroleo/yi-hack-Allwinner-v2#424]
Privacy initialize as on, on reboot of the camera. I have to turn off with the service 
http://IP:8080/cgi-bin/privacy.sh?value=off

Why?

**Comment by roleoroleo** [comment]
I recently noticed this problem.
I will check it.

**Comment by piesinopoli** [comment]
Let me know.

**Comment by piesinopoli** [comment]
@roleoroleo news?

**Comment by roleoroleo** [comment]
Try to apply this commit:
https://github.com/roleoroleo/yi-hack_ha_integration/commit/b84334c016dc4e57f3311793665c563dfecb77c4
