### ISSUE TITLE
Yi Dome Guard (r30gb) solid red light v0.2.2

### ISSUE THREAD

**Issue by pagkly** [roleoroleo/yi-hack-Allwinner-v2#438]
Someone gave me Yi Dome Guard (r30gb) YRS.3019.
I set it up one time with Yi app from Play Store and worked fine.
During setup it usually blinks red light and once connected to wifi steady green light.
After unplugging the power cable and re-plug, I noticed it showed steady red light and not connected at all to the wifi and the app.
Hard reset button did not work at all.

I used Sandisk SDHC 16 GB sd card and successfully backed up the firmware following the wiki.
[r30gb_factory_backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8730600/r30gb_factory_backup.zip)

Thinking maybe the hack will fix it, I applied the hack (0.2.2 release), but it still showed steady red light.
Applying [backup_r30gb.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8730660/backup_r30gb.gz) generated from unbricking guide and mtdblock4.bin seems not working and still showed steady red light.
Hard reset button still did not work.

Please kindly help.
Thank you.

**Comment by roleoroleo** [comment]
Are you using the original power supply and cable?

**Comment by pagkly** [comment]
@roleoroleo yes, I use both

**Comment by roleoroleo** [comment]
If you were able to create a backup, the cam is alive.
But, analyzing your backup, it's not clear why your cam doesn't work.
It seems ok.

**Comment by roleoroleo** [comment]
> Thinking maybe the hack will fix it, I applied the hack (0.2.2 release), but it still showed steady red light.
> Applying [backup_r30gb.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/8730660/backup_r30gb.gz) generated from unbricking guide and mtdblock4.bin seems not working and still showed steady red light.

If the cam doesn't work without hack, it will not work applying the hack.
