### ISSUE TITLE
Escam PT202

### ISSUE THREAD

**Issue by macedpo** [roleoroleo/yi-hack-Allwinner-v2#439]
I have a PT202 with installed Hack B091QP .
Is there a possibility to provide a HTTP Port such as 82xx.
I would like to use the PT202 with my DVR that uses a NETIP ----> 192.168.0.129:82xx
On my DVR the Channel status is: Mainstream/Sub-stream --->  1080P/UNKNOWN
The Sub-stream is not detected on my DVR although the RSTP stream is set to "BOTH"
On all my other IP ONVIF/RSTP cams  i see both streams.
I think the DVR is using the Sub-stream image for the mosaic because ik see only a black picture. If i "doubble-click on the black mosaic i get a perfect 1080P "Mainstream" picture of my PT202.
Any thoughts ?
Many thanks.
PT202 is D07
![IMG_20220523_073058](https://user-images.githubusercontent.com/106037592/169750046-8b0f68d5-e284-4d19-adf1-d34ce1dd79f0.jpg)

**Comment by roleoroleo** [comment]
> Is there a possibility to provide a HTTP Port such as 82xx.

You can change the TCP ports in the configuration web page. But I don't understand how this will help you.

IMHO onvif is not a good standard and there are many compatibility problems.
I don't know what your DVR expects and onvif_srvd contains only a partial implementation of the whole protocol.

**Comment by macedpo** [comment]
Hi Roleo,
Thanks for your reply.
On the web page i see indeed RTSP port, Onvif port & HTTPD port but no HTTP port.
My problem is that motion detection doesn't work if i use ONVIF on my DVR (cheap one).
I have also 2 Escam QF218 (D02 & D03 on the picture) and i must configure them as NETIP with HTTP port 82xx and then motion detection works fine. Dont ask my why...
Any idea why the sub stream is not recognized (see picture) ?

**Comment by roleoroleo** [comment]
> On the web page i see indeed RTSP port, Onvif port & HTTPD port but no HTTP port.

HTTPD is the daemon that provides HTTP.

> My problem is that motion detection doesn't work if i use ONVIF on my DVR (cheap one).

Events are not implemented in this onvif daemon.

> I have also 2 Escam QF218 (D02 & D03 on the picture) and i must configure them as NETIP with HTTP port 82xx and then motion detection works fine. Dont ask my why...

This cam doesn't implement NETIP protocol, you can't use it.

> Any idea why the sub stream is not recognized (see picture) ?

No, sorry.

**Comment by macedpo** [comment]
Thanks Roleo for your answer.
Great hack anyway !

**Comment by macedpo** [comment]
Replaced onvif_srvd but no change. Sub-stream unknown on my NVR and black picture on the mosaic. However if i click on the black picture in the mosaic i get a full screen HD image (as before).

**Comment by macedpo** [comment]
Roleo,
I've activated the 2 sliders RTSP server + RTSP altenative server and now i get in the channel status ---> mainstream/substream ---> 1080P/QVGA and see now a perfect image on the mosaic. I'm sure i did that before but with no + results.
So it must be your new onvif_srvd file who did the job !
1000 times thanks !!
