### ISSUE TITLE
xiaomi imilab ec2

### ISSUE THREAD

**Issue by tv4you2016** [roleoroleo/yi-hack-Allwinner-v2#441]
hello, what is the possibility of this hack working on a xiaomi imilab ec2 (CMSXJ11AG)?

**Comment by roleoroleo** [comment]
I don't know.
Please post the firmware version you read in the app.
And take some picture of the internal board.

**Comment by tv4you2016** [comment]
The gateway unit is using a Mediatek Mt7628NN SOC, running a customized version of OpenWrt (version 14, if I recall).
It has 64MB of RAM and 8MB of flash (as far as I could tell).

There is a serial (UART) console connector, close to the usb power port, connect at speed 57600 bps.

**Comment by roleoroleo** [comment]
This hack can't work with your cam.
It needs a new hack.

**Comment by tv4you2016** [comment]
what do you need to do it?? Or can you give me some tips
where to start??

**Comment by roleoroleo** [comment]
Sorry but I don't own this cam and I can't create a hack at the moment.
