### ISSUE TITLE
y21ga | BFUS | v0.2.2: Continuous "click sound" from the cameras after updates?

### ISSUE THREAD

**Issue by outofsight** [roleoroleo/yi-hack-Allwinner-v2#462]
Installed few Yi Hack cameras (also Dome X) around April 15 (previous firmware). Updated firmware in June. 

Now, several times a day, these camera start making a "click sound", in a loop of 20-30 times every 1sec.

The cameras are not rebooting.

There is SD on everyone with swap enabled.

**Comment by roleoroleo** [comment]
If the camera is not in a boot loop the reason could be a the light of the room.
Dark to switch on ir leds and filter but not enough to mantain it.
So the cam switches on the night mode and then comes back to day mode.

**Comment by zimgui** [comment]
My h51ga camera do the same sound, but only when switch video is closed and camera parked, I disabled the IR led and the sound is still there.

**Comment by zimgui** [comment]
Another test, hide camera using PTZ commands (and status switch always ON) and no click sounds detected.

**Comment by zimgui** [comment]
One more test, compiling with the latest commits make this sound disappear.

**Comment by roleoroleo** [comment]
Which commit?

**Comment by zimgui** [comment]
Sorry, I don't remember, I compiled it about 2 weeks ago, where I can find this information (SD, linux compilation dir)?

**Comment by roleoroleo** [comment]
"2 weeks ago" is enough, thank you.

**Comment by ashish-tandon** [comment]
Hi is there a solution for this

**Comment by roleoroleo** [comment]
I didn't find a fix, but I'm, not able to repeat this behavior with my cams.
