### ISSUE TITLE
[Question] Create an AP on the camara itself? 

### ISSUE THREAD

**Issue by ignaciolg** [roleoroleo/yi-hack-Allwinner-v2#464]
Not sure if possible, but I want to check if is possible or planned at all. 

I've reviewed the configuration to connect to an AP, and it looks like it is doing some "black magic" by writing the configuration on some specific block of the block devices, so I discard the possibility of using those scripts to try to bring an AP up. 

I think that this could be a cool feature, allowing us to use the camera without requiring us to connect it to the internet or an external AP. 

Thx you in advance

**Comment by roleoroleo** [comment]
I already tried to implement this feature but there is an annoying process that periodically checks the wifi configuration and resets it if different from what YI expects. And I can't remove this process.
I failed.
