### ISSUE TITLE
MQTT Settings not working

### ISSUE THREAD

**Issue by hiagocosta** [roleoroleo/yi-hack-Allwinner-v2#469]
I have Yi home camera with model y291ga
and this optoins on home assistant via mqtt doesn't change, only in camera webpage

could be something with this model, is on seria RFUS with 9.0.35 version firmware, using this version [https://github.com/roleoroleo/yi-hack-Allwinner-v2/discussions/445#discussioncomment-2936174](url) of the hack:

![image](https://user-images.githubusercontent.com/22087481/180591789-de1072c6-8660-4d34-a07f-7d4cbafbbea1.png)

**Comment by roleoroleo** [comment]
How did you install these controls?

**Comment by hiagocosta** [comment]
installed via MQTT, using HA integration and MQTT

**Comment by roleoroleo** [comment]
I didn't write the mqtt discovery part.
I need some time to check it.

**Comment by hiagocosta** [comment]
ok,

I will Wait

**Comment by duhow** [comment]
Oh, I thought this was already working... 🤔 
I'll try have a look!

**Comment by duhow** [comment]
For me in f2ddb4034a4a4632b2c4f25064eed03b7c0a149a (`v0.2.3`) only `ROTATE` change works.
