### ISSUE TITLE
Yi home hack not working

### ISSUE THREAD

**Issue by Liquidgsr** [roleoroleo/yi-hack-Allwinner-v2#475]
I have 4 yi home 1080p, 2 yi home dome, and 2 yi home outdoor cameras.  I have tried loading multiple versions of the hack to two of the yi home 1080p 9fus cameras but can't log into the ip address.  I am using a net gear orbi mesh wifi and I have looked up the cameras on both my network and the app.  They connect to the app just fine and work.  Am I doing something wrong.  I have loaded the files on a 8gb and 16gb micro and tried 4 different cards.  No luck.  Fat32 format and saved right on the card not in a folder.

**Comment by roleoroleo** [comment]
First of all, you need to detect the correct version.
If it still doesn't work, check if the backup procecure works.
