### ISSUE TITLE
Missing y291ga hack file in latest release 0.2.2  asset

### ISSUE THREAD

**Issue by radiumfu** [roleoroleo/yi-hack-Allwinner-v2#476]
I got 4 Yi 1080p Home Camera Family Pack, model prefix **RFUS**, out of box FW version **9.0.35**.00202111291330, based on [README.md](https://github.com/roleoroleo/yi-hack-Allwinner-v2#readme), I should download file with prefix **y291ga**, then it missing from the [latest release page](https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/tag/0.2.2) 

official app reminder for latest official FW 11.1.35.3_202207191613, I hold for the upgrade (I like to apply the hack Allwinner-v2)

**Comment by roleoroleo** [comment]
Some users have had problems with the update, there is an issue about this problem.
The fw for this version is pushed but not released.
You can find a beta here: https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/316
