### ISSUE TITLE
MQTT switching between online and offline constantly

### ISSUE THREAD

**Issue by fernandolcardoso** [roleoroleo/yi-hack-Allwinner-v2#489]
There is some bug in the MQTT service

![image](https://user-images.githubusercontent.com/16019127/188430088-ca1f1bd2-1590-45a8-be77-7f7776fe8451.png)

When I activate only the basic with MQTT connections and only the Home Assistant, it works normally.

If I enable any of the features below, the bug occurs.
- MQTT Information Advertisement
- MQTT Link Advertise
- MQTT Camera Settings Advertise
- MQTT Telemetry Advertise

The problem occurs in Firmware 0.2.2 of models r35gb, y211ga and y291ga (beta)

**Comment by fernandolcardoso** [comment]
I forgot to mention that the Wi-Fi is at 100% on most cameras and I tested it on 3 different network systems (cable, regular Wi-Fi and Mesh Wi-Fi).

I also tested with snapshot off and swap on, getting the same result.

Without configuring, the countless times I formatted, changed the cards and reset the settings.

**Comment by roleoroleo** [comment]
Check if you are using the same client id for both services:

![immagine](https://user-images.githubusercontent.com/39277388/188640525-dd99ad8b-3dfc-4f45-a132-698a0221a17a.png)

![immagine](https://user-images.githubusercontent.com/39277388/188640461-ed255391-e24c-4884-b6e4-6ae6927ab5c9.png)

**Comment by fernandolcardoso** [comment]
All cameras are properly identified and in their separate topics.

I'm using the MQTT Explorer app which makes it easy to see all cameras.

Using the default settings, I can get the online status and binary motion sensor.

But if I enable any of the features below, the online and offline situation occurs.

- MQTT Information Advertisement
- MQTT Link Advertise
- MQTT Camera Settings Advertise
- MQTT Telemetry Advertise

![image](https://user-images.githubusercontent.com/16019127/188648016-d8a98992-2d7c-4f31-b6c2-a927c96e7ed8.png)

![image](https://user-images.githubusercontent.com/16019127/188648070-028735c5-091d-4679-85db-5319bc211829.png)

![image](https://user-images.githubusercontent.com/16019127/188648599-6700d6b8-53f0-424c-9415-b077c0c2bba6.png)

![image](https://user-images.githubusercontent.com/16019127/188648709-c5f86cb3-34a2-4832-9dde-3bf8f0dc1c30.png)

**Comment by roleoroleo** [comment]
There are 2 ids in the same cam.
One for the page http://IP:8080/?page=mqtt and another in the page http://IP:8080/?page=mqtt_adv
Are they different?

**Comment by fernandolcardoso** [comment]
**/?page=mqtt**

![image](https://user-images.githubusercontent.com/16019127/189151520-c7ba47dc-03e9-4bc5-9b61-704d78acda5e.png)

![image](https://user-images.githubusercontent.com/16019127/189151580-0c216d80-ab54-4edb-8e26-a54a9b7662c8.png)

**/?page=mqtt_adv**

![image](https://user-images.githubusercontent.com/16019127/189151771-cd0798cf-e30a-445e-b9ad-8c7d59fc2690.png)

**Comment by roleoroleo** [comment]
Ok, change the id in mqtt_adv to "yi-850c-adv" and try if it works.

**Comment by fernandolcardoso** [comment]
It does not solve...

?page=mqtt_adv

![image](https://user-images.githubusercontent.com/16019127/189343276-3d70b83d-04ce-4d12-bbea-6ff63232c1bd.png)

![image](https://user-images.githubusercontent.com/16019127/189343229-e46bffed-a415-4829-914c-746cb6f2c445.png)

No matter what setting I apply, if I enable some of the services below, the problem occurs.
- MQTT Information Advertisement
- MQTT Link Advertise
- MQTT Camera Settings Advertise
- MQTT Telemetry Advertise

![image](https://user-images.githubusercontent.com/16019127/189343432-8bb14079-80bd-48e9-b630-02611d788789.png)

**Comment by roleoroleo** [comment]
Try to overwrite mqtt_adv_* scripts with the content of this archive:
[mqtt_adv.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/9535388/mqtt_adv.tar.gz)
Please, make a backup copy of the files before overwriting.

**Comment by fernandolcardoso** [comment]
I believe it solved, all services are active and with stability in status.

![image](https://user-images.githubusercontent.com/16019127/189403324-fc0da1e5-031d-4421-88f5-0741d16c6af2.png)

**Comment by fernandolcardoso** [comment]
Since my last report, there have been no availability changes and all information is being presented correctly in Home Assistant.

I believe the problem has been resolved.

**Comment by roleoroleo** [comment]
Yes, I will apply it in the next build.
The problem happens when you set hostname and mqtt client id at the same value.

**Comment by fernandolcardoso** [comment]
I inform you that after updating to version 0.2.3, the problem remains

**Comment by roleoroleo** [comment]
I know, I prepared 0.2.3 before these changes.
Please use the scripts I posted above until the next release.

**Comment by leranp** [comment]
Any solution about this issues? 0.3.5 version

**Comment by roleoroleo** [comment]
I think I already fixed this issue.
Please explain me better your setup.
How many cams do you have?
Did you set a different client id for each cam?
...

**Comment by leranp** [comment]
> I think I already fixed this issue.
> Please explain me better your setup.
> How many cams do you have?
> Did you set a different client id for each cam?
> ...

I have only one camera, the problem is only with the  status sensor (binary_sensor.yi_hack_a2_8664f8_status) , the other senaor and the camera are working great, the uptime stay still

**Comment by roleoroleo** [comment]
Please, try to run these commands with a terminal connection.
```
killall wd.sh
killall mqttv4
mqttv4
```
and post the log when the sensor switchs on/off.

**Comment by leranp** [comment]
> Please, try to run these commands with a terminal connection.
> ```
> killall wd.sh
> killall mqttv4
> mqttv4
> ```
> and post the log when the sensor switchs on/off.
> 

root@yi-64f8:~# killall wd.sh
root@yi-64f8:~# killall mqttv4
root@yi-64f8:~# mqttv4
Starting mqttv4 v0.1.0
key: HTTPD | value: yes
Unrecognized config line, ignore it
key: TELNETD | value: no
Unrecognized config line, ignore it
key: SSHD | value: yes
Unrecognized config line, ignore it
key: FTPD | value: no
Unrecognized config line, ignore it
key: BUSYBOX_FTPD | value: no
Unrecognized config line, ignore it
key: MDNSD | value: yes
Unrecognized config line, ignore it
key: DISABLE_CLOUD | value: yes
Unrecognized config line, ignore it
key: REC_WITHOUT_CLOUD | value: no
Unrecognized config line, ignore it
key: RTSP | value: yes
Unrecognized config line, ignore it
key: RTSP_ALT | value: standard
Unrecognized config line, ignore it
key: RTSP_STREAM | value: high
Unrecognized config line, ignore it
key: RTSP_STI | value: yes
Unrecognized config line, ignore it
key: SPEAKER_AUDIO | value: yes
Unrecognized config line, ignore it
key: SNAPSHOT | value: no
Unrecognized config line, ignore it
key: SNAPSHOT_VIDEO | value: no
Unrecognized config line, ignore it
key: SNAPSHOT_LOW | value: no
Unrecognized config line, ignore it
key: TIMELAPSE | value: no
Unrecognized config line, ignore it
key: TIMELAPSE_FTP | value: no
Unrecognized config line, ignore it
key: TIMELAPSE_FTP_SAME_NAME | value: no
Unrecognized config line, ignore it
key: TIMELAPSE_DT | value: 60
Unrecognized config line, ignore it
key: ONVIF | value: no
Unrecognized config line, ignore it
key: ONVIF_WSDD | value: yes
Unrecognized config line, ignore it
key: ONVIF_PROFILE | value: high
Unrecognized config line, ignore it
key: ONVIF_NETIF | value: wlan0
Unrecognized config line, ignore it
key: ONVIF_WM_SNAPSHOT | value: yes
Unrecognized config line, ignore it
key: ONVIF_AUDIO_BC | value: NONE
Unrecognized config line, ignore it
key: ONVIF_ENABLE_MEDIA2 | value: no
Unrecognized config line, ignore it
key: ONVIF_FAULT_IF_UNKNOWN | value: no
Unrecognized config line, ignore it
key: ONVIF_FAULT_IF_SET | value: no
Unrecognized config line, ignore it
key: ONVIF_SYNOLOGY_NVR | value: no
Unrecognized config line, ignore it
key: TIME_OSD | value: no
Unrecognized config line, ignore it
key: NTPD | value: yes
Unrecognized config line, ignore it
key: NTP_SERVER | value: 192.168.31.254
Unrecognized config line, ignore it
key: PROXYCHAINSNG | value: no
Unrecognized config line, ignore it
key: SWAP_FILE | value: yes
Unrecognized config line, ignore it
key: SWAP_SWAPPINESS | value: 15
Unrecognized config line, ignore it
key: KERNEL_TUNING | value: yes
Unrecognized config line, ignore it
key: RTSP_PORT | value: 554
Unrecognized config line, ignore it
key: HTTPD_PORT | value: 80
Unrecognized config line, ignore it
key: TIMEZONE | value: EET-2EEST,M3.5.6/0:01,M9.1.5
Unrecognized config line, ignore it
key: EVENTS_TIME | value: autodetect
Unrecognized config line, ignore it
key: FREE_SPACE | value: 0
Unrecognized config line, ignore it
key: FTP_UPLOAD | value: no
Unrecognized config line, ignore it
key: FTP_DIR_TREE | value: no
Unrecognized config line, ignore it
key: FTP_FILE_DELETE_AFTER_UPLOAD | value: yes
Unrecognized config line, ignore it
key: DEBUG_LOG | value: yes
Unrecognized config line, ignore it
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
CALLBACK AI_HUMAN_DETECTION
Thread 0 available
Wait 0.5 seconds and take a snapshot
Snapshot is disabled
CALLBACK MOTION STOP
Thread 0 waiting
Thread 0 starting
CALLBACK AI_HUMAN_DETECTION
Thread 1 available
Wait 0.5 seconds and take a snapshot
Snapshot is disabled
CALLBACK MOTION STOP
Thread 1 waiting
Thread 1 starting
SENDING FILES LIST
Cannot open directory: 2026Y04M01D11H
Thread exiting
CALLBACK AI_HUMAN_DETECTION
Thread 0 available
Wait 0.5 seconds and take a snapshot
Snapshot is disabled
Error in recv -1 (4)
Connection lost (rc=-1). Reconnect...
Trying to connect...
Connected!
SENDING FILES LIST
Cannot open directory: 2026Y04M01D11H
Thread exiting
CALLBACK MOTION STOP
Thread 0 waiting
Thread 0 starting
SENDING FILES LIST
Cannot open directory: 2026Y04M01D11H
Thread exiting
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!
Connection lost (rc=-8). Reconnect...
Trying to connect...
Connected!

**Comment by roleoroleo** [comment]
The problem is related to frequent disconnection from the brokler.
Please, try this beta:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/tag/0.3.5-8659420

**Comment by leranp** [comment]
> The problem is related to frequent disconnection from the brokler.
> Please, try this beta:
> https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/tag/0.3.5-8659420
> 

Didn't work, the disconnected is happening exactly every 90 second, maybe this can help

**Comment by leranp** [comment]
> > The problem is related to frequent disconnection from the brokler.
> > Please, try this beta:
> > https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/tag/0.3.5-8659420
> > 
> 
> Didn't work, the disconnected is happening exactly every 90 second, maybe this can help

Changing the keepalive to 0  solved the problem

**Comment by roleoroleo** [comment]
I probably fixed the problem, please try this binary:
[mqttv4.gz](https://github.com/user-attachments/files/26481631/mqttv4.gz)
