### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by tv4you2016** [roleoroleo/yi-hack-Allwinner-v2#492]
hello I'm trying to compile the latest version.
git clone https://github.com/roleoroleo/yi-hack-Allwinner-v2

git submodule update --init

then I do:
./scripts/compile.sh
or sudo ./scripts/compile.sh

and this error always occurs, I'm using Visual Studio code with Remote - Containers

![image](https://user-images.githubusercontent.com/83761813/189397639-5cc761b7-4e4d-4460-9eb4-8d667594b824.png)

**Comment by roleoroleo** [comment]
Are you using the master?

**Comment by roleoroleo** [comment]
I need some time to check it.

**Comment by roleoroleo** [comment]
The issue is detailed here:
https://github.com/libffi/libffi/issues/552
Try this commit:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/6c450491682c06116a7c45c4833056da67e5be0c
