### ISSUE TITLE
Snapshots not working, Motion detection broken in IR camera

### ISSUE THREAD

**Issue by edofullin** [roleoroleo/yi-hack-Allwinner-v2#494]
Hi, lately I'm having issues with my camera (IFUS). I tried updating to the latest firmware (0.2.3) but it did not help.

- I cannot take snapshots, the page errors out saying "The image http://10.0.150.240:8080/cgi-bin/snapshot.sh?res=high&watermark=yes cannot be displayed because it contains errors.". After I reboot the camera maybe it works for a few hours and then stops working again.
- The camera detects motion at night randomly and continuously (see picture below), I tried to turn the sensitivity all the way down from the GUI but it did not fix the issue (I am sure there was no motion as it does that every single night)
- Sound detection seems to be not working (though that I can live with no problem)

I'm starting to wonder if maybe it's a hardware issue? Does anyone have any idea if they can be solved?

![image](https://user-images.githubusercontent.com/13950625/190438063-e044de1d-84ba-432b-8bc5-000cdc8e91b6.png)

Thanks in advance!

**Comment by roleoroleo** [comment]
Try to run manually the command with debug option.
```
# . /tmp/sd/yi-hack/script/env.sh
# imggrabber -m YOUR_MODEL -r high -d
```

**Comment by edofullin** [comment]
> Try to run manually the command with debug option.
> 
> ```
> # . /tmp/sd/yi-hack/script/env.sh
> # imggrabber -m YOUR_MODEL -r high -d
> ```
> 
> About detection, does it work without the hack?

Sorry for the late reply, it seems like the issue fixed itself after a number of reset/reinstallation of the firmware.
The second issue also has dropped in frequency, now I don't get a motion notification every thirty seconds (still, every few minutes it still detects non-existent motions)

Sound detection still not working, but as I said that would be a nice to have but I don't really care that much.

Thanks anyway and thanks for your work that makes us really own our cameras.

**Comment by edofullin** [comment]
> still, every few minutes it still detects non-existent motions

This is kinda hilarious, I made the room completely dark (with IR LED always on) and it _still_ only does this at night.
Does the behavior of the motion detection change "at night"? Because I really can't understand why it does that.
