### ISSUE TITLE
y21ga 0.1.0 boot loop

### ISSUE THREAD

**Issue by pep4n** [roleoroleo/yi-hack-Allwinner-v2#5]
Hey there, 

camera is sent into bootloop when trying to boot up 0.1.0: 
Initial boot up with yellow LED until it is stable blue. 
Does the click sound once. 
HTTP is reachable for a few seconds. 
Then yellow LED again and cam reboots. 

Just applied 0.0.8 which is booting up and seems not to reboot (few minutes now). 

Cheers,
P

**Comment by damanti-me** [comment]
I can confirm this.

**Comment by Blutnovsky** [comment]
I have the same issue

**Comment by roleoroleo** [comment]
I remove the release temporarily.

**Comment by c3kkos** [comment]
Where the webui stores settings? May they interfere somehow with services booting up?

**Comment by roleoroleo** [comment]
The webui stores the configuration in /tmp/sd/yi-hack/etc

I compared 0.0.8 and 0.1.0 and I can't understand the problem.
Remember that I don't own this cam :)
I need help.

**Comment by c3kkos** [comment]
Are there any watchdogs active?

**Comment by roleoroleo** [comment]
Only if rmm is not running.
But I think it's not possible.

**Comment by roleoroleo** [comment]
Could you try this?
[y21ga_0.1.0.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5440642/y21ga_0.1.0.tar.gz)

**Comment by roleoroleo** [comment]
Could you try this?
[y21ga_0.1.1.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5440647/y21ga_0.1.1.tar.gz)

**Comment by pep4n** [comment]
> 
> 
> Could you try this?
> [y21ga_0.1.1.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5440647/y21ga_0.1.1.tar.gz)

fixed the boot loop! :) 
I have the feeling the cam, or at least HTTP is work more smoothly. 
RTSP delay via VLC: 2sec. 
no artefacts or other video related issues

issues now: 
- snapshots (high: greenish broken / low: not loading) 
- no audio in RTSP stream 

I guess this issue can be closed for now.
