### ISSUE TITLE
MQTT status rapidly change

### ISSUE THREAD

**Issue by korasinski** [roleoroleo/yi-hack-Allwinner-v2#50]
Hi!

It seems that MQTT integration pings all the time messages about status.
Status is getting online state and around 1,5 seconds later it becomes offline.

<img width="534" alt="Screen Shot 2020-12-09 at 18 39 30" src="https://user-images.githubusercontent.com/48629045/101667677-eabcc800-3a4f-11eb-8609-bd0d266a8834.png">

Firmware Version: 0.1.3
Base Version: 9.0.19.02_202007141512
Model Suffix: y21ga
Serial Number: BFUSY******

**Comment by roleoroleo** [comment]
This is not the correct behavior.
Check your connection because "offline" message could be sent from the broker when the connection goes down.
If the cam loses the connection to the broker, it will send "offline" message.
I checked on my cam and I have no problems.

**Comment by korasinski** [comment]
Yes! You were right, something was not configured. I restored yi-hack settings to the default one, rebotted the cam and now everything works! 

<img width="522" alt="Screen Shot 2020-12-09 at 19 46 00" src="https://user-images.githubusercontent.com/48629045/101673426-6ff7ab00-3a57-11eb-9d7a-79053f5125bf.png">

Maybe someone will have simmilar issue so this may be the fix.
