### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by tv4you2016** [roleoroleo/yi-hack-Allwinner-v2#518]
Version is **master**

git clone https://github.com/roleoroleo/yi-hack-Allwinner-v2

git submodule update --init

then I do:
./scripts/compile.sh
or sudo ./scripts/compile.sh

![image](https://user-images.githubusercontent.com/83761813/198836675-271b59c4-a957-4105-b765-2f762cf01b69.png)

**Comment by roleoroleo** [comment]
Something went wrong in the command
`git submodule update --init`

Did you enter in the yi-hack-Allwinner-v2 folder?

**Comment by roleoroleo** [comment]
Try again with this sequence and check the errors:
```
# git clone https://github.com/roleoroleo/yi-hack-Allwinner-v2
# cd yi-hack-Allwinner-v2
# git submodule update --init
# ./scripts/compile.sh
# ./scripts/pack_fw.all.sh
```
