### ISSUE TITLE
BFUS 9.0.19* - brick

### ISSUE THREAD

**Issue by mates21** [roleoroleo/yi-hack-Allwinner-v2#52]
Can I unbrick cam if i don't have backup files? :(
when i updated to 0.1.3 the camera only has yellow light. Same without sd card.

**Comment by roleoroleo** [comment]
Very strange this brick...
But you need a backup to unbrick your cam.
Another backup of the same model is enough.
Maybe another user could share it with you.

**Comment by mcanteri** [comment]
Hi @mates21 
I shared my backup here, let me know if you can download it (first time I share using MEGA):
https://mega.nz/folder/sCwXFIiJ#hs9HPcYackYvCZ0ThfKImA

**Comment by mates21** [comment]
Thank you very much @mcanteri ! I've already downloaded and I'll try to fix the camera tomorrow
I must open my cam and try this https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Unbrick-the-cam ? is there any other way?

**Comment by mcanteri** [comment]
Well, I never had to unbrick the camera so I suppose that is the reference guide.
But are you sure it is briked ? Have you tried to take out the sd card and reset the camera ? It should factory reset it and the original software should back to work. The hack is not writing anything on the internal memory of the camera, so it is hard to make damages, but maybe could happen.

**Comment by mates21** [comment]
Without sd card, same situation - yellow light only :(
reset also did not help. after turning on the power, immediately yellow paw and that's it

**Comment by maocas** [comment]
I have verified that in my camera the yellow light stays on and hanging when I start the camera with a lower power source. With the original power supply or higher power it starts correctly

**Comment by roleoroleo** [comment]
> I have verified that in my camera the yellow light stays on and hanging when I start the camera with a lower power source. With the original power supply or higher power it starts correctly

I had the same problem with a similar model.

> I must open my cam and try this https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Unbrick-the-cam ? is there any other way?

There is no other way, but the wiki page is tested, another user used it.

**Comment by roleoroleo** [comment]
@mates21 
Did you restore the cam?

**Comment by mates21** [comment]
@maocas it's not the charger fault - I checked on a few, also on the original one.
@roleoroleo unfortunately no :( for me the instruction is too difficult - I'm an amateur in such things :(

**Comment by trtracer** [comment]
Had the same problem. Nothing worked so I connected to the serial port of the Cam to see more details. Turned out, the Backup-Partition was full and the init.sh was truncated. I restored the Backup-Partition (thanks to @mcanteri !) and now it works (with 0.1.2) again. Didn't try upgrading to 0.1.3 yet.

**Comment by roleoroleo** [comment]
Unfortunately this is a problem.
Backup partition is almost full and the jffs driver doesn't handle very well the free space whel it's low.

**Comment by speendo** [comment]
It seems I ran into the same problem.

Lucky me also ripped off the RX solder point. Is there any other place where I can solder the RX connection?

**Comment by speendo** [comment]
> It seems I ran into the same problem.
> 
> Lucky me also ripped off the RX solder point. Is there any other place where I can solder the RX connection?

Lucky me managed to get the camera working again. Actually I didn't really do anything. When I turned it on again today, it was back to normal. Maybe it just didn't like the SD card or the power supply I was using yesterday. Or maybe I just had to leave it switched off for some time in order to get it working again...

However, now the RX solder point is ripped off so I don't have a chance to repair it, in case it breaks in the future. Therefore I would still be interested if there is another place to solder the RX connection.

**Comment by roleoroleo** [comment]
> However, now the RX solder point is ripped off so I don't have a chance to repair it, in case it breaks in the future. Therefore I would still be interested if there is another place to solder the RX connection.

To find another place we need a high res picture of the pcb.

**Comment by speendo** [comment]
I see. I cannot provide that at the moment. Thanks anyway!

**Comment by zalewma** [comment]
Hi Guys, Link is not available anymore... Can you share it again please...
I've run into the same issue ...

**Comment by mcanteri** [comment]
> Hi Guys, Link with backup is not available anymore... Can you share it again please... I've run into the same issue ...

Here is the backup data for the y21ga model
https://mega.nz/folder/lKo1GSgT#LGi8dJt7DdmUZLWXmEjv1g
