### ISSUE TITLE
[FEATURE REQUEST] WiFi Mac Address Selection

### ISSUE THREAD

**Issue by Burbacottero** [roleoroleo/yi-hack-Allwinner-v2#529]
Ciao, mi servirebbe la possibilità di poter scegliere il MAC Address dell'Access Point a cui connettere le telecamere, perche avendo 2 Access Point ogni tanto fa confusione su quale connettersi e sceglie quello con potenza peggiore.
Vorrei impostarne uno che rimanga sempre.
Grazie.

**Comment by roleoroleo** [comment]
Sorry but the connection is managed by Yi software and I can't change it.
wifi_conf binary creates and checks /tmp/wpa_suppplicant.conf file
And it start and kill wpasupplicant process.
I can't add a bssid option.
