### ISSUE TITLE
Camera Crash with NTP String

### ISSUE THREAD

**Issue by AmbiguousCA** [roleoroleo/yi-hack-Allwinner-v2#536]
The camera crashes when using the NTP string PST8PDT,M3.2.0,M11.1.0.  Have to reset SD card and leave the NTP string blank to get the camera to work.  Unfortunately the camera clocks are all wrong.

**Comment by roleoroleo** [comment]
What string do you mean?
Timezone or NTP Server?

**Comment by AmbiguousCA** [comment]
TimeZone String

**Comment by roleoroleo** [comment]
Please, check the last commit.

**Comment by natloh** [comment]
The last commit looks to fix it! 👍

**Comment by natloh** [comment]
@AmbiguousCA did you apply the change to your system.sh file like was done in the commit? There isn’t a new release yet. You need to edit the yi-hack/scripts/system.sh file on your sd card

**Comment by AmbiguousCA** [comment]
Thanks for your assistance.  Updating the system.sh file works.  Much appreciated.
