### ISSUE TITLE
Problem 291ga - continuous reboot loop

### ISSUE THREAD

**Issue by xpinguinx** [roleoroleo/yi-hack-Allwinner-v2#540]
The YI-HACK firmware works perfectly in fact I can enter the configuration page http://[IP-ADDRESS:8080].
The problem is that unfortunately after 10 seconds the CAM keeps restarting and this happens endlessly. If instead I extract the SD memory the cam resumes working regularly. I also tried to load the old versions but without success
I haven't found any reference how to fix it.
Regards

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/FAQ#why-does-my-cam-often-reboot

**Comment by xpinguinx** [comment]
Thanks for the reply.
I performed all the tricks and suggestions step by step before even sending the request for help but unfortunately with negative results.
I disabled the snapshot, I enabled the swap memory, I replaced the power supply with a bigger capacity one, I also disabled other services like FTP, ONVIF to optimize the ram. But unfortunately nothing!
Help me

**Comment by roleoroleo** [comment]
Maybe something went wrong during the installation phase.
Try to install again using another SD card.

**Comment by xpinguinx** [comment]
I tried 32GB memory from three different vendors (SanDisk, Kinkstone, Kodak). After a few seconds the cam loses connection because it restarts as can also be seen from the ping test.
What could this problem be caused by?
Thanks for the support

![access-temp-ok](https://user-images.githubusercontent.com/19188638/206012314-2c276edd-ace1-44ce-95fb-3129c0d49606.PNG)
![ping](https://user-images.githubusercontent.com/19188638/206012319-a1e7342e-c72d-4a4b-9300-cb7518377bf5.PNG)

**Comment by roleoroleo** [comment]
As you can see in this table https://github.com/roleoroleo/yi-hack-Allwinner-v2#supported-cameras
your cam is not supported.
Please send me a backup of the flash and I will try to support it.

**Comment by xpinguinx** [comment]
RoleoRoleo thanks for the reply.
The cam is listed, in fact you can see the photo but unfortunately it doesn't seem to work :(
I backed up the flash as requested. Thanks again for the support.
Regards
![Y291GA](https://user-images.githubusercontent.com/19188638/206132241-f05af02c-f589-4ffe-892d-75c4e190c90d.PNG)
![RFUSY62](https://user-images.githubusercontent.com/19188638/206132246-d55c8b63-0a5a-48ec-a105-6193d3b1be78.PNG)
[backup-fash.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10174281/backup-fash.zip)

**Comment by roleoroleo** [comment]
Only fw 9.x is supported at the moment.

**Comment by xpinguinx** [comment]
Overwritten the file as recommended. 
Unfortunately the orange LED stays on and won't start :(

Thank you for the time you are dedicating to me..
![led-arancione-fisso](https://user-images.githubusercontent.com/19188638/206174365-17cd5289-f21b-4ae6-a068-1192783336f3.PNG)

**Comment by roleoroleo** [comment]
Is it bricked?
Or it works when you remove the sd...

**Comment by xpinguinx** [comment]
When I remove the SD it works perfectly

**Comment by roleoroleo** [comment]
Please, try again with this file.
[lower_half_init.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10177272/lower_half_init.zip)

**Comment by roleoroleo** [comment]
I will add your cam to the list.

**Comment by ec-blaster** [comment]
Hey!

I flashed it again and now it's stable.
I'll keep up trying tonight and tell you tomorrow...

**Comment by ec-blaster** [comment]
I don't know why, but it was stable for a while, but as soon as I powered off the camera and switched in on again, the boot loop continues

**Comment by ec-blaster** [comment]
> try enabling swap and disabling snapshot

It's done already. Both things. And memory seems ok.

The problem comes when I reboot or power off and on again.

But, if I remove the SD card, boot the original firmware, power off, insert the SD again and power it on, it works.

Strange, but it seems that it needs that the original firmware boots before the yi-hack.

**Comment by ec-blaster** [comment]
OK, sorry to bother you, but it was my mistake:

As I had the browser windows open, I thought that the settings changes had been saved, but they weren't. So I went step by step, saving a change every time and waiting for the next reboot, and finally I was able to make it work.

The settings changed to make it work are:

* Swap file: enabled.
* Snapshot for recorded video: disabled.
* FTP: disabled.
* Telnet: disabled.

With these settings everything works OK, so I think this issue could be closed.

Thanks.

**Comment by yivo** [comment]
> Please, try again with this file. [lower_half_init.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10177272/lower_half_init.zip)

This also helped me. Thank you.

Here are the details about my camera.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/7421323/207721910-85eac01d-5eb3-42b8-8d64-15cd9ceca530.png">

**Comment by Blayven** [comment]
+1
Yi Home 1080p RFUS 12.0.35 - working! Thanks.

**Comment by roleoroleo** [comment]
Please, wait the next release for a full support.

**Comment by babsz02** [comment]
J'ai modifié le nouveau fichier et ça fonctionne merci !

> lower_half_init.zip
