### ISSUE TITLE
Bricked(?) Yi 1080p Home IFUS

### ISSUE THREAD

**Issue by lazarevski** [roleoroleo/yi-hack-Allwinner-v2#542]
So I've had this camera for a year or so, and when I got it, I successfully hacked it. And the cam worked great up until few months ago when the cam just stopped working - constant yellow light, no audio prompts. I don't have a backup and I don't remember what I flashed it with originally, so I don't know where to start. Can someone help me try to revive it?

![photo_2022-12-10_00-55-02 (2)](https://user-images.githubusercontent.com/6970172/206814774-70e9eaef-5e7c-44d5-8e75-89bea6951521.jpg)
![photo_2022-12-10_00-55-02](https://user-images.githubusercontent.com/6970172/206814775-933f9e3c-39d1-47cc-b043-28991ac8bab8.jpg)
![photo_2022-12-10_01-10-28](https://user-images.githubusercontent.com/6970172/206814776-a56a4a95-3f2a-4184-9832-9c25bd9e96de.jpg)

**Comment by roleoroleo** [comment]
It could be a y291ga or a y211ga.
Does it work if you switch on without the sd card?

**Comment by lazarevski** [comment]
Same behavior with or without SD card. Was support for y291ga added just recently? I ordered this cam back in April '21 from ali, so it was probably flashed May/June 2021.

**Comment by roleoroleo** [comment]
Do you have a backup inside your sd card?

**Comment by lazarevski** [comment]
> Do you have a backup inside your sd card?

That's the thing, I've misplaced or have overwritten the card.

> Support for y291ga is from august.
> 
> If it's not a hardware failure, you could try to restore backup partition. If the file is not related to your model, it will not loaded. [y291ga.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10200658/y291ga.zip) [y29ga.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10200659/y29ga.zip) [y211ga.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10200660/y211ga.zip)
> 
> Read the wiki,

Thanks for the prompt replies, ill give it a try and report back.

**Comment by wolverine-0** [comment]
@lazarevski did you have any luck?  I have the same model and I am in exactly the same boat as you.  I have tried the backup files linked above (thanks @roleoroleo) but haven't had any joy.  Still just a static orange light on boot.  I'm half tempted to think that the hardware has failed but I am willing to try anything else that can be suggested.

**Comment by babsz02** [comment]
> @lazarevskiavez-vous eu de la chance? J'ai le même modèle et je suis exactement dans le même bateau que toi. J'ai essayé les fichiers de sauvegarde liés ci-dessus (merci@roleoroleo) mais je n'ai eu aucune joie. Toujours juste une lumière orange statique au démarrage. Je suis à moitié tenté de penser que le matériel a échoué, mais je suis prêt à essayer tout ce qui peut être suggéré.

Have you heard from your camera?
Because I have the same problem, fixed orange light

**Comment by roleoroleo** [comment]
The only method to fix the orange led is restoring the original partition using a backup (if it's not a hardware failure).
If you have it, please follow the unbrick procedure.

**Comment by lazarevski** [comment]
No luck on my end, probably a bricked device.

**Comment by roleoroleo** [comment]
Are you sure about the model suffix?

**Comment by twillist** [comment]
I had a similar problem and I had to solder wires on the uart pads and hook it to a serial port on a computer and the it would flash the recovery images from an sd card.
