### ISSUE TITLE
Yi Home 1080p RFUS 12.0.35 reboots over and over

### ISSUE THREAD

**Issue by pryordr** [roleoroleo/yi-hack-Allwinner-v2#546]
The camera model and firmware line up for the y291ga file. Add the camera in the Yi app, and it works fine. Put the hack on a 16G SD card, the folder changes to Factory.done so it looks like the hack took. But it just boots over and over again with the SD card left in, and you can't see the IP address of the camera on the network or see the camera in the Yi app. If you take the SD card out, the camera goes back to working the same as if the hack was never applied, that is I can see the camera in the Yi app, you can ping the IP address. I followed the wiki to add the sdwifi.tar.gz files in case it was just not getting back on the network, but again, it just reboots over and over as long as the SD card is in. I have tried one other brand of SD card, exactly the same things happens. Any ideas? Thx

**Comment by pryordr** [comment]
More-with the SD card left in, can't ping the IP address of the camera, does not show up when I try to add it in Agent UI for example, with the card left in the camera reboots over and over and does not work in the Yi app and can't be seen on network. Pulling card out lets it be seen again in the Yi app, but you can't ping the IP address or add it in Agent UI, appears like hack never applied. I have tried formatting the SD card using the camera app.

**Comment by roleoroleo** [comment]
Please, check this issue:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/540#issuecomment-1341109470

**Comment by pryordr** [comment]
Thanks, that did seem to fix it, although I didn't think so at first as it rebooted several times for a few minutes. It would ping, then not ping, then finally settled out working ok. 
![image](https://user-images.githubusercontent.com/120391997/207371272-f343d4aa-62f5-40c4-ab2f-8afb9d6a599b.png)

**Comment by roleoroleo** [comment]
If the cam continues to reboot, check the faq page in the wiki: snapshots, swap, etc...
