### ISSUE TITLE
Determine which Yi 1080 Home Camera From DID

### ISSUE THREAD

**Issue by burchis** [roleoroleo/yi-hack-Allwinner-v2#549]
I have RFUSY6259TBVC... with FW 12.0.35.8* .  Like others I have lost motion record to SD-card and wishing to downgrade firmware.  Here is a screen shot from Kami firmware download page. The third option (XFXXX65XXX..) has a y211ga file but my camera is XFXXX62. Can you confirm which option I need?  I believe I use to have 9.0.35 which uses y291ga and that is not listed on Kami.    I have flashed two other cameras (9FUS) with y20ga and all went well so I understand the process.

![Kami FW Page](https://user-images.githubusercontent.com/121259121/209214163-0deeb734-4a72-4472-9c3b-b550321a9f4f.jpg)

**Comment by roleoroleo** [comment]
Your cam is a y291ga and the firmware is not available in the Kami web site (AFAIK).
In any case, a downgrade is not a good idea if you don't have a complete fw.
Normally, the fw available as a download file is only a partial update.

You can restore fw 9.x if you have a backup of the old fw or if another user share its own backup.
Or you can wait the next update of the hack which will probably support fw 12.

**Comment by burchis** [comment]
Thanks for your reply. I found and downloaded a backup file named 'backup_rfus_9_0_35'.  I am assuming it is valid.  After extracting the zip file a folder titled 'backup' existed with these files: 

![Backup Bin Files](https://user-images.githubusercontent.com/121259121/209227247-cf6ecfa0-ba55-4c92-b68b-55ea9cce62fe.jpg)

![Bin File Index](https://user-images.githubusercontent.com/121259121/209227269-514ca775-1d22-4a37-a4d5-1665198ddb0e.jpg)

Do I place the backup folder in the SD-card root directory or copy all the individual bin files or just certain bin files. 

Any tips much appreciated, thanks in advance.

**Comment by roleoroleo** [comment]
Read the wiki about unbrick procedure.
It's the same.
Try to overwrite mtdblock3 and mtdblock4.
It should be enough.
