### ISSUE TITLE
Update to fw 12.x vs AI detections

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-Allwinner-v2#550]
Many models have received the update to version 12 in recent weeks.
This new fw version contains a big update about AI functions (thanks to a new Pilot AI library).
Some features disapperead from the menu and other appeared.
For example animal detection and vehicle detection are now supported (if you buy a cloud plan).
I opened this issue to collect feature removed and added for all models.
What happens to your model about:
- sound detection
- baby cry detection
- generic motion detection
- human detection
- face detection
- animal detection
- vehicle detection
- motion tracking
- ...

**Comment by evider2002** [comment]
y291ga 
Version 12: 
Person, vehicle, animal & sound. 
Version 9: 
Person & sound 

First 2 screenshots - Version 12
last screenshot - Version 9

![fw 12 a cropped](https://user-images.githubusercontent.com/118506981/210323331-e131e75a-73fe-422f-a084-35b439e7b446.png)


![fw 12 b cropped](https://user-images.githubusercontent.com/118506981/210323344-0b07fa05-dcde-4a3e-8cb6-b6b0c4b84fce.png)


![fw 9 cropped](https://user-images.githubusercontent.com/118506981/210323354-30e3561a-8e9e-4e46-a390-fefd5352281d.png)
