### ISSUE TITLE
YI Dome Guard IFUS - camera is restarting when connected to RTSP stream

### ISSUE THREAD

**Issue by SirAd** [roleoroleo/yi-hack-Allwinner-v2#552]
Hi, 
I have installed r30gb 0.2.5 hack on yi dome guard camera with firmware starting from IFUS. Camera is restarting when I'm trying to connect to RTSP. I've captured debug from rRTSPServer.

**Comment by SirAd** [comment]
see  rRTSPServer output with debug
[rRTSPServer.err.txt](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10307040/rRTSPServer.err.txt)

**Comment by Giuserver** [comment]
Hello. Try to enable Swap space! After that, use tcp transport.
If you use ffplay it's like:
ffplay -rtsp_transport tcp -i "rtsp://IP-CAM/ch0_0.h264"

**Comment by SirAd** [comment]
I'm closing this ticked. I applied change described in #484 - swith to h264 and now camera is stable.
Thanks for assistance.
