### ISSUE TITLE
FTP upload keeps uploading lots of files

### ISSUE THREAD

**Issue by mopicus** [roleoroleo/yi-hack-Allwinner-v2#553]
Hello, I have setup the yiihack options to upload files to FTP
In camera settings I have set Low detection sensitivity and AI Human detection on, but the camera uploads a new file every 30 seconds, the minimum movement triggers it, without any human motion.
I have tried different settings but the result is always the same.

Model is a MIBAO G1 1296p dome with 0.2.5 fw

Thanks!

**Comment by roleoroleo** [comment]
Check if this option is true:
![immagine](https://user-images.githubusercontent.com/39277388/210447176-07db3064-70dc-41bb-b85d-d470bd93d7fd.png)

**Comment by mopicus** [comment]
Yes I have tried both options, checked and unchecked. In both cases, as soon as I enable the FTP upload, the camera starts uploading lots of files

**Comment by roleoroleo** [comment]
FTP upload is not related to the quantity of video files.
The problem is: why your cam saves lots of files.

**Comment by mopicus** [comment]
These days is working ok, but there is no wind at all, I will keep an eye on it
Thanks!
