### ISSUE TITLE
FTP directory name not matching timestamp

### ISSUE THREAD

**Issue by Plop** [roleoroleo/yi-hack-Allwinner-v2#562]
Hi,

I've got an issue with the directories names on the FTP : it always set the time one hour behind the real (and displayed on the cam overlay) time : ![image](https://user-images.githubusercontent.com/876470/211405299-fcea742f-fab9-4e51-9466-6833c6f8c9c8.png)

Also, is it possible to rename the pattern of the folders and files ?

Also, I don't understand why some files starts with "E0" and others with "E1" ?

![image](https://user-images.githubusercontent.com/876470/211405600-a81ac26d-2f57-45a2-aa5b-2bd4d420a9be.png)

![image](https://user-images.githubusercontent.com/876470/211405659-5b469570-7882-4ec6-baf2-fe2cba181f45.png)

Thanks for your help !

**Comment by roleoroleo** [comment]
> I've got an issue with the directories names on the FTP : it always set the time one hour behind the real

What's the correct time?
"Date & time" column or "Directory name" column?

> Also, is it possible to rename the pattern of the folders and files ?

No, it's defined by Yi software.

> Also, I don't understand why some files starts with "E0" and others with "E1" ?

I don't know, probably it's the type of alarm.

**Comment by Plop** [comment]
> > I've got an issue with the directories names on the FTP : it always set the time one hour behind the real
> 
> What's the correct time? "Date & time" column or "Directory name" column?

The "Date & time" column

Thanks for your answers !
