### ISSUE TITLE
So many Yis supported, but none work on my 4 different models?

### ISSUE THREAD

**Issue by starman2k01** [roleoroleo/yi-hack-Allwinner-v2#564]
I have:
YYS2016 9FUS "Yi 1080P home camera"
YYS2518 9FUS "Yi home camera 3"
YHS3017 9CUS "Yi outdoor camera 1080p"
YHS2016 BFUS "Yi dome camera 1080p"

And none of these work on any of them?? The "9" series is pretty common but I don't see any of those versions. But the BFUS is YiDome Camera 1080P-- isn't that the"Yi 1080p Dome *FUS" that's listed here?

**Comment by Giuserver** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner

**Comment by roleoroleo** [comment]
Please check the fw version with the app.

**Comment by starman2k01** [comment]
That worked! Thank you. Sooo many versions of hardware...
