### ISSUE TITLE
Use H.264 instead of H.265 in high quality stream of the r30gb

### ISSUE THREAD

**Issue by 0xgrm** [roleoroleo/yi-hack-Allwinner-v2#567]
Hello,

I am using the Yi Dome r30gb with Scrypted and HomeKit Secure Video. At the moment I must use the low quality stream as HKSV doesn't support x265.

Would it be possible to change the compression algorithm of the high quality stream to H.264?

**Comment by roleoroleo** [comment]
Check this issue:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/484

**Comment by 0xgrm** [comment]
Sorry, I searched before opening the issue but didn't found this post.

It's working perfectly, thank you very much!
