### ISSUE TITLE
3 days after update camera down

### ISSUE THREAD

**Issue by tarbax** [roleoroleo/yi-hack-Allwinner-v2#568]
have 3 cameras updated them all and 1 out of 3 went down after couple of days.
i rebooted them multiple times but nothing pops up anymore.
got a blue status light and no camera feed, web interface or ssh but still has connection to the wifi.

**Comment by roleoroleo** [comment]
Strange.
When the led is blue, normally the cam is working properly.
Maybe the sd card is corrupted and the hack doesn't start.

**Comment by tarbax** [comment]
> Strange. When the led is blue, normally the cam is working properly. Maybe the sd card is corrupted and the hack doesn't start.

so i got a new sd took all the files onto it and wont boot only got a solid yellow light.
reset button dousnt work what should i do now ?

**Comment by roleoroleo** [comment]
Are you using the original cable and power adapter?

**Comment by tarbax** [comment]
> Are you using the original cable and power adapter?

was a wifi issue. now i got a blue solid light and connects to network but no webpage shows up.
do i have to reset the camera after a new sd install (clean install from download) ?

**Comment by roleoroleo** [comment]
No, reset is not necessary.
Are you using port 8080?

**Comment by tarbax** [comment]
> No, reset is not necessary.
> Are you using port 8080?

Yes

**Comment by roleoroleo** [comment]
Try to login with telnet.
If the cam is hacked you will enter.
If not, the hack didn't work.

**Comment by tarbax** [comment]
> Try to login with telnet. If the cam is hacked you will enter. If not, the hack didn't work.

i reformatted on a windows instead of mac and now it works. thanks!
