### ISSUE TITLE
Yi Camera BFUS Firmware version 9.0.19.02_202007141512

### ISSUE THREAD

**Issue by r4zi3lrrr** [roleoroleo/yi-hack-Allwinner-v2#57]
Hi Guys,

Extracted to SD as per below screenshot, put the SD card into the Yi camera - left it for several minutes but not getting anything else, just a amber light.

Using yi-hack-Allwinner-v2 FYI

Any ideas, please?

![image](https://user-images.githubusercontent.com/38400294/102690588-5ba57200-41fe-11eb-92d3-90bc2f17622f.png)

**Comment by r4zi3lrrr** [comment]
Just to add if I remove the SD card the camera boots up normally.

**Comment by roleoroleo** [comment]
The content of the sd card you posted is before or after to try the hack?

**Comment by r4zi3lrrr** [comment]
After the hack

**Comment by roleoroleo** [comment]
If Factory is not renamed Factory.done the hack didn't start.
Try to use a different sd card or try to reformat the card with another software (eg. Rufus).

**Comment by r4zi3lrrr** [comment]
Tried another SD card and formatted it using MiniTool Partition Wizard 11

Unfortunately still not working just stuck on static amber light - waited for 5 mins.

If the hack works should the color of the LED change?

Should the folder rename to factory.done or a file?

![image](https://user-images.githubusercontent.com/38400294/102695623-7983ce80-4220-11eb-949d-0236839b910b.png)


This is what I have in the factory folder:

![image](https://user-images.githubusercontent.com/38400294/102695672-b3ed6b80-4220-11eb-8ce6-8e3dbe1b13ea.png)

**Comment by r4zi3lrrr** [comment]
Tried another SD card (formatted to FAT 32) and plugged in directly into the mains still stuck on amber light and won't go any further.

**Comment by r4zi3lrrr** [comment]
It does say AI+ on the back of the camera - could this be model of camera be too new perhaps?  Maybe why this firmware doesn't work?

**Comment by r4zi3lrrr** [comment]
Issue finally resolved due to a good guy from Hotukdeals:- jezcooke

The problem was due to the way Winzip was extracting the TAR file.

Link to the fix that helped me: https://support.esri.com/en/technical-article/000002710
