### ISSUE TITLE
New beta release for fw 12

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-Allwinner-v2#571]
If your cam is updated with fw 12 and you want to try a new beta, please try these files:
[r35gb_x.x.x.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10567167/r35gb_x.x.x.zip)
[y21ga_x.x.x.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10567172/y21ga_x.x.x.zip)
[y211ga_x.x.x.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10567169/y211ga_x.x.x.zip)
[y291ga_x.x.x.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10567173/y291ga_x.x.x.zip)

Unzip the file inside the sd card (/tmp/sd folder of the cam).
You should have the file with the .tgz extension.
Go to "Maintenance" webpage and click "UPGRADE FIRMWARE" button.

**Comment by NikNikolay7** [comment]
hello, many people who updated their YI cameras regret that they updated the cameras to version 12 because they got problems with human detection, and they don’t know they can’t return the previous firmware version

**Comment by NikNikolay7** [comment]
Существует ли такой же лёгкий способ, где нужно просто на отформатированную карту памяти распаковать прошивку для того чтобы вернуть предыдущую заводскуюпрошивку камеры  yi dome guard YRS3521
Я смотрел вашу статью с рекомендациями по восстановлению заводского бэкапа но Насколько я понял там применяется виртуальная машина Linux К сожалению для меня это пока очень сложно

**Comment by NikNikolay7** [comment]
Is there an easy way where you just need to unpack the firmware on a formatted memory card in order to restore the previous factory firmware of the camera yi dome guard YRS3521
 I looked at your article with recommendations for restoring a factory backup, but as far as I understand, a Linux virtual machine is used there. Unfortunately, this is still very difficult for me.

**Comment by roleoroleo** [comment]
If you want to create the image from windows, you can user mkimage from here:
https://www.mediawiki.compulab.com/w/index.php?title=U-Boot:_Images
but it works only for "factory" image.

**Comment by morenod** [comment]
Can you compile it for h30?

**Comment by NikNikolay7** [comment]
Большое спасибо ,попробую сделать так

**Comment by roleoroleo** [comment]
I added the tools for windows.
Please try to use build.bat

**Comment by NikNikolay7** [comment]
Thank you very much, I’m sure that someone who is more advanced than me
will help, I still can’t figure it out, I’ll hope that yi will fix it in
the next firmware, on many resources and on the application page in the
play store, many users complain about the updated version 12  yi camera
software

 Thank you for your help

вс, 5 февр. 2023 г., 16:40 roleo ***@***.***>:

**Comment by pafade89** [comment]
Hi @roleoroleo,

I am checking your new beta with my Yi Home IFUS (y211ga) and it works fine.

I also have a Yi Outdoor 1080p IFUS Cam (h30ga). Is it possible to get a beta for these model from you as well for testing? The new firmware is called 11.1.26.

Cheers

**Comment by roleoroleo** [comment]
@pafade89 
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/576#issuecomment-1432859992

**Comment by pafade89** [comment]
Thank you very much. Installation worked and is currently running without problems.

**Comment by maRoff** [comment]
Do you plan to support YI Dome Guard YRS.3019 (r30gb) at new firmware version 12.1.05?

**Comment by roleoroleo** [comment]
This version is new for me.
Please, send me a backup copy.

**Comment by maRoff** [comment]
Copy from: YI Dome Guard YRS.3019 (r30gb), firmware version 12.1.05
[backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/11274929/backup.zip)

**Comment by roleoroleo** [comment]
Please, overwrite this file in your sd card:
[lower_half_init.sh.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/11283839/lower_half_init.sh.gz)
and check if the cam works.

**Comment by maRoff** [comment]
Web panel is working, but rtsp stream is not.
![image](https://user-images.githubusercontent.com/9580217/233384255-e6ab5363-6f1a-4aa2-a154-ce5a87214cfd.png)

**Comment by roleoroleo** [comment]
Maybe Yi changed the frames.
Please, send me a copy of /dev/shm/fshare_frame_buf

**Comment by maRoff** [comment]
[fshare_frame_buf.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/11314559/fshare_frame_buf.zip)

**Comment by roleoroleo** [comment]
The frame buffer is not changed, it should work.
Please try to run the server manually.
```
# kill wd_rtsp.sh
# kill rRTSPServer
# rRTSPServer -m r30gb -r both -a alaw -p 554
```
and check the output.

**Comment by JohnHolg** [comment]
I have the same problem

**Comment by roleoroleo** [comment]
Enable debug log with "-d" please.
Is rmm running?

**Comment by maRoff** [comment]
What is rmm?

**Comment by roleoroleo** [comment]
Sorry...
rmm is the main process that manages the cam (a Yi process).
You can check if it's running with a `ps` command executed in the shell.

**Comment by maRoff** [comment]
Yes, rmm is running:
![image](https://user-images.githubusercontent.com/9580217/236196279-0f59b694-e26b-4694-a770-55597f31ed99.png)

**Comment by roleoroleo** [comment]
Maybe the frame buffer is locked and rRTSPServer is in loop.
Run this command twice:
`hexdump -C -n 16 /dev/shm/fshare_frame_buf`
You should see different outputs.

**Comment by maRoff** [comment]
YI APP is working without any problem.

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/9580217/d757098b-880d-4976-a777-02c3e42f915a)

**Comment by roleoroleo** [comment]
I don't understand...
Please try to run the process without audio and with log:
```
# killall wd_rtsp.sh
# killall rRTSPServer
# rRTSPServer -m r30gb -r both -a no -p 554 -d 7
```

**Comment by maRoff** [comment]
It's not helped:
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/9580217/16ad6f60-8b2b-49fd-bffa-45dbdd71f764)
If is an option I will try to downgrade camera firmware.

**Comment by maRoff** [comment]
I downgraded this camera firmware, but if you have other idea I can test it again. Thank you.

**Comment by roleoroleo** [comment]
After downgrade is it working properly?

**Comment by maRoff** [comment]
Yes, without any problem with your official version. I didn't test modified files from this thread.

**Comment by Rohja** [comment]
Hi !

Seems like I'm encountering the same issue as @maRoff with my `Yi Dome Camera YRS.3019`.

I didn't use it for a long time and it was using an outdated firmware. After a backup (of version 9.x), I upgraded the firmware to `12.1.05_xx` using the Yi Home application on Android.

The app doesn't offer any other upgrade after that.

Following the setup instructions I get a working web panel but the RTSP server isn't responding (port seems closed) and any configuration change followed by a reboot result in (at least) the telnet and web servers being unavailable.

I checked that the `rmm` process is running and it is:

```
root@(none):~# ps | grep rmm
 1215 root     39944 S    ./rmm
 5533 root       980 S    grep rmm
```

Running `hexdump -C -n 16 /dev/shm/fshare_frame_buf` twice always output the same data:

 - First time:
```
root@(none):~# hexdump -C -n 16 /dev/shm/fshare_frame_buf
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010
```
 - Second time:
```
root@(none):~# hexdump -C -n 16 /dev/shm/fshare_frame_buf
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000010
```

With the hack on the SD card and the web panel/telnet working, the video stream isn't loading in the Yi Home app: it get stuck loading `25%` until I get a timeout error.

I tried running `rRTSPServer` manually like suggested above:

```
root@(none):~# killall wd_rtsp.sh
root@(none):~# killall rRTSPServer
root@(none):~# rRTSPServer -m r30gb -r both -a no -p 554 -d 7
1695557197390: the size of the buffer is 1786156
1695557197395: mapping file fshare_frame_buf, size 1786156, to b6be7000
1695557197395: closing the file fshare_frame_buf
1695557197395: starting capture main loop
1695557197396: buf_idx_end == buf_idx_end_prev
1695557197406: buf_idx_end == buf_idx_end_prev
1695557197416: buf_idx_end == buf_idx_end_prev
1695557197427: buf_idx_end == buf_idx_end_prev
1695557197441: buf_idx_end == buf_idx_end_prev
1695557197452: buf_idx_end == buf_idx_end_prev
1695557197462: buf_idx_end == buf_idx_end_prev
1695557197472: buf_idx_end == buf_idx_end_prev
1695557197483: buf_idx_end == buf_idx_end_prev
1695557197493: buf_idx_end == buf_idx_end_prev
1695557197503: buf_idx_end == buf_idx_end_prev
1695557197513: buf_idx_end == buf_idx_end_prev
1695557197523: buf_idx_end == buf_idx_end_prev
1695557197534: buf_idx_end == buf_idx_end_prev
1695557197544: buf_idx_end == buf_idx_end_prev
[TRUCATED]
```

Do you want me to try [this version](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/571#issuecomment-1554619154) of `rRTSPServer` or to replace `lower_half_init.sh` by [this one](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/571#issuecomment-1515898469) and post logs ?

Let me know if I can help with any other informations/logs.

I can provide you with a backup of both the old `9.x` firmware as well as the recent `12.1.05_xx` firmware if needed.

If needed, I can get hardware serial access by opening the camera and soldering some wires, I'll just need some documentation for that task. 

Thanks !

**Comment by roleoroleo** [comment]
rmm is running but the stream doesn't start (the buffer is empty).
So RTSP server can't work.

A telnet access is enough to debug the problem.
Did you restart from scratch with the sd card, after upgrade 9-12?
If no, please erase your card and apply the hack again.

Please send me a dump of these commands:
- `cat /backup/init.sh`
- `ps`
- `cat /tmp/sd/yi-hack/etc/system.conf`

Clean personal info from the last command.

**Comment by Rohja** [comment]
First of all, thanks for your answer.

I tried the hack on version 9.x, the rtsp server wasn't working so I upgraded the camera without the sdcard after rebooting.
I then re-installed the hack on the SD card and did the steps of my previous message.

Content of `/backup/init.sh`:

```
#!/bin/sh
echo "--------------------------home app init.sh--------------------------"
SUFFIX=r30gb

PATH="/usr/bin:/usr/sbin:/bin:/sbin:/home/base/tools:/home/app/localbin:/home/base"
LD_LIBRARY_PATH="/lib:/usr/lib:/home/lib:/home/qigan/lib:/home/app/locallib:/tmp/sd:/tmp/sd/gdb"
export PATH
export LD_LIBRARY_PATH

ulimit -c unlimited
ulimit -s 1024
#echo /tmp/sd/core.exe[%e].pid[%p].sig[%s] > /proc/sys/kernel/core_pattern

echo 100 > /proc/sys/vm/dirty_writeback_centisecs
echo 50 > /proc/sys/vm/dirty_expire_centisecs
#echo 2048 > /proc/sys/vm/extra_free_kbytes

echo 400 > /proc/sys/vm/vfs_cache_pressure
echo 0 > /proc/sys/vm/drop_caches
echo 256 > /proc/sys/vm/min_free_kbytes


sysctl -w vm.dirty_background_ratio=2
sysctl -w vm.dirty_expire_centisecs=500
sysctl -w vm.dirty_ratio=2
sysctl -w vm.dirty_writeback_centisecs=100

sysctl -w fs.mqueue.msg_max=256
mkdir /dev/mqueue
mount -t mqueue none /dev/mqueue

mount tmpfs /tmp -t tmpfs -o size=32m
mkdir /tmp/sd
mkdir /dev/shm
mkdir /tmp/var
mkdir /tmp/var/run
mkdir /tmp/run


checkdisk
rm -fr /tmp/sd/FSCK*.REC
umount -l /tmp/sd
mount -t vfat /dev/mmcblk0p1 /tmp/sd

#----insmod hardware cyption------


#extract files
mkdir /tmp/ko/
mkdir /tmp/app/
mkdir /tmp/tools/

if [ -f /home/home_${SUFFIX}m ]; then
    echo "---/home/home_${SUFFIX}m exist, update begin---"
        dd if=/home/home_${SUFFIX}m of=/tmp/newver bs=22 count=1
        newver=$(cat /tmp/newver)
        if [ -f /home/homever ]; then
                curver=$(cat /home/homever)
        else
                curver=0
        fi
        echo check version: newver=$newver, curver=$curver
        if [ $newver != $curver ]; then
                ### cipher ###
                sleep 1
                mkdir /tmp/update
                cp -rf /home/base/tools/extpkg.sh /tmp/update/extpkg.sh
                /tmp/update/extpkg.sh /home/home_v429m
                rm -rf /tmp/update
                rm -rf /home/home_${SUFFIX}m
                #sync
                echo "update finish"
                reboot -f
        fi
        echo "---same version ? update fail---"
        rm -rf mv /home/home_${SUFFIX}m
elif [ -f /tmp/sd/home_${SUFFIX}m ]; then
        echo "---tmp/sd/home_${SUFFIX}m exist, update begin---"
        dd if=/tmp/sd/home_${SUFFIX}m of=/tmp/newver bs=22 count=1
        newver=$(cat /tmp/newver)
        if [ -f /home/homever ]; then
                curver=$(cat /home/homever)
        else
                curver=0
        fi
        echo check version: newver=$newver, curver=$curver
        if [ $newver != $curver ]; then
                ### cipher ###
                sleep 1
                mkdir /tmp/update
        cp -rf /tmp/sd/home_${SUFFIX}m /tmp/update/
                cp -rf /backup/tools/extpkg.sh /tmp/update/extpkg.sh
                /tmp/update/extpkg.sh /tmp/sd/home_${SUFFIX}m
                rm -rf /tmp/update
                mv /tmp/sd/home_${SUFFIX}m      /tmp/sd/home_${SUFFIX}m.done
                sync
                echo "update finish"
                reboot -f
        fi
        echo "---same version ? update fail---"
        mv /tmp/sd/home_${SUFFIX}m      /tmp/sd/home_${SUFFIX}m.done
else
        echo "---update file(home_${SUFFIX}m) Not exist---"
fi

if [ -f /backup/url ];then
    #when ota upgrade failure, will enter this
    echo "--------------------------insmod sensor--------------------------"
    if [ -f /backup/ko/icplus.ko ];then
        insmod /backup/ko/icplus.ko
    fi

    if [ -f /backup/ko/8188fu.ko ];then
        insmod /backup/ko/8188fu.ko
    fi

    if [ -f /backup/ko/8189fs.ko ];then
        insmod /backup/ko/8189fs.ko
    fi
    sleep 1
    ifconfig lo up
    ifconfig wlan0 up
    ethmac=d2:`ifconfig wlan0 |grep HWaddr|cut -d' ' -f10|cut -d: -f2-`
    ifconfig eth0 hw ether $ethmac
    ifconfig eth0 up

    echo "============================================= begin to upgrade...... ========================================="
    /backup/tools/upgrade.sh
    reboot -f
fi

# Running telnetd
/usr/sbin/telnetd &

if [ -f /tmp/sd/lower_half_init.sh ];then
    source /tmp/sd/lower_half_init.sh
elif [ -f /home/app/lower_half_init.sh ];then
    source /home/app/lower_half_init.sh
else
    source /backup/lower_half_init.sh
fi
```

Output of `ps` command:

```
root@(none):~# ps
  PID USER       VSZ STAT COMMAND
    1 root       980 S    /sbin/init
    2 root         0 SW   [kthreadd]
    3 root         0 SW   [ksoftirqd/0]
    4 root         0 SW   [kworker/0:0]
    5 root         0 SW<  [kworker/0:0H]
    6 root         0 SW   [kworker/u2:0]
    7 root         0 SW   [rcu_preempt]
    8 root         0 SW   [rcu_sched]
    9 root         0 SW   [rcu_bh]
   10 root         0 SW<  [lru-add-drain]
   11 root         0 SW   [kdevtmpfs]
   12 root         0 SW   [kworker/u2:1]
  207 root         0 SW   [oom_reaper]
  208 root         0 SW<  [writeback]
  210 root         0 SW   [kcompactd0]
  211 root         0 SW<  [crypto]
  212 root         0 SW<  [bioset]
  214 root         0 SW<  [kblockd]
  255 root         0 SW   [sys_user]
  262 root         0 SW   [kworker/0:1]
  263 root         0 SW<  [cfg80211]
  269 root         0 SW<  [watchdogd]
  284 root         0 SW<  [spi0]
  294 root         0 SW   [kswapd0]
  378 root         0 SW<  [bioset]
  383 root         0 SW<  [bioset]
  388 root         0 SW<  [bioset]
  393 root         0 SW<  [bioset]
  398 root         0 SW<  [bioset]
  403 root         0 SW<  [bioset]
  408 root         0 SW<  [bioset]
  413 root         0 SW<  [bioset]
  418 root         0 SW<  [bioset]
  446 root         0 SW   [irq/302-sunxi-m]
  448 root         0 SW   [irq/166-sdc0 cd]
  512 root         0 SW   [kworker/0:2]
  518 root         0 SW<  [kworker/0:1H]
  519 root         0 SW   [kworker/0:3]
  521 root         0 SW<  [bioset]
  522 root         0 SW   [mmcqd/0]
  524 root         0 SW   [kworker/u2:2]
  539 root         0 SWN  [jffs2_gcd_mtd4]
  545 root       980 S    -/bin/sh
  575 root       988 S    /usr/sbin/telnetd
  604 root      1320 S    ./dispatch
 1212 root     39944 S    ./rmm
 1268 root         0 SW   [RTW_CMD_THREAD]
 1286 root      1468 S    /backup/tools/wpa_supplicant -c/tmp/wpa_supplicant.conf -g/var/run/wpa_supplicant-global -Dnl80211 -iwlan0 -B
 1290 root      2596 S    ./mp4record
 1291 root       960 S    ./cloud
 1292 root      3520 S    ./p2p_tnp
 1293 root      3244 S    ./oss
 1295 root       744 S    ./watch_process
 1309 root       964 S    {httpd} /tmp/sd/yi-hack/bin/busybox /tmp/sd/yi-hack/usr/sbin/httpd -p 80 -h /tmp/sd/yi-hack/www/ -c /tmp/httpd.conf
 1321 root       844 S    pure-ftpd (SERVER)
 1335 root       892 S    /tmp/sd/yi-hack/bin/dropbearmulti /tmp/sd/yi-hack/sbin/dropbear -R -B -p 0.0.0.0:22
 1362 root      1048 S    udhcpc -i wlan0 -b -s /backup/tools/default.script -x hostname:yi-hack
 1380 root       964 S    {ntpd} /tmp/sd/yi-hack/bin/busybox /tmp/sd/yi-hack/usr/sbin/ntpd -p pool.ntp.org
 1407 root       996 S    {wd_rtsp.sh} /bin/sh /tmp/sd/yi-hack/script/wd_rtsp.sh
 1446 root       680 S    wsd_simple_server --pid_file /var/run/wsd_simple_server.pid --if_name wlan0 --xaddr http://%s/onvif/device_service -m yi_hack -n Yi
 1506 root       964 S    {crond} /tmp/sd/yi-hack/bin/busybox /tmp/sd/yi-hack/usr/sbin/crond -c /var/spool/cron/crontabs/
 1980 root       980 S    -ash
 2558 root      4180 S<   rRTSPServer -m r35gb -r high -a yes -p 554
 2564 root       980 S    sleep 10
 2604 root       980 R    ps
```

Content of `/tmp/sd/yi-hack/etc/system.conf`:

```
HTTPD=yes
TELNETD=yes
SSHD=yes
FTPD=yes
BUSYBOX_FTPD=no
DISABLE_CLOUD=no
REC_WITHOUT_CLOUD=no
MQTT=no
RTSP=yes
RTSP_ALT=no
RTSP_STREAM=high
RTSP_AUDIO=yes
SPEAKER_AUDIO=yes
SNAPSHOT=yes
SNAPSHOT_VIDEO=no
SNAPSHOT_LOW=no
TIMELAPSE=no
TIMELAPSE_FTP=no
TIMELAPSE_DT=60
TIMELAPSE_VDT=
ONVIF=yes
ONVIF_WSDD=yes
ONVIF_PROFILE=high
ONVIF_NETIF=wlan0
ONVIF_WM_SNAPSHOT=yes
TIME_OSD=no
NTPD=yes
NTP_SERVER=pool.ntp.org
PROXYCHAINSNG=no
SWAP_FILE=yes
RTSP_PORT=554
HTTPD_PORT=80
USERNAME=
PASSWORD=
TIMEZONE=
FREE_SPACE=0
FTP_UPLOAD=no
FTP_HOST=
FTP_DIR=
FTP_DIR_TREE=no
FTP_USERNAME=
FTP_PASSWORD=
FTP_FILE_DELETE_AFTER_UPLOAD=yes
SSH_PASSWORD=
CRONTAB=
DEBUG_LOG=no
```

Note: I didn't do any kind of configuration in the web panel. 

Let me know if you need anything else.

**Comment by roleoroleo** [comment]
The cam is ok.
The hack is properly installed and all processes are running.
So it's not clear why it's not working.

- Clean the cache of the browser and try to configure the cam.
- Run ipc_cmd -x and check if the buffer is filled.

**Comment by Rohja** [comment]
Running `ipc_cmd -x` does solve the buffer being empty and the rtsp server is now working !
(Btw this arg isn't documented in `ipc_cmd -h`, would you accept a PR for that change ?)

I'll check if this solution survive a reboot and try more in-depth configuration in the web UI later.

**Comment by roleoroleo** [comment]
This parameter is intentionally not documented...
:)
And it won't survive reboot.

But the command is already executed in the system.sh.
You should try to add a sleep after line 27: https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/d69fdfc5072f2153c526db8c49aec11908709a4c/src/static/static/yi-hack/script/system.sh#L28
Maybe 1 second.

**Comment by Rohja** [comment]
Ok, so I think I figured out what's (part of) the issue.

In `/tmp/sd/yi-hack/etc/system.conf` I have `DISABLE_CLOUD=no` by default so [this part of the script run](https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/d69fdfc5072f2153c526db8c49aec11908709a4c/src/static/static/yi-hack/script/system.sh#L175-L201) and [start_buffer](https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/d69fdfc5072f2153c526db8c49aec11908709a4c/src/static/static/yi-hack/script/system.sh#L228) is never executed. 

Setting `DISABLE_CLOUD=yes` did the job. 

Is that a normal behavior ? Shouldn't the buffer be filled no matter is cloud features are enabled or not ?

**Comment by roleoroleo** [comment]
When DISABLE_CLOUD=no, you shouldn't need to start the buffer, it should do it by itself.
It's the standard behavior of the cam.

It's definitely a race condition.

Does the cam access to internet?

**Comment by Rohja** [comment]
Yes the camera has access to the internet.

**Comment by Alexselutin** [comment]
> Я добавил инструменты для Windows. Пожалуйста, попробуйте использовать build.bat

Can you send it to me too please?

**Comment by roleoroleo** [comment]
> Yes the camera has access to the internet.

Try to add a sleep (2 seconds) before line 185:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/abaefd499f1e79e7a3f1ba3075c327b994897652/src/static/static/yi-hack/script/system.sh#L185

> > Я добавил инструменты для Windows. Пожалуйста, попробуйте использовать build.bat
> 
> Can you send it to me too please?

It's released:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/tree/master/unbrick

**Comment by Cofffeek** [comment]
> If your cam is updated with fw 12 and you want to try a new beta, please try these files: [r35gb_x.x.x.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10567167/r35gb_x.x.x.zip) [y21ga_x.x.x.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10567172/y21ga_x.x.x.zip) [y211ga_x.x.x.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10567169/y211ga_x.x.x.zip) [y291ga_x.x.x.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10567173/y291ga_x.x.x.zip)
> 
> Unzip the file inside the sd card (/tmp/sd folder of the cam). You should have the file with the .tgz extension. Go to "Maintenance" webpage and click "UPGRADE FIRMWARE" button.

Good afternoon, I am the owner of two cameras YRS 3521. 
One camera failed during the update, when copying a jump from a working camera using ch341a, I accidentally deleted the camera in the application. After that, I can't connect in the application to add not the first not the second camera.  Says the Wifi connection, then after 1-2 minutes passes and says: - Bearing has timed out, please reset the camera. Overloaded that one that the second camera nothing happens please help!

**Comment by roleoroleo** [comment]
If the hack is installed, you should use the unbrick procedure to restore the factory fw.
Than, reset the cam with the button and try again.
If it doesn't connect to the wifi, try another access point.
And disable 5 GHz network if you have it.
