### ISSUE TITLE
YI OUTDOOR  1080 reboot loop after firmware updated to 11.1.26.1

### ISSUE THREAD

**Issue by morenod** [roleoroleo/yi-hack-Allwinner-v2#576]
Hack was working fine with 0.2.5 but yesterday I updated the stock firmare to 11.1.26.1 and now camera is on a reboot loop.

I have flashed card again with 0.2.5 yi-hack but when using it, camera reboots (without SD card, it works fine)

```
$ ls -1
backup
Factory.done
log
lower_half_init.sh
record
yi-hack
```

**Comment by morenod** [comment]
I have already enabled swap and disabled snapshots but it keeps rebooting

**Comment by roleoroleo** [comment]
What's your model suffix?
At the moment fw 11 is not supported.
Please, make a backup copy of the flash and share it with me.

**Comment by morenod** [comment]
[backup.tar.gz](https://github.com/morenod/yi-hack-Allwinner-v2/raw/yi_outdoor_fw_11/backup/backup.tar.gz)

Model: Yi Outdoor Camera 1080p (YHS_3020)

Base Version: 11.1.26.1_202301191526
Suffix: IFUSY593GX


Thanks!

**Comment by micruz76** [comment]
Same here.

YI Outdoor Camera 1080p YHS_3020

Firmware after update: 11.1.26.1_202301191526

**Comment by kubikub** [comment]
Hello, 
I did the upgrade to 11.1.26.1_202301191526 and now the hack do not work. 
I there a way to downgrade the 9.26 firmware ?
I have the yi Outdoor YHS-3017 with RFUS Y59IR

**Comment by roleoroleo** [comment]
Beta release for fw 11:
[h30ga_0.2.5.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10754875/h30ga_0.2.5.tar.gz)

**Comment by morenod** [comment]
Confirmed it is working fine

![image](https://user-images.githubusercontent.com/25103450/219342937-c363907c-c430-43fa-8bfe-61d70b2a7077.png)


Thanks!!

**Comment by micruz76** [comment]
Works fine. Thanks alot

**Comment by roleoroleo** [comment]
Did you install the released version?

**Comment by pafade89** [comment]
> Beta release for fw 11:
> [h30ga_0.2.5.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10754875/h30ga_0.2.5.tar.gz)
> 

Hi @roleoroleo your beta version worked great for me.  Now I have installed the new official release 0.2.6 which contains all features and now the person detection no longer works with hg30. What can be the reason?

Thx in advanced P

**Comment by fred-c1** [comment]
Just FYI:
Yi Outdoor Camera 1080p IFUS with F/W   11.1.26.6_202411091539
The hack 0.3.4 works about 10-20 seconds before the camera reboots.
After downgrading to 11.1.26.1_202301191526 the hack sems to works OK

**Comment by luis-fuentes** [comment]
Hi @roleoroleo, jumping in on this thread. I have the exact same situation as @fred-c1's recent comment.

**Setup:**
- Model: Yi Outdoor Camera 1080p (YHS.3020, H30GA V1.2)
- DID prefix: IFUSY591 (EU version, FCC ID 2AFIB-YHS3020)
- Stock firmware: **11.1.26.6_2024** (currently unhacked)

Before I attempt the flash, two questions:

1. Does the latest release **0.3.6** (May 2026) resolve the reboot-loop issue that @fred-c1 reported with 0.3.4 on firmware 11.1.26.6? I didn't see it mentioned explicitly in the release notes.

2. If 0.3.6 still has the issue, would you be able to share the `mtdblockX.bin.gz` files for **h30ga firmware 11.1.26.1_202301191526** so I can downgrade first, similar to what you did for `n4rrOx` in #921?

Happy to provide a full backup of my current 11.1.26.6 if useful for the project. Thanks for keeping this alive.

**Comment by roleoroleo** [comment]
>     1. Does the latest release **0.3.6** (May 2026) resolve the reboot-loop issue that [@fred-c1](https://github.com/fred-c1) reported with 0.3.4 on firmware 11.1.26.6? I didn't see it mentioned explicitly in the release notes.

No, the issue is not fixed.

>     2. If 0.3.6 still has the issue, would you be able to share the `mtdblockX.bin.gz` files for **h30ga firmware 11.1.26.1_202301191526** so I can downgrade first, similar to what you did for `n4rrOx` in [LFUS Downgrade Firmware #921](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/921)?

[11.1.26.1_202301191526.tar.gz](https://github.com/user-attachments/files/29284670/11.1.26.1_202301191526.tar.gz)

> Happy to provide a full backup of my current 11.1.26.6 if useful for the project. Thanks for keeping this alive.

Yes, please.
