### ISSUE TITLE
Multimedia on Home Assistant Error

### ISSUE THREAD

**Issue by hiagocosta** [roleoroleo/yi-hack-Allwinner-v2#581]
Hi, when I try to navigate into the recorded videos inside the camera with multimedia menu in home assistant, it gives me this error 

![image](https://user-images.githubusercontent.com/22087481/219233259-73597746-785e-49e6-b628-92e20d78a8f5.png)

<html>
<body>

Firmware Version | 0.2.5
-- | --
Base Version | 9.0.35.00_202111291330
Model Suffix | y291ga

</body>
</html>

**Comment by roleoroleo** [comment]
HA version?
Integration version?

**Comment by hiagocosta** [comment]
![image](https://user-images.githubusercontent.com/22087481/219438319-69153b19-74a2-4036-bdaf-ab63f9ef35d2.png)
![image](https://user-images.githubusercontent.com/22087481/219438445-d34f65d8-e12d-4a90-85a0-6c499f443fd8.png)

**Comment by roleoroleo** [comment]
I think the problem is already fixed but not released.

**Comment by hiagocosta** [comment]
After update The CAM still keeps in that situation,

I see The logs and I have this:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/media_source/__init__.py:173
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:27:20 (4 occurrences)
Last logged: 19:29:08


  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 173, in websocket_browse_media
    media.as_dict(),
AttributeError: 'NoneType' object has no attribute 'as_dict'

**Comment by roleoroleo** [comment]
Are there errors related to my integrations?
Are you using a special network configuration?
Reverse proxy, firewalls, etc...?
