### ISSUE TITLE
Add two ways audio with go2rtc

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#583]
WebRTC (now go2rtc) has updated
https://github.com/AlexxIT/go2rtc#two-way-audio
https://github.com/AlexxIT/WebRTC#stream-to-camera
How can I configure it?

**Comment by roleoroleo** [comment]
The configuration of the component is not changed.
You can use the old config.

**Comment by PilaScat** [comment]
ok but how can I set the two way audio?

**Comment by roleoroleo** [comment]
No (two) way.
The cam should support ONVIF Profile T.

**Comment by PilaScat** [comment]
Ok sad, I was just wondering if it could be doneFilippo Scatigna On 18 Feb 2023 18:24, roleo ***@***.***> wrote:
No (two) way.
The cam should support ONVIF Profile T.
