### ISSUE TITLE
[FEATURE REQUEST] FTP deleting older than...

### ISSUE THREAD

**Issue by uzior** [roleoroleo/yi-hack-Allwinner-v2#584]
It will be really nice to have functionality like in the title. To manage the space used on FTP, and chose how old files should be automatically deleted.

**Comment by roleoroleo** [comment]
A similar function is already present.
You can choose the percentage of free space to keep on the sd card.
![immagine](https://user-images.githubusercontent.com/39277388/220042352-05182e35-7323-4cd8-ab4a-b6f4c135e06e.png)

**Comment by alfiriel** [comment]
Would love this too
