### ISSUE TITLE
Issue with Yi Home Y4 1296P Fullhan chip

### ISSUE THREAD

**Issue by redphx** [roleoroleo/yi-hack-Allwinner-v2#585]
I bougth a new Y4 camera from China today, and I think it's a new version of Y4

SN: AKY4CH... (not IFCN)
Model: YYS.2919 (I think it's still the same as other versions)
Chip: FH8632V2
Board name: Y4_8632+SV6256_V2.0 (20221031)
Firmware: 5.1.00.01_202212281036 (latest version)
Manufacture date: 2023.02
Not region locked. Was able to pair it using the Yi Home China app.

I tried to hack it with the y29ga file multiple times but it didn't work. The LED light stucks at dimmer blue light, instead of bright blue.

I got this file when browsing the SD card: [wifi_connected.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10831381/wifi_connected.zip)
  
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/96280/221381986-d7a202b2-ecb9-4806-923f-e7f1936a34ed.png">

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/96280/221362453-a156daac-ea23-47e9-980f-2086717025f5.png">
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/96280/221362463-fab78013-49ae-40a7-a497-4a327d1f05fd.png">

Edit: I also tried to format the SD card using the Yi Home app but the card became unrecognizable by Mac/Windows.

**Comment by redphx** [comment]
Surprisingly I can download firmware files by just opening its FTP server. Do you want these files?

<img width="999" alt="image" src="https://user-images.githubusercontent.com/96280/221365835-76b77b41-72e1-435a-a418-144a7160cadd.png">

**Comment by redphx** [comment]
I was able to dump the `/backup/` folder by running the `debug.sh` file in the SD card.  Not sure why it didn't run `Factory/config.sh`. Maybe it's missing chmod permission?
  
Hope these files are useful:
- [backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10832551/backup.zip)  
- [ftp.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10832550/ftp.zip)

**Comment by roleoroleo** [comment]
At the moment, I can't support it.
I should buy one.

**Comment by redphx** [comment]
comment to prevent closing

**Comment by muava12** [comment]
up

**Comment by roleoroleo** [comment]
Please, send me a link where it's possible to buy it.
