### ISSUE TITLE
The image cannot be displayed because it contains errors.

### ISSUE THREAD

**Issue by pwlgrzs** [roleoroleo/yi-hack-Allwinner-v2#589]
Firmware Version | 0.2.6
Base Version | 9.0.21.08_202007270941
Model Suffix | h51ga

Issue:
Going to any of low/res snapshot links ends with: "The image cannot be displayed because it contains errors."

Camera is functional as I can access ONVIF stream, going to snapshot link do not reset camera, just throws error.

**Comment by cjgarciao** [comment]
I had a similar issue with h30ga after update yi-hack to 0.2.6. I have deleted all events and, I don't know why, but now works better.
Carlos.

**Comment by roleoroleo** [comment]
Normally this happens when another snapshot is currently running.
How many clients do you use?
Web ui? HA?

**Comment by pwlgrzs** [comment]
Only client is Synology on ONVIF stream. Nothing is accessing snapshots.

I have removed all events and rebooted, but this had no effect. Same applies for disabling streaming on Synology side.

**Comment by roleoroleo** [comment]
Try to disable this option:
![immagine](https://user-images.githubusercontent.com/39277388/223048420-0b556f86-3a32-4f19-9356-8c5e0a5df75b.png)
