### ISSUE TITLE
Yoosee camera bricked 

### ISSUE THREAD

**Issue by vla268** [roleoroleo/yi-hack-Allwinner-v2#591]
Hello.
I would like to recover my old camera Yoosee Techage Novatek/Grain Media GM8135S 1080p, 8135s_8M_firmware 21.00.01.05
Resetting doesn't work. Camera starts but can't be flashed with IPCTest tool. Everytime I try, camera flashes and goes offline, no LAN access for about a minute, then comes back online, but it doesn't let you do everything with it.
All started when I flashed a wrong firmware using IPCTool.
I have been reading your method using a file in the sdcard. Could I get a file for my camera? 
I contacted manufacturer and said camera is broken with no solution, but I don't think so.
The problem with the camera can be fixed with your method, I just need the right file.
Thanks for any assistance.
Regards.

**Comment by dreimer1986** [comment]
Quite sure you are wrong here. Grain Media GM8135S is no Allwinner v2 based camera.
