### ISSUE TITLE
y211ga: Installed FW 12 and Hack 0.2.6, motion detection not working

### ISSUE THREAD

**Issue by dreimer1986** [roleoroleo/yi-hack-Allwinner-v2#595]
After FW 12.0.37.0_202211241030 installing by official app and 0.2.6 hack reinstalled the camera does not really allow any motion detection anymore (MQTT in HA). Even more interesting, in camera settings the switch for motion detection always switches back to off after I refresh the page.

![image](https://user-images.githubusercontent.com/29841368/223549180-2bab2184-eaf3-4479-b864-f29984ea04d6.png)

Trying the same over REST link http://x.x.x.x:8080/cgi-bin/camera_settings.sh?motion_detection=yes brings back this:

```
{
"error":"false"
}
```

This happens on two cams, not just one, so I think that a problem on flashing is not our problem here...

**Comment by roleoroleo** [comment]
Check this commit:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/b40b880afa217446582eeaa6664541f661ccb59c

**Comment by dreimer1986** [comment]
Ooops, I thought this one was in 0.2.6 already. OK, then this is fine as it's already fixed upstream.
Regarding the motion detection failing. After I switched on the cam on Addin side and it was active on both sides (cam and ha) it did not work... Now a few hours later it indeed sends images again. I think it takes a while to start working maybe?
Regardless, I think it's working as expected now.
