### ISSUE TITLE
Yi Dome Guard RFUS - Reboots with 0.2.6

### ISSUE THREAD

**Issue by auanasgheps** [roleoroleo/yi-hack-Allwinner-v2#596]
Hi,

Since I updated to 0.2.6 this camera reboots spontaneously every now and then.
Model Suffix is r35gb

here is a series of reboots, reported by the HA integration.
![immagine](https://user-images.githubusercontent.com/20586878/223873684-f3827913-d63d-4cec-87e6-dfb02396b20e.png)

I do not know what logs should I check, please let me know.
Also, when it reboots spontaneously, the camera is pointed to another direction.

**Comment by roleoroleo** [comment]
Please, try to disable these options:
![immagine](https://user-images.githubusercontent.com/39277388/224073608-007aee6a-cba2-45c0-836b-a0a9f45fcead.png)

**Comment by auanasgheps** [comment]
Yup they are already disabled.

![Screenshot_20230309-195434_Brave](https://user-images.githubusercontent.com/20586878/224126537-d2d9a84c-8e13-46b7-ade7-48f54edd5c22.png)

**Comment by auanasgheps** [comment]
Rebooted again :(

**Comment by roleoroleo** [comment]
What's the last running hack?

**Comment by auanasgheps** [comment]
I had not downgraded yet, so I followed your instructions and rebooted the camera.

It may take a couple of days for the crash to occur. When it happens, what files should I grab?

**Comment by auanasgheps** [comment]
After I made the changes, the camera has rebooted 2/4 times before stabilizing.

**Comment by roleoroleo** [comment]
Please, send me the file /tmp/sd/yi-hack/etc/system.conf
and share your system.conf, if you can (remove personal data).

**Comment by auanasgheps** [comment]
```
HTTPD=yes
TELNETD=no
SSHD=yes
FTPD=yes
BUSYBOX_FTPD=no
DISABLE_CLOUD=yes
REC_WITHOUT_CLOUD=yes
MQTT=yes
RTSP=yes
RTSP_ALT=no
RTSP_STREAM=high
RTSP_AUDIO=
SPEAKER_AUDIO=yes
SNAPSHOT=yes
ONVIF=no
ONVIF_WSDD=no
ONVIF_PROFILE=high
ONVIF_NETIF=wlan0
ONVIF_WM_SNAPSHOT=no
NTPD=yes
NTP_SERVER=pool.ntp.org
PROXYCHAINSNG=no
SWAP_FILE=yes
RTSP_PORT=554
ONVIF_PORT=80
HTTPD_PORT=8080
USERNAME=
PASSWORD=
TIMEZONE=CET-1CEST,M3.5.0,M10.5.0/3
FREE_SPACE=30
FTP_UPLOAD=no
FTP_HOST=
FTP_DIR=
FTP_DIR_TREE=no
FTP_USERNAME=
FTP_PASSWORD=
FTP_FILE_DELETE_AFTER_UPLOAD=yes
SSH_PASSWORD=<redacted>
CRONTAB=
SNAPSHOT_VIDEO=no
SNAPSHOT_LOW=no
DEBUG_LOG=yes

```

**Comment by roleoroleo** [comment]
> Please, send me the file /tmp/sd/yi-hack/etc/system.conf

Sorry, my mistake.
Please, send me the file /tmp/sd/hack_debug.log

**Comment by auanasgheps** [comment]
Here it is! [hack_debug.log](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10952392/hack_debug.log)

**Comment by roleoroleo** [comment]
The log is perfect.
Compared to my log you have more free memory than me.
The only difference is that I don't use mqtt_adv.

**Comment by auanasgheps** [comment]
I've checked the camera and it rebooted spontaneously two days ago.

`Uptime | 2d 8h 19m 14s`

It keeps going on forever I believe.

RAM is not an issue: Free/Total Memory | 33244/60676 KB

**Comment by roleoroleo** [comment]
Maybe a power issue?

**Comment by auanasgheps** [comment]
The camera, along with other devices, is connected to a UPS.

It's running stable so far - 4d 18h of uptime, but I haven't touched a single option since I flashed the update, so I cannot explain the instability. I'll keep you posted

**Comment by lolorc** [comment]
same here with r35gb / 0.2.6, I'll check the power, it's happening here every 8-12h.

**Comment by roleoroleo** [comment]
If we exclude power issues and hardware failure, there are 2 reasons why the camera can reboot:
1 - Out of memory: the kernel kills unnecessary process and finally the cam reboots.
Solution: enable swap file.
2 - The process rmm dies and the watchdog restart the cam.
Solution: I don't know...
I could try to log the output of the process and check for errors.

**Comment by roleoroleo** [comment]
Does 0.2.5 work properly?

**Comment by auanasgheps** [comment]
I would like to downgrade to 0.2.5, but I believe the latest HA integration won't work. 
It's a problem because I have a number of automation that rely on this camera's sensors and I spent a lot of time to adapt them to the new integration,

**Comment by lolorc** [comment]
looks like it was a power issue here.
I guess I could disable check_rmm in /tmp/sd/yi-hack/script/wd_rtsp.sh to see if it's a  rmm issue, kill wd_rtsp.sh or make it  log a message before rebooting.
I think I'll kill it because I don't like the while true; loop ;-)

**Comment by roleoroleo** [comment]
Yes, try to kill the watchdog (or disable it from system.sh) and check if the cam remains on.
If yes, ssh should work and you should able to login and run some command.
For example a ps to show the running processes.
And:
```
cd /home/app
./rmm
```
to check what goes wrong in rmm.

**Comment by lolorc** [comment]
hi, just to let you know, it hasn't crashed with a proper power supply:
```
root@yidome:~# awk '{printf "%f\n",$1/86400}' /proc/uptime 
7.804881
```
