### ISSUE TITLE
Support for RFUS y62 fps

### ISSUE THREAD

**Issue by digitarenet** [roleoroleo/yi-hack-Allwinner-v2#597]
I have a new _Yi Home 1080 AI_ with code **RFUSY62FPS**
Seem that is not supported, it is correct?

It's possible that it will be supported in near future?

Thank you
A.

**Comment by digitarenet** [comment]
Can I help to support this implementation in any way?

**Comment by digitarenet** [comment]
Hi have the backup, how can I share it with you?

**Comment by digitarenet** [comment]
This is the backup:

[backupYI.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/11172006/backupYI.zip)

**Comment by roleoroleo** [comment]
y291ga
https://github.com/roleoroleo/yi-hack-Allwinner-v2
