### ISSUE TITLE
Few days after upgrade camera is offline

### ISSUE THREAD

**Issue by rt400** [roleoroleo/yi-hack-Allwinner-v2#598]
I have the issue... no ssh no web no rtsp and onvif
all I have is that telnet is work and login.
The camera is installed in a high ceiling so I have an accessibility problem at the moment and I'm trying to solve it without climbing a ladder.
any idea ?

**Comment by roleoroleo** [comment]
If telnet is the only workng service, probably the sd card is damaged.
You should try to login with telnet and check if the sd is properly mounted.
```
root@yi-hack-allwinner-v2:~# mount | grep /tmp/sd
/dev/mmcblk0p1 on /tmp/sd type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
```
If it's not mounted you could try a fsck to restore it (if it's possible).
If it's mounted, read the content:
`ls -laR /tmp/sd`

**Comment by rt400** [comment]
is this a single command?

**Comment by rt400** [comment]
can you please write me the commands?  cause i am newbie in linux

**Comment by rt400** [comment]
this what i have in sd folder 
<img width="175" alt="image" src="https://user-images.githubusercontent.com/38878996/224568666-af9b946a-2ee6-483f-9cee-f45387d38362.png">
 and dont have mmcblk0p1 only mmcblk0

**Comment by roleoroleo** [comment]
A single command:
`mount | grep /tmp/sd`

If mmcblk0 is absent, probably the sd card is corrupted.

**Comment by rt400** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/38878996/224571300-2b7624dc-a5da-4929-9eeb-bfe78d367b1b.png">
this what i have in /dev folder

**Comment by roleoroleo** [comment]
Try mount command:
`mount | grep /tmp/sd`

**Comment by rt400** [comment]
The sdcard was defected so i put it out and format it and copy the hack
and still no web ssh only telnet
if i run this command that what i get : 
![image](https://user-images.githubusercontent.com/38878996/224674292-0738b602-62cd-46a1-86c4-576204b2bb26.png)

**Comment by rt400** [comment]
Now the telnet connect and after few seconds disconnect.
I try to remove the hack but i can't see the correct zip .
my camera is : Yi Doom Guard QFUS 9v firmware so its : r35gb.
so any idea how to continue from here ?

**Comment by rt400** [comment]
![image](https://user-images.githubusercontent.com/38878996/224685621-e28a8cdf-a6fa-46b8-84a9-15ce97f095b6.png)
i see in folder /tmp/sd/yi-hack a file fw_upgarde_in_progress
that mean that the hack still in progress ?

**Comment by rt400** [comment]
Now if i run the command : `root@(none):/tmp/sd/yi-hack/script# sh system.sh` the camera work.
But if i reboot the camera the issue return...

**Comment by roleoroleo** [comment]
> The sdcard was defected so i put it out and format it and copy the hack and still no web ssh only telnet if i run this command that what i get : ![image](https://user-images.githubusercontent.com/38878996/224674292-0738b602-62cd-46a1-86c4-576204b2bb26.png)

This situation can happen but it's not ok. The sd card is not properly formatted and there are no partitions inside the card.
I don't know if this is the problem but you should reformat the sd card: try with a linux machine following this guide:
https://www.nayab.xyz/linux-tools/partitioning-using-fdisk
Or try with a windows machine.

At the end of the procedure you should have a partition mmcblk0p1 inside the disk mmcblk0 and the mount should refer to mmcblk0p1.

**Comment by roleoroleo** [comment]
Damn...
Are you able to provide me a temporary telnet access to the cam (if you want)?

**Comment by rt400** [comment]
can you send me your email and i send you the link?

**Comment by rt400** [comment]
maybe you have the remove hack for my cam?
i want to try to remove the hack and install it again

**Comment by roleoroleo** [comment]
roleo@iperbole.bologna.it

Before making changes I would like to understand the reason.
If we need to remove the hack I'll tell you.

**Comment by roleoroleo** [comment]
Use this file to unbrick the cam.
Decompress it in the sd card and start the cam.
[backup_r35gb.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/10973527/backup_r35gb.gz)
