### ISSUE TITLE
thumb.sh and cron-timings findings leading to minimp4

### ISSUE THREAD

**Issue by dieideeistgut** [roleoroleo/yi-hack-Allwinner-v2#599]
Heya, this is just a feedback from some findings with the latest versions, ha-integration and the media thumbs. i had been digging around an issue i had (with HA) for a while now and this are my findings:

- the thumbs.sh script runs quite often. on two of my cams (allwinner-v2s) this caused some issues:
- Failed creations sometimes kept a 0-byte JPG file. I worked around this out by modding my thumb.sh to delete the 0-byte JPG  in the current run, forcing a re-creation next time. 
- slowing down the * * * * cron-pattern (disabled it for testing, running the thumbs.sh manually for now) i could reduce my missing thumbs. 

I've tested this with a 4-GB-full SD and a smaller video collection. 

Looking after the reason for the failed creations though, i stumbled upon an issue where minimp4 creates kind of empty (aka frameless) .h26x files. The .JPG creation then finds nothing. This seems to happen only on short records. 

--

For testing i've extended the thumbs.sh script and dropping a static placeholder if/when thumb-creation failed in the past. This way the script  keeps running through a (indeed) very large records folder, creating the thumbs for the video  files it never reached previously

**Comment by roleoroleo** [comment]
Thany you.
Please create a PR, I will integrate your code.

**Comment by dieideeistgut** [comment]
Will do. What's your preferred location for the placeholder image? i have mine currently in /tmp/sd/yi-hack/fallback.jpg

**Comment by roleoroleo** [comment]
/tmp/sd/yi-hack/etc/fallback.jpg
