### ISSUE TITLE
How to activate the speaker?

### ISSUE THREAD

**Issue by occoder** [roleoroleo/yi-hack-Allwinner-v2#60]
My camera features built-in speaker which enables two-way conversation between both ends.
I'd like to know if this hack could activate the speaker? If yes, how to set it up.
Thanks a lot.

P.S. my system info. is
Hardware: YRS.3019
Firmware Version | 0.1.3
Base Version | 9.0.05.33_202009251856
Model Suffix | r30gb

**Comment by roleoroleo** [comment]
No, it' not supported.
