### ISSUE TITLE
Panoramic Webcam

### ISSUE THREAD

**Issue by lanfur** [roleoroleo/yi-hack-Allwinner-v2#601]
Hi everyone,
I really appreciate this hack and I wanted to ask if it was possible to evaluate the possibility of adding an automatic photo capture function every 5/10 minutes, in order to use the YI camera as a panoramic webcam via FTP. Thank you

**Comment by roleoroleo** [comment]
What do you mean?
A snapshot schedule, a panoramic picture using pan or both?

**Comment by lanfur** [comment]
I mean a simple snapshot function, every 5 minutes, which saves the webcam.jpg file to an ftp server
such as the function that reolink IP webcams have

**Comment by roleoroleo** [comment]
I could add this feature but you could already do this today by adding a script.
At the end of the boot procedure, the cam runs a script in the sd card.
You could use this script to make a snapshot and send it to a server.
And schedule it with crond.

**Comment by lanfur** [comment]
thank you for your interest in my proposal
about the script, I'm not able to do it.. I don't have programming skills.. I'm a simple user

**Comment by lanfur** [comment]
thank you sincerely
