### ISSUE TITLE
Yi Home 1080p LOG file?

### ISSUE THREAD

**Issue by KayGundhardt** [roleoroleo/yi-hack-Allwinner-v2#605]
Hi there,

I am using two YiHome 1080p cams actually with y291ga v0.2.6 (9.0.35.00_202111291330). Since ever they both work like a charm, but one of them gets unreachable after several days. It reboots so often until it gets unreachable. Power-On/Off- helps - but only for a few days again.

How can I get a log out of the cam? 
Via SSH I can find 

```
log_first_login.tar.gz     
log_wifi_connected.tar.gz
log_login.tar.gz

```

 in `/tmp/sd/log` but cannot understand what i.ex.

```
  266 root         0 SW   [kworker/0:1]
  267 root         0 SW<  [cfg80211]
  273 root         0 SW<  [watchdogd]
```

means. Are there any other log files?

Any help would be really appreciated!

**Comment by roleoroleo** [comment]
No, at the moment there are no logs.
I'm working on it for the next release.

**Comment by KayGundhardt** [comment]
Great, thank you!

As for now, it seems to be the same issue as described [here](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/603): and the "swap-file-activation-workaround" works (for now ;)
