### ISSUE TITLE
No web interface http://IP-CAM:8080

### ISSUE THREAD

**Issue by MrCykor** [roleoroleo/yi-hack-Allwinner-v2#607]
Hello,

Can u help me, i hacked the camera, i see theese files:
![obraz_2023-03-28_125604190](https://user-images.githubusercontent.com/67111172/228214594-9365c3fa-3c9a-409e-93ad-81eb7ee7605b.png)

i suppose if filename = **Factory.done** then camera is hacked, but i dont see web interface.

Any suggestions?

**Comment by MrCykor** [comment]
@roleoroleo i know IP-CAM, nad skan it with nmap:
Only one port is open
PORT   STATE SERVICE    VERSION
23/tcp open  tcpwrapped

**Comment by roleoroleo** [comment]
Ok, if just telnet is started, the main script is hacked but the script in the sd card is not executed.
Try with another sd.

**Comment by MrCykor** [comment]
I switch card to smaller 4GB, format it using yi apk and still the same.
Capacity of cdcard is matter?

**Comment by feeleep75** [comment]
I have the same problem but I noticed my BFUS camera have newer firmware than recommended: 12.2.0.2 - may this be a problem?

**Comment by roleoroleo** [comment]
Could be.
Please, make a backup copy of the new firmware and share it with me.

**Comment by romainbeaumont** [comment]
Hello,

I've the same issue : just 23/tcp port for telnet is open.. 
I've Dome Guard Camera.

**Comment by feeleep75** [comment]
i just realised that for firmware 12.2.0.2 you should use this repo: https://github.com/roleoroleo/yi-hack-Allwinner - works for me

**Comment by romainbeaumont** [comment]
Can you show me the tree structure of your sd card during the hack? Also, do you know if I can rehack it by simply pressing the reset button? I also noticed one thing: it doesn’t seem to connect properly to the internet when the SD card is inserted.

**Comment by roleoroleo** [comment]
feelep75 is right.

**Comment by MrCykor** [comment]
Hi,
I try with https://github.com/roleoroleo/yi-hack-Allwinner but for me it doesnt change enything :( 
![image](https://user-images.githubusercontent.com/67111172/236196002-d3c138cf-61ee-4dda-8713-3f316620002a.png)
No respond from http://192.168.0.45:8080

**Comment by roleoroleo** [comment]
What the Yi firmware version of the cam?

**Comment by MrCykor** [comment]
Yi firmware version 9.0.19.02

**Comment by roleoroleo** [comment]
Your cam is a y21ga.
Try with the proper hack.

**Comment by roleoroleo** [comment]
Clean the sd card and try again the hack with y21ga.

**Comment by AlexNikMak** [comment]
Hello!

Seemse that I have a similar issue. After successful hacking for some reason, I cannot reach WEB UI on my YI1080p Home http://192.168.1.10:8080.
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/138360871/2d48f3de-b964-448c-b63d-30ef2d10b995)
 According to YI APP my Yi firmware version 12.0.37.0_202211241030 and model IFUSY6557Y. I were installing [y211ga_0.2.7.tgz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/download/0.2.7/y211ga_0.2.7.tgz)
I tried switching sd cards 3 times(different manufacturers and capacities) but it did not help.
Pinging my ip cam is successful. 

I would be grateful to receive some help

**Comment by roleoroleo** [comment]
The default port is changed to 80.
Try it.

**Comment by AlexNikMak** [comment]
I tried it right now but still i am unable to connect to WEB UI
