### ISSUE TITLE
[y29ga] newer versions causing bricking

### ISSUE THREAD

**Issue by NarkyAbyss** [roleoroleo/yi-hack-Allwinner-v2#609]
Base Version	9.0.09.06_202103291039
Model Suffix	y29ga
Serial Number	IFCN

Using 0.2.6 to hack causes corruption of backup partition.
SDcard has Factory.done but camera will not boot anymore.
Requires unbrick with factory backup.

successful hack with y29ga_0.1.9.tar.gz from issue #268 
Same SDcard

**Comment by JMichaelKane** [comment]
0.2.9 is working.

**Comment by roleoroleo** [comment]
> 0.2.9 is working.

Through 0.1.9 or from factory fw?

**Comment by JMichaelKane** [comment]
> > 0.2.9 is working.
> 
> Through 0.1.9 or from factory fw?

Through 0.1.9. Not tested from factory fw.
