### ISSUE TITLE
The streaming frame is frozen after a while

### ISSUE THREAD

**Issue by occoder** [roleoroleo/yi-hack-Allwinner-v2#61]
I don't know why the streaming frame is frozen after a while. 
It may have something to do with motion detection. But even my waving in front of the camera does not get it back automatically.
I have to stop and restart VideoLAN play to get it back.
What setting could be wrong?

**Comment by Afterster** [comment]
May be related to https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/53

I also reverted back RTSP to https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/53#issuecomment-747280805 and it works better on my side. Please give a try.
