### ISSUE TITLE
yi home brick

### ISSUE THREAD

**Issue by wankio** [roleoroleo/yi-hack-Allwinner-v2#610]
So i just flashed wrong firmware for my 12CNX7BQLO, now it stucked at yellow light forever
i'm research and found a way to unbrick it is use UART-USB, but the problem is  i don't know that 3pin jst size : https://youtu.be/fBjKTfWN4TI?t=86

there are so many of them

**Comment by sugar012** [comment]
that seems a 1.25 ST
