### ISSUE TITLE
Cruise mode on Yi Dome Guard failures

### ISSUE THREAD

**Issue by morenod** [roleoroleo/yi-hack-Allwinner-v2#611]
Firmware Version | 0.2.6
-- | --
Base Version | 12.1.47.2_202301121850
Model Suffix | r35gb
Serial Number | RFUSY73xxx (Yi Dome Guard)

When selecting cruise mode 360, camera tries to infinite rotate, but it cant. this camera rotates 360 but with no infinite loop. it should change direction when arriving the limit

**Comment by roleoroleo** [comment]
What's the behavior when you activate cruise mode from the app?

**Comment by morenod** [comment]
you mean the yi app? there is no cruise mode on it.

if enabled on the yi-hack page, camera rotates until the limit, and keeps trying on it each few seconds, so it hangs in a forever loop

**Comment by roleoroleo** [comment]
So you don't have the cruise menu?
![Screenshot_20230405_173606_YI Home](https://user-images.githubusercontent.com/39277388/230296098-447f6150-4f68-47fe-b638-0a3e3cedb3cc.jpg)
![Screenshot_20230405_173617_YI Home](https://user-images.githubusercontent.com/39277388/230296106-0ba42d81-f781-4df3-8ef6-c6b45473b526.jpg)

Probably your cam doesn't support it.

**Comment by morenod** [comment]
I dont see that menu, only a drop down switch to select cruise mode:

![image](https://user-images.githubusercontent.com/25103450/231105246-fe471848-db9c-4135-b0ba-1c96413465b2.png)


If I set to 360, it fails. I can only use presets or off

**Comment by roleoroleo** [comment]
I mean the menu in the app, not in the web interface.

**Comment by morenod** [comment]
> I mean the menu in the app, not in the web interface.

which app?

**Comment by roleoroleo** [comment]
"Yi Home" app for mobile.
Probably you don't use the app but inside it you can see the supported feature of your cam.
