### ISSUE TITLE
[Documentation] Add another model to the support table.

### ISSUE THREAD

**Issue by e3ndr** [roleoroleo/yi-hack-Allwinner-v2#613]
The [Tovendor Mini Smart Home Camera](https://a.co/d/dMEhTUW) appears to be a rebranded Yi model. It runs the `9.0.41*` firmware and is compatible with the `b091qp` firmware. It's serial number/ID starts with `A001E`. Cheers.

**Comment by roleoroleo** [comment]
Thank you. I will add it to the readme.
