### ISSUE TITLE
Camera hangs after one day 

### ISSUE THREAD

**Issue by bocob5** [roleoroleo/yi-hack-Allwinner-v2#614]
System
Hostname	Mansarda
Firmware Version	0.2.6
Base Version	9.0.36.00_202011101611
Model Suffix	y211ga
Serial Number	IFUSY65M633D2O210114
Local Time	Fri Apr 7 17:06:44 CET 2023
Uptime	0h 23m 3s
Load Average	1.03 1.40 1.24
Free/Total Memory	38408/60912 KB
Free SD Space	100%

After the install of the 0.2.6 version Yi Camera hangs after approximately one day. There is no ping or SSH available. Issue looks like some type of kernel crash. I also tried to solder wires on console pins, but somehow I do not get anything on the console. Minicom on linux was used. So, unfortunately I can't provide any diagnostic information that might help with the investigation. 
  
Yi Cam running  Yi firmware base Version 11.1.35.3 and Yi Hack version 0.2.5 does not show this problem. 
My Yi Cams where running OK on version 0.2.5. So it looks this is version 0.2.6 specific problem. 

Let me know if there is any further information I can provide in order to find root cause of this issue. 
For the time being I can live with this problem, since I added ESP32 power switch to the cameras and it is possible to remotely power On/Off the cameras.
 
Thanks

root@Mansarda:~# cat /tmp/sd/yi-hack/etc/system.conf
HTTPD=yes
TELNETD=yes
SSHD=no
FTPD=no
BUSYBOX_FTPD=no
DISABLE_CLOUD=no
REC_WITHOUT_CLOUD=no
MQTT=no
RTSP=yes
RTSP_ALT=no
RTSP_STREAM=high
RTSP_AUDIO=no
SPEAKER_AUDIO=yes
SNAPSHOT=no
SNAPSHOT_VIDEO=no
SNAPSHOT_LOW=no
ONVIF=no
ONVIF_WSDD=no
ONVIF_PROFILE=high
ONVIF_NETIF=wlan0
ONVIF_WM_SNAPSHOT=no
NTPD=yes
NTP_SERVER=ntp1.arnes.si
PROXYCHAINSNG=no
SWAP_FILE=no
RTSP_PORT=554
ONVIF_PORT=80
HTTPD_PORT=8080
USERNAME=
PASSWORD=
TIMEZONE=CET-1
FREE_SPACE=0
FTP_UPLOAD=no
FTP_HOST=
FTP_DIR=
FTP_DIR_TREE=no
FTP_USERNAME=
FTP_PASSWORD=
FTP_FILE_DELETE_AFTER_UPLOAD=yes
SSH_PASSWORD=
CRONTAB=

**Comment by bocob5** [comment]
Thank you for the suggestion. 
I've already enabled swap on one camera, just to be sure I enabled it on another one, but results are the same. Cameras still hangs.

**Comment by roleoroleo** [comment]
Reading your config file, swap seems to be disabled:

> SWAP_FILE=no

**Comment by bocob5** [comment]
I have 4 cameras and swap was enabled on another camera, not the one config
was used in this issue report. But behavior is the same.
If you might find some time to look into this issue, what diagnostic info
could be interesting for you?
And thank you for this great solution you provided to the community in this
project.

**Comment by roleoroleo** [comment]
When the cam reboots the reason could be:
1 - Not original power adapter or cable (it may seem silly but i have seen it happen many times).
2 - Power suppy problem.
3 - Memory problem (a process requires a lot of memory, the kernel starts to kill processes and the watchdog reboots the system).

In the last case you could try to rename the watchdog process wd_rtsp.sh and check what happens.
