### ISSUE TITLE
Can't access HTTP using newly created login/password.

### ISSUE THREAD

**Issue by ikhimichenko** [roleoroleo/yi-hack-Allwinner-v2#620]
Hi guys,
First of all thank you a lot for your efforts on this project!
So I've a flashed BFUS yi 1080p home camera.
1. just added username/password fields here:
![image](https://user-images.githubusercontent.com/14169026/233823040-bf9f202f-0f5c-4cf7-a956-6d5df0dc1171.png)
2. Saved
3. Then rebooted camera.
4. Now I can't access camera by HTTP: it prompts me login/password but they are incorrect.
Only re-flash helps.
Is there a way to set username/password ?
Thank you.

**Comment by ikhimichenko** [comment]
My apologies, I have to use '#' sign.
Sorry and thanks for your efforts.

**Comment by ikhimichenko** [comment]
@roleoroleo last question here:
I set login/password. But how can I reach this camera by ftp? I tried to use mentioned login/password but ftp server says "530 Login authentication failed"

**Comment by roleoroleo** [comment]
ftp login is with root user.
