### ISSUE TITLE
Unable to hack or backup Escam PT202

### ISSUE THREAD

**Issue by Fredrik81** [roleoroleo/yi-hack-Allwinner-v2#625]
After putting the sdcard with hack or backup into the camera and turn it back on, all it does is getting stuck in the boot process with the "floodlight" on. I left it for a few hours and still the same. 
Tries several SD cards. 
Firmware of the camera say: 5.0.00.00

Any idea on what to do?

**Comment by roleoroleo** [comment]
Probably your cam is not compatible:
Read this: https://github.com/roleoroleo/yi-hack-Allwinner-v2/discussions/624#discussioncomment-5816561

**Comment by Fredrik81** [comment]
Thanks for the info.. time to look for new hardware

**Comment by Fredrik81** [comment]
New hardware not supported
