### ISSUE TITLE
Wiki Backup typo fix

### ISSUE THREAD

**Issue by Copro** [roleoroleo/yi-hack-Allwinner-v2#63]
I am not sure how to provide a pull request for the typo on the Wiki page for the backup instructions under:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)

So maybe someone with editor rights can directly and more efficiently change it.

-t in "Decompress the file int the root folder of your SD card."
--> 

1. Decompress the file in the root folder of your SD card.

**Comment by roleoroleo** [comment]
Fixed.
Thanks.
