### ISSUE TITLE
Wi-Fi strength not being passed by MQTT

### ISSUE THREAD

**Issue by fernandolcardoso** [roleoroleo/yi-hack-Allwinner-v2#631]
WIFI strength not being passed by MQTT thread

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/16019127/96bd5347-7ced-4562-9d81-2ca464c26e56)

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/16019127/9efd88ea-92e2-44d6-8fb4-5fe90ea87402)

**Comment by roleoroleo** [comment]
I check the code and tested with my cam.
It seems to be ok.
What is your model_suffix?
Please try both commands:
```
cat /proc/net/wireless | awk 'END { print $3 }' | sed 's/\.$//'
cat /proc/net/wireless | grep wlan0 | awk '{ print $3 }' | sed 's/\.$//'
```

**Comment by fernandolcardoso** [comment]
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/16019127/70ec2354-b848-49ab-bb1a-f66129ed4613)

**Comment by roleoroleo** [comment]
Check this commit:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/46d0ded99e59c89da52997a0595df2b0d5a73c32
