### ISSUE TITLE
Crop RSTP stream possible?

### ISSUE THREAD

**Issue by sibero80** [roleoroleo/yi-hack-Allwinner-v2#632]
I have successfully replaced the camera´s lens for a FishEye. 
I'm sending the stream to Frigate, but effective image size covers a smaller portion of the sensor. 
I was wondering if I could improve quality and performance of both the camera and Frigate by processing a smaller image.
Example image (In yellow the area I'd like to crop):
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/28715756/3e0809df-34b4-45b5-b16e-ef41aa19daf7)

**Comment by roleoroleo** [comment]
Sorry but it's not possible.
I can't change stream processing, it's handled by Yi processes.

**Comment by sibero80** [comment]
Thank you for your reply! closing issue.
