### ISSUE TITLE
Possibility to make Yi-Hack permanent in Camera Firmware

### ISSUE THREAD

**Issue by fernandolcardoso** [roleoroleo/yi-hack-Allwinner-v2#636]
Would it be possible to make Yi-Hack permanent on the system, without the need for an SD Card?

I ask because cameras with Yi-Hack make everything easier and I don't see myself using these cameras without this repository.

I believe there are limitations like little space, or ways to initialize Yi-Hack.

It doesn't hurt to ask and see if there is a light at the end of the tunnel.

**Comment by roleoroleo** [comment]
There are 2 problems:
- root and home partitions are squasfs = read only file system. Only backup partition is r/w. I should completely change the hack process: rewrite whole partition instead of edit some file.
- there is space for a limited set of features.
