### ISSUE TITLE
Yi Dome Guard YRS 3521 firmware

### ISSUE THREAD

**Issue by iamzaychik** [roleoroleo/yi-hack-Allwinner-v2#640]
Hi there!
At first, thank you for your great work on this!

So, I have 2 Guard cams.

First one is:
 - YRS 3019
 - Winbond flash
 - hacked in SD-card way using r35gb
 - works well
 
Second one is:
 - YRS 3521
 - XMC QA64AHIG flash
 - doesn't work (not sure if previously was), just have red led on power connect.

Tried to boot second cam:
 - from SD with usual r35gb firmware
 - with backup made on first cam
 - with your mtd from [this post](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/574#issuecomment-1416802524)

Doesn't boot, no reaction, still red led

I have also friend with CH34A1 programmer, so we tried to backup entire flash from cam1 and restore it to cam2
Everything went fine, excepting the fact it still does't boot 🤷🏻‍♂️ 

Also, we tried to connect with console, but or done something wrong or this USB plug doesn't support chip/etc

So, maybe you have or can do the whole FLASH dump from 3521 or tell me what could be the issue?

Thanks

**Comment by Cofffeek** [comment]
Hello, I am also having the same problem. Did you manage to solve it?

**Comment by Cofffeek** [comment]
Damn in vain put on a firmware update.

**Comment by roleoroleo** [comment]
Do you have a backup copy of the flash (when original)?

**Comment by roleoroleo** [comment]
Yes, I mean a backup of the broken cam.
To be sure it's a r35gb.

**Comment by roleoroleo** [comment]
Here it is:
[mtds_r30gb.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/11793183/mtds_r30gb.tar.gz)

**Comment by Alexselutin** [comment]
> Finally, looks like I found the initial backup of broken cam LINK REMOVED

please send it again, link has been removed
