### ISSUE TITLE
Y29GAM cannot start

### ISSUE THREAD

**Issue by lioulangzhb** [roleoroleo/yi-hack-Allwinner-v2#642]
My camera cannot start and the yellow light is constantly on. Can you give me the original firmware? thanks
9.0.09.06_202103291039home_y29gam
9.0.09.03_202006090939home_y29gam

**Comment by roleoroleo** [comment]
Here it is:
[backup_y29ga.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/11660638/backup_y29ga.gz)
