### ISSUE TITLE
Low resolution Corruption of video stream on tensor g1

### ISSUE THREAD

**Issue by wired-dev** [roleoroleo/yi-hack-Allwinner-v2#643]
![Screenshot_20230606-183656](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/35621115/56905602-afa2-407a-b798-612a67d958cc)

If I turn it to 1080p it works just fine.
It also works when I force the tensor chip to software decode on the low res stream.

**Comment by roleoroleo** [comment]
Sorry but I can't change the stream compression.
It's handled by Yi hw codec.
