### ISSUE TITLE
Change WiFi credentials - fix?

### ISSUE THREAD

**Issue by lenisko** [roleoroleo/yi-hack-Allwinner-v2#65]
Hey!

https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Change-WiFi-credentials

WiFi change script was not working for me on __Yi 1080p Home BFUS / 9.0.19*.__

**To fix it** I've created `/Factory` dir with empty `/Factor/factory_test.sh` file and `/Factor/config.sh` with content:
```
source /tmp/sd/yi-hack/configure_wifi.sh

if [ -e /tmp/sd/Factory ]; then
    mv /tmp/sd/Factory /tmp/sd/Factory.done
fi

reboot
```

Now it worked.

Updated version: [sdwifi.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5802019/sdwifi.tar.gz)

**Comment by roleoroleo** [comment]
The script in the wiki works only if the hack is installed because it use as a startupper the script /tmp/sd/yi-hack/startup.sh
If you want to run it on a original cam you have to start the script through config.sh as you wrote above.
