### ISSUE TITLE
Can you make the same for Escam pt200?

### ISSUE THREAD

**Issue by alper061** [roleoroleo/yi-hack-Allwinner-v2#650]
Can you make the same for Escam pt200?

This is the camera:
http://www.escam.cn/product/223-en.html
https://www.banggood.com/ESCAM-PT200-2MP-1080P-5G-Dome-WIFI-IP-Camera-Mobile-Tracking-Coud-Storage-Bidirectional-Voice-Night-Vision-Home-Security-CCTV-Monitor-p-1948164.html?cur_warehouse=CN&p=6B232338637912016021&utm_campaign=22331227_1874&utm_content=3547&ID=47757

**Comment by roleoroleo** [comment]
Try to make a backup of the cam.
If it works, maybe I can try to support this cam.

**Comment by alper061** [comment]
Okay. I'll try it and upload if it works.

**Comment by alper061** [comment]
I tryed to upload the backup .sh files, but camera starts and after 50 sec it reboots and it repeats. So if the card is in, the camera will rebooting constantly.

**Comment by alper061** [comment]
The reboot happens if i copy the backup files to the sd. If its blank, the camera starts normal

**Comment by roleoroleo** [comment]
Maybe a problem with this card?
Please try another sd or try to reformat it.

**Comment by alper061** [comment]
It is a brand new card. If its blank, the cam put some folders and files when it starts. (recordings folder, a .db file). I tryed to reformat. When i put the backup files to the card, camera bein to restarting.

**Comment by alper061** [comment]
So the card is probably working.

**Comment by alper061** [comment]
tryed with 2 more cards and no luck :(

**Comment by roleoroleo** [comment]
Even if the cam restarts, is the backup created?

**Comment by alper061** [comment]
No, unfortunately. :(

**Comment by roleoroleo** [comment]
Which OS are you using?
Which unzip program are you using?
Make sure that the sh file is a linux file and not a windows file.

**Comment by alper061** [comment]
I'm using windows and 7zip.

**Comment by alper061** [comment]
I tryed to delete the dd lines from config.sh. The change is faster restarts :)

With original config.sh:
- Start cam
- Wait 20-30 seconds
- Restart
- Repeat

With modifyed config.sh (deleted the dd lines):
- Start cam
- Wait 5 seconds
- Restart
- Repeat

**Comment by alper061** [comment]
Its not solwed. What needs to do to make forward with this?

**Comment by roleoroleo** [comment]
> I tryed to delete the dd lines from config.sh. The change is faster restarts :)
> 
> With original config.sh:
> 
>     * Start cam
> 
>     * Wait 20-30 seconds
> 
>     * Restart
> 
>     * Repeat
> 
> 
> With modifyed config.sh (deleted the dd lines):
> 
>     * Start cam
> 
>     * Wait 5 seconds
> 
>     * Restart
> 
>     * Repeat

This means that dd commands are executed.
But the output file are not saved inside the sd card and I don't know why.
Probably the fw is different and the mount point is not /tmp/sd
I don't know how to fix this problem.
