### ISSUE TITLE
PCM sound RTSP streaming not working, in 0.2.7, y291ga 9.0.35

### ISSUE THREAD

**Issue by hj2650** [roleoroleo/yi-hack-Allwinner-v2#651]
Hi,

PCM audio streaming used to work in 0.2.6, but in 0.2.7, there is no sound output.

ACM audio streaming is working, however.

**Comment by hj2650** [comment]
And after changing the audio streaming option to ACM, the stream is very unstable -- a frame arrives in 2 mins.

**Comment by roleoroleo** [comment]
This is a very insidious and recurring problem.
When I enable -O2 optimization flag in gcc, the resulting binary doesn't work properly.
I have to set -O0.
I will release a new versione ASAP.
Meanwhile use this:
[rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/11787372/rRTSPServer.gz)

**Comment by hj2650** [comment]
> This is a very insidious and recurring problem. When I enable -O2 optimization flag in gcc, the resulting binary doesn't work properly. I have to set -O0. I will release a new versione ASAP. Meanwhile use this: [rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/11787372/rRTSPServer.gz)

Thank you for the fast reply. Could you please link me a document/wiki page or just briefly explain how to apply the rRTSPServer.gz package file on a camera?

**Comment by hj2650** [comment]
Now It works flawlessly. Thank you.
