### ISSUE TITLE
Is there a method to disable all feature & recording and only stream the video?

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#652]
I'm using it with frigate and I don't need camera features anymore, I only want a reliable and stable stream

**Comment by roleoroleo** [comment]
There isn't a single switch, but you can disable the features one at a time.
Below the most important options:
Disable cloud - ON
Recording without Cloud - OFF
Snapshot - OFF
MQTT Enable - OFF
Motions... - OFF

**Comment by PilaScat** [comment]
Thanks, and this?
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/12989749/165be424-d2c4-4c10-afd1-0a64a48d62a9)

**Comment by roleoroleo** [comment]
You can't disable it.
You could try with the app. It depends, in some model there is a switch to turn it on/off.

**Comment by PilaScat** [comment]
Okay thanks
