### ISSUE TITLE
Status of the camera is not correct

### ISSUE THREAD

**Issue by ttarzan01** [roleoroleo/yi-hack-Allwinner-v2#664]
I use firmware 0.2.7 with model y291ga. Unfortunately, I can no longer read the status with IP:8080/cgi-bin/get_configs.sh?conf=camera. It always says "SWITCH_ON": "yes" even if the camera is turned off. What is the reason, what can I do?

**Comment by roleoroleo** [comment]
This is not the correct behavior.
If you switch off the cam from camera_settings web page and click "Save Configuration", the cam should reply "SWITCH_ON":"no"
Please clean the cache of the browser and check again.

**Comment by ttarzan01** [comment]
Sorry, this approach shows no effect. Everytime ist "SWITCH_ON":"yes".

**Comment by roleoroleo** [comment]
Please, use the debug of the browser and try to capture the network request.
F12 with Chrome, network tab.

**Comment by ttarzan01** [comment]
Ok. Camera is off, but camera-setting-page show "on".

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/6c3ed0ae-1133-44d9-823b-8bb08e993f98)

This ist the network request:

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/074b9742-35e9-43f6-848f-b1bc4984ba91)

**Comment by roleoroleo** [comment]
Ok.
Now press Save button and capture the request and the response:

![immagine](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39277388/a8e5add8-fa28-42d2-811a-194079dc17c5)

![immagine](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39277388/5f68adeb-1820-4f9a-8eec-a46754329ca3)

**Comment by thoemmes86** [comment]
I face the same issue.
Looks like after some time 1/2 day camera switched off, it is not longer possible to turn on/off the camera via the hack web interface or the applicable request.

Workaround is to use the yi app to get it again turned on.

**Comment by captaincanada** [comment]
could someone figure out whats the problem?
I have the same issue...

Few times ago i got the correct values within the response of  
"... cgi-bin/get_configs.sh?conf=camera"

but now theres nothing changing after switch something 
neither from the app, nor from Webpage

i used to resolve the json file for a state sensor in Mediola AIO Remote and wanted to use these 
at Home Assistant now.

Maybe this is also the Reason why the HASS Integration does not work for me...?!

Thx to All

**Comment by roleoroleo** [comment]
Please explain me better.
The issue refers to an old version of the hack.

**Comment by captaincanada** [comment]
Hi, thank you for taking care! 

the states of the camera are not correct when I check them with the "conf=camera" request.

this is always the answer, no matter what I use to change:

{
"SWITCH_ON":"yes",
"SAVE_VIDEO_ON_MOTION":"yes",
"SENSITIVITY":"low",
"AI_HUMAN_DETECTION":"no",
"SOUND_DETECTION":"no",
"SOUND_SENSITIVITY":"80",
"LED":"no",
"ROTATE":"no",
"IR":"yes",
"HOMEVER":"9.0.19.02_202007141512",
"NULL":"NULL"
}

**Comment by roleoroleo** [comment]
Maybe you need a refresh of the cache.
If the js script is not synchronized the "Save" function doesn't work.
Please clean the cache and try again.

**Comment by ttarzan01** [comment]
> cache is empty. when I save changed settings and refresh the page, it doesn't keep the changes...
> 
>  Screen_Recording_20231113_112526_Samsung.Internet.mp4

Same here.

**Comment by roleoroleo** [comment]
Please, open the debug console in the browser and click "Save configuration".
Then check the response:
![immagine](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39277388/748ca8cc-bd80-4c1e-bab2-15885b217c98)

**Comment by ttarzan01** [comment]
> Please, open the debug console in the browser and click "Save configuration".
> Then check the response:

I do not receive such a response.

It does not matter whether the camera is on or off, it is always displayed as on. It doesn't matter whether I call 'cgi-bin/get_configs.sh?conf=camera' or 'index.html?page=camera_settings'. 

I noticed another point: If I set the rotation to 'on' under 'index.html?page=camera_settings' so that the image is rotated, this setting is not displayed either. It always shows 'off' when I have saved the settings. Same with 'Status led'.

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/e541454b-baee-4e9f-a389-b7ea50ce3213)

**Comment by roleoroleo** [comment]
> I do not receive such a response.

Please share the request.

**Comment by ttarzan01** [comment]
Ok, I cleared the browser cache, then called 'index.html?page=camera_settings'. The camera is displayed as 'on' even though it is off.
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/86fe2846-9397-4026-a950-4bff70379428)
In the console I only see the following error:

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/288c776f-2c05-4a4a-ada9-1a6250d0425f)
Nothing more.

**Comment by captaincanada** [comment]
<img width="960" alt="camera request" src="https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/2e2cbd57-c82d-4a0d-86ee-efbe5a388668">

**Comment by ttarzan01** [comment]
After refresh:

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/c2971ae9-6117-4e90-a1dc-17e34f8b084e)

But camera is off.

**Comment by captaincanada** [comment]
it sends switch_on= on and switch_on=yes and the camera is switching on and of too, 
but eyerytime i ask for the state it says 

"SWITCH_ON":"yes"

same for browser and postman

**Comment by roleoroleo** [comment]
Check if the file /tmp/sd/yi-hack/etc/camera.conf changes when you switch on/off.

**Comment by ttarzan01** [comment]
> Check if the file /tmp/sd/yi-hack/etc/camera.conf changes when you switch on/off.

Do I have to take the SD out of the camera? Or can I access it in another way?

**Comment by roleoroleo** [comment]
Use ssh.

**Comment by captaincanada** [comment]
I did it with ftp and the files show exactly the same...

https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/bb29e0dd-8b5a-4a5e-bb36-4e207f959c28

**Comment by captaincanada** [comment]
when I manually edit the camera.conf file to switch_on=no... it shows the right state on the web server.

But the effect is the same... it doesn't change the settings set from the web server... it's falling back to state "no"

**Comment by roleoroleo** [comment]
I don't understand. Probably 2 different problems.
The status it' not correct but the question is: does the cam change the internal setting when you click "Save"?
Does the file camera.conf change?
So, the problem is the save method or just the get method?

**Comment by captaincanada** [comment]
the camera.conf does not change.

1.switch web server to "on" 
> camera turns on

-web server button changes to on
-camera.conf doesn't change
-http request doesn't change (thought this would get the data from the camera.conf file)

2.switch web server to "off" 
(whiteout refreshing the web page, cause the button would change by it self after a refresh...)
> camera turns off

-web server button changes to off
-camera.conf doesn't change
-http request doesn't change

the web server button keeps its state and the camera.conf doesn't change. whatever I do
so I guess  the problem is the save method of the camera.conf

**Comment by ttarzan01** [comment]
I have the same behavior of camera.conf on the SD like @captaincanada . No matter what I do, camera.conf doesn't change. Although the camera goes on or off as desired.

**Comment by roleoroleo** [comment]
If the camera switch on/off but doesn't save, it's probably a problem related to mqttv4.

**Comment by ttarzan01** [comment]
It says

root@xxx:~# ps | grep mqttv4
 1403 root       792 S    mqttv4
11639 root       980 S    grep mqttv4

**Comment by roleoroleo** [comment]
mqttv4 is running.
Now try to kill and restart it manually.
```
# killall mqttv4
# mqttv4
```
and click the save button in the web gui.
You should see a log with:
```
...
CALLBACK COMMAND
Updating file "/tmp/sd/yi-hack/etc/camera.conf", parameter "switch_on" with value "no"
Client yi-cam-a2 sending PUBLISH (d0, q1, r1, m12, 'home-assistant/spare/stat/camera/switch_on', ... (2 bytes))
...
```

**Comment by ttarzan01** [comment]
Only see this:

![Zwischenablage01](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/3c5156e2-1c6f-46ed-9b9f-129ed3f3d132)

![Zwischenablage02](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/f07ccd8a-e862-4223-b659-fd08acec224b)

**Comment by captaincanada** [comment]
> So, please, check if it's running:
> `# ps | grep mqttv4`

I got this
![20231118_213232](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/088bcf2d-5248-460d-af40-366fe78ed8be)


ther was no file to kill
![20231118_213352](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/585e8c75-c916-491b-b974-bb8233f33dc6)

But I could restart it and got a callback
![Screenshot_20231118_212736_ConnectBot](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/363073f6-9a29-4b89-bdac-899980e2de14)

**Comment by captaincanada** [comment]
wow, it keeps the state now! Great 👍 
tomorrow I will test if it's still working after a reboot.

I need the cam at the moment, baby boy is sleeping now

**Comment by ttarzan01** [comment]
I completely disconnected the camera from the power supply and restarted it. However, I keep getting the same output in the terminal when I try to start mqttv4.

**Comment by captaincanada** [comment]
> wow, it keeps the state now! Great 👍 tomorrow I will test if it's still working after a reboot.
> 
> I need the cam at the moment, baby boy is sleeping now

could test it now and the problem is back.
it doesn't save the state

**Comment by captaincanada** [comment]
why do I have to restart mqtt4 everytime now?

**Comment by roleoroleo** [comment]
@ttarzan01
In your case, the cam is unable to connect to the mqtt broker.
![immagine](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39277388/a4538e71-33a4-498f-ab7d-0c7d57ed9566)
Could you check the server parameters?

@captaincanada
In your case, the process doesn't start at boot (or it dies immediately).
Edit the file /tmp/sd/yi-hack/script/system.conf and redirect the log of the process.
From:
```
if [ "$HV" == "11" ] || [ "$HV" == "12" ]; then
    if [ "$MODEL_SUFFIX" != "y291ga" ] && [ "$MODEL_SUFFIX" != "y211ga" ]; then
        mqttv4 -t local &
    else
        mqttv4 &
    fi
else
    mqttv4 &
fi
```
To:

```
if [ "$HV" == "11" ] || [ "$HV" == "12" ]; then
    if [ "$MODEL_SUFFIX" != "y291ga" ] && [ "$MODEL_SUFFIX" != "y211ga" ]; then
        mqttv4 -t local > /tmp/mqttv4.log 2>&1 &
    else
        mqttv4 > /tmp/mqttv4.log 2>&1 &
    fi
else
    mqttv4 > /tmp/mqttv4.log 2>&1 &
fi
```

**Comment by ttarzan01** [comment]
> Could you check the server parameters?

Where can I find them?

**Comment by captaincanada** [comment]
> @captaincanada In your case, the process doesn't start at boot (or it dies immediately). Edit the file /tmp/sd/yi-hack/script/system.conf and redirect the log of the process. From:
> 
> ```
> if [ "$HV" == "11" ] || [ "$HV" == "12" ]; then
>     if [ "$MODEL_SUFFIX" != "y291ga" ] && [ "$MODEL_SUFFIX" != "y211ga" ]; then
>         mqttv4 -t local &
>     else
>         mqttv4 &
>     fi
> else
>     mqttv4 &
> fi
> ```
> 
> To:
> 
> ```
> if [ "$HV" == "11" ] || [ "$HV" == "12" ]; then
>     if [ "$MODEL_SUFFIX" != "y291ga" ] && [ "$MODEL_SUFFIX" != "y211ga" ]; then
>         mqttv4 -t local > /tmp/mqttv4.log 2>&1 &
>     else
>         mqttv4 > /tmp/mqttv4.log 2>&1 &
>     fi
> else
>     mqttv4 > /tmp/mqttv4.log 2>&1 &
> fi
> ```

did it... 
I found System.sh but I'm sure that's the right
![Screenshot_20231119_072135_Cx File Explorer](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/5ac870ca-4f83-4976-9694-c15078bd733f)

no change after reboot

the log file contains this
![Screenshot_20231119_074559_Cx File Explorer](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/88c00b41-13c2-4b03-bfc8-802b65378ce5)

**Comment by roleoroleo** [comment]
> Where can I find them?

Probably now I understand the problem: you don't use a mqtt broker.
Right?

**Comment by roleoroleo** [comment]
@captaincanada 
There is a fatal error:
`Can't open mqueue /ipc_dispatch_1`
This shouldn't happen. Probably a problem in the start procedure of the hack.
Post your /tmp/sd/lower_half_init.sh.

**Comment by ttarzan01** [comment]
Hmm, on index.html?page=mqtt MQTT ist enabled:
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/a5551c2b-b498-499a-ae57-d341a53fff52)

`Configuration file for mqttv4
# -----------------------------------------------------------------------------
# Basic MQTT settings
# -----------------------------------------------------------------------------

MQTT_IP=192.168.178.100
MQTT_PORT=1883

MQTT_CLIENT_ID=yicam-penny1

MQTT_USER=
MQTT_PASSWORD=

MQTT_PREFIX=yicam-penny1
MQTT_PREFIX_CONFIG=`

But on index.html?page=mqtt_adv is MQTT disabled:
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/76578892-0a5c-4456-8b39-25937951e813)

**Comment by captaincanada** [comment]
#!/bin/sh

### wifi 8188 ###
if [ "${enable_4g}" = "y" ];then
    echo "4g is running...."
else
    if [ -f /home/base/wifi/8188fu.ko ];then
        insmod /home/base/wifi/8188fu.ko
    elif [ -f /home/base/wifi/8189fs.ko ];then
        insmod /home/base/wifi/8189fs.ko
    elif [ -f /backup/ko/8188fu.ko ];then
        insmod /backup/ko/8188fu.ko
    elif [ -f /backup/ko/8189fs.ko ];then
        insmod /backup/ko/8189fs.ko
    elif [ -f /backup/ko/8192fu.ko ];then
        insmod /backup/ko/8192fu.ko
    elif [ -f /backup/ko/ssv6x5x.ko ];then
        if [ "${SUFFIX}" = "d071qp"  ];then
            if [ -f /home/base/firmware/ssv6x5x/ssv6152-wifi.cfg ];then
                insmod /backup/ko/ssv6x5x.ko stacfgpath="/home/base/firmware/ssv6x5x/ssv6152-wifi.cfg"
            else
                echo "not found ssv6x5x-wifi.cfg"
            fi	
        else
            if [ -f /home/base/firmware/ssv6x5x/ssv6x5x-wifi.cfg ];then
                insmod /backup/ko/ssv6x5x.ko stacfgpath="/home/base/firmware/ssv6x5x/ssv6x5x-wifi.cfg"
            else
                echo "not found ssv6x5x-wifi.cfg"
            fi
        fi
    fi
fi

echo "--------------------------insmod sensor--------------------------"
insmod /home/base/ko/videobuf2-core.ko
insmod /home/base/ko/videobuf2-memops.ko
insmod /home/base/ko/videobuf2-dma-contig.ko
insmod /home/base/ko/videobuf2-v4l2.ko
insmod /home/base/ko/vin_io.ko

if [ "${SUFFIX}" = "b091qp" ];then
    insmod /backup/ko/cam_sensor.ko
    insmod /home/base/ko/vin_v4l2.ko ccm0=$SENSOR_DRIVE_NAME i2c0_addr=$SENSOR_ADDR
else
    insmod /home/base/ko/cam_sensor.ko
    insmod /home/base/ko/vin_v4l2.ko
fi

if [ -f /home/base/ko/icplus.ko ];then
    insmod /home/base/ko/icplus.ko
elif [ -f /backup/ko/icplus.ko ];then
    insmod /backup/ko/icplus.ko
fi

if [ -f /home/base/ko/sunxi_gpadc.ko ];then
    insmod /home/base/ko/sunxi_gpadc.ko
fi

#/home/app/script/factory_test.sh

#echo "MTK 7601" > /tmp/MTK
#echo /tmp/sd/core.exe[%e].pid[%p].sig[%s] > /proc/sys/kernel/core_pattern

sleep 1
ifconfig lo up

ifconfig ${NETWORK_IFACE} up
ethmac=d2:`ifconfig ${NETWORK_IFACE} |grep HWaddr|cut -d' ' -f10|cut -d: -f2-`
#if [ "${enable_4g}" = "y" ];then
#    ifconfig usb0 up
#    ethmac=d2:`ifconfig usb0 |grep HWaddr|cut -d' ' -f10|cut -d: -f2-`
#else
#    ifconfig wlan0 up
#    ethmac=d2:`ifconfig wlan0 |grep HWaddr|cut -d' ' -f10|cut -d: -f2-`
#fi

ifconfig eth0 hw ether $ethmac
a=1
if [ "${SUFFIX}" = "b111qp" ] || [ "${SUFFIX}" = "b101qp" ] || [ "${SUFFIX}" = "b092qp" ] || [ "${SUFFIX}" = "b091qp" ] || [ "${SUFFIX}" = "q321br_aldz_3m" ]; then
    while ( ! ifconfig eth0 up)
    do
        echo "ifconfig eth0 up failed"
        let a++
        if [ $a -eq 10 ]; then
            break
        fi
    done
else
    ifconfig eth0 up
fi

HOMEVER=$(cat /home/homever)
HV=${HOMEVER:0:2}

if [ "$HV" == "11" ] || [ "$HV" == "12" ]; then
    ln -s /home/model/BodyVehicleAnimal3.model /tmp/BodyVehicleAnimal3.model
fi

echo "============================================= home low_half_init.sh... ========================================="
echo "============================================= begin to start app... ========================================="
cd /home/app
if [ -f /home/app/property ];then
    ./property &
fi
#./log_server &

if [ -f "/tmp/sd/Factory/factory_test.sh" ]; then
	/tmp/sd/Factory/config.sh
	exit
fi

if [ "$HV" == "11" ] || [ "$HV" == "12" ]; then
    if [ -f "/tmp/sd/log_tools.tar.gz" ];then
        echo "run log_tools start."
        if [ ! -d /tmp/sd/log_tools ];then
            cd /tmp/sd
            mkdir log_tools
        fi
        cd /tmp/sd
        tar -zxvf log_tools.tar.gz -C /tmp/sd/log_tools
        chmod +x /tmp/sd/log_tools/run_log_app.sh
        source /tmp/sd/log_tools/run_log_app.sh
        cd -
        echo "run log_tools end."
        #exit
    fi
fi

mount --bind /tmp/sd/yi-hack/script/wifidhcp.sh /home/app/script/wifidhcp.sh
mount --bind /tmp/sd/yi-hack/script/wifidhcp.sh /backup/tools/wifidhcp.sh

LD_PRELOAD=/tmp/sd/yi-hack/lib/ipc_multiplex.so ./dispatch &
#sleep 2
#./rmm &
#sleep 2
#./mp4record &
#./cloud &
#./p2p_tnp &
#./oss &
#./rtmp &
#./watch_process &

chmod 777 /tmp/sd/debug.sh
if [ -f "/tmp/sd/debug.sh" ]; then
    echo "calling /tmp/sd/debug.sh"
    sh /tmp/sd/debug.sh &
fi

chmod 755 /tmp/sd/yi-hack/script/system.sh
sh /tmp/sd/yi-hack/script/system.sh &

**Comment by roleoroleo** [comment]
@ttarzan01
mqttv4 exits with a connection error related to your mqtt broker.
So, check that the broker is running on this IP 192.168.178.100 and the connection is not filtered.

**Comment by roleoroleo** [comment]
@captaincanada
lower_half_init.sh is ok.
The error `Can't open mqueue /ipc_dispatch_1` can be a problem with dispatch.
Please, try to reinstall the hack from scratch: format again the sd card and decompress the last released version.

**Comment by captaincanada** [comment]
good morning. 

I reinstalled the whole cam and it works now👍

what I noticed is that I need the port to access the web service anymore...

@ttarzan01 
I suggest to do the same.
I configured network credentials and there was no problem refreshing the hack.
It took about 5min

@roleoroleo 
to use it with the home assistant plug in, do I have to change some settings of the cam?

maybe I have overwritten something the last time i tried to set it up for home assistant...

thx a lot for the great support!!!

**Comment by roleoroleo** [comment]
The port depends on your configuration.
The old version of the hack used port 8080.
Some version ago I changed and now the standard port is 80.
But finally, it depends on your configuration.

To use with ha, you need to enable mqtt and you need a mqtt broker (i.e. mqtt components fot ha).
When you start the wizard to configure the cam, insert the http address of the cam and the port where it resides.
No other requirements.

**Comment by ttarzan01** [comment]
Ok, I have completely reinstalled the hack. Despite everything, I don't see any change. The status on 'cgi-bin/get_configs.sh?conf=camera' does not change when I switch off the camera. I use the web service 'cgi-bin/camera_settings.sh?switch_on=no' from HA. The camera goes off, but the status never changes. 'service.sh?name=mqtt&action=status' tells me that MQTT is running.

ps | grep mqttv4 says:

```
1402 root       792 S    mqttv4
8466 root       980 S    grep mqttv4
```

**Comment by captaincanada** [comment]
did you reboot the cam? I forgot to do that the last time and was wondering...

**Comment by ttarzan01** [comment]
> did you reboot the cam?

Yes. I have rebooted the camera. After installing the hack, I disconnected the camera from the power supply and reconnected it.

**Comment by captaincanada** [comment]
one more question about the HA integration:

I saw that the default port on the mqtt settings (?page=mqtt) is set to 1883.
![Screenshot_20231121_125103_Samsung Internet](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/e714957b-b8c7-4a02-a5bc-4e5fa03fe009)


this wasn't configured on my broker in Home Assistant. 
After activate this "hidden" port on the Broker and setting a user/pw on the web interface (?page=mqtt) the integration was showing "connected" as state.

![Screenshot_20231121_124921_Home Assistant](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/e1328feb-57f1-4a8a-add0-f4c2b4658a25)

![Screenshot_20231121_132633_Home Assistant](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/32679c38-2d48-4230-9d20-0499639a8c30)



But why do I have an disconnected user <unknown> in my log?
it tries to connect regularly...
![Screenshot_20231121_132225_Home Assistant](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/9fbf6676-3500-49ce-a862-14bcafdcda83)

**Comment by roleoroleo** [comment]
Are you using different devices with the same client id?
![immagine](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39277388/c94f2812-9d7c-4ab0-84f2-08a0a6a483cd)

**Comment by captaincanada** [comment]
when i configured the integration the client id was set automatically.

yi_hack_a2_4898ff

i didn't use this id for my mqtt configuration on the web client... Do i have to use this name that was created?

There is no other Yi cam in the Network.

**Comment by roleoroleo** [comment]
In the image above, client id is set to "yi-cam".
If you have 2 devices with the same id, the second one will not login to the broker.

**Comment by captaincanada** [comment]
OK, so that means in the mqtt config must be the same like in Home Assistant (yi_hack_a2_4898ff in my case)?!

i edited the name in Home Assistant, to Yi_babyphone ant set this name in the web config... 
then this appeared in the log
<img width="653" alt="new client name" src="https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/fdf65bce-807e-4f86-8a20-225d079dc3e0">




i changed the name now of the entity (its called Yi_babyphone now and i couldn't change the

**Comment by roleoroleo** [comment]
Please, check again the log of mqttv4.

**Comment by captaincanada** [comment]
![Screenshot_20231121_213733_ConnectBot](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/a66ae6c8-ae71-479d-add8-b91beb572081)

**Comment by roleoroleo** [comment]
I mean the log: the procedure explained here:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/664#issuecomment-1817607252

**Comment by captaincanada** [comment]
![Screenshot_20231122_195748_ConnectBot](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/1cd99d8f-6856-4e8e-81d3-7cf5e81f843f)

![Screenshot_20231122_200133_Home Assistant](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2896314/95e69867-5e24-4288-a071-3b34cf6be7f1)

the  unknown User is a 172.30... IP
what could that be?
it is still in the log shown above

**Comment by roleoroleo** [comment]
The log seems ok now.
Now you should try to remove the cam from ha and add it again.

I don'y know what could be the IP 172.30..
Maybe ha?

**Comment by ttarzan01** [comment]
It seems that my problem is slightly different from @captaincanada . I don't need all the functionalities that MQTT provides in Home Assistant. I just switch the camera on or off via the web service. That still works.

I have also queried the status of the camera via the web service, whereby I have simply evaluated the JSON, which I have sent via "... cgi-bin/get_configs.sh?conf=camera". And here is the problem: the status never changes in the JSON. It is always "on".

**Comment by captaincanada** [comment]
> The log seems ok now. Now you should try to remove the cam from ha and add it again.
> 
> I don'y know what could be the IP 172.30.. Maybe ha?

i removed the cam from HA and configured it again.
Everything is working, but i have a log of the unknown user switching to connected> disconnected about every 10seconds...

**Comment by roleoroleo** [comment]
> Everything is working, but i have a log of the unknown user switching to connected> disconnected about every 10seconds...

Which log? ha, mqtt broker, cam...

**Comment by ttarzan01** [comment]
> Which web service do you use to switch on/off the cam?

I use: `http://ip/cgi-bin/camera_settings.sh?switch_on=yes` for switching on and `http://ip/cgi-bin/camera_settings.sh?switch_on=no` for switching off. And it works.

**Comment by roleoroleo** [comment]
Let me summarize.
I don't want to confuse your case with others.
- You send the switch_on command through web service.
- The cam applies the new setting
- The cam doesn't save it to the camera.conf file

If this is the case, the chain is:
- camera_settings.sh web service runs ipc_cmd to emulate the yi command
- yi software receives the command and switches the cam
- meanwhile mqttv4 sniffs the command and saves the new configuration to the file

If the 1st and the 2nd work the problem is mqttv4.
mqttv4 is not strictly related to the mqtt feature, it works without a configured broker, just for the configuration file part.

There are 2 possible problems:
- ipc_multiplex is not working: dispatch process is executed without the patched library and the ipc events are not shared between processes (mqttv4 doesn't receive the event).
- mqttv4 has a problem.

Restart from scratch and check the following:
- run ps command and check if dispatch and mqttv4 are running
- read /tmp/sd/lower_half_init.sh and check if dispatch is executed with the proper parameters
- kill mqttv4 and run it manually to check the log

**Comment by ttarzan01** [comment]
> I don't want to confuse your case with others.
> 
> * You send the switch_on command through web service.
> * The cam applies the new setting
> * The cam doesn't save it to the camera.conf file

Thats right. I'll try your suggestion.

ps | grep mqttv4 says:
` 1402 root       792 S    mqttv4
18743 root       980 S    grep mqttv4
`
 
/tmp/sd/lower_half_init.sh:
<details>
#!/bin/sh

### wifi 8188 ###
if [ "${enable_4g}" = "y" ];then
    echo "4g is running...."
else
    if [ -f /home/base/wifi/8188fu.ko ];then
		insmod /home/base/wifi/8188fu.ko
    elif [ -f /home/base/wifi/8189fs.ko ];then
        insmod /home/base/wifi/8188fs.ko
    elif [ -f /backup/ko/8188fu.ko ];then
		insmod /backup/ko/8188fu.ko
    elif [ -f /backup/ko/8189fs.ko ];then
        insmod /backup/ko/8189fs.ko
    elif [ -f /backup/ko/atbm603x_wifi_usb.ko ];then
        insmod /backup/ko/atbm603x_wifi_usb.ko
    elif [ -f /backup/ko/ssv6x5x.ko ];then
        if [ "${SUFFIX}" = "d071qp"  ];then
            if [ -f /home/base/firmware/ssv6x5x/ssv6152-wifi.cfg ];then
                insmod /backup/ko/ssv6x5x.ko stacfgpath="/home/base/firmware/ssv6x5x/ssv6152-wifi.cfg"
            else
                echo "not found ssv6x5x-wifi.cfg"
            fi	
        else
            if [ -f /home/base/firmware/ssv6x5x/ssv6x5x-wifi.cfg ];then
                insmod /backup/ko/ssv6x5x.ko stacfgpath="/home/base/firmware/ssv6x5x/ssv6x5x-wifi.cfg"
            else
                echo "not found ssv6x5x-wifi.cfg"
            fi	
        fi	
    fi
fi

echo "--------------------------insmod sensor--------------------------"
insmod /home/base/ko/videobuf2-core.ko
insmod /home/base/ko/videobuf2-memops.ko
insmod /home/base/ko/videobuf2-dma-contig.ko
insmod /home/base/ko/videobuf2-v4l2.ko
insmod /home/base/ko/vin_io.ko

#统一版本
if [ "${SUFFIX}" = "b091qp" ];then
insmod /backup/ko/cam_sensor.ko
insmod /home/base/ko/vin_v4l2.ko ccm0=$SENSOR_DRIVE_NAME i2c0_addr=$SENSOR_ADDR
else
insmod /home/base/ko/cam_sensor.ko
insmod /home/base/ko/vin_v4l2.ko
fi


if [ -f /home/base/ko/icplus.ko ];then
    insmod /home/base/ko/icplus.ko
elif [ -f /backup/ko/icplus.ko ];then
    insmod /backup/ko/icplus.ko
fi

if [ -f /home/base/ko/sunxi_gpadc.ko ];then
    insmod /home/base/ko/sunxi_gpadc.ko
fi

#/home/app/script/factory_test.sh

#echo "MTK 7601" > /tmp/MTK
#echo /tmp/sd/core.exe[%e].pid[%p].sig[%s] > /proc/sys/kernel/core_pattern

sleep 1
ifconfig lo up

ifconfig ${NETWORK_IFACE} up
ethmac=d2:`ifconfig ${NETWORK_IFACE} |grep HWaddr|cut -d' ' -f10|cut -d: -f2-`
#if [ "${enable_4g}" = "y" ];then
#    ifconfig usb0 up
#    ethmac=d2:`ifconfig usb0 |grep HWaddr|cut -d' ' -f10|cut -d: -f2-`
#else
#    ifconfig wlan0 up
#    ethmac=d2:`ifconfig wlan0 |grep HWaddr|cut -d' ' -f10|cut -d: -f2-`
#fi

ifconfig eth0 hw ether $ethmac
a=1
if [ "${SUFFIX}" = "b111qp" ] || [ "${SUFFIX}" = "b101qp" ] || [ "${SUFFIX}" = "b091qp" ] || [ "${SUFFIX}" = "q321br_aldz_3m" ]; then
    while ( ! ifconfig eth0 up)
    do
        echo "ifconfig eth0 up failed"
        let a++
        if [ $a -eq 10 ]; then
            break
        fi
    done
else
    ifconfig eth0 up
fi

echo "============================================= home low_half_init.sh... ========================================="
echo "============================================= begin to start app... ========================================="
cd /home/app
if [ -f /home/app/property ];then
    ./property &
fi
#./log_server &

if [ -f "/tmp/sd/Factory/factory_test.sh" ]; then
	/tmp/sd/Factory/config.sh
	exit
fi

mount --bind /tmp/sd/yi-hack/script/wifidhcp.sh /home/app/script/wifidhcp.sh
mount --bind /tmp/sd/yi-hack/script/wifidhcp.sh /backup/tools/wifidhcp.sh

LD_PRELOAD=/tmp/sd/yi-hack/lib/ipc_multiplex.so ./dispatch &
#sleep 2
#./rmm &
#sleep 2
#./mp4record &
#./cloud &
#./p2p_tnp &
#./oss &
#./rtmp &
#./watch_process &

chmod 777 /tmp/sd/debug.sh
sh /tmp/sd/debug.sh &

chmod 755 /tmp/sd/yi-hack/script/system.sh
sh /tmp/sd/yi-hack/script/system.sh &

</details>

Then  `killall mqttv4`
Seems ok

After run `mqttv4`

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/104685534/cd1e6c0d-3881-4c1d-a594-75d5473b88b0)

The last line comes over and over again

**Comment by captaincanada** [comment]
> > Everything is working, but i have a log of the unknown user switching to connected> disconnected about every 10seconds...
> 
> Which log? ha, mqtt broker, cam...

The LOG in Home Assistant

**Comment by roleoroleo** [comment]
@ttarzan01 
The problem is the connection with your mqtt broker.
But if you don't need mqtt features you have to disable mqtt in the web gui:
![immagine](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39277388/8b33b9c0-27bb-4485-bdfc-b19bf6470b71)

If you enable it, you must have a working mqtt broker.

**Comment by roleoroleo** [comment]
> Everything is working, but i have a log of the unknown user switching to connected> disconnected about every 10seconds...

If the problem is related to the cam, you should see connection and disconnection in the mqttv4 log.

Did you enable something in mqtt advertising page?
http://IP-CAM/?page=mqtt_adv

**Comment by ttarzan01** [comment]
> you have to disable mqtt in the web gui

Ok, I have deactivated mqtt in the web interface. Then rebooted the camera. To be on the safe side, I disconnected it from the power supply and reconnected it. Nevertheless, the status of the camera.conf does not change. Regardless of whether I switch the camera on or off, the file is not written.

**Comment by roleoroleo** [comment]
Incredible...
I know this is a difficult request but... are you able to grant me a temporary ssh access to the cam?
I could try to debug it directly.

**Comment by ttarzan01** [comment]
> are you able to grant me a temporary ssh access to the cam?

I have no idea how this is supposed to work, accessing the camera from outside via ssh.

**Comment by roleoroleo** [comment]
For example you could open a ngrok session.
https://ngrok.com

**Comment by ttarzan01** [comment]
> For example you could open a ngrok session. https://ngrok.com

That sounds like a lot of effort. I would have a look at the connection via mqtt. That seems to work.

Or would it make sense to try an older version of the firmware? Were there any changes at some point that could have triggered the behavior in my case?

**Comment by roleoroleo** [comment]
> Or would it make sense to try an older version of the firmware? Were there any changes at some point that could have triggered the behavior in my case?

A lot of changes... It's not simple.
Another way: you could dump the network traffic inside the cam.
Download tcpdump from here
https://github.com/roleoroleo/yi-hack-utils/tree/main/Allwinner-v2
Copy it to the sd card and run it with the following command:
`tcpdump -i wlan0 -w /tmp/sd/capture_01.pcap`
Send me the file.

**Comment by ttarzan01** [comment]
> Another way: you could dump the network traffic inside the cam.

Ok, will try it.
