### ISSUE TITLE
Only the first 2 lines of the Crontab are saved

### ISSUE THREAD

**Issue by sirduke989** [roleoroleo/yi-hack-Allwinner-v2#666]
yiCam Outdoor camera running firmware version 0.2.7 for model y211ga

The Crontab configuration is only saving the first two lines that are entered.

This appears to be caused by the bash replace only replacing the first instance of \n with \t here: https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/3d11161a9e958561c48a9a476fb7c3e099d9d03d/src/www/httpd/cgi-bin/set_configs.sh#L79C28-L79C28 so anything past the 2nd newline gets discarded.

I believe the first forward slash needs to be doubled up for a global replace like this: POST_DATA="${POST_DATA//\\n/\\t}"

**Comment by roleoroleo** [comment]
Thank you for your time.
Fixed here: https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/e5e998e05f8968d5fbad6438b61728f5195a5fed
