### ISSUE TITLE
nc not in path

### ISSUE THREAD

**Issue by ldeodato** [roleoroleo/yi-hack-Allwinner-v2#67]
in the ftppush.sh script I've added: PATH=$PATH:/tmp/sd/yi-hack/usr/bin at line 8 because nc was not in PATH and no upload was done
The tree replication doens't works, it fails with "ftpput: unexpected server response to STOR: 550 " in log
In the ftp server log I Can't see any mkdir operation... I'll investigate

**Comment by roleoroleo** [comment]
ftppush.sh already contains /tmp/sd/yi-hack/usr/bin in the PATH.
See line 18: https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/master/src/static/static/yi-hack/script/ftppush.sh
