### ISSUE TITLE
PTZ controls reversed

### ISSUE THREAD

**Issue by Zephael86** [roleoroleo/yi-hack-Allwinner-v2#68]
On Yi 1080p Dome (r30gb) fw. version: 1.0.3 I experience that the PTZ movement controls move the camera head in the opposite direction as I expect.

When I rotate the image for ceiling mount mode, the controls move the camera as they should in floor mounting mode. And vica versa.

I see the same behavior when using Onvifer application.

**Comment by roleoroleo** [comment]
Is this the only case?
Do the other users of the r30gb have the same problem?

**Comment by fabiodirauso** [comment]
i have this problem, on the ptz command as invertited

**Comment by roleoroleo** [comment]
Ok, I will change left with right.

**Comment by Zephael86** [comment]
Up-Down is affected as well.
Without knowing the code I am just guessing. Can it be that it is invers stored that the cam is on its "foot" or ceil mounted?

**Comment by roleoroleo** [comment]
I agree with you.

**Comment by roleoroleo** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/0d0b7a50e674e095c1570153661fc5e577352189
