### ISSUE TITLE
Why multiple firmware is per camera type? Which one?

### ISSUE THREAD

**Issue by phoenix1887** [roleoroleo/yi-hack-Allwinner-v2#680]
On the supported cameras I see now 4 different firmware types listed for the same camera:

Yi 1080p Home IFUS

Which one do we choose? This is confusing. I've been installing this software for a few years now and there's always been 1 firmware version that corresponds for the camera type. Now there's multiple for all these types. It's very confusing which one to use? What's the difference?

**Comment by roleoroleo** [comment]
"Yi 1080p Home IFUS" is not enough to know which model is the cam.
It depends on the fw version (Yi firmware).
