### ISSUE TITLE
RTSP not working Iphone

### ISSUE THREAD

**Issue by tv4you2016** [roleoroleo/yi-hack-Allwinner-v2#686]
hello

I have an ESCAM PT202 with the version yi-hack-Allwinner-v2 0.2.9 and when I have the rtsp view on the iphone through HomeAssistant I can't get the black image.
I have another camera that works,

I opened Vlc with one and the other to compare setting
will it be possible to apply the img2 setting to see it work?

- img2 (works on iphone).png

![img2 (works on iphone)](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/83761813/83a07e73-1c1d-4de7-94cd-3ae92fbd377d)

- img1 (not works on iphone).png

![img1 (not works on iphone)](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/83761813/521ce0d4-a88a-4489-a9f3-786c59865fd8)

**Comment by roleoroleo** [comment]
What do you mean with "through HomeAssistant"?
You are opening ha with a browser inside your iphone?
If yes, which control are you using? WebRTC? Picture glance?
