### ISSUE TITLE
Password problems

### ISSUE THREAD

**Issue by AditaNi** [roleoroleo/yi-hack-Allwinner-v2#688]
Hi

I have a wired situation regarding password.

If I put in my password things like % or & or # or + after rebooting the camera, my password will be not recognised....why?

I must pust some complexity in my password.

**Comment by iubmadiwtu** [comment]
Which password are you setting and on which page. 
Configurations -> Authentication
if its to access RTSP, ONVIF, and HTTP you cant use + or # 
`Allowed special chars: \ | ! " $ % & / ( ) ' ? ^ [ ] @ < > , ; . : - _ *`

**Comment by roleoroleo** [comment]
Please use only allowed special chars as specified above.
