### ISSUE TITLE
How to stop Hack from creating Events

### ISSUE THREAD

**Issue by r4zi3lrrr** [roleoroleo/yi-hack-Allwinner-v2#69]
Hi All,

Apologies if this has been asked before but is there any way to stop this hack from creating events i.e. mp4 files.

It's just that my SD card seems to fill up extremely quickly 16 GB.

If there isn't a way of stopping these events from occurring.  What's the easiest way to delete them (don't really want to go through the web-interface as it take ages to delete)

Thank you.

**Comment by roleoroleo** [comment]
The hack is not responsible for this behavior. It's the main configuration made with the app.
But you could:
- Disable che switch "Recording without Cloud".
- Set a percentage in the "SD free space (%)" box.
- Create a script and schedule with cron where you delete the files.

**Comment by r4zi3lrrr** [comment]
Thank you for the info.
