### ISSUE TITLE
Reset after "connecting to wifi" Yi outdoor camera.

### ISSUE THREAD

**Issue by riceart** [roleoroleo/yi-hack-Allwinner-v2#690]
model is YHS.3020
IFUSY59CV5

Hi, ive bought 4 yi outdoor cameras and after a year or something one of them has some weird issue. It "resets?" after "connecting to wifi" and starts back to "waiting to connect". Im not sure what happed, probably my dad clicked something in app and updated firmware? I dont know. 
I tried your file "h30ga_0.2.9.tgz" and it flashed but issue persist.

any ideas ?

Best regards, Paul
ps. yi did not respond to me ;<

**Comment by roleoroleo** [comment]
You should try to unbrick the cam and restart the pairing process.
Follow the guide in the wiki.
