### ISSUE TITLE
RFUS 9.0.19.12 - Any luck with others?

### ISSUE THREAD

**Issue by leafnie** [roleoroleo/yi-hack-Allwinner-v2#691]
I've been struggling to find any firmwares that support the exact pair of RFUS* + 9.0.19.12. I am unable to update further through the app.

The page says if it does not exactly match, don't try it. Is it still possible to perform this? 

This person went off the beaten path a little bit, I think.

"Also tested on Yi Camera Outdoor RFUS on firmware version 12 running 0.2.9 for h30ga and it looks good."

_Originally posted by @sirduke989 in https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/246#issuecomment-1645580875_

**Comment by roleoroleo** [comment]
Please, try y21ga.
It should work.

**Comment by leafnie** [comment]
I have confirmed it works with y21ga. Thanks.
