### ISSUE TITLE
Yi 1080p Home BFUS - Yellow LED

### ISSUE THREAD

**Issue by lenisko** [roleoroleo/yi-hack-Allwinner-v2#695]
Hey there!

BFUSY44L1U / YYS.2016

At first, I tried using y21ga, but there was no reaction (solid yellow led). After that, tried unbrick using backup files I had on microSD card, but there was no reaction for backup or any other file on empty microSD card. Any clues?

Sadly, can't remember what was the previous state of this camera.
I'm using 4GB FAT32 formatted microSD card

No reaction to https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Dump-your-backup-firmware-(SD-card)

**Comment by roleoroleo** [comment]
Check the model of the cam with this procedure:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/discussions/693#discussioncomment-6779130
Then follow the unbrick guide.

**Comment by lenisko** [comment]
I had to do something wrong before... All good now. Thank you!

Leaving my notes:
```
➜  yi binwalk -eM mtdblock2.bin
➜  yi cat _mtdblock3.bin.extracted/squashfs-root/homever
9.0.19.02_202007141512
```

Moved backup files to `\unbrick\y21ga` and created images.

Moved them to microSD
![2023-08-22_02-13-56-explorer](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/10072920/af7d4e2c-854e-4e47-a59d-b62ce14d1241)

Camera booted successfully!
