### ISSUE TITLE
Motion detection not working

### ISSUE THREAD

**Issue by rikrdo89** [roleoroleo/yi-hack-Allwinner-v2#696]
In the Camera Settings in UI, I enable "Save video when a motion is detected"  as shown below:
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/24930604/5a34e675-70e8-4343-8ea9-5022651c0f45)

and in Configurations in the UI, I enable recording without cloud as show below:
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/24930604/f44d5363-f257-4656-a65c-56054e40378b)

however, I don't get any recording after a motion event. I do get recording when sound detection is enabled.

What is interesting is that the UI says: `Motion Detection | You don't need to enable motion detection, it's always enabled.`
However, looking at the camera.conf in the camera, I see that the MOTION_DETECTION is not enabled.
```
$ cat /tmp/sd/yi-hack/etc/camera.conf
SWITCH_ON=yes
SAVE_VIDEO_ON_MOTION=yes
MOTION_DETECTION=no
SENSITIVITY=high
AI_HUMAN_DETECTION=no
AI_VEHICLE_DETECTION=no
AI_ANIMAL_DETECTION=no
FACE_DETECTION=no
MOTION_TRACKING=no
SOUND_DETECTION=no
SOUND_SENSITIVITY=80
LED=no
ROTATE=no
IR=yes
CRUISE=no
```
Is this some sort of bug?

# Details of my system:
Firmware Version | 0.2.9
Base Version | 9.0.35.00_202111291330
Model Suffix | y291ga
Serial Number | RFUSY62X2PP2O3220620

**Comment by roleoroleo** [comment]
> However, looking at the camera.conf in the camera, I see that the MOTION_DETECTION is not enabled.

This settings is used only if the cam has fw 12.
In your case is not important.

What about the app? If you try to enable motion detection with the app.
