### ISSUE TITLE
Feature request: pass Wi-Fi credentials on the very first run of the hack

### ISSUE THREAD

**Issue by troyane** [roleoroleo/yi-hack-Allwinner-v2#698]
My personal use-case was to use cameras wireless. So I need to take cameras one by one and attach to router via LAN cable, so it become visible in my network. It would be way easier if I could pass Wi-Fi credentials file alongside with the rest of the files required to run YI hack on first time.

**Comment by roleoroleo** [comment]
I will add to the next release.

**Comment by troyane** [comment]
Great to hear that! Thanks a lot!

**Comment by troyane** [comment]
@roleoroleo There is an optional step described in [(4)](https://github.com/roleoroleo/yi-hack-Allwinner-v2/tree/master#installation), but there is no such file in `Factory` folder of [b091qp_0.2.9.tgz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/tag/0.2.9). Here is its content:
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/477468/9027dca5-703f-4a9b-8d86-fd52fcae6fed)

**Comment by roleoroleo** [comment]
You are right.
I committed the code and the new readme but it's not yet released.

**Comment by roleoroleo** [comment]
If you want to try it, you can add the file manually to the sd.
