### ISSUE TITLE
the Free/Total Memory counter in the web interface seems wrong

### ISSUE THREAD

**Issue by nemonoid** [roleoroleo/yi-hack-Allwinner-v2#701]
Example:

In the web interface it says that there are 38420KB of free RAM:

![mem3](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/142457275/acd48127-3048-4947-ba7a-9530dc3c288f)

But from the SSH console, I can see that there are only 11077KB of free RAM (or 18096K available)

![mem1](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/142457275/e450a515-ec86-4b09-8f89-8c19cef7db1e)

Is this a bug, or am I missing something ?

----
Additional info:
- My cam is: Yi 1080p Home RFUS | 9.0.35* | y291ga  version 0.2.9
- Tried to reinstall the hack, the issue persists.

**Comment by roleoroleo** [comment]
Free is the sum of 3 fields: free + buff/cache + available.
I don't remember why, probably I never changed this calculation after cloning yi-hack-v4.
I think it's not ok, it should be free + buff/cache.
I will fix it.

**Comment by nemonoid** [comment]
> free is the sum of 3 fields: free + buff/cache + available. 

Ok, that is certainly wrong:  I just checked, and in Linux **available** is the sum of **free + the portions of buff/cache that can be released immediately**  

Good Explaination Here: https://www.howtogeek.com/456943/how-to-use-the-free-command-on-linux/

( in fact it makes sense, as the kernel uses a lot of memory for buffers and caches to speed up operations, but they are not strictly needed and can be quickly released, therefore they are considered part of the **available** memory )

So I believe the correct thing is to just quote the Available/Total Memory numbers in the Web Interface. 
So for example taking my screenshot above it would be:  _Available/Total Memory 18096/60908 KB_

**Comment by roleoroleo** [comment]
I will change it.

**Comment by nemonoid** [comment]
> The reason of the current calculation is the format of the output. It depends on the version, the number of columns can be different (buffers and cache columns).

Oh, I see!

Thanks
