### ISSUE TITLE
camera with hack tries to reach DNS and github servers.

### ISSUE THREAD

**Issue by AI-wwu** [roleoroleo/yi-hack-Allwinner-v2#702]
I installed the hack, thank you! I blocked the camera from accessing internet, only NTP is reachable.
I see the following dropped packets to DNS and github servers, question is, what is that?

```
DROP  SRC=192.168.1.110 DST=8.8.8.8 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=4339 DF PROTO=UDP SPT=57203 DPT=53 LEN=40
DROP  SRC=192.168.1.110 DST=8.208.8.243 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=62929 DF PROTO=UDP SPT=57203 DPT=53 LEN=40
DROP SRC=192.168.1.110 DST=8.8.8.8 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=4340 DF PROTO=UDP SPT=57203 DPT=53 LEN=40
DROP SRC=192.168.1.110 DST=8.208.8.243 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=62930 DF PROTO=UDP SPT=57203 DPT=53 LEN=40
DROP SRC=192.168.1.110 DST=140.82.121.6 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=57683 DF PROTO=TCP SPT=44518 DPT=443 WINDOW=23200 RES=0x00 SYN URGP=0
DROP SRC=192.168.1.110 DST=140.82.121.6 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=57685 DF PROTO=TCP SPT=44518 DPT=443 WINDOW=23200 RES=0x00 SYN URGP=0
DROP SRC=192.168.1.110 DST=140.82.121.6 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=57686 DF PROTO=TCP SPT=44518 DPT=443 WINDOW=23200 RES=0x00 SYN URGP=0
```

where camera ip is 192.168.1.110

I also try to add it into iobroker MQTT, the image at mqtt.0.yicam2.motion_detection_image somehow not correctly stored (could be issue of mqtt in iobroker), can you store it also in mqtt.0.yicam2.motion_detection_imagebase64 in base64 format?
here is the link to solution, that could be probably used: [https://stackoverflow.com/questions/41378155/convert-unsigned-char-array-to-base64-string](url)

**Comment by iubmadiwtu** [comment]
Github it checks if it's on the latest version see 
http://your host:8080/?page=maintenance
for DNS see [issue 340](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/340)
