### ISSUE TITLE
feature request - rotate image 90 degree

### ISSUE THREAD

**Issue by TungstenE2** [roleoroleo/yi-hack-Allwinner-v2#704]
Would it be possible to implement also option to rotate image/stream 90 dregree (clockwise and anti-clockwise)?

Currently only 180degree is possible.

![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39955685/e94b5c44-f66b-4697-84f5-11833619e2cb)

**Comment by roleoroleo** [comment]
Sorry but it's not possible.
This class of settings is managed by Yi firmware.

**Comment by TungstenE2** [comment]
ok, thx for checking.
I was wondering as with other webcams this is possible.
