### ISSUE TITLE
Kami Baby support

### ISSUE THREAD

**Issue by osh123** [roleoroleo/yi-hack-Allwinner-v2#705]
Any option to have Kami (YI) Baby camera support?
Serial number is starting with LFUS, firmware version is 1.3.0.0C.

**Comment by osh123** [comment]
Hi @roleoroleo,

Thanks for the reply, I've ran backup script - it did work, can I post it here? does it contain any sensitive information of my Kami/YI account?

Thanks!

**Comment by roleoroleo** [comment]
Ok, you can remove the link, if you want.
The cam seems to be Allwinner based and probably compatible with this hack:
https://github.com/roleoroleo/yi-hack-Allwinner

But I need some time to add the support.
I will create a beta version to try.
Please, open the issue in the repo https://github.com/roleoroleo/yi-hack-Allwinner

**Comment by roleoroleo** [comment]
How long ago did you buy it?

**Comment by osh123** [comment]
> Ok, you can remove the link, if you want. The cam seems to be Allwinner based and probably compatible with this hack: https://github.com/roleoroleo/yi-hack-Allwinner
> 
> But I need some time to add the support. I will create a beta version to try. Please, open the issue in the repo https://github.com/roleoroleo/yi-hack-Allwinner

Will do, thank you!


> How long ago did you buy it?

10 months ago.
