### ISSUE TITLE
request: 2nd or alternative wifi SSID & credentials

### ISSUE THREAD

**Issue by TungstenE2** [roleoroleo/yi-hack-Allwinner-v2#715]
Hi all,

is there an option to have 2nd or alternative wifi SSID & credentials configured, as it is possible with ESP32-cams?

That would be great.

thx

**Comment by roleoroleo** [comment]
It is not easy to implement this feature because the wifi connection is handled entirely by Yi's original processes.
We should overwrite the flash partition with backup credentials but it would become a reliability problem and the risk of bricking is high.

**Comment by Dotatay** [comment]
You can place the "/Factory/wpa_supplicant.conf" with new credentials and reboot the cam.
