### ISSUE TITLE
Strange IR filter activation

### ISSUE THREAD

**Issue by tempod** [roleoroleo/yi-hack-Allwinner-v2#718]
I noticed a strange behavior of the camera in night mode.
the IR filter turns on and off for a few minutes every hour.

![night](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/71033514/b8f13325-32eb-4e00-8ed5-a4fdaac152a7)

What could this behavior depend on?

**Comment by roleoroleo** [comment]
Strange behavior.
Is there a light source that changes the light in the room?
