### ISSUE TITLE
New rRTSPServer.gz for Yi Home new firmware 9.0.19.02_202007141512 

### ISSUE THREAD

**Issue by nmenoux** [roleoroleo/yi-hack-Allwinner-v2#72]
As your fix is working like a charm on the yi-hack-Allwinner concerned camera 👍 @roleoroleo could you provide the new rRTSPServer.gz for the Allwinner-v2 platform please as I'm not able to compile source files, I do not have the livemedia subdirectory for compiling. 

Thanks a lot.

**Comment by roleoroleo** [comment]
Here it is:
[rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5844055/rRTSPServer.gz)
Let me know it it works correctly.

I will release a new version asap.

**Comment by nmenoux** [comment]
Thanks @roleoroleo ! I will keep you informed if it works as it does for previous cameras. As it is night here in France, I will wait tomorrow light for reliable tests ;-) Thanks for your work again.

**Comment by kkawett** [comment]
Hi there,
I've juste checked the version of my cam and it is the same as yours. Is it why I can't access rtsp stream ?
Thanks for the help and the fix :)

**Comment by roleoroleo** [comment]
No.
This update improves reliability.

**Comment by nmenoux** [comment]
@roleoroleo I've launched the new rRTSPServer on the camera and stream is still ok right now after one complete day period, night is back now :-) I would say that your fix is working very well on Allwinner-v2 too  👍  Well done ! Thanks

**Comment by roleoroleo** [comment]
Good news!
