### ISSUE TITLE
Stuck in bootloop

### ISSUE THREAD

**Issue by manmeet3** [roleoroleo/yi-hack-Allwinner-v2#726]
Hello,
I have a 1080p Yi Home that whos serial number starts with "IFUSY..."; I tried both
<html>
<body>

Yi 1080p Home IFUS | 9.0.19* | y21ga | -
-- | -- | -- | --
Yi 1080p Home IFUS | 12.1.19* | y21ga

</body>
</html>

and 

<html>
<body>

Yi 1080p Home IFUS | 9.0.36* | y211ga | -
-- | -- | -- | --
Yi 1080p Home IFUS | 12.0.37* | y211ga | -

</body>
</html>

but they both keep sending my camera into bootloop. What could I be doing wrong?

Follow up: Is there a significant difference between the 2 firmwares?

**Comment by roleoroleo** [comment]
> but they both keep sending my camera into bootloop. What could I be doing wrong?

You need to check the fw version inside Yi app. And select the hack based on this version.

> Follow up: Is there a significant difference between the 2 firmwares?

No, just a couple of files. But the file lower_half_init.sh is very important and can cause problems if it's not correct.
