### ISSUE TITLE
After a human detection, if camera is switched off, detection remain active for eternity

### ISSUE THREAD

**Issue by thelittlefireman** [roleoroleo/yi-hack-Allwinner-v2#727]
With the HA integration plugin.

When a yicam_human_detection binary sensor (HA) is on (human detected) and right after the camera is switched off through HA integration plugin switch. The human binary sensor is permanently on until the camera is switched off.

Seems to be the follow-up of this [https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/27e43b07ced09fa5d0231a4f05886c312cebcf2a#diff-852d3936a3b3a31b0e9d36253e05d456afa8abe163c2a3d60d30b72929ef4eceR54](https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/27e43b07ced09fa5d0231a4f05886c312cebcf2a#diff-852d3936a3b3a31b0e9d36253e05d456afa8abe163c2a3d60d30b72929ef4eceR54).
==> ` ipc_cmd -T` needs to be call also when switch off from mqtt.

**Comment by roleoroleo** [comment]
You are right.
I need to add this piece of code for all alarm events.

**Comment by roleoroleo** [comment]
I checked the code and AFAIK there is no specific stop messages for these events.
The cam receive the standard stop message and send it to the mqtt broker.
Probably I should switch off the alarm inside the integration.

**Comment by roleoroleo** [comment]
I tried to follow the path...
- ha switches off the cam
- the integration sends a mqtt message "switch_on" "off"
- mqtt-config process receives the cmd message from the broker and changes the internal state running `ipc_cmd -t`
- the cam switches off
- mqttv4 process sniff the ipc command, save the conf file and replies to the broker with the state "switch=off"
- ha updates the state

I should run a `ipc_cmd -T` somewhere in this path.
Probably inside `mqtt-config`.
