### ISSUE TITLE
New wifi credentials procedure - no file named Factory/configure_wifi.cfg.ori

### ISSUE THREAD

**Issue by idogrf** [roleoroleo/yi-hack-Allwinner-v2#731]
According to the new instructions in the readme, setting up wifi creds is done by changing the name of a file named `Factory/configure_wifi.cfg.ori`
The file does not exist in any of the 0.2.9 tgz archives

**Comment by roleoroleo** [comment]
You are right.
The readme file refers to the commited (and not yet released) version.
If you want to use it, you have to overwrite the Factory folder with the files from the master repo.
