### ISSUE TITLE
Can't update to 0.3.0

### ISSUE THREAD

**Issue by PilaScat** [roleoroleo/yi-hack-Allwinner-v2#733]
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/12989749/991f71bb-8064-47fc-baeb-273bacbb993b)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/12989749/bb26b1d3-c7c4-4a3e-b8bb-75b10ef97cb5)

**Comment by roleoroleo** [comment]
This piece of code fails:
```
        /tmp/sd/yi-hack/usr/bin/wget https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/download/$LATEST_FW/${MODEL_SUFFIX}_${LATEST_FW}.tgz
        if [ ! -f ${MODEL_SUFFIX}_${LATEST_FW}.tgz ]; then
            printf "Content-type: text/html\r\n\r\n"
            printf "Unable to download firmware file."
            exit
        fi
```
Try to tun the following commands replacing $LATEST_FW with 0.3.0 and $MODEL_SUFFIX with your suffix (e.g y21ga).
And check the error:
```
mkdir -p /tmp/sd/.fw_upgrade
cd /tmp/sd/.fw_upgrade
/tmp/sd/yi-hack/usr/bin/wget https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/download/$LATEST_FW
```

**Comment by roleoroleo** [comment]
Maybe a issue with the sd card.

**Comment by PilaScat** [comment]
I'm having problems connecting with ssh, I didn't tell but this problem is present in 2 cameras

**Comment by PilaScat** [comment]
facepalm, I remembered only now I blocked internet connectivity 😂

**Comment by Bodengriller** [comment]
Same problem here:
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/50927649/242a6c46-0cbc-4b00-928f-8d28d935fa0b)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/50927649/9478f7c0-6a2e-4690-a02c-d9876a13687e)

I noticed that the complete folder /tmp/sd/yi-hack/usr/bin is missing - accordingly the update script wget can't find it either.
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/50927649/bf2de28f-6eeb-4f90-83ce-e049a2f6c88f)

I have now simply copied the complete folder /yi-hack/usr/bin from the v0.3.0 via ssh to the cam - after that the online update went through without problems.

no idea why the bin folder was missing

**Comment by roleoroleo** [comment]
Maybe a problem during the previous upgrade.
