### ISSUE TITLE
Feature request: Same file name for "Time-lapse ftp push" images 

### ISSUE THREAD

**Issue by maxen0815** [roleoroleo/yi-hack-Allwinner-v2#736]
Hi there,
I would like to request the following feature:
- there should be an option added, that all snapshots uploaded to FTP are having the same file name - replacing the last uploaded file on the server.

The reason is quite simple:
I would like to use the timelapse snapshot upload but I don't care about the "history", but only need the current situation on my FTP.
I'm monitoring a parking lot to see, if there is free space available. Since several users access the pictures, I don't want to grant direkt access to the camera.

I can also try to contribute if i get some hint, which part of the sourcecode has to be changed therefore. I'm not very experienced, but highly motivated 😂.

Best regards,
Maxen

**Comment by roleoroleo** [comment]
Ok, I will add this feature to the next release.

**Comment by maxen0815** [comment]
That will be great!
If you need someone to test the feature while implementing, let me know.

**Comment by roleoroleo** [comment]
Please, try this script:
[time_lapse.sh.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13296975/time_lapse.sh.gz)

**Comment by maxen0815** [comment]
I run a test using the script and it seems to work!
On my FTP I get every minute an updated picture (placing a running timer in front of the cam) all named the sane "snapshot.jpg".
So functional as expected - Thanks!


Since for me it was unclear how to set the Option "TIMELAPSE_FTP_SAME_NAME" on true, I did a small adaption within your script which made it active independently from this setting  ;-) 
I simply replaces the ELSE with the same naming convention.
![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/ea283ee2-7c4e-40b9-9274-37db163b5703)

**Comment by roleoroleo** [comment]
You are right.
The option "TIMELAPSE_FTP_SAME_NAME" is a new option I added to the web gui.
But you don't have it because I shared with just the shell script.
I committed it for the next version.

**Comment by maxen0815** [comment]
Running stable for 1 hour now, with a timelapse time of 1 min.

Possbile problem with Time-lapse video creation:
- What will happen to the Time-lapse video creation, if this option is active?

**Comment by maxen0815** [comment]
Improvement option:
Currently the "snapshot.jpg" creates the "timelapse" directory on the FTP server. 
Not a big issue - bute since this is not a timelapse any more, you could also place the snapshot.jpg directly to the selected FTP directory, without adding a new folder.

**Comment by roleoroleo** [comment]
> Running stable for 1 hour now, with a timelapse time of 1 min.
> 
> Possbile problem with Time-lapse video creation:
> 
>     * What will happen to the Time-lapse video creation, if this option is active?

No problem, if ftp is enable time lapse is disabled.
