### ISSUE TITLE
Hack installed - RTSP running, but no access to web-interface

### ISSUE THREAD

**Issue by maxen0815** [roleoroleo/yi-hack-Allwinner-v2#741]
Hi there,

I installed y211ga on another CAM like I did in the past on another camera.
Now I cant connect to the web-interface. I would expect to find a connection on:
http://192.168.0.74:8080/

Regarding the SD-file structure the hack was sucessfully performed.
![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/0bba23d2-e582-468e-9551-b3020d35b7f2)

Within the router I can find the camera named as "yi-hack"
![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/43f0c435-6215-4d30-a4e5-12946d9f8063)

Also the RTSP Stream is accessible on the IP.
![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/891d322e-0209-4e0a-9a58-db7d981dcd54)

Any suggestions what to do next, to get the web-IF running?

Thanks & best regards
Maxen

**Comment by ericbrowley** [comment]
I'm pretty sure the default port is 80 for the Web GUI now, have you tried just http://192.168.0.74

**Comment by maxen0815** [comment]
Thanks for this simple hint - It's working on port 80...

I feel like stupid now, since both other hacked cameras are running web interface on port 8080!
Also the FAQ remembers to use 8080 to access the web interface:
![Screenshot_20231104_234411](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/85107d96-dbac-4fd4-8d87-168a430f1568)

**Comment by roleoroleo** [comment]
Sorry for the problem.
I moved web gui from 8080 to 80 in a recent release.
But only if you restart the configuration from scratch.
I updated the faq.
