### ISSUE TITLE
Possibly wrong hack filename for Yi Dome Guard YRS

### ISSUE THREAD

**Issue by fearpro13** [roleoroleo/yi-hack-Allwinner-v2#745]
As described in "Supported cameras" table **Yi Dome Guard YRS** camera suppose to work with **r35gb** version of the hack.
Actually it works: hack is being applied well, web-interface working e.t.c But most of the features does not work - rtsp live video, screenshot, ptz
I do have 2 same cameras - **Yi Dome Guard YRS.3019**. Both of them are failed to have working features listed above. It was decided to dismantle both of them just to see what is inside. After that it was noticed that both camera's motherboard have r30gb sign in the corner. After that hack with **r30gb** version was applied and everything is working nice as it should be.
![j2](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/67797618/cd4ef92b-0658-4684-9e67-c847fbe23291)
![j1](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/67797618/4ceaf1f0-5a71-4197-aa30-2f2c67de4c48)

**Comment by fearpro13** [comment]
Message that Yi Dome guard supports r30gb hack version is also mentioned here
https://github.com/TheCrypt0/yi-hack-v4/issues/265

**Comment by fearpro13** [comment]
> To identify the model, check the fw version.

All 4 fw versions listed in table are suppose to work with r35gb

**Comment by roleoroleo** [comment]
The question is: what's the fw version of your cam?

**Comment by fearpro13** [comment]
Copied from hack web-interface

Firmware Version | 0.3.0
Base Version | 9.0.05.33_202009251856
Model Suffix | r30gb
Serial Number | KFUSY36OJ3V7NK200808

**Comment by roleoroleo** [comment]
Yes, you are right.
Fw 9.0.05 means r30gb.

**Comment by fearpro13** [comment]
Maybe it is reasonable to update "Supported cameras" table in README file?

**Comment by roleoroleo** [comment]
> Maybe it is reasonable to update "Supported cameras" table in README file?

Done.
Is there a fw update available for this model (from 9 to 12)?

**Comment by fearpro13** [comment]
Unfortunately i dont know
Could not find any information about this
I think you could close this issue
