### ISSUE TITLE
Menu entries on mobile Web Interface missing 

### ISSUE THREAD

**Issue by maxen0815** [roleoroleo/yi-hack-Allwinner-v2#746]
I'm currently playing a lot with the cameras using my smartphone. Within this I realized that there are two elements missing in the menu:

1. The menu "sandwich" icon is not available when I navigate to the maintenance tab
![Screenshot_20231112_182941](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/4a69d50f-5c21-44a4-bfec-67f218c916b1)

2. The menu names are not visible on smartphone view, since they are just visible by a mouseover (which is not possible on smartphone)
![Screenshot_20231112_182427_edit_723300670432726](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/820219c5-7656-4d94-baab-0e54c302d055)

**Comment by roleoroleo** [comment]
I'm not a good web developer.
Is there anyone who wants to help?

**Comment by maxen0815** [comment]
I found a solution for the missing menu entries in smartphone mode (with some help - thanks ;)

Addd a merge request for the custom.css file which will give us menu titles also on mobile devices
![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/5196fed5-8f48-4408-a1db-f48022a253a0)

**Comment by roleoroleo** [comment]
Merged.
Thanks.
