### ISSUE TITLE
Feature Request: Email notifications for YI-Hack cameras - Integration of script "WalkingDot / yihmail" into Allwinner 2

### ISSUE THREAD

**Issue by maxen0815** [roleoroleo/yi-hack-Allwinner-v2#750]
I accidently found the following script https://github.com/WalkingDot/yihmail which offers the posibility to send email notifications when a motion event is detected.
Wouldn't this be a nice feature being integrated as standard in the Allwinner 2 firmware?

**Comment by maxen0815** [comment]
We would need Yihmail + ipc_multiplexer to get it running. Some file restoring from previous releases will be necessary.

If this will be included I can try to contribute the corresponding web interface for configuration inputs.

**Comment by roleoroleo** [comment]
ipc_multiplexer is no longer present in the current hack version.
The stragedy is changed and the source code of yihmail should be updated.
You should try to ask to WalkingDot.
Sorry but I don't know go language.
