### ISSUE TITLE
Allwinner v2 features - no video record camera still poweron

### ISSUE THREAD

**Issue by weado** [roleoroleo/yi-hack-Allwinner-v2#754]
Hello, 
After using the Yi Hack All Winner v2 tool for a Pi Home 1080p camera, I am looking to disable video recording on demand without turning off the camera because I want to maintain visibility of my home's content even when I am inside without recording video. Do you have any ideas?

**Comment by roleoroleo** [comment]
Configure the cam as below:
![immagine](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39277388/531ab106-4ac5-44b2-ac81-fc566ea44f5a)

**Comment by weado** [comment]
In fact, I would like with Home Assistant to have the camera constantly running, but to activate automatic recording when the camera detects motion.
The configuration you're talking about cannot be changed via MQTT or Yi Hack Home assistant plugin.
Is-it possible to change this option by API ?

**Comment by weado** [comment]
Thank you for your feedback. 
Unfortunately, I cannot modify this option through web services for Home Assistant (https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description#camera-settings) . Do you know how I can proceed?

**Comment by roleoroleo** [comment]
Turn on/off mp4record using web services:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description#service-start-and-stop
