### ISSUE TITLE
Yi Pro 2K Home YFUS 12.0.51 deleting files not working

### ISSUE THREAD

**Issue by isibizi** [roleoroleo/yi-hack-Allwinner-v2#755]
Hello, i have the cam that you can see in the title. Yi-Hack is running and i have some records on the sd. When i try  to delete the files, the files removed from the wui, but when i restart my device, i can see the files again.

**Comment by roleoroleo** [comment]
Probably the file system in your sd card is not ok.
Remove and check it with a PC.
