### ISSUE TITLE
Send command via mqtt

### ISSUE THREAD

**Issue by salvadorAnt** [roleoroleo/yi-hack-Allwinner-v2#759]
go to preset
change some aspects of config

**Comment by roleoroleo** [comment]
Please, explain me better.

**Comment by salvadorAnt** [comment]
In the same way you can recive events, you could publish an event into topic subcribed the camera to look in preset direction, or change some configured values.
ex: mosquito_pub -h 192.168.1.10 -t "yi_cam/command/preset" -m "num_preset" in the same way when you click in "Go to Preset" in the webpage
or: mosquito_pub -h 192.168.1.10 -t "yi_cam/command/cruise_control" -m "none"

**Comment by roleoroleo** [comment]
About configuration, you can use the topic:
%TOPICS_PREFIX%/cmnd/%FILE%
to change all parameters.
For example:
topic: %TOPICS_PREFIX%/cmnd/system/timelapse
payload: yes
switches on timelapse in system.conf
topic: %TOPICS_PREFIX%/cmnd/camera/ir
payload: yes
switches on ir led in camera.conf

About services (like ptz, speak) there is no mqtt command at the moment.
I could try to add this feature but I need time.
Meanwhile you can use web services.

**Comment by salvadorAnt** [comment]
Perfect, I apreciate very much your work!

**Comment by sippeeey** [comment]
this will be awesome. i really hope so. :) Thanks for this great work!!

**Comment by roleoroleo** [comment]
I developed this part but the performance is poor: the delay is big.
Because the chain is too long: mqtt-v4 -> shell script of the web service -> ipc_cmd
At the moment I will publish this feature as is but probably I will need to improve.

**Comment by roleoroleo** [comment]
Meainwhile I will send a beta to test: which model suffix do you have?

**Comment by salvadorAnt** [comment]
I use Dome Guard IFUS - h30ga

Salvador. 

    En miércoles, 6 de diciembre de 2023, 14:55:32 CET, roleo ***@***.***> escribió:  
 
 


Meainwhile I will send a beta to test: which model suffix do you have?

**Comment by roleoroleo** [comment]
Try this beta:
[h30ga_0.3.0.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13625048/h30ga_0.3.0.tar.gz)

**Comment by salvadorAnt** [comment]
Sorry, my fault, this firmware didn't work it, later i use r30gb_0.3.0. Can you send me your beta with that version?

**Comment by roleoroleo** [comment]
[r30gb_0.3.0.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13625051/r30gb_0.3.0.tar.gz)

**Comment by salvadorAnt** [comment]
ok, I've deployed it, how would be the topic?

**Comment by salvadorAnt** [comment]
This version doesn't stream anything
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/46705890/799f8182-a7ac-471b-b6eb-5a18cb4ad253)

**Comment by roleoroleo** [comment]
About configuration files, you can use the topic:
%TOPICS_PREFIX%/cmnd/%FILE%
to change all parameters.
For example:
topic: %TOPICS_PREFIX%/cmnd/system/timelapse
payload: yes
switches on timelapse in system.conf
topic: %TOPICS_PREFIX%/cmnd/camera/ir
payload: yes
switches on ir led in camera.conf

About ptz commands:
topic: %TOPICS_PREFIX%/cmnd/ptz/move
payload: right, left, down, up, stop
%TOPICS_PREFIX%/cmnd/ptz/goto_preset
payload: 0..7
%TOPICS_PREFIX%/cmnd/ptz/add_preset
payload: name
%TOPICS_PREFIX%/cmnd/ptz/set_home_position
payload: NONE (empty)
%TOPICS_PREFIX%/cmnd/ptz/remove_preset
payload: 0..7

**Comment by roleoroleo** [comment]
> This version doesn't stream anything

What do you mean?
Does rtsp work?
Does snapshot work?

**Comment by salvadorAnt** [comment]
neither rstp nor snapshot, which log can i send you?

**Comment by roleoroleo** [comment]
If the stream doesn't work it's probably the wrong version.
Are you sure the cam is a r30gb?

**Comment by salvadorAnt** [comment]
This version gone perfect
[r30gb_0.3.0.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13798909/r30gb_0.3.0.zip)

**Comment by roleoroleo** [comment]
Please, wait for the next release.

**Comment by roleoroleo** [comment]
Try this:
[r30gb_0.3.0.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/13841261/r30gb_0.3.0.tar.gz)

**Comment by EugenEule** [comment]
I have a similar problem. I can read the status of the camera (e.g., IR on or off) via MQTT, and it updates correctly, but I cannot change the status via MQTT. No changes are reflected in the camera. Do I need to configure something differently? I’m using ioBroker with the MQTT Broker adapter, and the camera is running version 0.3.2 Allwinner-v2.”
![Allwinner](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/129485285/0f3be4cd-bef5-420b-b586-b2dbb7e40716)
![iobroker](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/129485285/7f102d67-e928-486d-a4cc-4520bfd4756f)
![camera](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/129485285/3ce41c10-14da-47cc-8961-bdd78f4634e8)
![MQTT](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/129485285/a0c57fda-ab81-445a-9475-04d1da5acb91)

**Comment by EugenEule** [comment]
On the camera web page I activated:
MQTT Camera Settings Advertise
Camera Settings Advertise contain the information of Camera Settings page:
Switch on/off camera, Sound Detection, Status Led, IR Led, Rotate.
Suffix topic: camera_setting

where can I see the payload?
![einstellungen](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/129485285/efefe7e0-d784-4df2-a766-a88e915bb2df)
