### ISSUE TITLE
Bricked yi home  1080p please help

### ISSUE THREAD

**Issue by mazik87** [roleoroleo/yi-hack-Allwinner-v2#763]
Hi. I have a problem with my camera. Unfortunately, from the first start, it does not turn on. Only yellow light.  The camera has been  in the locker for 2 years and today I turned it on for the first time. I've tried to upload the firmware from yi site, But it doesn't do anything.Yellow solid light is on.  Uploading the hack is the same. On the SD card I write the file home_21gam and Hack y21ga_0.3.0.tgz.
 What can I do? 
I don't have any backup. Sorry for my English. Thank you for your help. 
![20231128_211642](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/37815808/39f80016-90e3-4cfd-9c4d-7bcac0987255)
![20231128_212225](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/37815808/9172fa4e-5b3e-4a5b-8b28-7afb396a3473)

**Comment by roleoroleo** [comment]
Are you sure it's a y21ga model?
Are you able to open it and take some picture?

**Comment by mazik87** [comment]
![20231129_191126](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/37815808/9f6ef4e3-7a71-4cf8-892c-84d503bacc13)
![20231129_191208](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/37815808/84910ae7-c5fb-4325-9822-354cd147010f)
![20231129_191237](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/37815808/b59e18f6-90ae-4ce8-891a-802195945934)

**Comment by roleoroleo** [comment]
The label on the pcb says y29ga.
It's not always reliable but you should try y29ga.

**Comment by mazik87** [comment]
Ok. I will try
