### ISSUE TITLE
Camera no longer working, web interface is running fine

### ISSUE THREAD

**Issue by borgqueenx** [roleoroleo/yi-hack-Allwinner-v2#765]
I have a yi dome cam [h51ga] and it does not work anymore for some reason. the yi home app does not connect any longer, but the rtsp stream also does not work. however, the web interface still works.
i tried to use the unbricking method on a fresh VPS debian machine, but it does not flash anything on the device. it simply does nothing after turning around the led goes off and stays idle. putting back the yi hack card, the web menu loads again....but still no yi home app connection or rtsp stream. Already tried resetting the configs in the web interface, also no luck.

here is the generated log on rtsp at the end of the file:
```
 1381 root       892 S    /tmp/sd/yi-hack/bin/dropbearmulti /tmp/sd/yi-hack/sb
 1411 root      1048 S    udhcpc -i wlan0 -b -s /backup/tools/default.script -
 1472 root       980 S    sh -c /home/app/cloudAPI -c 136 -url http://api.eu.x
 1473 root       980 S    {cloudAPI} /bin/sh /home/app/cloudAPI -c 136 -url ht
 1480 root      1132 S    /tmp/sd/yi-hack/bin/cloudAPI_real -c 136 -url http:/
 1492 root       964 S    {ntpd} /tmp/sd/yi-hack/bin/busybox /tmp/sd/yi-hack/u
 1521 root      2868 S<   rRTSPServer -m h51ga -r high -p 554
 1522 root       996 S    {wd_rtsp.sh} /bin/sh /tmp/sd/yi-hack/script/wd_rtsp.
 1558 root       680 S    wsd_simple_server --pid_file /var/run/wsd_simple_ser
 1606 root       964 S    {crond} /tmp/sd/yi-hack/bin/busybox /tmp/sd/yi-hack/
 1865 root         0 Z    [init]
 1915 root       980 R    ps
 1916 root       980 R    killall -q rRTSPServer
```

**Comment by roleoroleo** [comment]
Which mtdblocks do you create with unbrick procedure?
Is the file size correct (similar to the original mtdblock file)?
