### ISSUE TITLE
Which firmware for Yi 1080p Home SFUS 12.2.0.2_202304071306 ?

### ISSUE THREAD

**Issue by ZeVince** [roleoroleo/yi-hack-Allwinner-v2#768]
Hello,

Which firmware file prefix version would work with the Yi 1080p Home SFUS 12.2.0.2_202304071306 ?

Thanks.

**Comment by roleoroleo** [comment]
At the moment is not supported.
Please, try to make a backup and share it with me.
I could try to support it.

**Comment by ZeVince** [comment]
Backup done !
I just dropped it on wetransfer
https://we.tl/t-l9IutvQq7g

**Comment by roleoroleo** [comment]
Your cam is already supported but it's an Allwinner cam: y20ga.
Check here: https://github.com/roleoroleo/yi-hack-Allwinner
