### ISSUE TITLE
FTP stopped randomly after update from 2.5 to 3.0

### ISSUE THREAD

**Issue by uzior** [roleoroleo/yi-hack-Allwinner-v2#769]
I have two y21ga,BFUSY44 cameras which are uploading footage 24/7 to NAS via FTP protocol. 
As I mentioned in the title, after update (2.5 --> 3.0) both are running like allways but every few days they stop uploading.
Every another feature even after stopping remain ok. 
After restart, upload works as usual.

thx for help!

**Comment by roleoroleo** [comment]
When the upload starts to fail, please run the command manually and check the output:
`
/tmp/sd/yi-hack/script/ftppush.sh cron
`
