### ISSUE TITLE
[Support Request] Yi Dome X BFUS 8.1.0.0A - alt hack?

### ISSUE THREAD

**Issue by lukemikeluke** [roleoroleo/yi-hack-Allwinner-v2#770]
Hi there. 
Is there a firmware that can be used to hack YI Dome Camera X - BFUS - 8.1.0.0A_202001211.  There seem to be a problem with this camera even though it's pretty popular, but maybe other firmware can be used and someone has a sucess with it. Thank oyu.

**Comment by roleoroleo** [comment]
Check Allwinner:
https://github.com/roleoroleo/yi-hack-Allwinner

**Comment by lukemikeluke** [comment]
Thank you very much.
