### ISSUE TITLE
ONVIF 2k Pro YFUSY crendtials not accepeted

### ISSUE THREAD

**Issue by isibizi** [roleoroleo/yi-hack-Allwinner-v2#777]
Hello, i have a problem with my 2 cams at the moment. The cams and the webui working well, i can see the stream when i use HomeAssistant and open the rtsp stream directly. The connection over onvif don't working annymore, the credntials not accepted... The credentials working in HomeAssistant but over onvif the credentials are wrong.

**Comment by roleoroleo** [comment]
Please, test the credentials using Onvif Device Manager and check if it works.

**Comment by isibizi** [comment]
OK, i can login with  ODM, but i see the message no signal, i think that is the problem

**Comment by isibizi** [comment]
I use Synology Surveillance Station, the cameras were working with this software. After my NAS crashed, my cameras are no longer being recognized. I have already reset both the cameras and the NAS. I have also changed the passwords and ports. Authentication always fails. Is it possible that there is an IP ban list somewhere in the camera?

**Comment by Marcin685** [comment]
i have 0.3.0 y211ga and not working with HIK VISION RECORDER. I tried with RTSP and ONVIF settings and each time I get the message "establishing a connection" or "cannot download the stream". On HomeAssistant, ONVIF works well, but I would like to record video and sound 24/7, but my DVR does not want to work with this camera.

**Comment by Giuserver** [comment]
if work with other software is not a problem with camera.

**Comment by isibizi** [comment]
ONVIF still not working on my system, i use the rtsp now.

**Comment by Giuserver** [comment]
> ONVIF still not working on my system, i use the rtsp now.

are you in VPN?
are you check with another software in the same network (no VPN)?

**Comment by isibizi** [comment]
No, i don’t use vpn, everything running local in the same subnet.

**Comment by roleoroleo** [comment]
> Authentication always fails. Is it possible that there is an IP ban list somewhere in the camera?

No, there isn't a ban software in the cam.

> i have 0.3.0 y211ga and not working with HIK VISION RECORDER. I tried with RTSP and ONVIF settings and each time I get the message "establishing a connection" or "cannot download the stream". On HomeAssistant, ONVIF works well, but I would like to record video and sound 24/7, but my DVR does not want to work with this camera.

Please, try to capture the network traffic with tcpdump/wireshark and send it to me.

**Comment by roleoroleo** [comment]
> ONVIF still not working on my system, i use the rtsp now.

I tested my onvif server with Synology Surveillance Station (DSM 6.x and 7.x) and it works.
Please, try to capture the network traffic with tcpdump/wireshark and send it to me.
