### ISSUE TITLE
How change prefix?

### ISSUE THREAD

**Issue by gcarabetta** [roleoroleo/yi-hack-Allwinner-v2#778]
Hi, I think I've installed the wrong prefix: on a QFUS with Base Version 12.0.35 I have y211ga Model Suffix .
Seems that the correct prefix is y291ga, so how I can change it?
Can I "just" overwrite the tar content over the actual SD, or I need to do the unbrick procedure?

Thanks

Giulio

**Comment by Giuserver** [comment]
if camera is not brick, just redo the right procedure with a clean sd (format the sd).
