### ISSUE TITLE
Firmware match to RFUSY62CGF04Z8230322

### ISSUE THREAD

**Issue by enzopanzani** [roleoroleo/yi-hack-Allwinner-v2#780]
Hello my friend,
first of all, congratulations for all the work you do to allow tinkerers to get the most out of their camera!
Tell me, do you think this firmware model has a chance of being supported soon?
Thank you for your time and your response.

Camera : Yi 1080p
Model : YYS.2016
RFUSY62CGF04Z8230322
version : 12.0.35.8_202211241029

**Comment by roleoroleo** [comment]
It's supported: y291ga.

**Comment by enzopanzani** [comment]
Hi @roleoroleo 
Thank you very much, it works. I think that I took the wrong version.
