### ISSUE TITLE
RFUS 2023.02: Model supported? 

### ISSUE THREAD

**Issue by aqwserf** [roleoroleo/yi-hack-Allwinner-v2#781]
Hi @roleoroleo!
I have the possibility to buy a Yi Outdoor 1080p, DID `RFUSY595GH0XXN220620` from `2023.02`. It hasn't been unpacked yet so the guy can't tell about the firmware. 
On paper, it looks compatible, but I'd like your opinion. What do you think?
Thanks!

**Comment by aqwserf** [comment]
Oh and I just noticed that it says `ha30ga v1.4`  on the label

**Comment by roleoroleo** [comment]
Without a fw version I can't be sure but probably it's a h30ga.
So it's probably supported.

**Comment by aqwserf** [comment]
Camera received and I confirm the h30ga. Came with firmware 9.0.26 so it should be good.
Thanks for your response @roleoroleo !
