### ISSUE TITLE
Cannot access web interface after removing SD Card.  Camera is online, ping ok.

### ISSUE THREAD

**Issue by lukemikeluke** [roleoroleo/yi-hack-Allwinner-v2#785]
1080 AI+ RFUS running 9.0.19 hacked with y21ga_0.3.0
Hi. Similar to #783 I also have web interface access problem. Cannot access web interface after removing SD card. Camera is online, ping ok.  Other hacked cameras are accessible without SD. (2 x AI+ with BFUS hacked with y20ga and dome x's)

It's a brand new camera.

**Comment by roleoroleo** [comment]
Allwinner-v2 is different from Allwinner and MStar.
The SD card must be inserted.
