### ISSUE TITLE
Just a question: identify correct Dome U

### ISSUE THREAD

**Issue by moklev** [roleoroleo/yi-hack-Allwinner-v2#807]
I have a trouble regard a Dome U model

Product name: Yi Dome camera U
Resolution (max): 1080p
DID: SFUS Y49D WDI3 ***** / **
Production model: YHS.5020
Firmware: 9.0.22.15_2021073001006

Is compatible (or not) with h51ga?

Thanks for your hard work

**Comment by roleoroleo** [comment]
SFUS is new for me, but it should be a h52ga.
Please, try it and let me know if it works.

**Comment by moklev** [comment]
Thanks for you answer. It's a quite recent manifacture: late july 2023.
There's a way to check the h52ga firmware without installing it?

**Comment by roleoroleo** [comment]
Make a backup copy and send it to me.
I will check it.

**Comment by moklev** [comment]
Done
[DUMP Dome Camera U SFUS.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/14043981/DUMP.Dome.Camera.U.SFUS.tar.gz)

**Comment by roleoroleo** [comment]
Confirmed: h52ga.

**Comment by moklev** [comment]
Thank you, I'll test the h52ga build this weekend (and I'll sens you a report)

**Comment by moklev** [comment]
Confirmed! h52ga works!

![Schermata del 2024-01-27 13-08-08](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/157580426/81d06401-f461-4267-b98d-379a21ed8f0a)

**Comment by mkotek** [comment]
I have Dome U Camera as well: SFUSY4...
Came with 9.0.21.13_202109101104
I am running it with h51ga and wonder what is the difference between h51ga and h52ga?

**Comment by roleoroleo** [comment]
If I remember correcly the only difference is the wifi module.
