### ISSUE TITLE
Breaking change in 0.1.4

### ISSUE THREAD

**Issue by roleoroleo** [roleoroleo/yi-hack-Allwinner-v2#81]
I changed the OTA upgrade procedure because there was a bug.
Version 0.1.4 must be installed from scratch, so:

- make a configuration backup
- install 0.1.4 over 0.1.3
- restore the configuration

**Comment by ultrara1n** [comment]
"From scratch" means the initial "copy stuff to microSD" card process?

**Comment by roleoroleo** [comment]
Yes.

**Comment by syb3ria** [comment]
I used the browser update and it worked just fine? Now says Installed: 0.1.4 - Available: 0.1.4. Should I redo it manually or it's fine this way?

**Comment by roleoroleo** [comment]
You need to update manually.

**Comment by syb3ria** [comment]
Ok, thanks.
