### ISSUE TITLE
Question: Set IP-address

### ISSUE THREAD

**Issue by myhobby2** [roleoroleo/yi-hack-Allwinner-v2#811]
Default the IP-address is assigned by the DHCP server on the network. Tried to set that via my Fritzbox 7490 to a fixed IP address, but so far no success. 

Question: Is it possible to set an IP address manually via a camera configuration ?

**Comment by roleoroleo** [comment]
This is an old question, maybe never solved.
The network connection is handled by Yi processes and it's not simple to intercept the scripts to set an IP address.

You could try to add the following lines at the end of /tmp/sd/yi-hack/script/wifidhcp.sh

```
ifconfig wlan0 YOUR_IP netmask YOUR_NETMASK
route add -net 0.0.0.0 gw YOUR_GATEWAY
```

**Comment by myhobby2** [comment]
Super, I was able to change the IP address the way you advised. Great help! Thanks.

**Comment by roleoroleo** [comment]
Please, test it a couple of days.
If it works, I can add this feature to the hack.

**Comment by myhobby2** [comment]
I will test it and come back on this with 1 and 2 weeks ;-)

**Comment by myhobby2** [comment]
So far so good. Few reboots, new router firmware.... no issues. I think I can be added to setting for the web-interface

**Comment by myhobby2** [comment]
Come back on this... I'm not completely convinced ;-) Although I did set my camera to a fixed IP and even checked it, this afternoon it has a new IP address.. No power issues or reboot done. 

Is there a job running trying to do a dhcp handshake after a defined time ?

**Comment by roleoroleo** [comment]
Check my last commits.
I think I found a final solution.

**Comment by myhobby2** [comment]
I'm too incompetent to check this Can read a bit of code, but I can't find the commits on github online or in github desktop ;-) Any advice what I should do (I think a fresh download of your solution) ?

**Comment by myhobby2** [comment]
I found the commits ;-) Learning every day

**Comment by roleoroleo** [comment]
What's your model?
