### ISSUE TITLE
Online FW update

### ISSUE THREAD

**Issue by mspinolo** [roleoroleo/yi-hack-Allwinner-v2#815]
Hi,

for some reason I can't update anymore my cameras using the built in online update.
I have different cameras in different houses, some on 0.26, some on 0.30 FW and all show the same behavior.

Any hint to sort this out?
I would like to avoid the manual update procedure...

**Comment by alsar** [comment]
For me it also didn't work on v0.3.0 and had to update it manually.
Now it is possible on v0.3.1

**Comment by mspinolo** [comment]
yes I saw the manual procedure but some of my cameras are not super comfortable to reach, hence asking if there is a way to make it work again or upload the file remotely to the sd card

**Comment by roleoroleo** [comment]
You can start the manual procedure remotely.
Rename the file, copy it via ftp and restart.

**Comment by dreimer1986** [comment]
Same problem on two y211ga that were on 0.3.0. Fixed by enabling ftp and logging in with root:pwd. Moved file, disabled ftp, rebooted and then cliked on Firmware Update button. Both fine now.

**Comment by maakdan** [comment]
I was trying to upgrade from 0.2.7 to 0.3.1 via OTA, it failed several times but at the end I could upgrade it by trying it again and again.
