### ISSUE TITLE
Bootloop Yi IoT

### ISSUE THREAD

**Issue by f-mns** [roleoroleo/yi-hack-Allwinner-v2#820]
Hello,
I've recently purchased an chinese camera from aliexpress, which works only with the Yi IoT. I tried all the yi-hacks, but none worked for me. Only the Allwinner v1 & v2 create a bootloop so im guessing it listens to the "Factory" folder, but im not sure. I tried multiple SD cards with no luck the infrared turns on and as soon as it turns off normaly a sound should play and the usual calibration starts, but then after 2 seconds the infrared goes back on. 

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/78693466/ba68f877-1d81-4270-8b07-e047beab5324)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/78693466/f466d1d9-7747-455e-a016-de457e28625c)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/78693466/66c6bd56-9215-4bbb-98b1-2201b7ce6421)

**Comment by roleoroleo** [comment]
From the picture the chip seems an Anyka.
It's not compatible with this hack.
Try to make a backup following the wiki and I will check it.

**Comment by f-mns** [comment]
So the backup won't create. The camera has a long boot time and then its rebooting without creating a backup, but i tried removing the "reboot" line in the config file and then the infrared keeps on and it won't reboot. So its reading the file. could the /tmp/sd directory be another on that camera?

**Comment by f-mns** [comment]
Btw the DEBUG_LOG function also won't work.

**Comment by roleoroleo** [comment]
Ok, we should try a minimal hack to dump the flash:
add the command `telnetd `at the end of the file and try to enter with a telnet session.
If we are lucky telnetd is present in the cam and root user uses a blank password.

**Comment by f-mns** [comment]
The camerea has no ethernet, so it needs to connect via wifi first, but how? With the config.sh this won't work.

**Comment by roleoroleo** [comment]
Are you able to configure wifi thruogh the app?

**Comment by f-mns** [comment]
Yes, the camera works perfectly fine with the app, but when I run anything in the "Factory" folder it's not doing anything (just running the config.sh i guess).

**Comment by roleoroleo** [comment]
When the boot scripts finds the Factory folder changes the boot process.
It's not easy to start the wifi: load modules, run wpa...

Another try. Allwinners cam run another script at the end of the boot.

tmp/sd/debug.sh

Maybe...
Try to create debug.sh file into your sd and run telnetd from here.
The wifi connection should start normally.

**Comment by f-mns** [comment]
Now it's turning on working normally but all ports are still closed (including telnet)

**Comment by roleoroleo** [comment]
The hard way?!?
Are you able to connect a serial adapter to the uart?

**Comment by roleoroleo** [comment]
> The main problem with the yi-hack is that it‘s expecting /tmp/sd to be the moutpoint of the sd card, which in my case is just /mnt. Is there a way I could just change this directory so the yi-hack could work for me or is the entire code based on that directory?

You could try to create a symlink or a blind mount.
