### ISSUE TITLE
Which firmware should I use for YI Kami 1080p Model: YWS

### ISSUE THREAD

**Issue by miloit** [roleoroleo/yi-hack-Allwinner-v2#825]
Hello I have a YI Kami 1080p did number BFUSY27BBV Model YWS which firmware file shoul i use?

**Comment by roleoroleo** [comment]
Which firmware version is there in the app?

**Comment by miloit** [comment]
It's 5.1.0.0A_202105261538

**Comment by roleoroleo** [comment]
I don't know this firmware version.
Please, try to make a backup.

**Comment by miloit** [comment]
How can I do a backup?


Should I send it then to you?

**Comment by roleoroleo** [comment]
> How can I do a backup?

Check the wiki.

> Should I send it then to you?

You can share it here. If you have not configured the cam with the app, the backup will not contain any personal data.
