### ISSUE TITLE
[Question] Video filenames

### ISSUE THREAD

**Issue by Rushmed** [roleoroleo/yi-hack-Allwinner-v2#826]
Hi,

I am uploading all video files via FTP to my homeserver. As I don`t want subdirectorys I disabled "Create directory tree". The files are named "ExxxMxxSSxx.mp4".
SS seems to be the videolength in seconds but what does E and M mean and how to sort the videoclips correctly in a file explorer?

**Comment by roleoroleo** [comment]
E123M45S67.mp4
- E1 it's not clear, probably it's the type of detection that started the record
- 23 is the starting minute
- 45 is the starting second
- 67 is the length
Normally, in this world 45 + 67 = 60 :)
If you don't use "Create directory tree" there is a risk that 2 files have the same name.

**Comment by Rushmed** [comment]
OK, thanks for explaination.
