### ISSUE TITLE
Disabling the  IR led for night vision is not working

### ISSUE THREAD

**Issue by johol** [roleoroleo/yi-hack-Allwinner-v2#827]
Deselecting IR led is not working.
The switch is off, but i hear the relay clicking and the led is turned on when it gets dark.

Base Version 	12.0.35.8_202211241029
Model Suffix 	y291ga
Firmware Version 	0.3.1

**Comment by roleoroleo** [comment]
Does it work if you configure the IR led with the app?

**Comment by Reiju** [comment]
Hello, I was experiencing the same issue with 0.3.1 and now with 0.3.2. 
When "IR led" is OFF camera is cooreclty not turning ON IR led's but still flipping IR filter. 
This is very annoying for my sleeping kind in the same room.
