### ISSUE TITLE
Yi cam bricked... I kindly ask for a backup (I don't have any)

### ISSUE THREAD

**Issue by dentex** [roleoroleo/yi-hack-Allwinner-v2#829]
Yes, I'm an idiot, I didn't do a backup. I flashed the wrong hack assuming the cam was like the other two I have.
This one should be a y21ga instead.

Does anyone have a backup so I can unbrick the camera?

Many thanks.
![photo_2024-02-27_20-06-05](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/2931982/1cff8d63-5f31-44b3-a850-9def9dfcb689)

**Comment by roleoroleo** [comment]
If you flashed a recent version, you should find a backup in the sd card.
The hack procedure creates a backup.

**Comment by dentex** [comment]
Thanks for letting me know, but I wiped the sdcard trying to flash stock firmware or again the hack (which didn't work).

**Comment by roleoroleo** [comment]
This is for y21ga:
[mtdblock4.bin.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/14461359/mtdblock4.bin.gz)

**Comment by dentex** [comment]
Thanks @roleoroleo ❤️

**Comment by roleoroleo** [comment]
If this method doesn't work, probably it's not a y21ga.
You could try to open it and read the label on the pcb.
Maybe we can find the right model.

But, don't trow it away!!!

**Comment by dentex** [comment]
> If this method doesn't work, probably it's not a y21ga. You could try to open it and read the label on the pcb. Maybe we can find the right model.
> 
> But, don't trow it away!!!

Thanks @roleoroleo for the help, really appreciated. I didn't throw it away :) the online store has been nice enough to accept it returned ;)
