### ISSUE TITLE
problem with RFUSY v.9.0.19

### ISSUE THREAD

**Issue by ironhide9090** [roleoroleo/yi-hack-Allwinner-v2#833]
Hi everyone, I have a "YI Home camera 1080p" camera with firmware 9.0.19.12_202102241808 model RFUSY44, dismantling the camera on the card it says "Y29GA_MB_V2.1 2020/04/07". I tried to install the y211ga, y28ga, y29ga versions. they all work until I restart them and then they no longer connect to the wifi, they flash blue and I have to completely reset them. Can anyone tell me which version is right for this camera? Thank you

**Comment by roleoroleo** [comment]
y21ga

**Comment by ironhide9090** [comment]
same thing with this version, it works until I turn off the power.
I have 4 cameras like this and on all of them it is the same faulty

**Comment by roleoroleo** [comment]
What's the content of the sd card after you apply the hack?

**Comment by ironhide9090** [comment]
I have attached all the contents of the SD.
Thanks
[SD.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/14551187/SD.zip)

**Comment by ironhide9090** [comment]
today I tried the "y21ga_0.3.0" version and it works even after removing the voltage

**Comment by roleoroleo** [comment]
Probably a race condition.
Not simple to fix it.
rmm process doesn't start and the watchdog restart the cam.
Could you try with another sd card?

**Comment by ironhide9090** [comment]
I tried with a new SD card. everything works except enabling the "Enable/disable time OSD", you were very kind, thank you!!

**Comment by roleoroleo** [comment]
So, when you enable "Time OSD" and reboot the cam doesn't restart.
Correct?

What's the behavior? Is the cam in bootloop (reboot continuously) or not?
What color is the led?

**Comment by ironhide9090** [comment]
Yes, exactly, the problem appears when I enable "Time OSD", if you restart from the web page it works fine, but if I turn it off and on by unplugging the power it no longer connects to the wifi (the LED is blue and flashes) and you are forced to perform the reset from the button. Today I also tried with version 0.3.1 with a new SD and it has the same problem

**Comment by roleoroleo** [comment]
If the blue led flashes, the cam didn't save the wifi credentials.
Try to pair the cam without the sd card.
When the cam is paired reboot it 2 or 3 times.
If it works, insert again the sd card.

**Comment by ironhide9090** [comment]
I tried to do as you told me, the problem remains, it works fine until I activate "time OSD". for me there are no problems. maybe others might know too.

**Comment by roleoroleo** [comment]
Try to switch off "Time OSD".
Does the cam restart?

You need to remove the card and edit manually the file yi-hack/etc/system.conf

**Comment by ironhide9090** [comment]
Today to do the test the cam restarted by disabling "time OSD"! I tried on all the cameras, I can't give an explanation, could it be that it takes time to save the wifi credentials?

**Comment by roleoroleo** [comment]
> Today to do the test the cam restarted by disabling "time OSD"! I tried on all the cameras, I can't give an explanation, could it be that it takes time to save the wifi credentials?

I think it's not possible. But I don't understand the problem.
Is swap enabled?
Maybe a memory issue...

**Comment by bulletyhasor** [comment]
FYI: see [my issue related with bad reboot and wifi SSID](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/855#issue-2231788599)
