### ISSUE TITLE
Camera aus bzw. einschalten über Webinterface

### ISSUE THREAD

**Issue by biker1602** [roleoroleo/yi-hack-Allwinner-v2#836]
Hallo
Gibt ees die Möglichkeit so wie in der App Yi Home die Camera über das Webinterface mit einem Befehl aus bzw. wieder einzuschalten? Ich habe den Adapter onvif im Iobroker installiert aber dort auch leider nichts gefunden. Ich wollte über ein Blockly realisieren die Camera beim verlassen des Hauses wenn sich z.B. die Handys aus dem Wlan abgemeldet haben das die Kameras sich ein und beim anmelden im Wlan wieder ausschalten.

**Comment by roleoroleo** [comment]
Check the wiki:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description

Another way is mqtt.

**Comment by biker1602** [comment]
Das habe ich wohl gelesen aber welcher Befehl soll denn da für Kamera ausschalten bzw einschalten sein. Ich rede nicht von Video aus ein. Im Webinterface gibt es auch keinen Schalter so wie in der App.

![Screenshot_20240313-084213](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/85706081/9e1fa45c-9de5-49c1-8724-6f9d0389344d)

**Comment by roleoroleo** [comment]
You can't really switch off the cam. The switch in the app simply switch off the video.
The same behavior has the switch in the web page or the webservice:
`http://IP_CAM/cgi-bin/camera_settings.sh?switch_on=no`
All three call the same internal ipc command.
