### ISSUE TITLE
What cameras has highest chance to be working with Yi-Hack in 2024?

### ISSUE THREAD

**Issue by wekii** [roleoroleo/yi-hack-Allwinner-v2#837]
I would like to buy camera that can run Yi-Hack, but I can not check their serial number because I will order them online.
What camera has highest chance to be working with Yi-Hack in 2024?
I hate cloud based cameras, I only want IP wireless camera, that's why I would like to have Yi-Hack on camera.

**Comment by EEtinkerer** [comment]
ive had extraordinary luck with the dome guards, i have 31 with allwinnerv2 and two yi home pro 2k. only had a problem on 2 dome guards, first one was drunken user created problems, second tbd.
