### ISSUE TITLE
Random reboot with 0.1.4

### ISSUE THREAD

**Issue by sro2000** [roleoroleo/yi-hack-Allwinner-v2#84]
Hi,
Facing random reboots with 0.1.4/r30gb as soon as I access my camera with any ONVIF compatible apps (Android or Windows). No problem through RTSP however.
Thanks

**Comment by roleoroleo** [comment]
Check if the problem is the snapshot, for example through the web interface.

**Comment by sro2000** [comment]
Yes, seems to be. When I open the Snapshot tab, I can see a fresh snapshot and then the camera reboots itself. No problem however on the PTZ tab.

**Comment by roleoroleo** [comment]
It's a know issue: low memory.
Enable swap space.

**Comment by sro2000** [comment]
Thank you, it works. My bad, I desactivated the swap space in 0.1.4 and didn't think it could be the reason. Sorry for wasting your time !

**Comment by roleoroleo** [comment]
No problem.

**Comment by huntz** [comment]
It would be nice to indicate this configuration change in README.md, so new users would be aware of it

**Comment by roleoroleo** [comment]
This isn't a configuration change.
Swap space problem is here from the beginning.
But I could add a note in the readme.
