### ISSUE TITLE
Problem with Surveillance Station and firmware version 0.3.1

### ISSUE THREAD

**Issue by cvc90** [roleoroleo/yi-hack-Allwinner-v2#843]
Hello,

I have the same problem that is mentioned here [Issue 816](https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/816), my camera as you can see is an h60ga, could you send me the new version with new ONVIF configuration options? Thanks

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/ee4119ce-d909-4276-9c9a-f88409fc9357)

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/00e8b4a8-d0bd-48ad-a90f-f1db1beb635c)

**Comment by roleoroleo** [comment]
Here it is:
[h60ga_0.3.1.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/14670814/h60ga_0.3.1.tar.gz)

**Comment by cvc90** [comment]
Thanks, as soon as I try it I'll comment.

**Comment by cvc90** [comment]
Hi @roleoroleo,

I have carried out several tests that I will explain to you

### **Option 1** 

With both options disabled, it works but still gives an error when performing the connection test.

![imaginario](https://private-user-images.githubusercontent.com/39277388/314630777-0865766d-4e67-46ed-9feb-24b79609360f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDEzMzksIm5iZiI6MTcxMTA0MTAzOSwicGF0aCI6Ii8zOTI3NzM4OC8zMTQ2MzA3NzctMDg2NTc2NmQtNGU2Ny00NmVkLTlmZWItMjRiNzk2MDkzNjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE3MTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMzU2ZWY1MGRkMWEyOTRmOWI3NGY4OTllNTNjMDE4Mjg5ZTMwOTljOGUxYTExMjM0ZDM4Mjg2ZDcyYWY4MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hhhjJd5E3U8Autx76Oez34heu-lFY1BwiNB0yPnuLsA)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/f7b01319-450b-488e-bfac-7f32cf990b5b)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/00e8b4a8-d0bd-48ad-a90f-f1db1beb635c)

### **Option 2** 

With the "Fault response if unknown request" option activated, it does not work and still fails when performing the connection test.

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/1b25752d-88cb-4dd5-af9a-82834e4f1452)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/d177531a-958e-44b2-80ec-2b23ce44a914)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/00e8b4a8-d0bd-48ad-a90f-f1db1beb635c)

### **Option 3** 

With the "Synology NVR compatibility" option activated, it works and still gives an error when performing the connection test.

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/09fcd656-d52d-4113-8498-7772a136b5d9)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/5399ea5a-7277-4131-87e3-67d4a1855f11)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/00e8b4a8-d0bd-48ad-a90f-f1db1beb635c)

### **Option 4** 

With both options activated, it works and still gives an error when performing the connection test.

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/7cf2510b-b930-466a-8d43-2317dc820757)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/8e5a6b82-57e4-45bc-828f-57b1b30b3bf3)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/00e8b4a8-d0bd-48ad-a90f-f1db1beb635c)

**Comment by roleoroleo** [comment]
So, options 1, 3 and 4 have the same behavior.
Please send me a network capture during the connection test, if you can.

About resolution, the reason is simple, I will fix it.
You can try it manually editing the file /tmp/onvif_simple_server.conf

**Comment by cvc90** [comment]
Could you give me details of how you want me to perform the network capture? Activating the log? Wireshark?

I have made the modification of profile 0 in the file /tmp/onvif_simple_server.conf

width=2304
height=1296

But when I restart the camera, the modification is lost again and I can't check if it works.

**Comment by cvc90** [comment]
Okay, as soon as I can I'll send you the network capture.

I have modified profile 0 in the /tmp/onvif_simple_server.conf file and it did not seem to do anything without restarting, but I let it pass for a while and when it reloaded the new configuration as you can see in the image, but it loads it with 10 FPS by default but I can change it to 20 and everything seems to work correctly

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/7a5f439c-44d6-4554-b720-f22e714b498c)
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/76731844/c67aceaf-51e4-437f-8c75-0db85b5de0d6)

**Comment by roleoroleo** [comment]
Framerate  is not reported by the cam with this onvif server.
Set it client side.

**Comment by mibanezsm** [comment]
It seems that Synology Surveillance Station makes a second call to the CreateProfile method without Authentication data, the Onvif server correctly returns (according to the documentation) the NotAuthorized error and Synology understands this response as an authentication failure (screenshots shown on issue).

![image](https://github.com/user-attachments/assets/7f1ac4bf-a0ef-488a-b5c5-1fb0e6dbb96f)

[capture-filtered.pcap.gz](https://github.com/user-attachments/files/16439855/capture-filtered.pcap.gz)

It seems a bug specific to Synology Surveillance (at least version 9.2). It can be fixed by allowing the CreateProfile method (an ACTUATE class) to be called without authentication data.

![image](https://github.com/user-attachments/assets/98fe51ba-d205-472d-b6c2-cd2b29ce1d98)

... this is a bit outside the specifications, but it works.

![image](https://github.com/user-attachments/assets/42481b3d-b4b9-4aa5-9b03-42db8cc1f31a)

[capture-fix-filtered.pcap.gz](https://github.com/user-attachments/files/16440187/capture-fix-filtered.pcap.gz)

Thanks for all :)

**Comment by roleoroleo** [comment]
It's nor smart but I will add this patch to the code.
Thanks.
