### ISSUE TITLE
Kameras sind nicht mehr funktional wenn sie länger nicht mehr lief

### ISSUE THREAD

**Issue by Kenny-BC** [roleoroleo/yi-hack-Allwinner-v2#844]
Hi zusammen,
ich habe 3 Y21GA (9.0.19) welche ich nur gelegentlich benötige. Nun ist es mir wiederholt aufgefallen, dass wenn ich sie nach mehreren Monaten anschließe, nur vorne eine gelbe LED leuchtet, aber sonst nichts passiert. 
Die Daten sind aber auf der SD Karte noch ganz normal vorhanden. 

Jetzt müsste ich alles wieder von vorne flashen. Es geht auch nicht nach der Anleitung, dass ich hier in der  configure_wifi.cfg meine WLan Daten eintrage. 

Somit über die org. App alles einrichten und dann anschließend alle arbeiten ausführen. Kann mir jemand erklären wieso das so ist, bzw. wie man das umgehen kann?

**Comment by roleoroleo** [comment]
If all cams don't work in the same manner, probably the problem is somewhere else.
Check the power supply and the cable.

Otherwise, follow the unbrick procedure described in the wiki.
