### ISSUE TITLE
motion detection settings

### ISSUE THREAD

**Issue by TungstenE2** [roleoroleo/yi-hack-Allwinner-v2#847]
Hi all,

seems motion dection settings are nor working consistent.

I have 4 cams and I have same settings for all of them, but they act different.

I seems that motion detection and video recording is enabled, although I thought I disabled it.

On 1 cam it is not recording and no listing in motion events, but in 3 other cams it is still recording.

![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39955685/320b3799-8cfe-4a67-a8d5-c698ea5d84e4)

Who can check and give advice?

thx

**Comment by roleoroleo** [comment]
Same model?
Please start from a clean configuration: remove the sdcard and try the cams with the original app.

**Comment by TungstenE2** [comment]
2x 1080P Home using - y291ga - 0.3.1
for one it is working, for other not


2x 2K Pro Home using - y623 - 0.3.1
for both not working (recording all the time)
