### ISSUE TITLE
y21ga 0.1.4 sound issue

### ISSUE THREAD

**Issue by mcanteri** [roleoroleo/yi-hack-Allwinner-v2#85]
I've enabled the sound detection in the config page and saved, but after a reboot the switch is off.
I have two cams and both have same behaviour.

**Comment by roleoroleo** [comment]
Did you clear the cache of your browser?
I recently changed the js code.

**Comment by mcanteri** [comment]
I didn't know, now it is working :+1:

**Comment by roleoroleo** [comment]
Fixed:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/b74055d7600d98f2da0692c71cfab99e8ca31d93
