### ISSUE TITLE
y29ga - snapshot problems

### ISSUE THREAD

**Issue by alienatedsec** [roleoroleo/yi-hack-Allwinner-v2#851]
A low-res snapshot is fine, it's just the high-res with issues.
Swap enabled

```
Firmware Version | 0.3.1
Base Version | 9.0.19.02_202007141512
Model Suffix | y29ga
Serial Number | IFUS.....
```

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/73167064/95dec9b8-0c90-4067-ac99-cad1fdaf62ae)

**Comment by roleoroleo** [comment]
The watermark in the lower-right corner means that the process completed successfully and the problem is the source stream.
Does high res stream work?

**Comment by alienatedsec** [comment]
> Does high res stream work?

Yes

**Comment by roleoroleo** [comment]
What's the resolution of the cam?

**Comment by alienatedsec** [comment]
> What's the resolution of the cam?

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/73167064/ff57b52f-91af-4ea1-802d-d8d743ec32ec)

**Comment by alienatedsec** [comment]
Works Perfect - thank you
