### ISSUE TITLE
Error with FW0.3.1 (y211ga) and Syno surveillance station

### ISSUE THREAD

**Issue by scfrancis** [roleoroleo/yi-hack-Allwinner-v2#856]
Hello everyone,
I have the same problem as some. Unable to authenticate ONVIF on Synologie NVR.
Is it possible to have a patch please?
Thank you so much

**Comment by Dmario-dev** [comment]
HI,
The same problem is with 
Yi Dome Camera U (2K)	BFUS - SFUS	9.0.21*	h51ga

All other apps are working with ONVIF, just not Synology SS

Any workaround for this?
Can I help some how? Do you need logs?

**Comment by roleoroleo** [comment]
Please wait for the next release.
It's coming.

**Comment by mibanezsm** [comment]
Sorry, recently commented this on closed Issue.

@roleoroleo you can get tcp dumps on https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/843#issuecomment-2260229335
