### ISSUE TITLE
Manual time not sticking after reboot

### ISSUE THREAD

**Issue by gne5** [roleoroleo/yi-hack-Allwinner-v2#857]
Wondering if this can be changed to not reset after a reboot?

If the camera is not connected to the internet and I set the date & time via telnet with: [date -s "YYYY-MM-DD HH:MM:SS"] then it resets after reboot. And I get random reboots sometimes when it switches to and from IR night mode.

I tried enabling my router to act as a NTP time server and changed the address in the camera settings to the router IP but still no auto timing.

y21ga - v0.3.1

**Comment by roleoroleo** [comment]
The cam has no battery and it's not able to keep the time after a reboot.
But, with ntp it should work.
Are you sure your ntp is working properly?

**Comment by gne5** [comment]
It was an error in my routing, my bad. It's working now from the routers NTP server.

Thanks for the work. One small request is to add batch delete for videos.

**Comment by roleoroleo** [comment]
> One small request is to add batch delete for videos.

There are 2 methods for this:
- configure a free space value
![immagine](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39277388/0a84c5fb-c3f5-4bd6-a190-e15a86e03393)
- use the web service https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description#delete-directories
