### ISSUE TITLE
several change requests for recording settings

### ISSUE THREAD

**Issue by TungstenE2** [roleoroleo/yi-hack-Allwinner-v2#862]
Thx a lot for all the work you put into this project.

Using your hack now on several Yi cams, I found some topics for improvment, in order to make UI more intuative and user friendly.

Using:  v0.3.2, h52ga, SFUS

**Configuration/General:**
- move 'Recording without Cloud' to Page Camera Settings, in order to have all recording parameters on one page

**Camera Settings:**
- have one section only for recoding
- clearly make difference between local and Yi plan settings
- 'Recording without Cloud' and 'Save video when a motion is detected' have dependencies, clearly state, how they are interacting
- 'Motion Detection' remove this line, but have better explantion as listed before
- 'Detection sensitivity' did several tests and seems like there is nor difference if settings are set to High, Medium or Low. Motion is recorded all the time, even for just small wind detected. Even checked live status via MQTT. Would be good to have Low to only detection motion of really large objetcs. Currently low is still very sensitive.

**Events:**
- please rename this page just to 'Recordings' and change the description as well. Depending on the settings all recordings are listet here, not only for motion detected.
- 'Auto video cleaning' should be moved to 'Configuration' page
- 'Events time' should be renamed to 'Recording time' and moved to 'Camera Settings' section for recording, if this setting has impact on the file name for recording
- 'Events FTP Upload' should  should be renamed to 'Recording FTP Upload' and moved to 'Camera Settings' section for recording or  'Configuration' page
- 'FTP Options'  should be moved to 'Configuration' page

**Comment by roleoroleo** [comment]
In general, I agree with you.
The web gui needs a refactor.

About some specific point:

> **Configuration/General:**
> 
>     * move 'Recording without Cloud' to Page Camera Settings, in order to have all recording parameters on one page

Camera Settings is a "copy" of some functions contained in the app. This is why I added them to a different page.
The idea is: "Configuration" page is the page where you configure the hack settings and "Camera settings" page is the page where you configure factory options.
But we can move them, no problem.

> **Camera Settings:**
> 
>     * 'Motion Detection' remove this line, but have better explantion as listed before
> 

This line depends on the cam. With fw 12 the switch is working.

>     * 'Detection sensitivity' did several tests and seems like there is nor difference if settings are set to High, Medium or Low. Motion is recorded all the time, even for just small wind detected. Even checked live status via MQTT. Would be good to have Low to only detection motion of really large objetcs. Currently low is still very sensitive.
> 

This line is a copy of the corresponding switch in the app.

What do you think about a PR?
Are you able to develop the web gui?
