### ISSUE TITLE
MQTT feature request

### ISSUE THREAD

**Issue by TungstenE2** [roleoroleo/yi-hack-Allwinner-v2#865]
Using:  v0.3.2, h52ga, SFUS

Make option to disable 'motion_detection_image' sent to topic

**Comment by roleoroleo** [comment]
Do you mean through mqtt message?

**Comment by TungstenE2** [comment]
no, I mean in MQTT settings page, to have option to send raw image (yes/no)

![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39955685/bd221096-fe00-464b-9c8f-a26c5f02b492)

**Comment by roleoroleo** [comment]
In this case, empty means disabled.
I will add a label to describe this feature.
