### ISSUE TITLE
motion detection recording duration

### ISSUE THREAD

**Issue by TungstenE2** [roleoroleo/yi-hack-Allwinner-v2#866]
Using:  v0.3.2, h52ga, SFUS

I have some recorded videos, triggered by motion detection, that stop after 8 sec, while person still moving in video, while other videos still record 50 sec, after person left the video already.

Would be nice to have an option to set max recording duration, after motion was detected.

**Comment by roleoroleo** [comment]
Sorry but this feature is handled directly by Yi processes and I can't change it.
