### ISSUE TITLE
Dome Guard 2K, Supported? all info included

### ISSUE THREAD

**Issue by EEtinkerer** [roleoroleo/yi-hack-Allwinner-v2#870]
Yi 2k Pet Camera (Dome Guard)
Model; YRS.3521
S/N Prefix: RFUS
F/W Ver: 12.1.47.02_202310111243

Flash of r35gb 0.3.0 and 0.3.1 didnt take. feel like Im wearing my luck thin on my first brick, so i thought Id ask if this model supported yet. 

Yi Cam 34 for my set up, only the second one Ive run in to problems with. 

[backup.zip](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/15149534/backup.zip)

**Comment by roleoroleo** [comment]
r35gb should work.
