### ISSUE TITLE
y21ga camera issues

### ISSUE THREAD

**Issue by poseidogithub** [roleoroleo/yi-hack-Allwinner-v2#871]
Hello, 

I have this camera: 

y29ga_mb_v2.1
2020/04/07
realtek 8189ftv k91ky31 gkj9c
winband 25064jvsiq 2026

![Imagen de WhatsApp 2024-04-30 a las 19 42 13_b114b5d6](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/65620538/4f321939-6931-4a85-a5dc-eb6391dfcd74)
![Imagen de WhatsApp 2024-04-30 a las 19 42 31_2d6b6a65](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/65620538/33622dd1-569d-46f8-a419-8c54dc170cf4)
![Imagen de WhatsApp 2024-04-30 a las 19 41 59_4655be61](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/65620538/5e66e91b-6e2d-4fbc-891e-d295f0c9cf2e)

(same pcb except for the type of antenna to  https://github.com/roleoroleo/yi-hack-MStar/issues/331 thanks @marcel89l :) ) 

according to the post, I should use this firmware: https://github.com/roleoroleo/yi-hack-Allwinner-v2 and y21ga  version.

According to the instructions, I should download it from release page, so I donwload this: https://github.com/roleoroleo/yi-hack-Allwinner-v2/releases/download/0.2.6/y21ga_0.2.6.tgz
I do a format on FAT32 of a 8gb sd card, copy the files to the sdcard and first issue... according to the instructions I should have a configure_wifi.cfg.ori  on the Factory folder: 

4 _(Optional) If you want to set wifi credentials, rename the file Factory/configure_wifi.cfg.ori to Factory/configure_wifi.cfg and edit the file with your username and password._

but on that folder I only have config.sh and factory_test.sh

anyhow... I go ahead and I put the card on my brand new camera and I only get a "Welcome to Yi Home camera" audio message and then... "waiting to connect" audio message multiple times...

I´ve tried a couple of different SD cards

what I'm doing wrong?

thanks!

**Comment by sebastianha** [comment]
I had the same problem after I pressed the reset button on the camera. The hack was still installed but the WiFi credentials no longer available. As the hack was still active on the camera it did not re-install it and therefore did not re-configure wifi.

For me it helped to "unbrick" the camera, so to reset it to factory and then start all over with the hack.

**Comment by poseidogithub** [comment]
Tha la, but that's not exactly my problem, I can not install the hack on
the first place ..

**Comment by sebastianha** [comment]
The "hack" is a small modification in the original firmware of the camera. If this is in place the wifi connect procedure is not being executed when I understand the code correctly. So when at some point the hack has been installed with wrong wifi credentials it will not fix this.

Try the following: copy the hack to the SD card and change name + edit the wifi config. Then edit the "config.sh" script, add the following lines *before* "### Disable the hack for next reboot"

```
    ### Set wireless credentials if configure_wifi.cfg exists
    if [ -e /tmp/sd/Factory/configure_wifi.cfg ]; then
        /tmp/sd/Factory/configure_wifi.sh
    fi
```
(copied from above)

This will make sure your wifi will definitely be configured. The file should look something like:

```
[...]
    cp /tmp/init.sh /backup/init.sh
    rm /tmp/init.sh

    ### Set wireless credentials if configure_wifi.cfg exists
    if [ -e /tmp/sd/Factory/configure_wifi.cfg ]; then
        /tmp/sd/Factory/configure_wifi.sh
    fi
fi

### Set wireless credentials if configure_wifi.cfg exists
if [ -e /tmp/sd/Factory/configure_wifi.cfg ]; then
    /tmp/sd/Factory/configure_wifi.sh
fi

### Disable the hack for next reboot
echo "### Disabling hack for next reboot"
if [ -e /tmp/sd/Factory.done ]; then
    rm -rf /tmp/sd/Factory.done
fi
if [ -e /tmp/sd/Factory ]; then
    mv /tmp/sd/Factory /tmp/sd/Factory.done
fi

sync
sync
sync

reboot
```

**Comment by roleoroleo** [comment]
In addition to the problem reported by @sebastianha 

@poseidogithub
To choose the correct version of the hack, you need the Yi fw version.
According to your information I don't know which model is. Probably a y29ga but you need to check the Yi fw version,
