### ISSUE TITLE
Upgraded To Home Assistant Core 2024.5.0 Has Broken yi-hack Integration

### ISSUE THREAD

**Issue by yenney** [roleoroleo/yi-hack-Allwinner-v2#872]
Hello,

I upgraded to Home Assistant Core `2024.5.0` and now every time I try to turn on my yi camera I get the following error:
![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/26602133/088c1971-9646-4680-a49e-13bb2f0df979)

I own a Yi Dome U 1080p camera which worked 100% fine before upgrading via mqtt and yi hack home assistant integration.

Please help!
Thanks

**Comment by roleoroleo** [comment]
Fixed with this pr: https://github.com/roleoroleo/yi-hack_ha_integration/pull/152
