### ISSUE TITLE
Yi 1080 Home Camera BFUS Firmware version 9.0.36.00_202011101611 - is hackable?

### ISSUE THREAD

**Issue by GregoryZet** [roleoroleo/yi-hack-Allwinner-v2#88]
Is it possible to hack this model?
I've tried to use hack for "Yi 1080p Home IFUS 9.0.19* y21ga" but this hack doesn't work.  
After loading the files to the SD card and starting the camera, the camera reboots all the time. After removing the SD card, the camera works normally - the "Factory" directory on the SD card is renamed to "Factory.done".

**Comment by roleoroleo** [comment]
It's probably a new model.
Please, make a backup copy of the flash and share it with me.

**Comment by GregoryZet** [comment]
OK. How can I send backup of the flash to you?

**Comment by roleoroleo** [comment]
Please use a cloud file service.
I will remove your message asap.
