### ISSUE TITLE
h30ga and r35gb on 0.3.0 version do not find 0.3.2 online update

### ISSUE THREAD

**Issue by morenod** [roleoroleo/yi-hack-Allwinner-v2#893]
When trying to upgrade h30ga and r35gb, they say:

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/25103450/0175a227-0901-411c-bf54-2558a32f602a)

But you click on upgrade firmware and:

![image](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/25103450/bd82d063-1dec-43d9-888f-487fbe51d7e5)

**Comment by maxen0815** [comment]
I had a simmilar issue and upgraded to 0.3.2 manually - now it seems to work again.
![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/95c39cba-5b5e-4dd5-9543-d58437dbb071)

Upload File via FTP and follow the instructions to install the update manually:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Manual-firmware-upgrade

**Comment by djiesr** [comment]
Same here... I have many cameras, if I can didn't have to set a FTP on each , that can be a good thing. Hope to update to 3.3 from 3.0. Thanks

**Comment by roleoroleo** [comment]
There was a bug in the previous version of busybox.
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/779
You have to update with the manual procedure.

**Comment by djiesr** [comment]
ok.
I try turn on the FTP Serve, but I got:
421 Can't change directory to /home/ftp/ [/]
I miss something?

**Comment by morenod** [comment]
Upgrade completed using the manual procedure, thanks!!
