### ISSUE TITLE
Two timestamps within snapshot - any way to remove one?

### ISSUE THREAD

**Issue by maxen0815** [roleoroleo/yi-hack-Allwinner-v2#894]
Hi there,

I currently do see two timestamps within the snapshots on a newly hacked (Kami) camera.
My old devices don't show this duplicate. Any way to remove the original Kami timestamp?

![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/6d2365c0-d75e-4b08-b0c5-715d4ea2392a)

**Comment by roleoroleo** [comment]
How are you calling this snapshot?
Onvif? Web service?

**Comment by maxen0815** [comment]
Shows up in web interface snapshot as well as in ftp uploaded ones.
The ONVIF and RTSP streams only shows left upper timestamp.

![grafik](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39555958/77c18ff7-5d76-42cc-a009-fd787972ab66)

**Comment by roleoroleo** [comment]
The upper left osd is made by Yi processes and you can't remove it.
The lower right osd is made by the hack and can be removed with the option watermark=no:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/wiki/Web-services-description#snapshot
With onvif there is a specific option:
![immagine](https://github.com/roleoroleo/yi-hack-Allwinner-v2/assets/39277388/3535d05f-65b7-42be-b195-f28d4b97e477)

**Comment by maxen0815** [comment]
Thanks for your reply. So I can close this one.
