### ISSUE TITLE
BFUS 9.0.19* - brick [help]

### ISSUE THREAD

**Issue by mates21** [roleoroleo/yi-hack-Allwinner-v2#897]
When i updated, the camera only has yellow light. Same without sd card. :(
I tried following [these](https://github.com/roleoroleo/yi-hack-Allwinner-v2/tree/master/unbrick) instructions, but unfortunately my skills are too low.
Could someone create a zip file for me that will repair my camera? Please.
Here is the backup data for the y21ga model
https://mega.nz/folder/lKo1GSgT#LGi8dJt7DdmUZLWXmEjv1g
and here:
https://mega.nz/file/0AlSnAxC#LlQ0_pS7b1_jD2yWGeRNrQEVmT1cmvbwLPLRrvem40Q

Thank you very much

**Comment by roleoroleo** [comment]
Here it is:
[backup_y21ga.gz](https://github.com/user-attachments/files/16039847/backup_y21ga.gz)

**Comment by mates21** [comment]
Thank you very much! But after unpacking in windows I only have the backup_y21ga file without extension. Should I upload such a file to the SD card?

**Comment by roleoroleo** [comment]
You don't need home and rootfs if the problem is just the backup partition.
Try and check if it works.
