### ISSUE TITLE
Snapshot not working - V.0.1.1

### ISSUE THREAD

**Issue by fklement** [roleoroleo/yi-hack-Allwinner-v2#9]
Somehow I only get a green picture.
But I have not yet done any further investigation.

![snapshot sh](https://user-images.githubusercontent.com/7302097/97277110-5ea46780-1838-11eb-9631-b8242ff461a1.jpeg)

RTSP Stream is working just fine.

**Comment by marcomehnert** [comment]
Same here. But I am happy to get that far to have a partly working hack for the new version of the cam. OTA-Update did not work. It shows an older version than the one that is installed.

**Comment by mcanteri** [comment]
Which version of the hack are you referring (r30gb or y21ga) ?

**Comment by LukasVFL99** [comment]
y21ga @mcanteri

**Comment by fklement** [comment]
@mcanteri I'm also using y21ga

**Comment by mcanteri** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/commit/ae8d3932c96e9fbe5c72372d8c5f237b7461a1d1

Repository says it is still 0.1.0 , where did you get it ? :)

**Comment by marcomehnert** [comment]
a zipped package with version 0.1.1 was linked somewhere in the issue comments

**Comment by marcomehnert** [comment]
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/5#issuecomment-716736627

**Comment by mcanteri** [comment]
Ok, thank you, it's still in test for that issue.

**Comment by LukasVFL99** [comment]
Where to get this version? @mcanteri

**Comment by mcanteri** [comment]
@LukasVFL99 it was available in the other thread but seems now is no more, so my comment was for those that is following this hack from early days.
Probably in that 0.1.1 Roleo fixed the problem with boot loop if you haven't experienced, so it's good to stay with it too 👍

**Comment by roleoroleo** [comment]
Is low res snapshot working?

**Comment by pep4n** [comment]
> 
> 
> Is low res snapshot working?

no. but not like shown above. 
For me its not even loading. showing an error message something like this: 
"the picture ![grafik](https://user-images.githubusercontent.com/72208592/97292587-b6989980-184b-11eb-8355-ee61530e8651.png) can not be loaded, because it contains errors."

**Comment by artemy** [comment]
I have somewhat similar picture with high-res snapshot on r30gb.

**Comment by roleoroleo** [comment]
Please try this binary:
[framefinder.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5445232/framefinder.gz)

**Comment by mcanteri** [comment]
> Please try this binary:
> [framefinder.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5445232/framefinder.gz)

All snapshots are working now on y21ga.

**Comment by fklement** [comment]
> > Please try this binary:
> > [framefinder.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5445232/framefinder.gz)
> 
> All snapshots are working now on y21ga.

Yes I also can confirm this! 👍🏼

**Comment by roleoroleo** [comment]
Ok, I will try to release a new official release.
I hope it turns out better than 0.1.0 :)

**Comment by mcanteri** [comment]
For sure it'll be better :-) 👍

**Comment by roleoroleo** [comment]
Done!

**Comment by LukasVFL99** [comment]
Where to find @roleoroleo ?

**Comment by patschi1983** [comment]
> Where to find @roleoroleo ?

In the Release-Section ;-)
