### ISSUE TITLE
Please Add support for Grep option for busybox

### ISSUE THREAD

**Issue by mrxyzl** [roleoroleo/yi-hack-Allwinner-v2#900]
Current newest all winner v2 don't support grep command according to https://github.com/roleoroleo/yi-hack-Allwinner-v2/blob/master/src/busybox/.config

Which lead to this bug that I get (grep: unrecognize command - A)
https://github.com/denven/yihack-onedrive-uploader/issues/12

**Comment by roleoroleo** [comment]
I will add it.
