### ISSUE TITLE
Hack for Yi Camera Dome U?

### ISSUE THREAD

**Issue by Gizmo-Ger** [roleoroleo/yi-hack-Allwinner-v2#91]
I just got a new camera called Yi Dome U. I thought I would give it a try with the lastest hack. Unfortunately the hack doesn´t work on this model, although the backup worked fine. Is it possible to use the hack with this model as well? I can provide the backup files for investigation. Thanks in advance
Firmware is 9.0.22.14_202011061019

**Comment by roleoroleo** [comment]
I will check it.
Share the backup.

**Comment by Gizmo-Ger** [comment]
https://drive.google.com/file/d/1fPYTzNl3fE-pNGLFzcvKcdGBEkT5KNMc/view?usp=sharing

**Comment by roleoroleo** [comment]
Your cam is an h52ga.
Very similar to a y21ga.
I will try to add a beta support fot it.

**Comment by Gizmo-Ger** [comment]
Awesome. Thanks for your effort and your time. I highly appreciate.

**Comment by roleoroleo** [comment]
Try this hack.
You should be able to install it and reach the web interface.
I don't know if rtsp and snapshot are working.
Try it (low and high res).

[h52ga_0.1.4.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5958667/h52ga_0.1.4.tar.gz)

**Comment by Gizmo-Ger** [comment]
Thank you. I tried the version but the camera keeps rebooting and turning 360 and rebooting again. Can I provide any logs?

**Comment by roleoroleo** [comment]
If you remove the sd card, does it work?

**Comment by Gizmo-Ger** [comment]
Yes, once the SD card is removed the camera works normally.

**Comment by roleoroleo** [comment]
Dump the SD and share with me.
A compressed file is enough.

**Comment by Gizmo-Ger** [comment]
https://drive.google.com/file/d/1qYmrTb-99_YMYBc8Y1rxg35CZIwDYBvf/view?usp=sharing

**Comment by roleoroleo** [comment]
Is there a file "lower_half_init.sh" in the root of your sd card?

**Comment by Gizmo-Ger** [comment]
yes, it is

**Comment by roleoroleo** [comment]
No, it doesn't matter.

The SD seems to be ok.
Try to edit etc/system.conf with the following content:
```
HTTPD=yes
TELNETD=yes
SSHD=yes
FTPD=no
BUSYBOX_FTPD=no
DISABLE_CLOUD=no
REC_WITHOUT_CLOUD=no
MQTT=no
RTSP=no
RTSP_STREAM=high
RTSP_AUDIO=yes
ONVIF=no
ONVIF_WSDD=no
ONVIF_PROFILE=high
ONVIF_NETIF=wlan0
ONVIF_WM_SNAPSHOT=yes
NTPD=no
NTP_SERVER=pool.ntp.org
PROXYCHAINSNG=no
SWAP_FILE=yes
RTSP_PORT=554
ONVIF_PORT=80
HTTPD_PORT=8080
USERNAME=
PASSWORD=
TIMEZONE=
FREE_SPACE=0
FTP_UPLOAD=no
FTP_HOST=
FTP_DIR=
FTP_DIR_TREE=no
FTP_USERNAME=
FTP_PASSWORD=
FTP_FILE_DELETE_AFTER_UPLOAD=yes
SSH_PASSWORD=
CRONTAB=
```

and try again the cam.

**Comment by roleoroleo** [comment]
What program did you use to decompress the archive?

**Comment by Gizmo-Ger** [comment]
I´ll try in a minute. I am using 7zip

**Comment by Gizmo-Ger** [comment]
Ok, checked with your modifications. I can access the web interface and no more reboots. Streams and snapshots don´t work.

**Comment by roleoroleo** [comment]
Now you should enable the services one at a time and check which service causes the reboot.

**Comment by Gizmo-Ger** [comment]
I tested again with RTSP, ONVIF, SSH, NTPD, HTTPD, swap enabled. FTP and MTTQ are disabled. Camera works so far without any reboots.
PTZ works, but without preview. Snapshots and streams don´t work.

**Comment by roleoroleo** [comment]
Ok.
Probably the swap is mandatory.
Without it the cam reboots.

To fix snapshot and stream I need 2 copies of fshare_frame_buf file.
You can find it in /etc.

Copy it, wait 5 secs and copy it again.

**Comment by Gizmo-Ger** [comment]
Unfortunately there is no such file.

**Comment by Gizmo-Ger** [comment]
![Unbenannt](https://user-images.githubusercontent.com/1399860/107735533-34e85100-6d00-11eb-9b09-43b1ccaeb675.png)

**Comment by roleoroleo** [comment]
Sorry, my mistake.
It is in /dev.

**Comment by Gizmo-Ger** [comment]
Looks like something is really off on my side. Because there is no /dev directory
![Unbenannt1](https://user-images.githubusercontent.com/1399860/107793886-1792a180-6d57-11eb-8c58-364070f3cdb7.PNG)

**Comment by roleoroleo** [comment]
/dev in the root.
Not inside /tmp/sd/yi-hack

**Comment by Gizmo-Ger** [comment]
got it figured out
https://drive.google.com/open?id=1-317PmdFygSqH2MtX0Oa9tkWO7Ogk-GB&authuser=shstieglitz%40gmail.com&usp=drive_fs
https://drive.google.com/open?id=17XOu1iYtnAIQoK-fK9vNfFxx0k-jG1je&authuser=shstieglitz%40gmail.com&usp=drive_fs

**Comment by roleoroleo** [comment]
Try this beta:
[rRTSPServer.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5975381/rRTSPServer.gz)

Stop the watchdog and the old rtsp server and run this new binary:
```
. /tmp/sd/yi-hack/script/env.sh
killall wd_rtsp.sh
killall rRTSPServer
RRTSP_RES=both RRTSP_AUDIO=no RRTSP_MODEL=h52ga rRTSPServer
```
If you want to enable debug add RRTP_DEBUG=1
RRTSP_AUDIO could be: no, pcm, alaw, ulaw and aac.

**Comment by Gizmo-Ger** [comment]
Awesome! Thank you so much. Now I get a stream

**Comment by roleoroleo** [comment]
Does it works?
High res and low res?

This should fix snapshots:
[snap.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5975865/snap.tar.gz)

**Comment by Gizmo-Ger** [comment]
Both streams when freshly rebooted. After a cpl of hours it won´t work anymore. With the your new snap.tar.gz snapshots work flawlessly. Thanks again

**Comment by roleoroleo** [comment]
Run the server with debug option and redirect the stderr on file.
Then send me the file.
I need to check the log when the server stops working.

**Comment by roleoroleo** [comment]
Also check if ptz works.
Both in the web page and through onvif device manager.

**Comment by Gizmo-Ger** [comment]
ptz works, both in web page and onvif device manager. Although up and down seem to be mixed up.

**Comment by roleoroleo** [comment]
Up and down only?
Mmmmh
Check this issue and let me know if your cam is different:
https://github.com/roleoroleo/yi-hack-Allwinner-v2/issues/68

**Comment by roleoroleo** [comment]
I think h51ga.
