### ISSUE TITLE
y291ga backup lost

### ISSUE THREAD

**Issue by SmilinStanSStanman** [roleoroleo/yi-hack-Allwinner-v2#913]
I am trying yo restore a Yi Cam RFUSY44FDUTWEC230510 (y291ga) but I don't know where I left my backup file (facepalm...) Someone can help me? Thanks in advance...

**Comment by roleoroleo** [comment]
Which partitions do you need?
Is mtdblock4 enough?

**Comment by SmilinStanSStanman** [comment]
I found the pendrive with the backup this morning. Thanks!
