### ISSUE TITLE
y623 Firmware update prevents hack from working

### ISSUE THREAD

**Issue by Niklas0439** [roleoroleo/yi-hack-Allwinner-v2#915]
I bought the Yi Pro 2K Home in a 2 Pack. I connected one via app and updated the firmware to the latest version (a mistake!), 12.51.08_202403081746. The hack doesn't seem to work. The Factory.done file is created but it can't. connect. 
For the second Camera I directly inserted the Hack SD and it worked. Now I wonder if I can somehow rewind to an older Firmware (e.g. by creating a copy from the hacked camera), does someone have experience with that?

**Comment by Niklas0439** [comment]
I figured it out how to load the backup but it still can't connect

**Comment by roleoroleo** [comment]
Did you restore the previous version?
The cam is connected to the app? Is it working?

**Comment by viperracing** [comment]
> I figured it out how to load the backup but it still can't connect

Could you please tell me how to restore the backup or downgrade the firmware?

**Comment by Niklas0439** [comment]
> > I figured it out how to load the backup but it still can't connect
> 
> Could you please tell me how to restore the backup or downgrade the firmware?

Sure, so you got the mtdblock.bin files? If so you need to download the unbrick folder of this repo, add your mtdblock.bin files (-2, -3 & 4 are required) into the folder of your corresponding camera (in the case of the Yi Pro 2K Home it's the y623 folder). If you're on a Mac, make sure you have uboot tools installed (e.g. brew install u-boot-tools) then do: cd unbrick and run ./build.sh factory (as described in the documentation). 
This should give you the 3 zip files in your folder /unbrick/y623/  backup_y623.gz, home_y623.gz & rootfs_y623.gz. Unzip all, add them onto your SD card which you insert into the camera and power it up, when it reboots the previous firmware should be restored. I also attached my backup files which you can directly put on the SD-Card (for y623, they are zipped since I can't upload the corresponding file type).
Hope this helps
[Backup_Files.zip](https://github.com/user-attachments/files/16695465/Backup_Files.zip)

**Comment by mariomeglio** [comment]
> > > Ho capito come caricare il backup ma ancora non riesco a connettersi
> > 
> > 
> > Potresti dirmi come ripristinare il backup o eseguire il downgrade del firmware?
> 
> Certo, quindi hai i file mtdblock.bin? Se è così, devi scaricare la cartella unbrick di questo repository, aggiungere i tuoi file mtdblock.bin (-2, -3 e 4 sono obbligatori) nella cartella della tua fotocamera corrispondente (nel caso di Yi Pro 2K Home è la cartella y623). Se sei su un Mac, assicurati di avere gli strumenti uboot installati (ad esempio brew install u-boot-tools) quindi fai: cd unbrick e run ./build.sh factory (come descritto nella documentazione).Questo dovrebbe darti i 3 file zip nella tua cartella /unbrick/y623/ backup_y623.gz, home_y623.gz & rootfs_y623.gz. Scomprimi tutto, aggiungili alla scheda SD che inserisci nella fotocamera e accendilo, quando si riavvia il firmware precedente dovrebbe essere ripristinato. Ho anche allegato i miei file di backup che puoi mettere direttamente sulla scheda SD (per y623, sono zippati poiché non riesco a caricare il tipo di file corrispondente).Spero che questo aiuti [Backup_File.zip](https://github.com/user-attachments/files/16695465/Backup_Files.zip)

Ciao! Siccome sono un pò anzionotto ed ho la telecamera bloccata con Led fisso arancione, potresti spiegarmi ed inviare file per ripristinare il firmware originale? Ho tolto anche la SD con la modifica ma resta sempre bloccata. Grazie

**Comment by roleoroleo** [comment]
@mariomeglio 
Hai una y623?
Quale firmware Yi? Lo vedi nell'app. Tipo 12.0.51.08_202410081757

Anzianotto... non sarai più vecchio di me...

**Comment by mariomeglio** [comment]
Si

**Comment by roleoroleo** [comment]
Mi sai dire quale firmware Yi? Lo vedi nell'app. Tipo 12.0.51.08_202410081757

**Comment by mariomeglio** [comment]
Dovrebbe essere 12.0.51.08_202411131107
Grazie

**Comment by roleoroleo** [comment]
Here it is:
[backup_y623.gz](https://github.com/user-attachments/files/24149406/backup_y623.gz)

**Comment by mariomeglio** [comment]
Per favore mi spieghi come devo procedere.
Al momento la telecamera è con led giallo fisso e non fa niente.
Sai l’”anzianotto” non ne capisce molto.
Grazie e scusami del fastidio.

**Comment by roleoroleo** [comment]
Spegni la cam.
Prendi il file e lo decomprimi nella scheda SD.
Accend la cam.
Attendi...

Dovrebbe ripristinarsi "di fabbrica".

**Comment by roleoroleo** [comment]
Il file va decompresso.

**Comment by mariomeglio** [comment]
Ok, ci provo e ti faccio sapere.
Grazie di tutto.

**Comment by mariomeglio** [comment]
Allora, ho seguito le indicazioni.
Purtroppo non succede nulla
La camera resta con il led fisso giallo.
Se non hai altre indicazioni mi sa che la devo buttare.
Grazie dell’aiuto.

**Comment by roleoroleo** [comment]
Mmmmh...
Magari prova con un'altra scheda.
Questa è una procedura che non dovrebbe fallire.

A meno che non ci sia un problema hardware.

**Comment by mariomeglio** [comment]
Ho provato con diverse schede.
Purtroppo non va.
Forse sarà un problema hardware.

**Comment by rob500rob-dot** [comment]
Me to i have difficult with ZFUS yii cam, i did downgrade to12.0.51.01_202303091901 as in backup but nothing change. the led is blue but i can't find it neither in app neither on modem. i need help

**Comment by roleoroleo** [comment]
If the led is blue, it should work.
Remove the sd card and try to reset the cam with the back button.
It should ask for pairing.

**Comment by rob500rob-dot** [comment]
Yes It asked for connection what I have to do now?

Ok i use SD inside then the light come blue I see the cam in my modem but I can't reach it on browser. What can I do?
I found this in sd

Backup
Factory.done
Yi-hack
Lower_half_init
Mydblock7_19700101000013.bin

**Comment by rob500rob-dot** [comment]
Ok i use SD inside then the light come blue I see the cam in my modem but I can't reach it on browser. What can I do?

**Comment by roleoroleo** [comment]
The content of the sd card is ok.
If you are not able to reach the cam, it could be:
1 -  The cam is in boot loop: check if the led turns yellow and blue continuously.
2 - Something is wrong in the sd card: create again the sdcard and try to login with a telnet session (putty for example).

**Comment by rob500rob-dot** [comment]
Give me an example I don't know how to do a telnet session

**Comment by roleoroleo** [comment]
If you are using Windows...
1 - Download putty: https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html
2 - Install it and run it.
3 - Insert the IP address of your cam and select telnet protocol (port 23).

<img width="298" height="152" alt="Image" src="https://github.com/user-attachments/assets/50337332-46af-4060-8cd6-705aa2724faa" />

4 - Now putty should connect to your cam and ask for user/password: root is the user without password (if you didn't change it).

**Comment by rob500rob-dot** [comment]
Ok I am connected with putty. Now? It show me welcom to xiaoyi Linux. Root@


Il sab 3 gen 2026, 10:54 roleo ***@***.***> ha scritto:

**Comment by roleoroleo** [comment]
Now, post the output of the commands
`ps`
and
`top`

**Comment by rob500rob-dot** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/af14ea84-1779-488c-a75f-3ab061573389" />
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/553852a5-3e02-4080-91a0-380077a3f1a3" />
here there are

**Comment by roleoroleo** [comment]
Did you remove the sd card?

**Comment by rob500rob-dot** [comment]
No I didn't.
ok i understand the problem i had a yi-hack folder empty. now all is ok. Thank you very much!
