### ISSUE TITLE
0.3.2 hack hangs cameras on snapshot request

### ISSUE THREAD

**Issue by c3kkos** [roleoroleo/yi-hack-Allwinner-v2#918]
Hi there, i got a y21ga (BFUS) with v9 base and a newer y263 (ZFUS) with v12 base and BOTH had serious performance problem since the upgrade.

I got everything disabled but snapshot and mqtt.

my BFUS died today, i don't think its due to software honestly, it served me for years now and this very last night we had thunderstorm and electrical cut outs.

the ZFUS dies out if a snapshot image is accessed via web interface.
ping is still live though.

@roleoroleo i know this lacks some other infos, let me know if you need some more, some dumps, some logs ecc ecc.

unluckly, with ZFUS after snapshot request i cant even ssh into.

**Comment by roleoroleo** [comment]
It's probably a memory issue.
Is swap file enabled?
Try (just a try) to force the snapshot in low res.
