### ISSUE TITLE
Camera settings are resetted after a undefined period of time 

### ISSUE THREAD

**Issue by Gifford47** [roleoroleo/yi-hack-Allwinner-v2#919]
In section "camera settings" I enabled the camera as also the ai human detection and IR led.
After some time (f.e. 6hours) all the options are disabled automatically in the UI. I can reenable the options via webui or mqtt but the issue occurs continuously.

I've enabled swap, low snapshots/ stream and mqtt. No other unnecessary stuff.

What can cause this issue, any idea?

Details:
Firmware Version	 0.3.2
Base Version 9.0.19.09_202010291747
Model Suffix	 y21ga

**Comment by PBadz** [comment]
Exactly the same on ZFUS but in Configurations pane. All settings are rolling back to default after few reebots.

Firmware Version: 0.3.2
Base Version: 12.0.51.01_202303091901
Model Suffix: y623

**Comment by roleoroleo** [comment]
Are you using the app?

**Comment by Gifford47** [comment]
I don't use the app

**Comment by roleoroleo** [comment]
Does the cam reboot before the settings reset?

**Comment by Gifford47** [comment]
Maybe. I didn't recognise it yet. For me the reset occurs after about 24h (not exactly).

**Comment by roleoroleo** [comment]
Is cloud enabled? (Disable cloud switched off)

**Comment by Gifford47** [comment]
Cloud is disabled (switch is on)

**Comment by Gifford47** [comment]
> Does the cam reboot before the settings reset?
> 

Now it had a reboot and resetted the settings afterwards. Might be a service that isn't started successfully?

**Comment by Gifford47** [comment]
@roleoroleo any progress? Do you need any debug information?

**Comment by Gifford47** [comment]
After reinstall to 0.3.3 no issue persists.
