### ISSUE TITLE
yi dome guard KFUS firmware 9.0.05.32_202004101552

### ISSUE THREAD

**Issue by moriwaky** [roleoroleo/yi-hack-Allwinner-v2#92]
I tried the r30gb version 0.1.4 and 0.1.3 but it´s not stable for my camera. I know is a beta. But I can use my two camera as betatester if you want. RSPT just works on low quality and the PTZ doesn´t works on synology survillance, If I use ONVIF I get PTZ control but the camera restarts every minute. here you have the original firmaware of the camera if you want to take a look:

https://1drv.ms/u/s!Aq2FEDvef10rjh1eHb62QIeXFl4D?e=LxFgM7

**Comment by moriwaky** [comment]
Update I have read that "swap file" fixs randoms reboot on ONVIF.

**Comment by roleoroleo** [comment]
Does rtsp work after enabling swap?

**Comment by moriwaky** [comment]
yes but in low res and no PTZ control.  With swap file on, I don´t have randoms reboot on ONVIF but I have no live view on synology survillance.

**Comment by moriwaky** [comment]
Sorry I my last answer was wrong. I don´t have any video on rtsp with swap file "on" And with Onvif I don´t have live view from the synology survillance (maybe codec related issue because I can´t check the telemetry of the live video)

**Comment by roleoroleo** [comment]
Please check if video works with vlc and check if onvif works with onvif device manager.

**Comment by moriwaky** [comment]
Video works on vlc  high quality and low. And in onvif device manager i can use the ptz and I have video. but I synology I just get low quality video on rtsp. and no live video and no record video on onvif. Is anything I can do to make it work with the synology survillance? thanks for your time by the way

**Comment by rt400** [comment]
i have also yi dome guard, in the camera web i dont have option in PTZ to save presnt . the onvif work bad, the rtsp work good only in low res

**Comment by roleoroleo** [comment]
@moriwaky 
The high res stream is h265 coded while the low res stream is h264 coded.
Maybe Synology doesn't support h265.
Set onvif profile low and check if you are able to see low res stream in onvif.

@rt400
What's your model suffix? r30gb?

**Comment by rt400** [comment]
@roleoroleo yes.
KFUS with 9.0.05.33_202009251856

**Comment by rt400** [comment]
how can i stream video and audio together ?

**Comment by roleoroleo** [comment]
Enable it in configuration web page.

**Comment by rt400** [comment]
its enable but in live stream like vlc there is no sound. its looks that disparate..

**Comment by roleoroleo** [comment]
If you check the menu Tools->Codec Information, could you see the audio section?
Or is there only video section?

**Comment by rt400** [comment]
yes, i see the audio section.
but there is no sound. if i play the mp4 that the camera record i can hear the sound

**Comment by roleoroleo** [comment]
Strange behavior.
Sorry, I don't know how to check it because I don't have this model.
I will try to send you a beta version.

**Comment by rt400** [comment]
strange, i check it on other model YI Home 1080p with y20ga perfix and also didn't have sound

**Comment by rt400** [comment]
@roleoroleo What about the PTZ features ? Yi Doom Guard

**Comment by roleoroleo** [comment]
Try this beta:
[r30gb_0.1.4.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5960110/r30gb_0.1.4.tar.gz)

About PTZ it should work.
Please, explain me better your problem.
Did you try it with onvif device manager?

**Comment by rt400** [comment]
> Try this beta:
> [r30gb_0.1.4.tar.gz](https://github.com/roleoroleo/yi-hack-Allwinner-v2/files/5960110/r30gb_0.1.4.tar.gz)
> 
> About PTZ it should work.
> Please, explain me better your problem.
> Did you try it with onvif device manager?
here is what i have in the camera web control
![image](https://user-images.githubusercontent.com/38878996/107634946-05d7ce00-6c73-11eb-9554-5fac4c2c1f4e.png)
as tou can see i dont have save present and other option


there is other way to update the firmware without copy it to sd card ?

**Comment by roleoroleo** [comment]
Other options?
The web interface allows you to go to preset.
It doesn't allow to set preset.

> there is other way to update the firmware without copy it to sd card ?

If you have a previous version, you can update it online.

**Comment by rt400** [comment]
OK. i ask cause i have the sonoff camera also and there i have more option

How can i update it online ?

**Comment by roleoroleo** [comment]
> OK. i ask cause i have the sonoff camera also and there i have more option

Ok. The yi cam already has a system for setting presets.
So I didn't want to make a new one like Sonoff.
You can configure the presets using the app.

> How can i update it online ?

Menu Maintenance -> Upgrade firmware
But I recently solved a prblem in the ota procedure, so it is better if you do the installation from scratch.

**Comment by rt400** [comment]
so i need the yi app to do it ? there is no other way ?

**Comment by roleoroleo** [comment]
I didn't reverse the yi messages about presets (if there are).
Maybe it's possible sending ipc messages.

**Comment by rt400** [comment]
@roleoroleo first the update firmware that you send me fix something that I want to tell you, audio ... so thanks.
now about the ptz (ipc messages) can i help you with this to add it ? its really necessary for me.
many thanks for your job!!!

**Comment by josebc83** [comment]
Is it necessary to have the camera activated with the yi software? or can I apply the hack with the camera taken out of the box?

**Comment by WalkingDot** [comment]
@josebc83 The hack is working out of the box. If you want to use wifi for the first setup, you need to add the wpa_supplicant (https://github.com/roleoroleo/yi-hack-Allwinner/issues/289).

**Comment by muhammadyusuf99** [comment]
> I tried the r30gb version 0.1.4 and 0.1.3 but it´s not stable for my camera. I know is a beta. But I can use my two camera as betatester if you want. RSPT just works on low quality and the PTZ doesn´t works on synology survillance, If I use ONVIF I get PTZ control but the camera restarts every minute. here you have the original firmaware of the camera if you want to take a look:
> 
> https://1drv.ms/u/s!Aq2FEDvef10rjh1eHb62QIeXFl4D?e=LxFgM7

can you provide this firmware file ? this link is dead

**Comment by roleoroleo** [comment]
Is it a backup from a cam?
Tell my what version you need.
