### ISSUE TITLE
YI Dome U 2K (h51ga) - goes to pairing mode

### ISSUE THREAD

**Issue by stahelp** [roleoroleo/yi-hack-Allwinner-v2#955]
Hi

my YI Dome U (2K) has these config settings:
-Firmware Version	0.3.2
-Base Version	9.0.21.13_202109101104
-Model Suffix	h51ga

I have enabled RTSP, RTSP stream, ONVIF.
After saving changes and reboot or when I do a PTZ move the camera boots and starts the pairing process.

I have the same model working with no issues since month (same fw ect)

Any help is appreciated.
Thank you very much

**Comment by roleoroleo** [comment]
Try to restart from scratch.

- Remove the sd card.
- Reset the cam with the button.
- Pair the cam with the app.
- Format the sd card.
- Apply the hack.
