### ISSUE TITLE
Yi Home 2K Pro not saving configuration

### ISSUE THREAD

**Issue by LuisDiazUgena** [roleoroleo/yi-hack-Allwinner-v2#979]
Hi!

I just installed the custom fw on 3 cameras at home and one of those is not saving the configuration changes after a reboot.

Hostname | (none)
Firmware Version | 0.3.3
Base Version | 12.0.51.01_202303091901
Model Suffix | y623
Serial Number | YFUSY94DA0HGAF231212
Local Time | Sun Dec 15 13:09:14 GMT 2024
Uptime | 0h 2m 12s
Load Average | 2.59 0.99 0.37
Free/Total Memory | 6268/60912 KB
Free SD Space | 100%

Please let me know what information should I provide in order to clarify this issue.

**Comment by roleoroleo** [comment]
It could be a hardware issue or a power problem.
Please, try:

- another power adapter/cable
- another sd card

**Comment by LuisDiazUgena** [comment]
Sorry I was super busy and forgot to update the repo. 

SD card was faulty and swaping to another SD card worked great.
